use [BelcorpBolivia]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF NOT EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   INSERT INTO rolpermiso
			   select 3, PERMISOID,	1, 1
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			  -- where permisoid in(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			   SELECT 'EL REGISTRO FUE REALIZADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE REALIZO'
			   END

SELECT *  FROM   rolpermiso WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
SELECT * FROM ROL WHERE ROLID=3
go


use [BelcorpChile]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF NOT EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   INSERT INTO rolpermiso
			   select 3, PERMISOID,	1, 1
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			  -- where permisoid in(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			   SELECT 'EL REGISTRO FUE REALIZADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE REALIZO'
			   END

SELECT *  FROM   rolpermiso WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
SELECT * FROM ROL WHERE ROLID=3
go


use [BelcorpColombia]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF NOT EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   INSERT INTO rolpermiso
			   select 3, PERMISOID,	1, 1
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			  -- where permisoid in(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			   SELECT 'EL REGISTRO FUE REALIZADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE REALIZO'
			   END

SELECT *  FROM   rolpermiso WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
SELECT * FROM ROL WHERE ROLID=3
go

use [BelcorpCostaRica]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF NOT EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   INSERT INTO rolpermiso
			   select 3, PERMISOID,	1, 1
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			  -- where permisoid in(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			   SELECT 'EL REGISTRO FUE REALIZADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE REALIZO'
			   END

SELECT *  FROM   rolpermiso WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
SELECT * FROM ROL WHERE ROLID=3
go

use [BelcorpDominicana]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF NOT EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   INSERT INTO rolpermiso
			   select 3, PERMISOID,	1, 1
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			  -- where permisoid in(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			   SELECT 'EL REGISTRO FUE REALIZADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE REALIZO'
			   END

SELECT *  FROM   rolpermiso WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
SELECT * FROM ROL WHERE ROLID=3
go

use [BelcorpEcuador]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF NOT EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   INSERT INTO rolpermiso
			   select 3, PERMISOID,	1, 1
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			  -- where permisoid in(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			   SELECT 'EL REGISTRO FUE REALIZADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE REALIZO'
			   END

SELECT *  FROM   rolpermiso WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
SELECT * FROM ROL WHERE ROLID=3
go

use [BelcorpGuatemala]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF NOT EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   INSERT INTO rolpermiso
			   select 3, PERMISOID,	1, 1
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			  -- where permisoid in(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			   SELECT 'EL REGISTRO FUE REALIZADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE REALIZO'
			   END

SELECT *  FROM   rolpermiso WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
SELECT * FROM ROL WHERE ROLID=3
go

use [BelcorpMexico]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF NOT EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   INSERT INTO rolpermiso
			   select 3, PERMISOID,	1, 1
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			  -- where permisoid in(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			   SELECT 'EL REGISTRO FUE REALIZADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE REALIZO'
			   END

SELECT *  FROM   rolpermiso WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
SELECT * FROM ROL WHERE ROLID=3
go

use [BelcorpPanama]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF NOT EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   INSERT INTO rolpermiso
			   select 3, PERMISOID,	1, 1
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			  -- where permisoid in(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			   SELECT 'EL REGISTRO FUE REALIZADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE REALIZO'
			   END

SELECT *  FROM   rolpermiso WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
SELECT * FROM ROL WHERE ROLID=3
go

use [BelcorpPeru]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF NOT EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   INSERT INTO rolpermiso
			   select 3, PERMISOID,	1, 1
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			  -- where permisoid in(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			   SELECT 'EL REGISTRO FUE REALIZADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE REALIZO'
			   END

SELECT *  FROM   rolpermiso WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
SELECT * FROM ROL WHERE ROLID=3
go

use [BelcorpPuertoRico]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF NOT EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   INSERT INTO rolpermiso
			   select 3, PERMISOID,	1, 1
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			  -- where permisoid in(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			   SELECT 'EL REGISTRO FUE REALIZADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE REALIZO'
			   END

SELECT *  FROM   rolpermiso WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
SELECT * FROM ROL WHERE ROLID=3
go

use [BelcorpSalvador]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF NOT EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   INSERT INTO rolpermiso
			   select 3, PERMISOID,	1, 1
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			  -- where permisoid in(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			   SELECT 'EL REGISTRO FUE REALIZADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE REALIZO'
			   END

SELECT *  FROM   rolpermiso WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
SELECT * FROM ROL WHERE ROLID=3
go