use [BelcorpBolivia]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdMensajeDescargaWebDDSinMarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[UpdMensajeDescargaWebDDSinMarcar]
GO
/*           
CREADO POR  : PAQUIRRI SEPERAK           
FECHA : 24/06/2019           
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS    
*/ 
CREATE PROCEDURE UpdMensajeDescargaWebDDSinMarcar 
@NUEVONROLOTE     INT, 
@MENSAJETERMINADO VARCHAR(64), 
@ESTADOTERMINADO  INT 
AS 
  BEGIN 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 


      UPDATE PEDIDODESCARGASINMARCAR 
      SET    FECHAFIN = @FECHAGENERAL, 
             ESTADO = @ESTADOTERMINADO, 
             MENSAJE = @MENSAJETERMINADO 
      WHERE  NROLOTE = @NUEVONROLOTE; 
  END 
  go

  use [BelcorpChile]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdMensajeDescargaWebDDSinMarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[UpdMensajeDescargaWebDDSinMarcar]
GO
/*           
CREADO POR  : PAQUIRRI SEPERAK           
FECHA : 24/06/2019           
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS    
*/ 
CREATE PROCEDURE UpdMensajeDescargaWebDDSinMarcar 
@NUEVONROLOTE     INT, 
@MENSAJETERMINADO VARCHAR(64), 
@ESTADOTERMINADO  INT 
AS 
  BEGIN 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 


      UPDATE PEDIDODESCARGASINMARCAR 
      SET    FECHAFIN = @FECHAGENERAL, 
             ESTADO = @ESTADOTERMINADO, 
             MENSAJE = @MENSAJETERMINADO 
      WHERE  NROLOTE = @NUEVONROLOTE; 
  END 
  go

  use [BelcorpColombia]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdMensajeDescargaWebDDSinMarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[UpdMensajeDescargaWebDDSinMarcar]
GO
/*           
CREADO POR  : PAQUIRRI SEPERAK           
FECHA : 24/06/2019           
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS    
*/ 
CREATE PROCEDURE UpdMensajeDescargaWebDDSinMarcar 
@NUEVONROLOTE     INT, 
@MENSAJETERMINADO VARCHAR(64), 
@ESTADOTERMINADO  INT 
AS 
  BEGIN 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 


      UPDATE PEDIDODESCARGASINMARCAR 
      SET    FECHAFIN = @FECHAGENERAL, 
             ESTADO = @ESTADOTERMINADO, 
             MENSAJE = @MENSAJETERMINADO 
      WHERE  NROLOTE = @NUEVONROLOTE; 
  END 
  go

  use [BelcorpCostaRica]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdMensajeDescargaWebDDSinMarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[UpdMensajeDescargaWebDDSinMarcar]
GO
/*           
CREADO POR  : PAQUIRRI SEPERAK           
FECHA : 24/06/2019           
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS    
*/ 
CREATE PROCEDURE UpdMensajeDescargaWebDDSinMarcar 
@NUEVONROLOTE     INT, 
@MENSAJETERMINADO VARCHAR(64), 
@ESTADOTERMINADO  INT 
AS 
  BEGIN 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 


      UPDATE PEDIDODESCARGASINMARCAR 
      SET    FECHAFIN = @FECHAGENERAL, 
             ESTADO = @ESTADOTERMINADO, 
             MENSAJE = @MENSAJETERMINADO 
      WHERE  NROLOTE = @NUEVONROLOTE; 
  END 
  go

  use [BelcorpDominicana]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdMensajeDescargaWebDDSinMarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[UpdMensajeDescargaWebDDSinMarcar]
GO
/*           
CREADO POR  : PAQUIRRI SEPERAK           
FECHA : 24/06/2019           
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS    
*/ 
CREATE PROCEDURE UpdMensajeDescargaWebDDSinMarcar 
@NUEVONROLOTE     INT, 
@MENSAJETERMINADO VARCHAR(64), 
@ESTADOTERMINADO  INT 
AS 
  BEGIN 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 


      UPDATE PEDIDODESCARGASINMARCAR 
      SET    FECHAFIN = @FECHAGENERAL, 
             ESTADO = @ESTADOTERMINADO, 
             MENSAJE = @MENSAJETERMINADO 
      WHERE  NROLOTE = @NUEVONROLOTE; 
  END 
  go

  use [BelcorpEcuador]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdMensajeDescargaWebDDSinMarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[UpdMensajeDescargaWebDDSinMarcar]
GO
/*           
CREADO POR  : PAQUIRRI SEPERAK           
FECHA : 24/06/2019           
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS    
*/ 
CREATE PROCEDURE UpdMensajeDescargaWebDDSinMarcar 
@NUEVONROLOTE     INT, 
@MENSAJETERMINADO VARCHAR(64), 
@ESTADOTERMINADO  INT 
AS 
  BEGIN 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 


      UPDATE PEDIDODESCARGASINMARCAR 
      SET    FECHAFIN = @FECHAGENERAL, 
             ESTADO = @ESTADOTERMINADO, 
             MENSAJE = @MENSAJETERMINADO 
      WHERE  NROLOTE = @NUEVONROLOTE; 
  END 
  go

  use [BelcorpGuatemala]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdMensajeDescargaWebDDSinMarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[UpdMensajeDescargaWebDDSinMarcar]
GO
/*           
CREADO POR  : PAQUIRRI SEPERAK           
FECHA : 24/06/2019           
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS    
*/ 
CREATE PROCEDURE UpdMensajeDescargaWebDDSinMarcar 
@NUEVONROLOTE     INT, 
@MENSAJETERMINADO VARCHAR(64), 
@ESTADOTERMINADO  INT 
AS 
  BEGIN 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 


      UPDATE PEDIDODESCARGASINMARCAR 
      SET    FECHAFIN = @FECHAGENERAL, 
             ESTADO = @ESTADOTERMINADO, 
             MENSAJE = @MENSAJETERMINADO 
      WHERE  NROLOTE = @NUEVONROLOTE; 
  END 
  go

  use [BelcorpMexico]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdMensajeDescargaWebDDSinMarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[UpdMensajeDescargaWebDDSinMarcar]
GO
/*           
CREADO POR  : PAQUIRRI SEPERAK           
FECHA : 24/06/2019           
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS    
*/ 
CREATE PROCEDURE UpdMensajeDescargaWebDDSinMarcar 
@NUEVONROLOTE     INT, 
@MENSAJETERMINADO VARCHAR(64), 
@ESTADOTERMINADO  INT 
AS 
  BEGIN 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 


      UPDATE PEDIDODESCARGASINMARCAR 
      SET    FECHAFIN = @FECHAGENERAL, 
             ESTADO = @ESTADOTERMINADO, 
             MENSAJE = @MENSAJETERMINADO 
      WHERE  NROLOTE = @NUEVONROLOTE; 
  END 
  go

  use [BelcorpPanama]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdMensajeDescargaWebDDSinMarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[UpdMensajeDescargaWebDDSinMarcar]
GO
/*           
CREADO POR  : PAQUIRRI SEPERAK           
FECHA : 24/06/2019           
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS    
*/ 
CREATE PROCEDURE UpdMensajeDescargaWebDDSinMarcar 
@NUEVONROLOTE     INT, 
@MENSAJETERMINADO VARCHAR(64), 
@ESTADOTERMINADO  INT 
AS 
  BEGIN 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 


      UPDATE PEDIDODESCARGASINMARCAR 
      SET    FECHAFIN = @FECHAGENERAL, 
             ESTADO = @ESTADOTERMINADO, 
             MENSAJE = @MENSAJETERMINADO 
      WHERE  NROLOTE = @NUEVONROLOTE; 
  END 
  go

  use [BelcorpPeru]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdMensajeDescargaWebDDSinMarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[UpdMensajeDescargaWebDDSinMarcar]
GO
/*           
CREADO POR  : PAQUIRRI SEPERAK           
FECHA : 24/06/2019           
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS    
*/ 
CREATE PROCEDURE UpdMensajeDescargaWebDDSinMarcar 
@NUEVONROLOTE     INT, 
@MENSAJETERMINADO VARCHAR(64), 
@ESTADOTERMINADO  INT 
AS 
  BEGIN 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 


      UPDATE PEDIDODESCARGASINMARCAR 
      SET    FECHAFIN = @FECHAGENERAL, 
             ESTADO = @ESTADOTERMINADO, 
             MENSAJE = @MENSAJETERMINADO 
      WHERE  NROLOTE = @NUEVONROLOTE; 
  END 
  go

  use [BelcorpPuertoRico]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdMensajeDescargaWebDDSinMarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[UpdMensajeDescargaWebDDSinMarcar]
GO
/*           
CREADO POR  : PAQUIRRI SEPERAK           
FECHA : 24/06/2019           
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS    
*/ 
CREATE PROCEDURE UpdMensajeDescargaWebDDSinMarcar 
@NUEVONROLOTE     INT, 
@MENSAJETERMINADO VARCHAR(64), 
@ESTADOTERMINADO  INT 
AS 
  BEGIN 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 


      UPDATE PEDIDODESCARGASINMARCAR 
      SET    FECHAFIN = @FECHAGENERAL, 
             ESTADO = @ESTADOTERMINADO, 
             MENSAJE = @MENSAJETERMINADO 
      WHERE  NROLOTE = @NUEVONROLOTE; 
  END 
  go

  use [BelcorpSalvador]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdMensajeDescargaWebDDSinMarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[UpdMensajeDescargaWebDDSinMarcar]
GO
/*           
CREADO POR  : PAQUIRRI SEPERAK           
FECHA : 24/06/2019           
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS    
*/ 
CREATE PROCEDURE UpdMensajeDescargaWebDDSinMarcar 
@NUEVONROLOTE     INT, 
@MENSAJETERMINADO VARCHAR(64), 
@ESTADOTERMINADO  INT 
AS 
  BEGIN 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 


      UPDATE PEDIDODESCARGASINMARCAR 
      SET    FECHAFIN = @FECHAGENERAL, 
             ESTADO = @ESTADOTERMINADO, 
             MENSAJE = @MENSAJETERMINADO 
      WHERE  NROLOTE = @NUEVONROLOTE; 
  END 
  go