USE BelcorpPeru
GO

IF(EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'))
BEGIN
	DELETE FROM ConfiguracionPais WHERE ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO')
	DELETE FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'
END

USE BelcorpMexico
GO

IF(EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'))
BEGIN
	DELETE FROM ConfiguracionPais WHERE ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO')
	DELETE FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'
END

USE BelcorpColombia
GO

IF(EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'))
BEGIN
	DELETE FROM ConfiguracionPais WHERE ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO')
	DELETE FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'
END

USE BelcorpSalvador
GO

IF(EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'))
BEGIN
	DELETE FROM ConfiguracionPais WHERE ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO')
	DELETE FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'
END

USE BelcorpPuertoRico
GO

IF(EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'))
BEGIN
	DELETE FROM ConfiguracionPais WHERE ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO')
	DELETE FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'
END

USE BelcorpPanama
GO

IF(EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'))
BEGIN
	DELETE FROM ConfiguracionPais WHERE ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO')
	DELETE FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'
END

USE BelcorpGuatemala
GO

IF(EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'))
BEGIN
	DELETE FROM ConfiguracionPais WHERE ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO')
	DELETE FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'
END

USE BelcorpEcuador
GO

IF(EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'))
BEGIN
	DELETE FROM ConfiguracionPais WHERE ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO')
	DELETE FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'
END

USE BelcorpDominicana
GO

IF(EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'))
BEGIN
	DELETE FROM ConfiguracionPais WHERE ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO')
	DELETE FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'
END

USE BelcorpCostaRica
GO

IF(EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'))
BEGIN
	DELETE FROM ConfiguracionPais WHERE ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO')
	DELETE FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'
END

USE BelcorpChile
GO

IF(EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'))
BEGIN
	DELETE FROM ConfiguracionPais WHERE ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO')
	DELETE FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'
END

USE BelcorpBolivia
GO

IF(EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'))
BEGIN
	DELETE FROM ConfiguracionPais WHERE ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO')
	DELETE FROM CONFIGURACIONPAIS WHERE CODIGO='RESERVA_CONTADO'
END

