
update ConfiguracionPaisDatos set Valor1 = '', Valor2 = '' where Codigo = 'DCatalogoInscritaActiva'
update ConfiguracionPaisDatos set Valor1 = '', Valor2 = '' where Codigo = 'DCatalogoInscritaNoActiva'
update ConfiguracionPaisDatos set Valor1 = 'SUSCRÍBETE A TU NUEVO ESPACIO DE OFERTAS EXCLUSIVAS', Valor2 = '¡SIN DIGITAR CÓDIGOS!' where Codigo = 'DCatalogoNoInscritaActiva'
update ConfiguracionPaisDatos set Valor1 = 'SUSCRÍBETE A TU NUEVO ESPACIO DE OFERTAS EXCLUSIVAS', Valor2 = '¡SIN DIGITAR CÓDIGOS!' where Codigo = 'DCatalogoNoInscritaNoActiva'
update ConfiguracionPaisDatos set Valor1 = '', Valor2 = '' where Codigo = 'MCatalogoInscritaActiva'
update ConfiguracionPaisDatos set Valor1 = '', Valor2 = '' where Codigo = 'MCatalogoInscritaNoActiva'
update ConfiguracionPaisDatos set Valor1 = 'TU NUEVO ESPACIO DE OFERTAS EXCLUSIVAS', Valor2 = 'DISFRUTA DE LOS BENEFICIOS QUE EL CLUB TIENE PARA TI.' where Codigo = 'MCatalogoNoInscritaActiva'
update ConfiguracionPaisDatos set Valor1 = 'TU NUEVO ESPACIO DE OFERTAS EXCLUSIVAS', Valor2 = 'DISFRUTA DE LOS BENEFICIOS QUE EL CLUB TIENE PARA TI.' where Codigo = 'MCatalogoNoInscritaNoActiva'

update ConfiguracionPaisDatos set Valor1 = '<b>CONSULTORAS YA SUSCRITAS ¡GANAN HASTA 10% MÁS!</b>', Valor2 = '' where Codigo = 'DBienvenidaInscritaActiva'
update ConfiguracionPaisDatos set Valor1 = '<b>CONSULTORAS YA SUSCRITAS ¡GANAN HASTA 10% MÁS!</b>', Valor2 = '' where Codigo = 'DBienvenidaInscritaNoActiva'
update ConfiguracionPaisDatos set Valor1 = '#NOMBRE, TODAS <b>TUS OFERTAS EN UN SOLO LUGAR</b>', Valor2 = '' where Codigo = 'DBienvenidaNoInscritaActiva'
update ConfiguracionPaisDatos set Valor1 = '#NOMBRE, TODAS <b>TUS OFERTAS EN UN SOLO LUGAR</b>', Valor2 = '' where Codigo = 'DBienvenidaNoInscritaNoActiva'
update ConfiguracionPaisDatos set Valor1 = 'CONSULTORAS YA SUSCRITAS', Valor2 = '¡GANAN HASTA 10% MÁS!' where Codigo = 'MBienvenidaInscritaActiva'
update ConfiguracionPaisDatos set Valor1 = 'CONSULTORAS YA SUSCRITAS', Valor2 = '¡GANAN HASTA 10% MÁS!' where Codigo = 'MBienvenidaInscritaNoActiva'
update ConfiguracionPaisDatos set Valor1 = '#NOMBRE, TODAS <b>TUS OFERTAS EN UN SOLO LUGAR</b>', Valor2 = '' where Codigo = 'MBienvenidaNoInscritaActiva'
update ConfiguracionPaisDatos set Valor1 = '#NOMBRE, TODAS <b>TUS OFERTAS EN UN SOLO LUGAR</b>', Valor2 = '' where Codigo = 'MBienvenidaNoInscritaNoActiva'

update ConfiguracionPaisDatos set Valor1 = 'CONSULTORAS YA SUSCRITAS', Valor2 = '¡GANAN HASTA 10% MÁS!' where Codigo = 'DPedidoInscritaActiva'
update ConfiguracionPaisDatos set Valor1 = 'CONSULTORAS YA SUSCRITAS', Valor2 = '¡GANAN HASTA 10% MÁS!' where Codigo = 'DPedidoInscritaNoActiva'
update ConfiguracionPaisDatos set Valor1 = '#NOMBRE, TODAS', Valor2 = 'TUS OFERTAS EN UN<br/> SOLO LUGAR' where Codigo = 'DPedidoNoInscritaActiva'
update ConfiguracionPaisDatos set Valor1 = '#NOMBRE, TODAS', Valor2 = 'TUS OFERTAS EN UN<br/> SOLO LUGAR' where Codigo = 'DPedidoNoInscritaNoActiva'
update ConfiguracionPaisDatos set Valor1 = 'CONSULTORAS YA SUSCRITAS', Valor2 = '¡GANAN HASTA 10% MÁS!' where Codigo = 'MPedidoInscritaActiva'
update ConfiguracionPaisDatos set Valor1 = 'CONSULTORAS YA SUSCRITAS', Valor2 = '¡GANAN HASTA 10% MÁS!' where Codigo = 'MPedidoInscritaNoActiva'
update ConfiguracionPaisDatos set Valor1 = '#NOMBRE, TODAS <b>TUS OFERTAS EN UN SOLO LUGAR</b>', Valor2 = '' where Codigo = 'MPedidoNoInscritaActiva'
update ConfiguracionPaisDatos set Valor1 = '#NOMBRE, TODAS <b>TUS OFERTAS EN UN SOLO LUGAR</b>', Valor2 = '' where Codigo = 'MPedidoNoInscritaNoActiva'
