GO
IF NOT EXISTS(SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebDetalle'
	AND C.NAME = 'TipoEstrategiaID')
BEGIN
	ALTER TABLE PedidoWebDetalle
	ADD TipoEstrategiaID int
	CONSTRAINT COST_TipoEstrategia_TipoEstrategiaID DEFAULT 0
END
GO
