USE BelcorpBolivia
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = N'Encuesta' and schema_id = 1)
BEGIN

DROP TABLE dbo.Encuesta;

END
GO

CREATE TABLE dbo.Encuesta(
Id INT IDENTITY(1,1) NOT NULL,
Descripcion NVARCHAR(60) NOT NULL,
FechaDesde DATETIME NOT NULL,
FechaHasta DATETIME NOT NULL,
Prioridad INT NOT NULL,
CreatedBy NVARCHAR(30) NOT NULL,
CreatedOn DATETIME NOT NULL CONSTRAINT DF_Encuesta_CreatedOn DEFAULT (GETDATE()),
CreatedHost NVARCHAR(20) NULL,
ModifiedBy NVARCHAR(30) NULL,
ModifiedOn DATETIME NULL,
ModifiedHost NVARCHAR(20) NULL,
Status AS CASE WHEN FechaHasta > FechaDesde THEN 1 ELSE 0 END
)
GO

ALTER TABLE dbo.Encuesta WITH CHECK ADD CONSTRAINT PK_Encuesta_Id PRIMARY KEY CLUSTERED (Id) ON [PRIMARY];

GO

USE BelcorpChile
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = N'Encuesta' and schema_id = 1)
BEGIN

DROP TABLE dbo.Encuesta;

END
GO

CREATE TABLE dbo.Encuesta(
Id INT IDENTITY(1,1) NOT NULL,
Descripcion NVARCHAR(60) NOT NULL,
FechaDesde DATETIME NOT NULL,
FechaHasta DATETIME NOT NULL,
Prioridad INT NOT NULL,
CreatedBy NVARCHAR(30) NOT NULL,
CreatedOn DATETIME NOT NULL CONSTRAINT DF_Encuesta_CreatedOn DEFAULT (GETDATE()),
CreatedHost NVARCHAR(20) NULL,
ModifiedBy NVARCHAR(30) NULL,
ModifiedOn DATETIME NULL,
ModifiedHost NVARCHAR(20) NULL,
Status AS CASE WHEN FechaHasta > FechaDesde THEN 1 ELSE 0 END
)
GO

ALTER TABLE dbo.Encuesta WITH CHECK ADD CONSTRAINT PK_Encuesta_Id PRIMARY KEY CLUSTERED (Id) ON [PRIMARY];

GO

USE BelcorpColombia
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = N'Encuesta' and schema_id = 1)
BEGIN

DROP TABLE dbo.Encuesta;

END
GO

CREATE TABLE dbo.Encuesta(
Id INT IDENTITY(1,1) NOT NULL,
Descripcion NVARCHAR(60) NOT NULL,
FechaDesde DATETIME NOT NULL,
FechaHasta DATETIME NOT NULL,
Prioridad INT NOT NULL,
CreatedBy NVARCHAR(30) NOT NULL,
CreatedOn DATETIME NOT NULL CONSTRAINT DF_Encuesta_CreatedOn DEFAULT (GETDATE()),
CreatedHost NVARCHAR(20) NULL,
ModifiedBy NVARCHAR(30) NULL,
ModifiedOn DATETIME NULL,
ModifiedHost NVARCHAR(20) NULL,
Status AS CASE WHEN FechaHasta > FechaDesde THEN 1 ELSE 0 END
)
GO

ALTER TABLE dbo.Encuesta WITH CHECK ADD CONSTRAINT PK_Encuesta_Id PRIMARY KEY CLUSTERED (Id) ON [PRIMARY];

GO
	
USE BelcorpCostaRica
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = N'Encuesta' and schema_id = 1)
BEGIN

DROP TABLE dbo.Encuesta;

END
GO

CREATE TABLE dbo.Encuesta(
Id INT IDENTITY(1,1) NOT NULL,
Descripcion NVARCHAR(60) NOT NULL,
FechaDesde DATETIME NOT NULL,
FechaHasta DATETIME NOT NULL,
Prioridad INT NOT NULL,
CreatedBy NVARCHAR(30) NOT NULL,
CreatedOn DATETIME NOT NULL CONSTRAINT DF_Encuesta_CreatedOn DEFAULT (GETDATE()),
CreatedHost NVARCHAR(20) NULL,
ModifiedBy NVARCHAR(30) NULL,
ModifiedOn DATETIME NULL,
ModifiedHost NVARCHAR(20) NULL,
Status AS CASE WHEN FechaHasta > FechaDesde THEN 1 ELSE 0 END
)
GO

ALTER TABLE dbo.Encuesta WITH CHECK ADD CONSTRAINT PK_Encuesta_Id PRIMARY KEY CLUSTERED (Id) ON [PRIMARY];

GO

USE BelcorpDominicana
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = N'Encuesta' and schema_id = 1)
BEGIN

DROP TABLE dbo.Encuesta;

END
GO

CREATE TABLE dbo.Encuesta(
Id INT IDENTITY(1,1) NOT NULL,
Descripcion NVARCHAR(60) NOT NULL,
FechaDesde DATETIME NOT NULL,
FechaHasta DATETIME NOT NULL,
Prioridad INT NOT NULL,
CreatedBy NVARCHAR(30) NOT NULL,
CreatedOn DATETIME NOT NULL CONSTRAINT DF_Encuesta_CreatedOn DEFAULT (GETDATE()),
CreatedHost NVARCHAR(20) NULL,
ModifiedBy NVARCHAR(30) NULL,
ModifiedOn DATETIME NULL,
ModifiedHost NVARCHAR(20) NULL,
Status AS CASE WHEN FechaHasta > FechaDesde THEN 1 ELSE 0 END
)
GO

ALTER TABLE dbo.Encuesta WITH CHECK ADD CONSTRAINT PK_Encuesta_Id PRIMARY KEY CLUSTERED (Id) ON [PRIMARY];

GO

USE BelcorpEcuador
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = N'Encuesta' and schema_id = 1)
BEGIN

DROP TABLE dbo.Encuesta;

END
GO

CREATE TABLE dbo.Encuesta(
Id INT IDENTITY(1,1) NOT NULL,
Descripcion NVARCHAR(60) NOT NULL,
FechaDesde DATETIME NOT NULL,
FechaHasta DATETIME NOT NULL,
Prioridad INT NOT NULL,
CreatedBy NVARCHAR(30) NOT NULL,
CreatedOn DATETIME NOT NULL CONSTRAINT DF_Encuesta_CreatedOn DEFAULT (GETDATE()),
CreatedHost NVARCHAR(20) NULL,
ModifiedBy NVARCHAR(30) NULL,
ModifiedOn DATETIME NULL,
ModifiedHost NVARCHAR(20) NULL,
Status AS CASE WHEN FechaHasta > FechaDesde THEN 1 ELSE 0 END
)
GO

ALTER TABLE dbo.Encuesta WITH CHECK ADD CONSTRAINT PK_Encuesta_Id PRIMARY KEY CLUSTERED (Id) ON [PRIMARY];

GO

USE BelcorpGuatemala
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = N'Encuesta' and schema_id = 1)
BEGIN

DROP TABLE dbo.Encuesta;

END
GO

CREATE TABLE dbo.Encuesta(
Id INT IDENTITY(1,1) NOT NULL,
Descripcion NVARCHAR(60) NOT NULL,
FechaDesde DATETIME NOT NULL,
FechaHasta DATETIME NOT NULL,
Prioridad INT NOT NULL,
CreatedBy NVARCHAR(30) NOT NULL,
CreatedOn DATETIME NOT NULL CONSTRAINT DF_Encuesta_CreatedOn DEFAULT (GETDATE()),
CreatedHost NVARCHAR(20) NULL,
ModifiedBy NVARCHAR(30) NULL,
ModifiedOn DATETIME NULL,
ModifiedHost NVARCHAR(20) NULL,
Status AS CASE WHEN FechaHasta > FechaDesde THEN 1 ELSE 0 END
)
GO

ALTER TABLE dbo.Encuesta WITH CHECK ADD CONSTRAINT PK_Encuesta_Id PRIMARY KEY CLUSTERED (Id) ON [PRIMARY];

GO

USE BelcorpMexico
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = N'Encuesta' and schema_id = 1)
BEGIN

DROP TABLE dbo.Encuesta;

END
GO

CREATE TABLE dbo.Encuesta(
Id INT IDENTITY(1,1) NOT NULL,
Descripcion NVARCHAR(60) NOT NULL,
FechaDesde DATETIME NOT NULL,
FechaHasta DATETIME NOT NULL,
Prioridad INT NOT NULL,
CreatedBy NVARCHAR(30) NOT NULL,
CreatedOn DATETIME NOT NULL CONSTRAINT DF_Encuesta_CreatedOn DEFAULT (GETDATE()),
CreatedHost NVARCHAR(20) NULL,
ModifiedBy NVARCHAR(30) NULL,
ModifiedOn DATETIME NULL,
ModifiedHost NVARCHAR(20) NULL,
Status AS CASE WHEN FechaHasta > FechaDesde THEN 1 ELSE 0 END
)
GO

ALTER TABLE dbo.Encuesta WITH CHECK ADD CONSTRAINT PK_Encuesta_Id PRIMARY KEY CLUSTERED (Id) ON [PRIMARY];

GO

USE BelcorpPanama
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = N'Encuesta' and schema_id = 1)
BEGIN

DROP TABLE dbo.Encuesta;

END
GO

CREATE TABLE dbo.Encuesta(
Id INT IDENTITY(1,1) NOT NULL,
Descripcion NVARCHAR(60) NOT NULL,
FechaDesde DATETIME NOT NULL,
FechaHasta DATETIME NOT NULL,
Prioridad INT NOT NULL,
CreatedBy NVARCHAR(30) NOT NULL,
CreatedOn DATETIME NOT NULL CONSTRAINT DF_Encuesta_CreatedOn DEFAULT (GETDATE()),
CreatedHost NVARCHAR(20) NULL,
ModifiedBy NVARCHAR(30) NULL,
ModifiedOn DATETIME NULL,
ModifiedHost NVARCHAR(20) NULL,
Status AS CASE WHEN FechaHasta > FechaDesde THEN 1 ELSE 0 END
)
GO

ALTER TABLE dbo.Encuesta WITH CHECK ADD CONSTRAINT PK_Encuesta_Id PRIMARY KEY CLUSTERED (Id) ON [PRIMARY];

GO

USE BelcorpPeru
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = N'Encuesta' and schema_id = 1)
BEGIN

DROP TABLE dbo.Encuesta;

END
GO

CREATE TABLE dbo.Encuesta(
Id INT IDENTITY(1,1) NOT NULL,
Descripcion NVARCHAR(60) NOT NULL,
FechaDesde DATETIME NOT NULL,
FechaHasta DATETIME NOT NULL,
Prioridad INT NOT NULL,
CreatedBy NVARCHAR(30) NOT NULL,
CreatedOn DATETIME NOT NULL CONSTRAINT DF_Encuesta_CreatedOn DEFAULT (GETDATE()),
CreatedHost NVARCHAR(20) NULL,
ModifiedBy NVARCHAR(30) NULL,
ModifiedOn DATETIME NULL,
ModifiedHost NVARCHAR(20) NULL,
Status AS CASE WHEN FechaHasta > FechaDesde THEN 1 ELSE 0 END
)
GO

ALTER TABLE dbo.Encuesta WITH CHECK ADD CONSTRAINT PK_Encuesta_Id PRIMARY KEY CLUSTERED (Id) ON [PRIMARY];

GO

USE BelcorpPuertoRico
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = N'Encuesta' and schema_id = 1)
BEGIN

DROP TABLE dbo.Encuesta;

END
GO

CREATE TABLE dbo.Encuesta(
Id INT IDENTITY(1,1) NOT NULL,
Descripcion NVARCHAR(60) NOT NULL,
FechaDesde DATETIME NOT NULL,
FechaHasta DATETIME NOT NULL,
Prioridad INT NOT NULL,
CreatedBy NVARCHAR(30) NOT NULL,
CreatedOn DATETIME NOT NULL CONSTRAINT DF_Encuesta_CreatedOn DEFAULT (GETDATE()),
CreatedHost NVARCHAR(20) NULL,
ModifiedBy NVARCHAR(30) NULL,
ModifiedOn DATETIME NULL,
ModifiedHost NVARCHAR(20) NULL,
Status AS CASE WHEN FechaHasta > FechaDesde THEN 1 ELSE 0 END
)
GO

ALTER TABLE dbo.Encuesta WITH CHECK ADD CONSTRAINT PK_Encuesta_Id PRIMARY KEY CLUSTERED (Id) ON [PRIMARY];

GO

USE BelcorpSalvador
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name = N'Encuesta' and schema_id = 1)
BEGIN

DROP TABLE dbo.Encuesta;

END
GO

CREATE TABLE dbo.Encuesta(
Id INT IDENTITY(1,1) NOT NULL,
Descripcion NVARCHAR(60) NOT NULL,
FechaDesde DATETIME NOT NULL,
FechaHasta DATETIME NOT NULL,
Prioridad INT NOT NULL,
CreatedBy NVARCHAR(30) NOT NULL,
CreatedOn DATETIME NOT NULL CONSTRAINT DF_Encuesta_CreatedOn DEFAULT (GETDATE()),
CreatedHost NVARCHAR(20) NULL,
ModifiedBy NVARCHAR(30) NULL,
ModifiedOn DATETIME NULL,
ModifiedHost NVARCHAR(20) NULL,
Status AS CASE WHEN FechaHasta > FechaDesde THEN 1 ELSE 0 END
)
GO

ALTER TABLE dbo.Encuesta WITH CHECK ADD CONSTRAINT PK_Encuesta_Id PRIMARY KEY CLUSTERED (Id) ON [PRIMARY];

GO


