USE BelcorpPeru
GO
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO

CREATE proc [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP

	UNION ALL

	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))

END
GO


USE BelcorpColombia
GO
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO

CREATE proc [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP

	UNION ALL

	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))

END
GO


USE BelcorpMexico
GO
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO

CREATE proc [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP

	UNION ALL

	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))

END
GO


USE BelcorpChile
GO
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO

CREATE proc [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP

	UNION ALL

	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))

END
GO

USE [BelcorpChile_Plan20]
GO

DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO

CREATE proc [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP

	UNION ALL

	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))

END
GO


USE BelcorpBolivia
GO
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO

CREATE proc [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP

	UNION ALL

	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))

END
GO


USE BelcorpEcuador
GO
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO

CREATE proc [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP

	UNION ALL

	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))

END
GO


USE BelcorpCostaRica
GO
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO

CREATE proc [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP

	UNION ALL

	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))

END
GO


USE BelcorpDominicana
GO
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO

CREATE proc [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP

	UNION ALL

	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))

END
GO


USE BelcorpGuatemala
GO
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO

CREATE proc [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP

	UNION ALL

	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))

END
GO


USE BelcorpPanama
GO
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO

CREATE proc [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP

	UNION ALL

	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))

END
GO


USE BelcorpPuertoRico
GO
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO

CREATE proc [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP

	UNION ALL

	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))

END
GO


USE BelcorpSalvador
GO
GO
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO

CREATE proc [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP

	UNION ALL

	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))

END
GO


USE BelcorpVenezuela
GO
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO

CREATE proc [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP

	UNION ALL

	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))

END
GO