//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Consultoras.Data.ServiceSicc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/Belcorp.BDI.Service.PROL.Entidad")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoPeriodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoVtaGanadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoPedMontoMaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoPedMontoMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string formaPagoGanadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string indValiProlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string montoMaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string montoPedMontoMaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string montoPedMontoMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidOfertaGanadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidProductoGanadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Portal.Consultoras.Data.ServiceSicc.Detalle[] posicionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string precioGanadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string indEnvioSapField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoClienteField, value) != true)) {
                    this.codigoClienteField = value;
                    this.RaisePropertyChanged("codigoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoPais {
            get {
                return this.codigoPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoPaisField, value) != true)) {
                    this.codigoPaisField = value;
                    this.RaisePropertyChanged("codigoPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoPeriodo {
            get {
                return this.codigoPeriodoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoPeriodoField, value) != true)) {
                    this.codigoPeriodoField = value;
                    this.RaisePropertyChanged("codigoPeriodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoVtaGanador {
            get {
                return this.codigoVtaGanadorField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoVtaGanadorField, value) != true)) {
                    this.codigoVtaGanadorField = value;
                    this.RaisePropertyChanged("codigoVtaGanador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadoPedMontoMax {
            get {
                return this.estadoPedMontoMaxField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoPedMontoMaxField, value) != true)) {
                    this.estadoPedMontoMaxField = value;
                    this.RaisePropertyChanged("estadoPedMontoMax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadoPedMontoMin {
            get {
                return this.estadoPedMontoMinField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoPedMontoMinField, value) != true)) {
                    this.estadoPedMontoMinField = value;
                    this.RaisePropertyChanged("estadoPedMontoMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string formaPagoGanador {
            get {
                return this.formaPagoGanadorField;
            }
            set {
                if ((object.ReferenceEquals(this.formaPagoGanadorField, value) != true)) {
                    this.formaPagoGanadorField = value;
                    this.RaisePropertyChanged("formaPagoGanador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string indValiProl {
            get {
                return this.indValiProlField;
            }
            set {
                if ((object.ReferenceEquals(this.indValiProlField, value) != true)) {
                    this.indValiProlField = value;
                    this.RaisePropertyChanged("indValiProl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string montoMax {
            get {
                return this.montoMaxField;
            }
            set {
                if ((object.ReferenceEquals(this.montoMaxField, value) != true)) {
                    this.montoMaxField = value;
                    this.RaisePropertyChanged("montoMax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string montoPedMontoMax {
            get {
                return this.montoPedMontoMaxField;
            }
            set {
                if ((object.ReferenceEquals(this.montoPedMontoMaxField, value) != true)) {
                    this.montoPedMontoMaxField = value;
                    this.RaisePropertyChanged("montoPedMontoMax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string montoPedMontoMin {
            get {
                return this.montoPedMontoMinField;
            }
            set {
                if ((object.ReferenceEquals(this.montoPedMontoMinField, value) != true)) {
                    this.montoPedMontoMinField = value;
                    this.RaisePropertyChanged("montoPedMontoMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string oidOfertaGanador {
            get {
                return this.oidOfertaGanadorField;
            }
            set {
                if ((object.ReferenceEquals(this.oidOfertaGanadorField, value) != true)) {
                    this.oidOfertaGanadorField = value;
                    this.RaisePropertyChanged("oidOfertaGanador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string oidProductoGanador {
            get {
                return this.oidProductoGanadorField;
            }
            set {
                if ((object.ReferenceEquals(this.oidProductoGanadorField, value) != true)) {
                    this.oidProductoGanadorField = value;
                    this.RaisePropertyChanged("oidProductoGanador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Portal.Consultoras.Data.ServiceSicc.Detalle[] posiciones {
            get {
                return this.posicionesField;
            }
            set {
                if ((object.ReferenceEquals(this.posicionesField, value) != true)) {
                    this.posicionesField = value;
                    this.RaisePropertyChanged("posiciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string precioGanador {
            get {
                return this.precioGanadorField;
            }
            set {
                if ((object.ReferenceEquals(this.precioGanadorField, value) != true)) {
                    this.precioGanadorField = value;
                    this.RaisePropertyChanged("precioGanador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string indEnvioSap {
            get {
                return this.indEnvioSapField;
            }
            set {
                if ((object.ReferenceEquals(this.indEnvioSapField, value) != true)) {
                    this.indEnvioSapField = value;
                    this.RaisePropertyChanged("indEnvioSap");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Detalle", Namespace="http://schemas.datacontract.org/2004/07/Belcorp.BDI.Service.PROL.Entidad")]
    [System.SerializableAttribute()]
    public partial class Detalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoSAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string factorCuadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string factorRepeticionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string indAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string indLimiteVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numUnidOrigField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidCatalogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidDetaOfertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidEstrategiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidFormaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidGrupoOfertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidIndicadorCuadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidNiveOfertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidNiveOfertaGratisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidNiveOfertaRangoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidOfertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidPosicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidSubtipoPosicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oidTipoPosicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paginaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string precioCatalogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string precioContableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string precioUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rankingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unidadesDemandadasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unidadesPorAtenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valCodiOrigField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoSAP {
            get {
                return this.codigoSAPField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoSAPField, value) != true)) {
                    this.codigoSAPField = value;
                    this.RaisePropertyChanged("codigoSAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string CUV {
            get {
                return this.CUVField;
            }
            set {
                if ((object.ReferenceEquals(this.CUVField, value) != true)) {
                    this.CUVField = value;
                    this.RaisePropertyChanged("CUV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string factorCuadre {
            get {
                return this.factorCuadreField;
            }
            set {
                if ((object.ReferenceEquals(this.factorCuadreField, value) != true)) {
                    this.factorCuadreField = value;
                    this.RaisePropertyChanged("factorCuadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string factorRepeticion {
            get {
                return this.factorRepeticionField;
            }
            set {
                if ((object.ReferenceEquals(this.factorRepeticionField, value) != true)) {
                    this.factorRepeticionField = value;
                    this.RaisePropertyChanged("factorRepeticion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string indAccion {
            get {
                return this.indAccionField;
            }
            set {
                if ((object.ReferenceEquals(this.indAccionField, value) != true)) {
                    this.indAccionField = value;
                    this.RaisePropertyChanged("indAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string indLimiteVenta {
            get {
                return this.indLimiteVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.indLimiteVentaField, value) != true)) {
                    this.indLimiteVentaField = value;
                    this.RaisePropertyChanged("indLimiteVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string numUnidOrig {
            get {
                return this.numUnidOrigField;
            }
            set {
                if ((object.ReferenceEquals(this.numUnidOrigField, value) != true)) {
                    this.numUnidOrigField = value;
                    this.RaisePropertyChanged("numUnidOrig");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.observacionesField, value) != true)) {
                    this.observacionesField = value;
                    this.RaisePropertyChanged("observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string oidCatalogo {
            get {
                return this.oidCatalogoField;
            }
            set {
                if ((object.ReferenceEquals(this.oidCatalogoField, value) != true)) {
                    this.oidCatalogoField = value;
                    this.RaisePropertyChanged("oidCatalogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string oidDetaOferta {
            get {
                return this.oidDetaOfertaField;
            }
            set {
                if ((object.ReferenceEquals(this.oidDetaOfertaField, value) != true)) {
                    this.oidDetaOfertaField = value;
                    this.RaisePropertyChanged("oidDetaOferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string oidEstrategia {
            get {
                return this.oidEstrategiaField;
            }
            set {
                if ((object.ReferenceEquals(this.oidEstrategiaField, value) != true)) {
                    this.oidEstrategiaField = value;
                    this.RaisePropertyChanged("oidEstrategia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string oidFormaPago {
            get {
                return this.oidFormaPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.oidFormaPagoField, value) != true)) {
                    this.oidFormaPagoField = value;
                    this.RaisePropertyChanged("oidFormaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string oidGrupoOferta {
            get {
                return this.oidGrupoOfertaField;
            }
            set {
                if ((object.ReferenceEquals(this.oidGrupoOfertaField, value) != true)) {
                    this.oidGrupoOfertaField = value;
                    this.RaisePropertyChanged("oidGrupoOferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string oidIndicadorCuadre {
            get {
                return this.oidIndicadorCuadreField;
            }
            set {
                if ((object.ReferenceEquals(this.oidIndicadorCuadreField, value) != true)) {
                    this.oidIndicadorCuadreField = value;
                    this.RaisePropertyChanged("oidIndicadorCuadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string oidNiveOferta {
            get {
                return this.oidNiveOfertaField;
            }
            set {
                if ((object.ReferenceEquals(this.oidNiveOfertaField, value) != true)) {
                    this.oidNiveOfertaField = value;
                    this.RaisePropertyChanged("oidNiveOferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string oidNiveOfertaGratis {
            get {
                return this.oidNiveOfertaGratisField;
            }
            set {
                if ((object.ReferenceEquals(this.oidNiveOfertaGratisField, value) != true)) {
                    this.oidNiveOfertaGratisField = value;
                    this.RaisePropertyChanged("oidNiveOfertaGratis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string oidNiveOfertaRango {
            get {
                return this.oidNiveOfertaRangoField;
            }
            set {
                if ((object.ReferenceEquals(this.oidNiveOfertaRangoField, value) != true)) {
                    this.oidNiveOfertaRangoField = value;
                    this.RaisePropertyChanged("oidNiveOfertaRango");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string oidOferta {
            get {
                return this.oidOfertaField;
            }
            set {
                if ((object.ReferenceEquals(this.oidOfertaField, value) != true)) {
                    this.oidOfertaField = value;
                    this.RaisePropertyChanged("oidOferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string oidPosicion {
            get {
                return this.oidPosicionField;
            }
            set {
                if ((object.ReferenceEquals(this.oidPosicionField, value) != true)) {
                    this.oidPosicionField = value;
                    this.RaisePropertyChanged("oidPosicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public string oidProducto {
            get {
                return this.oidProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.oidProductoField, value) != true)) {
                    this.oidProductoField = value;
                    this.RaisePropertyChanged("oidProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string oidSubtipoPosicion {
            get {
                return this.oidSubtipoPosicionField;
            }
            set {
                if ((object.ReferenceEquals(this.oidSubtipoPosicionField, value) != true)) {
                    this.oidSubtipoPosicionField = value;
                    this.RaisePropertyChanged("oidSubtipoPosicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string oidTipoPosicion {
            get {
                return this.oidTipoPosicionField;
            }
            set {
                if ((object.ReferenceEquals(this.oidTipoPosicionField, value) != true)) {
                    this.oidTipoPosicionField = value;
                    this.RaisePropertyChanged("oidTipoPosicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                if ((object.ReferenceEquals(this.paginaField, value) != true)) {
                    this.paginaField = value;
                    this.RaisePropertyChanged("pagina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public string precioCatalogo {
            get {
                return this.precioCatalogoField;
            }
            set {
                if ((object.ReferenceEquals(this.precioCatalogoField, value) != true)) {
                    this.precioCatalogoField = value;
                    this.RaisePropertyChanged("precioCatalogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public string precioContable {
            get {
                return this.precioContableField;
            }
            set {
                if ((object.ReferenceEquals(this.precioContableField, value) != true)) {
                    this.precioContableField = value;
                    this.RaisePropertyChanged("precioContable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public string precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                if ((object.ReferenceEquals(this.precioUnitarioField, value) != true)) {
                    this.precioUnitarioField = value;
                    this.RaisePropertyChanged("precioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public string ranking {
            get {
                return this.rankingField;
            }
            set {
                if ((object.ReferenceEquals(this.rankingField, value) != true)) {
                    this.rankingField = value;
                    this.RaisePropertyChanged("ranking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public string unidadesDemandadas {
            get {
                return this.unidadesDemandadasField;
            }
            set {
                if ((object.ReferenceEquals(this.unidadesDemandadasField, value) != true)) {
                    this.unidadesDemandadasField = value;
                    this.RaisePropertyChanged("unidadesDemandadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public string unidadesPorAtender {
            get {
                return this.unidadesPorAtenderField;
            }
            set {
                if ((object.ReferenceEquals(this.unidadesPorAtenderField, value) != true)) {
                    this.unidadesPorAtenderField = value;
                    this.RaisePropertyChanged("unidadesPorAtender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public string valCodiOrig {
            get {
                return this.valCodiOrigField;
            }
            set {
                if ((object.ReferenceEquals(this.valCodiOrigField, value) != true)) {
                    this.valCodiOrigField = value;
                    this.RaisePropertyChanged("valCodiOrig");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSicc.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EjecutarCuadreOfertas", ReplyAction="http://tempuri.org/IService/EjecutarCuadreOfertasResponse")]
        Portal.Consultoras.Data.ServiceSicc.Pedido EjecutarCuadreOfertas(Portal.Consultoras.Data.ServiceSicc.Pedido input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EjecutarCuadreOfertas", ReplyAction="http://tempuri.org/IService/EjecutarCuadreOfertasResponse")]
        System.Threading.Tasks.Task<Portal.Consultoras.Data.ServiceSicc.Pedido> EjecutarCuadreOfertasAsync(Portal.Consultoras.Data.ServiceSicc.Pedido input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Portal.Consultoras.Data.ServiceSicc.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Portal.Consultoras.Data.ServiceSicc.IService>, Portal.Consultoras.Data.ServiceSicc.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Portal.Consultoras.Data.ServiceSicc.Pedido EjecutarCuadreOfertas(Portal.Consultoras.Data.ServiceSicc.Pedido input) {
            return base.Channel.EjecutarCuadreOfertas(input);
        }
        
        public System.Threading.Tasks.Task<Portal.Consultoras.Data.ServiceSicc.Pedido> EjecutarCuadreOfertasAsync(Portal.Consultoras.Data.ServiceSicc.Pedido input) {
            return base.Channel.EjecutarCuadreOfertasAsync(input);
        }
    }
}
