USE BelcorpPeru
GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerDNI')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerDNI
END

ALTER TABLE PedidoWeb
  ADD RecogerDNI VARCHAR(50);

GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerNombre')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerNombre
END

ALTER TABLE PedidoWeb
  ADD RecogerNombre VARCHAR(150);

USE BelcorpMexico
GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerDNI')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerDNI
END

ALTER TABLE PedidoWeb
  ADD RecogerDNI VARCHAR(50);

GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerNombre')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerNombre
END

ALTER TABLE PedidoWeb
  ADD RecogerNombre VARCHAR(150);

USE BelcorpColombia
GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerDNI')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerDNI
END

ALTER TABLE PedidoWeb
  ADD RecogerDNI VARCHAR(50);

GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerNombre')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerNombre
END

ALTER TABLE PedidoWeb
  ADD RecogerNombre VARCHAR(150);

USE BelcorpSalvador
GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerDNI')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerDNI
END

ALTER TABLE PedidoWeb
  ADD RecogerDNI VARCHAR(50);

GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerNombre')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerNombre
END

ALTER TABLE PedidoWeb
  ADD RecogerNombre VARCHAR(150);

USE BelcorpPuertoRico
GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerDNI')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerDNI
END

ALTER TABLE PedidoWeb
  ADD RecogerDNI VARCHAR(50);

GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerNombre')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerNombre
END

ALTER TABLE PedidoWeb
  ADD RecogerNombre VARCHAR(150);

USE BelcorpPanama
GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerDNI')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerDNI
END

ALTER TABLE PedidoWeb
  ADD RecogerDNI VARCHAR(50);

GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerNombre')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerNombre
END

ALTER TABLE PedidoWeb
  ADD RecogerNombre VARCHAR(150);

USE BelcorpGuatemala
GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerDNI')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerDNI
END

ALTER TABLE PedidoWeb
  ADD RecogerDNI VARCHAR(50);

GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerNombre')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerNombre
END

ALTER TABLE PedidoWeb
  ADD RecogerNombre VARCHAR(150);

USE BelcorpEcuador
GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerDNI')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerDNI
END

ALTER TABLE PedidoWeb
  ADD RecogerDNI VARCHAR(50);

GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerNombre')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerNombre
END

ALTER TABLE PedidoWeb
  ADD RecogerNombre VARCHAR(150);

USE BelcorpDominicana
GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerDNI')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerDNI
END

ALTER TABLE PedidoWeb
  ADD RecogerDNI VARCHAR(50);

GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerNombre')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerNombre
END

ALTER TABLE PedidoWeb
  ADD RecogerNombre VARCHAR(150);

USE BelcorpCostaRica
GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerDNI')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerDNI
END

ALTER TABLE PedidoWeb
  ADD RecogerDNI VARCHAR(50);

GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerNombre')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerNombre
END

ALTER TABLE PedidoWeb
  ADD RecogerNombre VARCHAR(150);

USE BelcorpChile
GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerDNI')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerDNI
END

ALTER TABLE PedidoWeb
  ADD RecogerDNI VARCHAR(50);

GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerNombre')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerNombre
END

ALTER TABLE PedidoWeb
  ADD RecogerNombre VARCHAR(150);

USE BelcorpBolivia
GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerDNI')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerDNI
END

ALTER TABLE PedidoWeb
  ADD RecogerDNI VARCHAR(50);

GO

IF EXISTS (SELECT *  FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'PedidoWeb' AND C.NAME = 'RecogerNombre')
BEGIN
	ALTER TABLE PedidoWeb
	DROP COLUMN RecogerNombre
END

ALTER TABLE PedidoWeb
  ADD RecogerNombre VARCHAR(150);