

 DECLARE @statament1 varchar(2000)='USE [?];IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
 WHERE TABLE_NAME = ''tablalogica'')
 BEGIN 
 IF NOT EXISTS  (SELECT * FROM TABLALOGICA WHERE DESCRIPCION =''Campanas AppCatalogo'')
 BEGIN
 INSERT INTO TABLALOGICA  VALUES (156,''Campanas AppCatalogo'')
 INSERT INTO TABLALOGICADATOS  VALUES (15601,156,01,''Campanas Atras'',5)
 INSERT INTO TABLALOGICADATOS  VALUES (15602,156,02,''Campanas Adelante'',2)
 END
 END'

 EXEC sp_MSForEachDB  @statament1 
