
USE BelcorpColombia
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES 
		WHERE TABLE_NAME = N'CertificadoDigitalLog')
BEGIN
	DROP TABLE dbo.CertificadoDigitalLog
END
GO

USE BelcorpEcuador
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES 
		WHERE TABLE_NAME = N'CertificadoDigitalLog')
BEGIN
	DROP TABLE dbo.CertificadoDigitalLog
END
GO