USE BelcorpBolivia
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebDetalleCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebDetalleCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebDetalleCulminado(
	LogCDRWebDetalleCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	LogCDRWebCulminadoId INT NOT NULL,
	CodigoOperacion VARCHAR(5) NOT NULL,
	CodigoReclamo VARCHAR(5) NOT NULL,
	CUV VARCHAR(5) NOT NULL,
	Cantidad INT NOT NULL,
	CUV2 VARCHAR(5) NULL,
	Cantidad2 INT NULL,
	FechaRegistro DATETIME NOT NULL,
);
GO
/*end*/

USE BelcorpChile
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebDetalleCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebDetalleCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebDetalleCulminado(
	LogCDRWebDetalleCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	LogCDRWebCulminadoId INT NOT NULL,
	CodigoOperacion VARCHAR(5) NOT NULL,
	CodigoReclamo VARCHAR(5) NOT NULL,
	CUV VARCHAR(5) NOT NULL,
	Cantidad INT NOT NULL,
	CUV2 VARCHAR(5) NULL,
	Cantidad2 INT NULL,
	FechaRegistro DATETIME NOT NULL,
);
GO
/*end*/

USE BelcorpCostaRica
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebDetalleCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebDetalleCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebDetalleCulminado(
	LogCDRWebDetalleCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	LogCDRWebCulminadoId INT NOT NULL,
	CodigoOperacion VARCHAR(5) NOT NULL,
	CodigoReclamo VARCHAR(5) NOT NULL,
	CUV VARCHAR(5) NOT NULL,
	Cantidad INT NOT NULL,
	CUV2 VARCHAR(5) NULL,
	Cantidad2 INT NULL,
	FechaRegistro DATETIME NOT NULL,
);
GO
/*end*/

USE BelcorpDominicana
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebDetalleCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebDetalleCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebDetalleCulminado(
	LogCDRWebDetalleCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	LogCDRWebCulminadoId INT NOT NULL,
	CodigoOperacion VARCHAR(5) NOT NULL,
	CodigoReclamo VARCHAR(5) NOT NULL,
	CUV VARCHAR(5) NOT NULL,
	Cantidad INT NOT NULL,
	CUV2 VARCHAR(5) NULL,
	Cantidad2 INT NULL,
	FechaRegistro DATETIME NOT NULL,
);
GO
/*end*/

USE BelcorpEcuador
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebDetalleCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebDetalleCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebDetalleCulminado(
	LogCDRWebDetalleCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	LogCDRWebCulminadoId INT NOT NULL,
	CodigoOperacion VARCHAR(5) NOT NULL,
	CodigoReclamo VARCHAR(5) NOT NULL,
	CUV VARCHAR(5) NOT NULL,
	Cantidad INT NOT NULL,
	CUV2 VARCHAR(5) NULL,
	Cantidad2 INT NULL,
	FechaRegistro DATETIME NOT NULL,
);
GO
/*end*/

USE BelcorpGuatemala
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebDetalleCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebDetalleCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebDetalleCulminado(
	LogCDRWebDetalleCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	LogCDRWebCulminadoId INT NOT NULL,
	CodigoOperacion VARCHAR(5) NOT NULL,
	CodigoReclamo VARCHAR(5) NOT NULL,
	CUV VARCHAR(5) NOT NULL,
	Cantidad INT NOT NULL,
	CUV2 VARCHAR(5) NULL,
	Cantidad2 INT NULL,
	FechaRegistro DATETIME NOT NULL,
);
GO
/*end*/

USE BelcorpPanama
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebDetalleCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebDetalleCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebDetalleCulminado(
	LogCDRWebDetalleCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	LogCDRWebCulminadoId INT NOT NULL,
	CodigoOperacion VARCHAR(5) NOT NULL,
	CodigoReclamo VARCHAR(5) NOT NULL,
	CUV VARCHAR(5) NOT NULL,
	Cantidad INT NOT NULL,
	CUV2 VARCHAR(5) NULL,
	Cantidad2 INT NULL,
	FechaRegistro DATETIME NOT NULL,
);
GO
/*end*/

USE BelcorpPuertoRico
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebDetalleCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebDetalleCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebDetalleCulminado(
	LogCDRWebDetalleCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	LogCDRWebCulminadoId INT NOT NULL,
	CodigoOperacion VARCHAR(5) NOT NULL,
	CodigoReclamo VARCHAR(5) NOT NULL,
	CUV VARCHAR(5) NOT NULL,
	Cantidad INT NOT NULL,
	CUV2 VARCHAR(5) NULL,
	Cantidad2 INT NULL,
	FechaRegistro DATETIME NOT NULL,
);
GO
/*end*/

USE BelcorpSalvador
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebDetalleCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebDetalleCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebDetalleCulminado(
	LogCDRWebDetalleCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	LogCDRWebCulminadoId INT NOT NULL,
	CodigoOperacion VARCHAR(5) NOT NULL,
	CodigoReclamo VARCHAR(5) NOT NULL,
	CUV VARCHAR(5) NOT NULL,
	Cantidad INT NOT NULL,
	CUV2 VARCHAR(5) NULL,
	Cantidad2 INT NULL,
	FechaRegistro DATETIME NOT NULL,
);
GO
/*end*/

USE BelcorpVenezuela
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebDetalleCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebDetalleCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebDetalleCulminado(
	LogCDRWebDetalleCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	LogCDRWebCulminadoId INT NOT NULL,
	CodigoOperacion VARCHAR(5) NOT NULL,
	CodigoReclamo VARCHAR(5) NOT NULL,
	CUV VARCHAR(5) NOT NULL,
	Cantidad INT NOT NULL,
	CUV2 VARCHAR(5) NULL,
	Cantidad2 INT NULL,
	FechaRegistro DATETIME NOT NULL,
);
GO
/*end*/

USE BelcorpColombia
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebDetalleCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebDetalleCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebDetalleCulminado(
	LogCDRWebDetalleCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	LogCDRWebCulminadoId INT NOT NULL,
	CodigoOperacion VARCHAR(5) NOT NULL,
	CodigoReclamo VARCHAR(5) NOT NULL,
	CUV VARCHAR(5) NOT NULL,
	Cantidad INT NOT NULL,
	CUV2 VARCHAR(5) NULL,
	Cantidad2 INT NULL,
	FechaRegistro DATETIME NOT NULL,
);
GO
/*end*/

USE BelcorpMexico
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebDetalleCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebDetalleCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebDetalleCulminado(
	LogCDRWebDetalleCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	LogCDRWebCulminadoId INT NOT NULL,
	CodigoOperacion VARCHAR(5) NOT NULL,
	CodigoReclamo VARCHAR(5) NOT NULL,
	CUV VARCHAR(5) NOT NULL,
	Cantidad INT NOT NULL,
	CUV2 VARCHAR(5) NULL,
	Cantidad2 INT NULL,
	FechaRegistro DATETIME NOT NULL,
);
GO
/*end*/

USE BelcorpPeru
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebDetalleCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebDetalleCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebDetalleCulminado(
	LogCDRWebDetalleCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	LogCDRWebCulminadoId INT NOT NULL,
	CodigoOperacion VARCHAR(5) NOT NULL,
	CodigoReclamo VARCHAR(5) NOT NULL,
	CUV VARCHAR(5) NOT NULL,
	Cantidad INT NOT NULL,
	CUV2 VARCHAR(5) NULL,
	Cantidad2 INT NULL,
	FechaRegistro DATETIME NOT NULL,
);
GO