
USE BelcorpPeru
GO

IF EXISTS(SELECT 1 FROM SYS.PROCEDURES WHERE NAME ='PROCESARCONSULTORASNUEVAS')
BEGIN

DROP PROCEDURE PROCESARCONSULTORASNUEVAS

END
GO

CREATE PROCEDURE PROCESARCONSULTORASNUEVAS 
	@CANTIDAD_TOP INT,
	@CODIGOISO VARCHAR(3) ,
	@CONSULTORAONLINE INT
AS


---PROCESO
DECLARE @TB_INFORMACION TABLE
(
	CONSULTORAID BIGINT NOT NULL,
	CODIGOUSUARIO VARCHAR(20),
	CODIGOCONSULTORA VARCHAR(25),
	PAISID INT,
	PRIMERNOMBRE VARCHAR(25) NULL,
	SEGUNDONOMBRE VARCHAR(25) NULL,
	PRIMERAPELLIDO VARCHAR(25) NULL,
	SEGUNDOAPELLIDO VARCHAR(25) NULL,
	NOMBRECOMPLETO VARCHAR(200) NULL,
	CLAVESECRETA NVARCHAR(MAX) NULL,
	CLAVEGENERADA VARCHAR(20) NULL,
	EMAIL VARCHAR(100) NULL,
	EMAILACTIVO BIT NULL,
	TELEFONO VARCHAR(20) NULL,
	TELEFONOTRABAJO VARCHAR(20) NULL,
	CELULAR VARCHAR(20) NULL,
	NUMERO_IDENTIFICACION VARCHAR(30) NOT NULL,
	IDESTADOACTIVIDAD INT NULL,
	SOBRENOMBRE VARCHAR(80) NULL,

	COMPARTIRDATOS BIT DEFAULT 0,
	ACTIVO BIT DEFAULT 1,
	TIPOUSUARIO TINYINT DEFAULT 1,
	CAMBIOCLAVE BIT DEFAULT 0,

	GZEMAIL VARCHAR(100) NULL,
	GERENTEZONA VARCHAR(250) NULL,
	CODIGOZONA VARCHAR(8) NULL,
	ZONAID INT
)

DECLARE @T_TIPODOCUMENTOS TABLE
(
	ISOPAIS VARCHAR(3),
	TIPO_DOCUMENTO VARCHAR(4)
)

SET NOCOUNT ON; 
BEGIN TRY
 BEGIN TRAN

	DECLARE @PAISID INT
	DECLARE @CANTIDAD_REGISTROS INT
	
	SET @PAISID = (SELECT TOP(1) PAISID  FROM PAIS Where CODIGOISO = @CODIGOISO)
    INSERT INTO @TB_INFORMACION
	SELECT CONSULTORAID,CODIGOUSUARIO,CODIGOCONSULTORA,@PAISID PAISID,	
			CASE WHEN PRIMERNOMBRE='' AND SEGUNDONOMBRE=''  THEN CODIGOUSUARIO ELSE PRIMERNOMBRE END PRIMERNOMBRE,SEGUNDONOMBRE,			
			CASE WHEN PRIMERAPELLIDO='' THEN CODIGOUSUARIO ELSE PRIMERAPELLIDO END PRIMERAPELLIDO,SEGUNDOAPELLIDO,	
			CASE WHEN NOMBRECOMPLETO ='' THEN CONCAT(PRIMERNOMBRE,' ',SEGUNDONOMBRE,' ',PRIMERAPELLIDO,' ',SEGUNDOAPELLIDO) ELSE NOMBRECOMPLETO END NOMBRECOMPLETO,			
			CLAVE,CLAVEGENERADA,EMAIL,1 EMAILACTIVO,TELEFONO,TELEFONOTRABAJO,CELULAR,NUMERO,IDESTADOACTIVIDAD,
		   SOBRENOMBRE,COMPARTIRDATOS,ACTIVO,TIPOUSUARIO,CAMBIOCLAVE,GZEMAIL,GERENTEZONA,CODIGOZONA,ZONAID	
	FROM (
		SELECT TOP (@CANTIDAD_TOP)
			C.CONSULTORAID,C.CODIGO AS CODIGOUSUARIO,C.CODIGO CODIGOCONSULTORA,
			REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ISNULL(C.PRIMERNOMBRE,''),',',''),'+',''),'"',''),';',''),'\','') PRIMERNOMBRE,
			REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ISNULL(C.SEGUNDONOMBRE,''),',',''),'+',''),'"',''),';',''),'\','') SEGUNDONOMBRE,
			REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ISNULL(C.PRIMERAPELLIDO,''),',',''),'+',''),'"',''),';',''),'\','') PRIMERAPELLIDO,
			REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ISNULL(C.SEGUNDOAPELLIDO,''),',',''),'+',''),'"',''),';',''),'\','') SEGUNDOAPELLIDO,
			REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ISNULL(C.NOMBRECOMPLETO,''),',',''),'+',''),'"',''),';',''),'\','') NOMBRECOMPLETO,
			UPPER(SUBSTRING(master.dbo.fn_varbintohexstr(HashBytes('SHA1',
				UPPER(CONVERT(NVARCHAR,
				CASE WHEN I.TIPODOCUMENTO = 'DNI' AND I.NUMERO <= 7 THEN RIGHT('00000000'+CONVERT(VARCHAR(8),I.NUMERO), 8) 
				WHEN I.TIPODOCUMENTO = 'DNI' AND I.NUMERO > 7 THEN SUBSTRING(I.NUMERO,LEN(I.NUMERO)-7,8)
				ELSE I.NUMERO
				END)))),3,40)) CLAVE,
			CASE	WHEN I.TIPODOCUMENTO = 'DNI' AND I.NUMERO <= 7  THEN RIGHT('00000000'+CONVERT(VARCHAR(8),I.NUMERO), 8) 
					WHEN  I.TIPODOCUMENTO = 'DNI' AND I.NUMERO>7 THEN SUBSTRING(I.NUMERO,LEN(I.NUMERO)-7,8) 
					ELSE I.NUMERO
			END CLAVEGENERADA,
			ISNULL(REPLACE(C.EMAIL,'}',''), '') EMAIL,
			ISNULL((SELECT TOP(1) NUMERO FROM ODS.TELEFONO T WHERE C.CONSULTORAID = T.CONSULTORAID AND TIPOTELEFONO = 'TF'),'') TELEFONO,
			ISNULL((SELECT TOP(1) NUMERO FROM ODS.TELEFONO T WHERE C.CONSULTORAID = T.CONSULTORAID AND TIPOTELEFONO = 'TT'),'') TELEFONOTRABAJO,
			ISNULL((SELECT TOP(1) NUMERO FROM ODS.TELEFONO T WHERE C.CONSULTORAID = T.CONSULTORAID AND TIPOTELEFONO = 'TM'),'') CELULAR,
			IIF(I.TIPODOCUMENTO = 'DNI', ISNULL(I.NUMERO, ''), '') NUMERO,
			C.IDESTADOACTIVIDAD,
			U.SOBRENOMBRE,
			0 COMPARTIRDATOS ,1 ACTIVO,1 TIPOUSUARIO,0 CAMBIOCLAVE,
			--I.TIPODOCUMENTO,
			ISNULL(REPLACE(Z.GZEMAIL,'}',''), '') GZEMAIL,
			ISNULL(Z.GERENTEZONA,'') GERENTEZONA,
			ISNULL(Z.CODIGO,'') CODIGOZONA,
			--ISNULL(C.FECHACARGA,'') FECHACARGA,--R20151116
			Z.ZONAID -- R20151116
		FROM ODS.CONSULTORA C
		LEFT JOIN ODS.IDENTIFICACION I ON C.CONSULTORAID = I.CONSULTORAID AND I.DOCUMENTOPRINCIPAL = '1'
		LEFT JOIN USUARIO U ON C.CODIGO = U.CODIGOCONSULTORA
		LEFT JOIN ODS.ZONA Z ON C.ZONAID = Z.ZONAID
		WHERE U.CODIGOCONSULTORA IS NULL AND LEN(I.NUMERO) > 6 --	AND I.TIPODOCUMENTO='CCI'
			AND ISNULL(I.NUMERO,'')<>''
	) T
		
	SET @CANTIDAD_REGISTROS=@@ROWCOUNT

	--INSERT EN LA TABLA POSTULANTE 
	 IF @CANTIDAD_REGISTROS>0
			BEGIN 
				--CARGA INFORMACIÓN EN LA TABLA DE USUARIO
				INSERT INTO DBO.USUARIO (CODIGOUSUARIO, CODIGOCONSULTORA, PAISID, NOMBRE, CLAVESECRETA, EMAIL,EMAILACTIVO, TELEFONO, TELEFONOTRABAJO, CELULAR, SOBRENOMBRE, COMPARTIRDATOS,ACTIVO, TIPOUSUARIO, CAMBIOCLAVE)
				SELECT CODIGOUSUARIO, CODIGOCONSULTORA, PAISID, CASE WHEN NOMBRECOMPLETO='' THEN CODIGOCONSULTORA ELSE NOMBRECOMPLETO END , CLAVESECRETA, EMAIL,EMAILACTIVO, TELEFONO, TELEFONOTRABAJO, CELULAR, SOBRENOMBRE, COMPARTIRDATOS,ACTIVO, TIPOUSUARIO, CAMBIOCLAVE 
				FROM @TB_INFORMACION

				--- CARGA INFORMACIÓN EN CONSULTORA INGRESO
				INSERT INTO  DBO.CONSULTORAINGRESO (Codigo)	
				SELECT CODIGOUSUARIO FROM @TB_INFORMACION
				-----
				--- CARGA USUARIO ROL
				INSERT INTO DBO.USUARIOROL ([CodigoUsuario], [RolID], [Activo])	
				SELECT CODIGOUSUARIO,1,1 FROM @TB_INFORMACION
      			---
				--GUARDAR CONSULTORAS ONLINE
				IF (@CONSULTORAONLINE=1)
				BEGIN
				DECLARE @FECHAGENERAL DATETIME 
				SET @FECHAGENERAL = dbo.fnObtenerFechaHoraPais()

				INSERT INTO AFILIACLIENTECONSULTORA (CONSULTORAID,ESAFILIADO,FECHACREACION,FECHAMODIFICACION,MOTIVODESAFILIACIONID)
				--VALUES (@CONSULTORAID, 1, @FECHAGENERAL, @FECHAGENERAL, NULL)
				SELECT CONSULTORAID,1,@FECHAGENERAL,@FECHAGENERAL,NULL FROM @TB_INFORMACION

				---ELIMINAR USUARIO
				DECLARE @TUSUARIOS TABLE
				( 
					CODIGO_USUARIO VARCHAR(15) NOT NULL,
					NUMERO_IDENTIFICACION VARCHAR(15) NOT NULL
				)
				--CARGA INFORMACIÓN DE USUARIOS POSTULANTES
				INSERT INTO @TUSUARIOS
				SELECT CODIGOUSUARIO,DOCUMENTOIDENTIDAD FROM DBO.USUARIO 
				WHERE TIPOUSUARIO=2 AND EXISTS (SELECT 1 FROM @TB_INFORMACION I WHERE I.NUMERO_IDENTIFICACION=DBO.USUARIO.DOCUMENTOIDENTIDAD)

				---	ELIMINAR USUARIOROL.
				DELETE FROM  DBO.USUARIOROL WHERE EXISTS (SELECT 1 FROM @TUSUARIOS U WHERE DBO.USUARIOROL.CODIGOUSUARIO=U.CODIGO_USUARIO)
				--- ELIMINAR USUARIOS DE POSTULANTES.
				DELETE FROM DBO.USUARIO WHERE EXISTS (SELECT 1 FROM @TUSUARIOS U WHERE DBO.USUARIO.CODIGOUSUARIO=U.CODIGO_USUARIO)
				--- Actualizar flag UsuarioReal
				UPDATE UsuarioPostulante SET  UsuarioReal = 1 WHERE  EXISTS (SELECT 1 FROM @TUSUARIOS U WHERE DBO.USUARIO.CODIGOUSUARIO=U.CODIGO_USUARIO)					
				END
			END

		/*RETORNAR LAS CONSULTORAS PROCESADAS.*/
		SELECT NombreCompleto, CODIGOCONSULTORA AS Codigo, CODIGOUSUARIO AS CodigoUsuario, CLAVEGENERADA, Email, NUMERO_IDENTIFICACION AS Numero, CodigoZona, GerenteZona, GZEmail
		FROM @TB_INFORMACION

		COMMIT TRAN
END TRY
BEGIN CATCH

	IF XACT_STATE() <> 0
	       BEGIN
	       ROLLBACK TRANSACTION;

					PRINT ERROR_NUMBER()
					PRINT ERROR_SEVERITY()
					PRINT ERROR_STATE()
					PRINT SUBSTRING(ERROR_PROCEDURE(), 1, 50)
					PRINT ERROR_LINE()
					PRINT SUBSTRING(ERROR_MESSAGE(), 1, 200)/1

		   END
END CATCH

SET NOCOUNT OFF; 

