IF  EXISTS (
	SELECT * 
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'Banner'
	AND C.NAME = 'URLMobile'
	)
BEGIN
	ALTER TABLE Banner
	DROP COLUMN URLMobile
END
GO