USE ODS_BO;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NULL
	ALTER TABLE dbo.CuponesProgramaNuevas ADD IND_CUPO_ELEC BIT NULL, INC_CUPO_ELEC_DEFA BIT NULL;

GO
USE ODS_CL;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NULL
	ALTER TABLE dbo.CuponesProgramaNuevas ADD IND_CUPO_ELEC BIT NULL, INC_CUPO_ELEC_DEFA BIT NULL;

GO
USE ODS_CO;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NULL
	ALTER TABLE dbo.CuponesProgramaNuevas ADD IND_CUPO_ELEC BIT NULL, INC_CUPO_ELEC_DEFA BIT NULL;

GO
USE ODS_CR;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NULL
	ALTER TABLE dbo.CuponesProgramaNuevas ADD IND_CUPO_ELEC BIT NULL, INC_CUPO_ELEC_DEFA BIT NULL;

GO
USE ODS_DO;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NULL
	ALTER TABLE dbo.CuponesProgramaNuevas ADD IND_CUPO_ELEC BIT NULL, INC_CUPO_ELEC_DEFA BIT NULL;

GO
USE ODS_EC;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NULL
	ALTER TABLE dbo.CuponesProgramaNuevas ADD IND_CUPO_ELEC BIT NULL, INC_CUPO_ELEC_DEFA BIT NULL;

GO
USE ODS_GT;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NULL
	ALTER TABLE dbo.CuponesProgramaNuevas ADD IND_CUPO_ELEC BIT NULL, INC_CUPO_ELEC_DEFA BIT NULL;

GO
USE ODS_MX;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NULL
	ALTER TABLE dbo.CuponesProgramaNuevas ADD IND_CUPO_ELEC BIT NULL, INC_CUPO_ELEC_DEFA BIT NULL;

GO
USE ODS_PA;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NULL
	ALTER TABLE dbo.CuponesProgramaNuevas ADD IND_CUPO_ELEC BIT NULL, INC_CUPO_ELEC_DEFA BIT NULL;

GO
USE ODS_PE;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NULL
	ALTER TABLE dbo.CuponesProgramaNuevas ADD IND_CUPO_ELEC BIT NULL, INC_CUPO_ELEC_DEFA BIT NULL;

GO
USE ODS_PR;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NULL
	ALTER TABLE dbo.CuponesProgramaNuevas ADD IND_CUPO_ELEC BIT NULL, INC_CUPO_ELEC_DEFA BIT NULL;

GO
USE ODS_SV;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NULL
	ALTER TABLE dbo.CuponesProgramaNuevas ADD IND_CUPO_ELEC BIT NULL, INC_CUPO_ELEC_DEFA BIT NULL;

GO
