USE ODS_BO;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NOT NULL
	ALTER TABLE dbo.CuponesProgramaNuevas DROP COLUMN IND_CUPO_ELEC, INC_CUPO_ELEC_DEFA;
GO
USE ODS_CL;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NOT NULL
	ALTER TABLE dbo.CuponesProgramaNuevas DROP COLUMN IND_CUPO_ELEC, INC_CUPO_ELEC_DEFA;
GO
USE ODS_CO;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NOT NULL
	ALTER TABLE dbo.CuponesProgramaNuevas DROP COLUMN IND_CUPO_ELEC, INC_CUPO_ELEC_DEFA;
GO
USE ODS_CR;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NOT NULL
	ALTER TABLE dbo.CuponesProgramaNuevas DROP COLUMN IND_CUPO_ELEC, INC_CUPO_ELEC_DEFA;
GO
USE ODS_DO;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NOT NULL
	ALTER TABLE dbo.CuponesProgramaNuevas DROP COLUMN IND_CUPO_ELEC, INC_CUPO_ELEC_DEFA;
GO
USE ODS_EC;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NOT NULL
	ALTER TABLE dbo.CuponesProgramaNuevas DROP COLUMN IND_CUPO_ELEC, INC_CUPO_ELEC_DEFA;
GO
USE ODS_GT;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NOT NULL
	ALTER TABLE dbo.CuponesProgramaNuevas DROP COLUMN IND_CUPO_ELEC, INC_CUPO_ELEC_DEFA;
GO
USE ODS_MX;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NOT NULL
	ALTER TABLE dbo.CuponesProgramaNuevas DROP COLUMN IND_CUPO_ELEC, INC_CUPO_ELEC_DEFA;
GO
USE ODS_PA;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NOT NULL
	ALTER TABLE dbo.CuponesProgramaNuevas DROP COLUMN IND_CUPO_ELEC, INC_CUPO_ELEC_DEFA;
GO
USE ODS_PE;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NOT NULL
	ALTER TABLE dbo.CuponesProgramaNuevas DROP COLUMN IND_CUPO_ELEC, INC_CUPO_ELEC_DEFA;
GO
USE ODS_PR;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NOT NULL
	ALTER TABLE dbo.CuponesProgramaNuevas DROP COLUMN IND_CUPO_ELEC, INC_CUPO_ELEC_DEFA;
GO
USE ODS_SV;
GO
IF COL_LENGTH('dbo.CuponesProgramaNuevas', 'IND_CUPO_ELEC') IS NOT NULL
	ALTER TABLE dbo.CuponesProgramaNuevas DROP COLUMN IND_CUPO_ELEC, INC_CUPO_ELEC_DEFA;
GO
