USE [BelcorpBolivia];
GO
UPDATE RolPermiso SET Activo = 0 WHERE PermisoID = (SELECT R.PERMISOID FROM ROLPERMISO R INNER JOIN PERMISO P ON R.PERMISOID = P.PermisoID WHERE P.Descripcion LIKE '%FECHAS DE PROMOCIONES%')
GO

USE [BelcorpChile];
GO
UPDATE RolPermiso SET Activo = 0 WHERE PermisoID = (SELECT R.PERMISOID FROM ROLPERMISO R INNER JOIN PERMISO P ON R.PERMISOID = P.PermisoID WHERE P.Descripcion LIKE '%FECHAS DE PROMOCIONES%')
GO

USE [BelcorpColombia];
GO
UPDATE RolPermiso SET Activo = 0 WHERE PermisoID = (SELECT R.PERMISOID FROM ROLPERMISO R INNER JOIN PERMISO P ON R.PERMISOID = P.PermisoID WHERE P.Descripcion LIKE '%FECHAS DE PROMOCIONES%')
GO

USE [BelcorpCostaRica];
GO
UPDATE RolPermiso SET Activo = 0 WHERE PermisoID = (SELECT R.PERMISOID FROM ROLPERMISO R INNER JOIN PERMISO P ON R.PERMISOID = P.PermisoID WHERE P.Descripcion LIKE '%FECHAS DE PROMOCIONES%')
GO

USE [BelcorpDominicana];
GO
UPDATE RolPermiso SET Activo = 0 WHERE PermisoID = (SELECT R.PERMISOID FROM ROLPERMISO R INNER JOIN PERMISO P ON R.PERMISOID = P.PermisoID WHERE P.Descripcion LIKE '%FECHAS DE PROMOCIONES%')
GO

USE [BelcorpEcuador];
GO
UPDATE RolPermiso SET Activo = 0 WHERE PermisoID = (SELECT R.PERMISOID FROM ROLPERMISO R INNER JOIN PERMISO P ON R.PERMISOID = P.PermisoID WHERE P.Descripcion LIKE '%FECHAS DE PROMOCIONES%')
GO

USE [BelcorpGuatemala];
GO
UPDATE RolPermiso SET Activo = 0 WHERE PermisoID = (SELECT R.PERMISOID FROM ROLPERMISO R INNER JOIN PERMISO P ON R.PERMISOID = P.PermisoID WHERE P.Descripcion LIKE '%FECHAS DE PROMOCIONES%')
GO

USE [BelcorpMexico];
GO
UPDATE RolPermiso SET Activo = 0 WHERE PermisoID = (SELECT R.PERMISOID FROM ROLPERMISO R INNER JOIN PERMISO P ON R.PERMISOID = P.PermisoID WHERE P.Descripcion LIKE '%FECHAS DE PROMOCIONES%')
GO

USE [BelcorpPanama];
GO
UPDATE RolPermiso SET Activo = 0 WHERE PermisoID = (SELECT R.PERMISOID FROM ROLPERMISO R INNER JOIN PERMISO P ON R.PERMISOID = P.PermisoID WHERE P.Descripcion LIKE '%FECHAS DE PROMOCIONES%')
GO

USE [BelcorpPeru];
GO
UPDATE RolPermiso SET Activo = 0 WHERE PermisoID = (SELECT R.PERMISOID FROM ROLPERMISO R INNER JOIN PERMISO P ON R.PERMISOID = P.PermisoID WHERE P.Descripcion LIKE '%FECHAS DE PROMOCIONES%')
GO

USE [BelcorpPuertoRico];
GO
UPDATE RolPermiso SET Activo = 0 WHERE PermisoID = (SELECT R.PERMISOID FROM ROLPERMISO R INNER JOIN PERMISO P ON R.PERMISOID = P.PermisoID WHERE P.Descripcion LIKE '%FECHAS DE PROMOCIONES%')
GO

USE [BelcorpSalvador];
GO
UPDATE RolPermiso SET Activo = 0 WHERE PermisoID = (SELECT R.PERMISOID FROM ROLPERMISO R INNER JOIN PERMISO P ON R.PERMISOID = P.PermisoID WHERE P.Descripcion LIKE '%FECHAS DE PROMOCIONES%')
GO
