USE BelcorpPeru
GO

IF OBJECT_ID('UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma') IS NOT NULL
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp DROP CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp ADD CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma UNIQUE (CodigoPrograma)
GO

USE BelcorpMexico
GO

IF OBJECT_ID('UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma') IS NOT NULL
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp DROP CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp ADD CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma UNIQUE (CodigoPrograma)
GO

USE BelcorpColombia
GO

IF OBJECT_ID('UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma') IS NOT NULL
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp DROP CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp ADD CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma UNIQUE (CodigoPrograma)
GO

USE BelcorpSalvador
GO

IF OBJECT_ID('UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma') IS NOT NULL
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp DROP CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp ADD CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma UNIQUE (CodigoPrograma)
GO

USE BelcorpPuertoRico
GO

IF OBJECT_ID('UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma') IS NOT NULL
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp DROP CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp ADD CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma UNIQUE (CodigoPrograma)
GO

USE BelcorpPanama
GO

IF OBJECT_ID('UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma') IS NOT NULL
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp DROP CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp ADD CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma UNIQUE (CodigoPrograma)
GO

USE BelcorpGuatemala
GO

IF OBJECT_ID('UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma') IS NOT NULL
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp DROP CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp ADD CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma UNIQUE (CodigoPrograma)
GO

USE BelcorpEcuador
GO

IF OBJECT_ID('UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma') IS NOT NULL
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp DROP CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp ADD CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma UNIQUE (CodigoPrograma)
GO

USE BelcorpDominicana
GO

IF OBJECT_ID('UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma') IS NOT NULL
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp DROP CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp ADD CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma UNIQUE (CodigoPrograma)
GO

USE BelcorpCostaRica
GO

IF OBJECT_ID('UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma') IS NOT NULL
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp DROP CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp ADD CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma UNIQUE (CodigoPrograma)
GO

USE BelcorpChile
GO

IF OBJECT_ID('UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma') IS NOT NULL
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp DROP CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp ADD CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma UNIQUE (CodigoPrograma)
GO

USE BelcorpBolivia
GO

IF OBJECT_ID('UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma') IS NOT NULL
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp DROP CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma
	ALTER TABLE dbo.ConfiguracionProgramaNuevasApp ADD CONSTRAINT UQ_ConfiguracionProgramaNuevasApp_CodigoPrograma UNIQUE (CodigoPrograma)
GO

