//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Consultoras.Web.ServiceCDR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BECDRWeb", Namespace="http://schemas.datacontract.org/2004/07/Portal.Consultoras.Entities.CDR")]
    [System.SerializableAttribute()]
    public partial class BECDRWeb : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CDRWebIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CampaniaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConsultoraIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCulminadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PedidoIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CDRWebID {
            get {
                return this.CDRWebIDField;
            }
            set {
                if ((this.CDRWebIDField.Equals(value) != true)) {
                    this.CDRWebIDField = value;
                    this.RaisePropertyChanged("CDRWebID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CampaniaID {
            get {
                return this.CampaniaIDField;
            }
            set {
                if ((this.CampaniaIDField.Equals(value) != true)) {
                    this.CampaniaIDField = value;
                    this.RaisePropertyChanged("CampaniaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConsultoraID {
            get {
                return this.ConsultoraIDField;
            }
            set {
                if ((this.ConsultoraIDField.Equals(value) != true)) {
                    this.ConsultoraIDField = value;
                    this.RaisePropertyChanged("ConsultoraID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCulminado {
            get {
                return this.FechaCulminadoField;
            }
            set {
                if ((this.FechaCulminadoField.Equals(value) != true)) {
                    this.FechaCulminadoField = value;
                    this.RaisePropertyChanged("FechaCulminado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Importe {
            get {
                return this.ImporteField;
            }
            set {
                if ((this.ImporteField.Equals(value) != true)) {
                    this.ImporteField = value;
                    this.RaisePropertyChanged("Importe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PedidoID {
            get {
                return this.PedidoIDField;
            }
            set {
                if ((this.PedidoIDField.Equals(value) != true)) {
                    this.PedidoIDField = value;
                    this.RaisePropertyChanged("PedidoID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BECDRWebDetalle", Namespace="http://schemas.datacontract.org/2004/07/Portal.Consultoras.Entities.CDR")]
    [System.SerializableAttribute()]
    public partial class BECDRWebDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CDRWebDetalleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CDRWebIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUV2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cantidad2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MotivoCDRIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoRechazoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperacionCDRIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CDRWebDetalleID {
            get {
                return this.CDRWebDetalleIDField;
            }
            set {
                if ((this.CDRWebDetalleIDField.Equals(value) != true)) {
                    this.CDRWebDetalleIDField = value;
                    this.RaisePropertyChanged("CDRWebDetalleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CDRWebID {
            get {
                return this.CDRWebIDField;
            }
            set {
                if ((this.CDRWebIDField.Equals(value) != true)) {
                    this.CDRWebIDField = value;
                    this.RaisePropertyChanged("CDRWebID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUV {
            get {
                return this.CUVField;
            }
            set {
                if ((object.ReferenceEquals(this.CUVField, value) != true)) {
                    this.CUVField = value;
                    this.RaisePropertyChanged("CUV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUV2 {
            get {
                return this.CUV2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CUV2Field, value) != true)) {
                    this.CUV2Field = value;
                    this.RaisePropertyChanged("CUV2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad2 {
            get {
                return this.Cantidad2Field;
            }
            set {
                if ((this.Cantidad2Field.Equals(value) != true)) {
                    this.Cantidad2Field = value;
                    this.RaisePropertyChanged("Cantidad2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MotivoCDRID {
            get {
                return this.MotivoCDRIDField;
            }
            set {
                if ((this.MotivoCDRIDField.Equals(value) != true)) {
                    this.MotivoCDRIDField = value;
                    this.RaisePropertyChanged("MotivoCDRID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoRechazo {
            get {
                return this.MotivoRechazoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoRechazoField, value) != true)) {
                    this.MotivoRechazoField = value;
                    this.RaisePropertyChanged("MotivoRechazo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperacionCDRID {
            get {
                return this.OperacionCDRIDField;
            }
            set {
                if ((this.OperacionCDRIDField.Equals(value) != true)) {
                    this.OperacionCDRIDField = value;
                    this.RaisePropertyChanged("OperacionCDRID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BECDRWebMotivoOperacion", Namespace="http://schemas.datacontract.org/2004/07/Portal.Consultoras.Entities.CDR")]
    [System.SerializableAttribute()]
    public partial class BECDRWebMotivoOperacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Portal.Consultoras.Web.ServiceCDR.BECDRMotivo CDRMotivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Portal.Consultoras.Web.ServiceCDR.BECDROperacion CDROperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MotivoCDRIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperacionCDRIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrioridadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Portal.Consultoras.Web.ServiceCDR.BECDRMotivo CDRMotivo {
            get {
                return this.CDRMotivoField;
            }
            set {
                if ((object.ReferenceEquals(this.CDRMotivoField, value) != true)) {
                    this.CDRMotivoField = value;
                    this.RaisePropertyChanged("CDRMotivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Portal.Consultoras.Web.ServiceCDR.BECDROperacion CDROperacion {
            get {
                return this.CDROperacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CDROperacionField, value) != true)) {
                    this.CDROperacionField = value;
                    this.RaisePropertyChanged("CDROperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MotivoCDRID {
            get {
                return this.MotivoCDRIDField;
            }
            set {
                if ((this.MotivoCDRIDField.Equals(value) != true)) {
                    this.MotivoCDRIDField = value;
                    this.RaisePropertyChanged("MotivoCDRID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperacionCDRID {
            get {
                return this.OperacionCDRIDField;
            }
            set {
                if ((this.OperacionCDRIDField.Equals(value) != true)) {
                    this.OperacionCDRIDField = value;
                    this.RaisePropertyChanged("OperacionCDRID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Prioridad {
            get {
                return this.PrioridadField;
            }
            set {
                if ((this.PrioridadField.Equals(value) != true)) {
                    this.PrioridadField = value;
                    this.RaisePropertyChanged("Prioridad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BECDRMotivo", Namespace="http://schemas.datacontract.org/2004/07/Portal.Consultoras.Entities.CDR")]
    [System.SerializableAttribute()]
    public partial class BECDRMotivo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BECDROperacion", Namespace="http://schemas.datacontract.org/2004/07/Portal.Consultoras.Entities.CDR")]
    [System.SerializableAttribute()]
    public partial class BECDROperacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Dias {
            get {
                return this.DiasField;
            }
            set {
                if ((this.DiasField.Equals(value) != true)) {
                    this.DiasField = value;
                    this.RaisePropertyChanged("Dias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BECDRWebDescripcion", Namespace="http://schemas.datacontract.org/2004/07/Portal.Consultoras.Entities.CDR")]
    [System.SerializableAttribute()]
    public partial class BECDRWebDescripcion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CDRWebDescripcionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoSSICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CDRWebDescripcionID {
            get {
                return this.CDRWebDescripcionIDField;
            }
            set {
                if ((this.CDRWebDescripcionIDField.Equals(value) != true)) {
                    this.CDRWebDescripcionIDField = value;
                    this.RaisePropertyChanged("CDRWebDescripcionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSSIC {
            get {
                return this.CodigoSSICField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoSSICField, value) != true)) {
                    this.CodigoSSICField = value;
                    this.RaisePropertyChanged("CodigoSSIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCDR.ICDRService")]
    public interface ICDRService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/InsCDRWeb", ReplyAction="http://tempuri.org/ICDRService/InsCDRWebResponse")]
        int InsCDRWeb(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWeb entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/InsCDRWeb", ReplyAction="http://tempuri.org/ICDRService/InsCDRWebResponse")]
        System.Threading.Tasks.Task<int> InsCDRWebAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWeb entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/DelCDRWeb", ReplyAction="http://tempuri.org/ICDRService/DelCDRWebResponse")]
        int DelCDRWeb(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWeb entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/DelCDRWeb", ReplyAction="http://tempuri.org/ICDRService/DelCDRWebResponse")]
        System.Threading.Tasks.Task<int> DelCDRWebAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWeb entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/GetCDRWeb", ReplyAction="http://tempuri.org/ICDRService/GetCDRWebResponse")]
        Portal.Consultoras.Web.ServiceCDR.BECDRWeb[] GetCDRWeb(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWeb entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/GetCDRWeb", ReplyAction="http://tempuri.org/ICDRService/GetCDRWebResponse")]
        System.Threading.Tasks.Task<Portal.Consultoras.Web.ServiceCDR.BECDRWeb[]> GetCDRWebAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWeb entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/InsCDRWebDetalle", ReplyAction="http://tempuri.org/ICDRService/InsCDRWebDetalleResponse")]
        int InsCDRWebDetalle(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/InsCDRWebDetalle", ReplyAction="http://tempuri.org/ICDRService/InsCDRWebDetalleResponse")]
        System.Threading.Tasks.Task<int> InsCDRWebDetalleAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/DelCDRWebDetalle", ReplyAction="http://tempuri.org/ICDRService/DelCDRWebDetalleResponse")]
        int DelCDRWebDetalle(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/DelCDRWebDetalle", ReplyAction="http://tempuri.org/ICDRService/DelCDRWebDetalleResponse")]
        System.Threading.Tasks.Task<int> DelCDRWebDetalleAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/GetCDRWebDetalle", ReplyAction="http://tempuri.org/ICDRService/GetCDRWebDetalleResponse")]
        Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle[] GetCDRWebDetalle(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/GetCDRWebDetalle", ReplyAction="http://tempuri.org/ICDRService/GetCDRWebDetalleResponse")]
        System.Threading.Tasks.Task<Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle[]> GetCDRWebDetalleAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/InsCDRWebMotivoOperacion", ReplyAction="http://tempuri.org/ICDRService/InsCDRWebMotivoOperacionResponse")]
        int InsCDRWebMotivoOperacion(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/InsCDRWebMotivoOperacion", ReplyAction="http://tempuri.org/ICDRService/InsCDRWebMotivoOperacionResponse")]
        System.Threading.Tasks.Task<int> InsCDRWebMotivoOperacionAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/DelCDRWebMotivoOperacion", ReplyAction="http://tempuri.org/ICDRService/DelCDRWebMotivoOperacionResponse")]
        int DelCDRWebMotivoOperacion(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/DelCDRWebMotivoOperacion", ReplyAction="http://tempuri.org/ICDRService/DelCDRWebMotivoOperacionResponse")]
        System.Threading.Tasks.Task<int> DelCDRWebMotivoOperacionAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/GetCDRWebMotivoOperacion", ReplyAction="http://tempuri.org/ICDRService/GetCDRWebMotivoOperacionResponse")]
        Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion[] GetCDRWebMotivoOperacion(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/GetCDRWebMotivoOperacion", ReplyAction="http://tempuri.org/ICDRService/GetCDRWebMotivoOperacionResponse")]
        System.Threading.Tasks.Task<Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion[]> GetCDRWebMotivoOperacionAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/InsCDRWebDescripcion", ReplyAction="http://tempuri.org/ICDRService/InsCDRWebDescripcionResponse")]
        int InsCDRWebDescripcion(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/InsCDRWebDescripcion", ReplyAction="http://tempuri.org/ICDRService/InsCDRWebDescripcionResponse")]
        System.Threading.Tasks.Task<int> InsCDRWebDescripcionAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/DelCDRWebDescripcion", ReplyAction="http://tempuri.org/ICDRService/DelCDRWebDescripcionResponse")]
        int DelCDRWebDescripcion(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/DelCDRWebDescripcion", ReplyAction="http://tempuri.org/ICDRService/DelCDRWebDescripcionResponse")]
        System.Threading.Tasks.Task<int> DelCDRWebDescripcionAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/GetCDRWebDescripcion", ReplyAction="http://tempuri.org/ICDRService/GetCDRWebDescripcionResponse")]
        Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion[] GetCDRWebDescripcion(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDRService/GetCDRWebDescripcion", ReplyAction="http://tempuri.org/ICDRService/GetCDRWebDescripcionResponse")]
        System.Threading.Tasks.Task<Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion[]> GetCDRWebDescripcionAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICDRServiceChannel : Portal.Consultoras.Web.ServiceCDR.ICDRService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CDRServiceClient : System.ServiceModel.ClientBase<Portal.Consultoras.Web.ServiceCDR.ICDRService>, Portal.Consultoras.Web.ServiceCDR.ICDRService {
        
        public CDRServiceClient() {
        }
        
        public CDRServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CDRServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDRServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDRServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsCDRWeb(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWeb entity) {
            return base.Channel.InsCDRWeb(PaisID, entity);
        }
        
        public System.Threading.Tasks.Task<int> InsCDRWebAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWeb entity) {
            return base.Channel.InsCDRWebAsync(PaisID, entity);
        }
        
        public int DelCDRWeb(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWeb entity) {
            return base.Channel.DelCDRWeb(PaisID, entity);
        }
        
        public System.Threading.Tasks.Task<int> DelCDRWebAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWeb entity) {
            return base.Channel.DelCDRWebAsync(PaisID, entity);
        }
        
        public Portal.Consultoras.Web.ServiceCDR.BECDRWeb[] GetCDRWeb(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWeb entity) {
            return base.Channel.GetCDRWeb(PaisID, entity);
        }
        
        public System.Threading.Tasks.Task<Portal.Consultoras.Web.ServiceCDR.BECDRWeb[]> GetCDRWebAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWeb entity) {
            return base.Channel.GetCDRWebAsync(PaisID, entity);
        }
        
        public int InsCDRWebDetalle(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle entity) {
            return base.Channel.InsCDRWebDetalle(PaisID, entity);
        }
        
        public System.Threading.Tasks.Task<int> InsCDRWebDetalleAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle entity) {
            return base.Channel.InsCDRWebDetalleAsync(PaisID, entity);
        }
        
        public int DelCDRWebDetalle(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle entity) {
            return base.Channel.DelCDRWebDetalle(PaisID, entity);
        }
        
        public System.Threading.Tasks.Task<int> DelCDRWebDetalleAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle entity) {
            return base.Channel.DelCDRWebDetalleAsync(PaisID, entity);
        }
        
        public Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle[] GetCDRWebDetalle(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle entity) {
            return base.Channel.GetCDRWebDetalle(PaisID, entity);
        }
        
        public System.Threading.Tasks.Task<Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle[]> GetCDRWebDetalleAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDetalle entity) {
            return base.Channel.GetCDRWebDetalleAsync(PaisID, entity);
        }
        
        public int InsCDRWebMotivoOperacion(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion entity) {
            return base.Channel.InsCDRWebMotivoOperacion(PaisID, entity);
        }
        
        public System.Threading.Tasks.Task<int> InsCDRWebMotivoOperacionAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion entity) {
            return base.Channel.InsCDRWebMotivoOperacionAsync(PaisID, entity);
        }
        
        public int DelCDRWebMotivoOperacion(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion entity) {
            return base.Channel.DelCDRWebMotivoOperacion(PaisID, entity);
        }
        
        public System.Threading.Tasks.Task<int> DelCDRWebMotivoOperacionAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion entity) {
            return base.Channel.DelCDRWebMotivoOperacionAsync(PaisID, entity);
        }
        
        public Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion[] GetCDRWebMotivoOperacion(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion entity) {
            return base.Channel.GetCDRWebMotivoOperacion(PaisID, entity);
        }
        
        public System.Threading.Tasks.Task<Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion[]> GetCDRWebMotivoOperacionAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebMotivoOperacion entity) {
            return base.Channel.GetCDRWebMotivoOperacionAsync(PaisID, entity);
        }
        
        public int InsCDRWebDescripcion(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion entity) {
            return base.Channel.InsCDRWebDescripcion(PaisID, entity);
        }
        
        public System.Threading.Tasks.Task<int> InsCDRWebDescripcionAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion entity) {
            return base.Channel.InsCDRWebDescripcionAsync(PaisID, entity);
        }
        
        public int DelCDRWebDescripcion(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion entity) {
            return base.Channel.DelCDRWebDescripcion(PaisID, entity);
        }
        
        public System.Threading.Tasks.Task<int> DelCDRWebDescripcionAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion entity) {
            return base.Channel.DelCDRWebDescripcionAsync(PaisID, entity);
        }
        
        public Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion[] GetCDRWebDescripcion(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion entity) {
            return base.Channel.GetCDRWebDescripcion(PaisID, entity);
        }
        
        public System.Threading.Tasks.Task<Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion[]> GetCDRWebDescripcionAsync(int PaisID, Portal.Consultoras.Web.ServiceCDR.BECDRWebDescripcion entity) {
            return base.Channel.GetCDRWebDescripcionAsync(PaisID, entity);
        }
    }
}
