USE BelcorpPeru
GO

IF exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
  ALTER TABLE dbo.MenuApp DROP COLUMN VigenciaNueva;  
END

USE BelcorpMexico
GO

IF exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
  ALTER TABLE dbo.MenuApp DROP COLUMN VigenciaNueva;  
END

USE BelcorpColombia
GO

IF exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
  ALTER TABLE dbo.MenuApp DROP COLUMN VigenciaNueva;  
END

USE BelcorpSalvador
GO

IF exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
  ALTER TABLE dbo.MenuApp DROP COLUMN VigenciaNueva;  
END

USE BelcorpPuertoRico
GO

IF exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
  ALTER TABLE dbo.MenuApp DROP COLUMN VigenciaNueva;  
END

USE BelcorpPanama
GO

IF exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
  ALTER TABLE dbo.MenuApp DROP COLUMN VigenciaNueva;  
END

USE BelcorpGuatemala
GO

IF exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
  ALTER TABLE dbo.MenuApp DROP COLUMN VigenciaNueva;  
END

USE BelcorpEcuador
GO

IF exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
  ALTER TABLE dbo.MenuApp DROP COLUMN VigenciaNueva;  
END

USE BelcorpDominicana
GO

IF exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
  ALTER TABLE dbo.MenuApp DROP COLUMN VigenciaNueva;  
END

USE BelcorpCostaRica
GO

IF exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
  ALTER TABLE dbo.MenuApp DROP COLUMN VigenciaNueva;  
END

USE BelcorpChile
GO

IF exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
  ALTER TABLE dbo.MenuApp DROP COLUMN VigenciaNueva;  
END

USE BelcorpBolivia
GO

IF exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
  ALTER TABLE dbo.MenuApp DROP COLUMN VigenciaNueva;  
END