USE BelcorpBolivia
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebCulminado(
	LogCDRWebCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	CDRWebId INT NOT NULL,
	PedidoID INT NOT NULL,
	PedidoNumero INT NOT NULL,
	CampaniaID INT NOT NULL,
	ConsultoraID BIGINT NOT NULL,
	FechaRegistro DATETIME NOT NULL,
	FechaCulminado DATETIME NOT NULL,
	Visualizado BIT NOT NULL
);
GO
ALTER TABLE dbo.LogCDRWebCulminado
ADD CONSTRAINT DF_LogCDRWebCulminado_Visualizado
DEFAULT 0 FOR Visualizado;
GO
/*end*/

USE BelcorpChile
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebCulminado(
	LogCDRWebCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	CDRWebId INT NOT NULL,
	PedidoID INT NOT NULL,
	PedidoNumero INT NOT NULL,
	CampaniaID INT NOT NULL,
	ConsultoraID BIGINT NOT NULL,
	FechaRegistro DATETIME NOT NULL,
	FechaCulminado DATETIME NOT NULL,
	Visualizado BIT NOT NULL
);
GO
ALTER TABLE dbo.LogCDRWebCulminado
ADD CONSTRAINT DF_LogCDRWebCulminado_Visualizado
DEFAULT 0 FOR Visualizado;
GO
/*end*/

USE BelcorpCostaRica
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebCulminado(
	LogCDRWebCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	CDRWebId INT NOT NULL,
	PedidoID INT NOT NULL,
	PedidoNumero INT NOT NULL,
	CampaniaID INT NOT NULL,
	ConsultoraID BIGINT NOT NULL,
	FechaRegistro DATETIME NOT NULL,
	FechaCulminado DATETIME NOT NULL,
	Visualizado BIT NOT NULL
);
GO
ALTER TABLE dbo.LogCDRWebCulminado
ADD CONSTRAINT DF_LogCDRWebCulminado_Visualizado
DEFAULT 0 FOR Visualizado;
GO
/*end*/

USE BelcorpDominicana
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebCulminado(
	LogCDRWebCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	CDRWebId INT NOT NULL,
	PedidoID INT NOT NULL,
	PedidoNumero INT NOT NULL,
	CampaniaID INT NOT NULL,
	ConsultoraID BIGINT NOT NULL,
	FechaRegistro DATETIME NOT NULL,
	FechaCulminado DATETIME NOT NULL,
	Visualizado BIT NOT NULL
);
GO
ALTER TABLE dbo.LogCDRWebCulminado
ADD CONSTRAINT DF_LogCDRWebCulminado_Visualizado
DEFAULT 0 FOR Visualizado;
GO
/*end*/

USE BelcorpEcuador
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebCulminado(
	LogCDRWebCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	CDRWebId INT NOT NULL,
	PedidoID INT NOT NULL,
	PedidoNumero INT NOT NULL,
	CampaniaID INT NOT NULL,
	ConsultoraID BIGINT NOT NULL,
	FechaRegistro DATETIME NOT NULL,
	FechaCulminado DATETIME NOT NULL,
	Visualizado BIT NOT NULL
);
GO
ALTER TABLE dbo.LogCDRWebCulminado
ADD CONSTRAINT DF_LogCDRWebCulminado_Visualizado
DEFAULT 0 FOR Visualizado;
GO
/*end*/

USE BelcorpGuatemala
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebCulminado(
	LogCDRWebCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	CDRWebId INT NOT NULL,
	PedidoID INT NOT NULL,
	PedidoNumero INT NOT NULL,
	CampaniaID INT NOT NULL,
	ConsultoraID BIGINT NOT NULL,
	FechaRegistro DATETIME NOT NULL,
	FechaCulminado DATETIME NOT NULL,
	Visualizado BIT NOT NULL
);
GO
ALTER TABLE dbo.LogCDRWebCulminado
ADD CONSTRAINT DF_LogCDRWebCulminado_Visualizado
DEFAULT 0 FOR Visualizado;
GO
/*end*/

USE BelcorpPanama
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebCulminado(
	LogCDRWebCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	CDRWebId INT NOT NULL,
	PedidoID INT NOT NULL,
	PedidoNumero INT NOT NULL,
	CampaniaID INT NOT NULL,
	ConsultoraID BIGINT NOT NULL,
	FechaRegistro DATETIME NOT NULL,
	FechaCulminado DATETIME NOT NULL,
	Visualizado BIT NOT NULL
);
GO
ALTER TABLE dbo.LogCDRWebCulminado
ADD CONSTRAINT DF_LogCDRWebCulminado_Visualizado
DEFAULT 0 FOR Visualizado;
GO
/*end*/

USE BelcorpPuertoRico
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebCulminado(
	LogCDRWebCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	CDRWebId INT NOT NULL,
	PedidoID INT NOT NULL,
	PedidoNumero INT NOT NULL,
	CampaniaID INT NOT NULL,
	ConsultoraID BIGINT NOT NULL,
	FechaRegistro DATETIME NOT NULL,
	FechaCulminado DATETIME NOT NULL,
	Visualizado BIT NOT NULL
);
GO
ALTER TABLE dbo.LogCDRWebCulminado
ADD CONSTRAINT DF_LogCDRWebCulminado_Visualizado
DEFAULT 0 FOR Visualizado;
GO
/*end*/

USE BelcorpSalvador
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebCulminado(
	LogCDRWebCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	CDRWebId INT NOT NULL,
	PedidoID INT NOT NULL,
	PedidoNumero INT NOT NULL,
	CampaniaID INT NOT NULL,
	ConsultoraID BIGINT NOT NULL,
	FechaRegistro DATETIME NOT NULL,
	FechaCulminado DATETIME NOT NULL,
	Visualizado BIT NOT NULL
);
GO
ALTER TABLE dbo.LogCDRWebCulminado
ADD CONSTRAINT DF_LogCDRWebCulminado_Visualizado
DEFAULT 0 FOR Visualizado;
GO
/*end*/

USE BelcorpVenezuela
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebCulminado(
	LogCDRWebCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	CDRWebId INT NOT NULL,
	PedidoID INT NOT NULL,
	PedidoNumero INT NOT NULL,
	CampaniaID INT NOT NULL,
	ConsultoraID BIGINT NOT NULL,
	FechaRegistro DATETIME NOT NULL,
	FechaCulminado DATETIME NOT NULL,
	Visualizado BIT NOT NULL
);
GO
ALTER TABLE dbo.LogCDRWebCulminado
ADD CONSTRAINT DF_LogCDRWebCulminado_Visualizado
DEFAULT 0 FOR Visualizado;
GO
/*end*/

USE BelcorpColombia
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebCulminado(
	LogCDRWebCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	CDRWebId INT NOT NULL,
	PedidoID INT NOT NULL,
	PedidoNumero INT NOT NULL,
	CampaniaID INT NOT NULL,
	ConsultoraID BIGINT NOT NULL,
	FechaRegistro DATETIME NOT NULL,
	FechaCulminado DATETIME NOT NULL,
	Visualizado BIT NOT NULL
);
GO
ALTER TABLE dbo.LogCDRWebCulminado
ADD CONSTRAINT DF_LogCDRWebCulminado_Visualizado
DEFAULT 0 FOR Visualizado;
GO
/*end*/

USE BelcorpMexico
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebCulminado(
	LogCDRWebCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	CDRWebId INT NOT NULL,
	PedidoID INT NOT NULL,
	PedidoNumero INT NOT NULL,
	CampaniaID INT NOT NULL,
	ConsultoraID BIGINT NOT NULL,
	FechaRegistro DATETIME NOT NULL,
	FechaCulminado DATETIME NOT NULL,
	Visualizado BIT NOT NULL
);
GO
ALTER TABLE dbo.LogCDRWebCulminado
ADD CONSTRAINT DF_LogCDRWebCulminado_Visualizado
DEFAULT 0 FOR Visualizado;
GO
/*end*/

USE BelcorpPeru
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = 'LogCDRWebCulminado' AND TABLE_SCHEMA = 'dbo')
BEGIN
    DROP TABLE dbo.LogCDRWebCulminado;
END
GO
CREATE TABLE dbo.LogCDRWebCulminado(
	LogCDRWebCulminadoId BIGINT IDENTITY(1,1) PRIMARY KEY,
	CDRWebId INT NOT NULL,
	PedidoID INT NOT NULL,
	PedidoNumero INT NOT NULL,
	CampaniaID INT NOT NULL,
	ConsultoraID BIGINT NOT NULL,
	FechaRegistro DATETIME NOT NULL,
	FechaCulminado DATETIME NOT NULL,
	Visualizado BIT NOT NULL
);
GO
ALTER TABLE dbo.LogCDRWebCulminado
ADD CONSTRAINT DF_LogCDRWebCulminado_Visualizado
DEFAULT 0 FOR Visualizado;
GO