GO
USE BelcorpPeru
GO
PRINT 'ADD COLUMNS'

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'NombreSet'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD NombreSet NVARCHAR(800)
END
GO

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'TipoEstrategiaId'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD TipoEstrategiaId INT
END
GO

PRINT 'DROP COLUMNS'

IF EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'ClienteID'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] DROP COLUMN ClienteID
END

GO
USE BelcorpMexico
GO
PRINT 'ADD COLUMNS'

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'NombreSet'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD NombreSet NVARCHAR(800)
END
GO

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'TipoEstrategiaId'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD TipoEstrategiaId INT
END
GO

PRINT 'DROP COLUMNS'

IF EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'ClienteID'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] DROP COLUMN ClienteID
END

GO
USE BelcorpColombia
GO
PRINT 'ADD COLUMNS'

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'NombreSet'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD NombreSet NVARCHAR(800)
END
GO

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'TipoEstrategiaId'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD TipoEstrategiaId INT
END
GO

PRINT 'DROP COLUMNS'

IF EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'ClienteID'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] DROP COLUMN ClienteID
END

GO
USE BelcorpSalvador
GO
PRINT 'ADD COLUMNS'

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'NombreSet'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD NombreSet NVARCHAR(800)
END
GO

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'TipoEstrategiaId'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD TipoEstrategiaId INT
END
GO

PRINT 'DROP COLUMNS'

IF EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'ClienteID'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] DROP COLUMN ClienteID
END

GO
USE BelcorpPuertoRico
GO
PRINT 'ADD COLUMNS'

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'NombreSet'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD NombreSet NVARCHAR(800)
END
GO

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'TipoEstrategiaId'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD TipoEstrategiaId INT
END
GO

PRINT 'DROP COLUMNS'

IF EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'ClienteID'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] DROP COLUMN ClienteID
END

GO
USE BelcorpPanama
GO
PRINT 'ADD COLUMNS'

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'NombreSet'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD NombreSet NVARCHAR(800)
END
GO

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'TipoEstrategiaId'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD TipoEstrategiaId INT
END
GO

PRINT 'DROP COLUMNS'

IF EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'ClienteID'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] DROP COLUMN ClienteID
END

GO
USE BelcorpGuatemala
GO
PRINT 'ADD COLUMNS'

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'NombreSet'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD NombreSet NVARCHAR(800)
END
GO

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'TipoEstrategiaId'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD TipoEstrategiaId INT
END
GO

PRINT 'DROP COLUMNS'

IF EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'ClienteID'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] DROP COLUMN ClienteID
END

GO
USE BelcorpEcuador
GO
PRINT 'ADD COLUMNS'

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'NombreSet'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD NombreSet NVARCHAR(800)
END
GO

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'TipoEstrategiaId'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD TipoEstrategiaId INT
END
GO

PRINT 'DROP COLUMNS'

IF EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'ClienteID'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] DROP COLUMN ClienteID
END

GO
USE BelcorpDominicana
GO
PRINT 'ADD COLUMNS'

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'NombreSet'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD NombreSet NVARCHAR(800)
END
GO

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'TipoEstrategiaId'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD TipoEstrategiaId INT
END
GO

PRINT 'DROP COLUMNS'

IF EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'ClienteID'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] DROP COLUMN ClienteID
END

GO
USE BelcorpCostaRica
GO
PRINT 'ADD COLUMNS'

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'NombreSet'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD NombreSet NVARCHAR(800)
END
GO

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'TipoEstrategiaId'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD TipoEstrategiaId INT
END
GO

PRINT 'DROP COLUMNS'

IF EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'ClienteID'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] DROP COLUMN ClienteID
END

GO
USE BelcorpChile
GO
PRINT 'ADD COLUMNS'

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'NombreSet'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD NombreSet NVARCHAR(800)
END
GO

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'TipoEstrategiaId'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD TipoEstrategiaId INT
END
GO

PRINT 'DROP COLUMNS'

IF EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'ClienteID'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] DROP COLUMN ClienteID
END

GO
USE BelcorpBolivia
GO
PRINT 'ADD COLUMNS'

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'NombreSet'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD NombreSet NVARCHAR(800)
END
GO

IF NOT EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'TipoEstrategiaId'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] ADD TipoEstrategiaId INT
END
GO

PRINT 'DROP COLUMNS'

IF EXISTS (
	SELECT *
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'PedidoWebSet'
	AND C.NAME = 'ClienteID'
	)
BEGIN
	ALTER TABLE [dbo].[PedidoWebSet] DROP COLUMN ClienteID
END

GO
