USE BelcorpPeru
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaRevista')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaRevista MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaWeb')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaWeb MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaOtros')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaOtros MONEY NULL
END
GO

USE BelcorpMexico
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaRevista')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaRevista MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaWeb')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaWeb MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaOtros')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaOtros MONEY NULL
END
GO

USE BelcorpColombia
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaRevista')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaRevista MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaWeb')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaWeb MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaOtros')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaOtros MONEY NULL
END
GO

USE BelcorpSalvador
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaRevista')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaRevista MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaWeb')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaWeb MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaOtros')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaOtros MONEY NULL
END
GO

USE BelcorpPuertoRico
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaRevista')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaRevista MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaWeb')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaWeb MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaOtros')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaOtros MONEY NULL
END
GO

USE BelcorpPanama
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaRevista')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaRevista MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaWeb')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaWeb MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaOtros')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaOtros MONEY NULL
END
GO

USE BelcorpGuatemala
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaRevista')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaRevista MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaWeb')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaWeb MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaOtros')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaOtros MONEY NULL
END
GO

USE BelcorpEcuador
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaRevista')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaRevista MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaWeb')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaWeb MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaOtros')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaOtros MONEY NULL
END
GO

USE BelcorpDominicana
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaRevista')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaRevista MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaWeb')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaWeb MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaOtros')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaOtros MONEY NULL
END
GO

USE BelcorpCostaRica
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaRevista')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaRevista MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaWeb')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaWeb MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaOtros')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaOtros MONEY NULL
END
GO

USE BelcorpChile
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaRevista')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaRevista MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaWeb')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaWeb MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaOtros')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaOtros MONEY NULL
END
GO

USE BelcorpBolivia
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaRevista')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaRevista MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaWeb')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaWeb MONEY NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'GananciaOtros')
BEGIN
  ALTER TABLE PedidoWeb ADD GananciaOtros MONEY NULL
END
GO

