USE SoporteConsultoras;
GO

DECLARE @URL AS VARCHAR(MAX)= 'CONSULTORAS/REPORTEPRODUCTOSUGERIDONIVELCONSULTORA' 
DECLARE @LISTUSERSRED AS VARCHAR(MAX)= 'STEVENAYALA,VEABETANCOURT' 
DECLARE @IDMENU AS INT=0 
DECLARE @IDPAIS AS INT=4  

SELECT @IDMENU = IDMENU 
FROM   MENU 
WHERE  ESTADOACTIVO = 1 
       AND URL = @URL 


INSERT INTO PERMISO 
select idperfil, @IDPAIS, @IDMENU
from usuario where USERLOGIN IN (SELECT VALOR 
                           FROM   DBO.SPLIT(@LISTUSERSRED, ',')) 
 AND IDPERFIL NOT IN(SELECT IDPERFIL 
                             FROM   PERMISO P 
                                    INNER JOIN MENU M 
                                            ON M.IDMENU = P.IDMENU 
                             WHERE  M.URL = @URL AND P.IDPAIS=@IDPAIS) 
