
USE BelcorpBolivia
go

IF NOT EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN
	DECLARE @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;

	SET	@CODIGO_POPUP	= 10;
	SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
	SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

	UPDATE	PopupPais
	SET		Orden = (Orden + 1)
	WHERE	Orden >= @ORDEN_SHOWROOM

	INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'BO', @ORDEN_SHOWROOM, 1);
END
GO
IF EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN
	DECLARE @ORDEN_CUPON INT, @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;
	SET @ORDEN_CUPON	= (SELECT Orden FROM PopupPais WHERE CodigoPopup = 10);

	DELETE FROM PopupPais WHERE CodigoPopup = 10

	UPDATE	PopupPais
	SET		Orden = (Orden - 1)
	WHERE	Orden > @ORDEN_CUPON

	SET	@CODIGO_POPUP	= 10;
	SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
	SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

	UPDATE	PopupPais
	SET		Orden = (Orden + 1)
	WHERE	Orden >= @ORDEN_SHOWROOM

	INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'BO', @ORDEN_SHOWROOM, 1);
END
GO
/*end*/

USE BelcorpChile
go

IF NOT EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN

DECLARE @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;

SET	@CODIGO_POPUP	= 10;
SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

UPDATE	PopupPais
SET		Orden = (Orden + 1)
WHERE	Orden >= @ORDEN_SHOWROOM

INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'CL', @ORDEN_SHOWROOM, 1);

END
GO
IF EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN
	DECLARE @ORDEN_CUPON INT, @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;
	SET @ORDEN_CUPON	= (SELECT Orden FROM PopupPais WHERE CodigoPopup = 10);

	DELETE FROM PopupPais WHERE CodigoPopup = 10

	UPDATE	PopupPais
	SET		Orden = (Orden - 1)
	WHERE	Orden > @ORDEN_CUPON

	SET	@CODIGO_POPUP	= 10;
	SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
	SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

	UPDATE	PopupPais
	SET		Orden = (Orden + 1)
	WHERE	Orden >= @ORDEN_SHOWROOM

	INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'CL', @ORDEN_SHOWROOM, 1);
END
GO
/*end*/

USE BelcorpColombia
go

IF NOT EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN

DECLARE @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;

SET	@CODIGO_POPUP	= 10;
SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

UPDATE	PopupPais
SET		Orden = (Orden + 1)
WHERE	Orden >= @ORDEN_SHOWROOM

INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'CO', @ORDEN_SHOWROOM, 1);

END
GO
IF EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN
	DECLARE @ORDEN_CUPON INT, @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;
	SET @ORDEN_CUPON	= (SELECT Orden FROM PopupPais WHERE CodigoPopup = 10);

	DELETE FROM PopupPais WHERE CodigoPopup = 10

	UPDATE	PopupPais
	SET		Orden = (Orden - 1)
	WHERE	Orden > @ORDEN_CUPON

	SET	@CODIGO_POPUP	= 10;
	SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
	SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

	UPDATE	PopupPais
	SET		Orden = (Orden + 1)
	WHERE	Orden >= @ORDEN_SHOWROOM

	INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'CO', @ORDEN_SHOWROOM, 1);
END
GO
/*end*/

USE BelcorpCostaRica
go

IF NOT EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN

DECLARE @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;

SET	@CODIGO_POPUP	= 10;
SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

UPDATE	PopupPais
SET		Orden = (Orden + 1)
WHERE	Orden >= @ORDEN_SHOWROOM

INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'CR', @ORDEN_SHOWROOM, 1);

END
GO
IF EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN
	DECLARE @ORDEN_CUPON INT, @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;
	SET @ORDEN_CUPON	= (SELECT Orden FROM PopupPais WHERE CodigoPopup = 10);

	DELETE FROM PopupPais WHERE CodigoPopup = 10

	UPDATE	PopupPais
	SET		Orden = (Orden - 1)
	WHERE	Orden > @ORDEN_CUPON

	SET	@CODIGO_POPUP	= 10;
	SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
	SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

	UPDATE	PopupPais
	SET		Orden = (Orden + 1)
	WHERE	Orden >= @ORDEN_SHOWROOM

	INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'CR', @ORDEN_SHOWROOM, 1);
END
GO
/*end*/

USE BelcorpDominicana
go

IF NOT EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN

DECLARE @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;

SET	@CODIGO_POPUP	= 10;
SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

UPDATE	PopupPais
SET		Orden = (Orden + 1)
WHERE	Orden >= @ORDEN_SHOWROOM

INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'DO', @ORDEN_SHOWROOM, 1);

END
GO
IF EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN
	DECLARE @ORDEN_CUPON INT, @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;
	SET @ORDEN_CUPON	= (SELECT Orden FROM PopupPais WHERE CodigoPopup = 10);

	DELETE FROM PopupPais WHERE CodigoPopup = 10

	UPDATE	PopupPais
	SET		Orden = (Orden - 1)
	WHERE	Orden > @ORDEN_CUPON

	SET	@CODIGO_POPUP	= 10;
	SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
	SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

	UPDATE	PopupPais
	SET		Orden = (Orden + 1)
	WHERE	Orden >= @ORDEN_SHOWROOM

	INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'DO', @ORDEN_SHOWROOM, 1);
END
GO
/*end*/

USE BelcorpEcuador
go

IF NOT EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN

DECLARE @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;

SET	@CODIGO_POPUP	= 10;
SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

UPDATE	PopupPais
SET		Orden = (Orden + 1)
WHERE	Orden >= @ORDEN_SHOWROOM

INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'EC', @ORDEN_SHOWROOM, 1);

END
GO
IF EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN
	DECLARE @ORDEN_CUPON INT, @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;
	SET @ORDEN_CUPON	= (SELECT Orden FROM PopupPais WHERE CodigoPopup = 10);

	DELETE FROM PopupPais WHERE CodigoPopup = 10

	UPDATE	PopupPais
	SET		Orden = (Orden - 1)
	WHERE	Orden > @ORDEN_CUPON

	SET	@CODIGO_POPUP	= 10;
	SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
	SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

	UPDATE	PopupPais
	SET		Orden = (Orden + 1)
	WHERE	Orden >= @ORDEN_SHOWROOM

	INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'EC', @ORDEN_SHOWROOM, 1);
END
GO
/*end*/

USE BelcorpGuatemala
go

IF NOT EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN

DECLARE @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;

SET	@CODIGO_POPUP	= 10;
SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

UPDATE	PopupPais
SET		Orden = (Orden + 1)
WHERE	Orden >= @ORDEN_SHOWROOM

INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'GT', @ORDEN_SHOWROOM, 1);

END
GO
IF EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN
	DECLARE @ORDEN_CUPON INT, @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;
	SET @ORDEN_CUPON	= (SELECT Orden FROM PopupPais WHERE CodigoPopup = 10);

	DELETE FROM PopupPais WHERE CodigoPopup = 10

	UPDATE	PopupPais
	SET		Orden = (Orden - 1)
	WHERE	Orden > @ORDEN_CUPON

	SET	@CODIGO_POPUP	= 10;
	SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
	SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

	UPDATE	PopupPais
	SET		Orden = (Orden + 1)
	WHERE	Orden >= @ORDEN_SHOWROOM

	INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'GT', @ORDEN_SHOWROOM, 1);
END
GO
/*end*/

USE BelcorpMexico
go

IF NOT EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN

DECLARE @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;

SET	@CODIGO_POPUP	= 10;
SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

UPDATE	PopupPais
SET		Orden = (Orden + 1)
WHERE	Orden >= @ORDEN_SHOWROOM

INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'MX', @ORDEN_SHOWROOM, 1);

END
GO
IF EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN
	DECLARE @ORDEN_CUPON INT, @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;
	SET @ORDEN_CUPON	= (SELECT Orden FROM PopupPais WHERE CodigoPopup = 10);

	DELETE FROM PopupPais WHERE CodigoPopup = 10

	UPDATE	PopupPais
	SET		Orden = (Orden - 1)
	WHERE	Orden > @ORDEN_CUPON

	SET	@CODIGO_POPUP	= 10;
	SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
	SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

	UPDATE	PopupPais
	SET		Orden = (Orden + 1)
	WHERE	Orden >= @ORDEN_SHOWROOM

	INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'MX', @ORDEN_SHOWROOM, 1);
END
GO
/*end*/

USE BelcorpPanama
go

IF NOT EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN

DECLARE @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;

SET	@CODIGO_POPUP	= 10;
SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

UPDATE	PopupPais
SET		Orden = (Orden + 1)
WHERE	Orden >= @ORDEN_SHOWROOM

INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'PA', @ORDEN_SHOWROOM, 1);

END
GO
IF EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN
	DECLARE @ORDEN_CUPON INT, @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;
	SET @ORDEN_CUPON	= (SELECT Orden FROM PopupPais WHERE CodigoPopup = 10);

	DELETE FROM PopupPais WHERE CodigoPopup = 10

	UPDATE	PopupPais
	SET		Orden = (Orden - 1)
	WHERE	Orden > @ORDEN_CUPON

	SET	@CODIGO_POPUP	= 10;
	SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
	SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

	UPDATE	PopupPais
	SET		Orden = (Orden + 1)
	WHERE	Orden >= @ORDEN_SHOWROOM

	INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'PA', @ORDEN_SHOWROOM, 1);
END
GO
/*end*/

USE BelcorpPeru
go

IF NOT EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN

DECLARE @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;

SET	@CODIGO_POPUP	= 10;
SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

UPDATE	PopupPais
SET		Orden = (Orden + 1)
WHERE	Orden >= @ORDEN_SHOWROOM

INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'PE', @ORDEN_SHOWROOM, 1);

END
GO
IF EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN
	DECLARE @ORDEN_CUPON INT, @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;
	SET @ORDEN_CUPON	= (SELECT Orden FROM PopupPais WHERE CodigoPopup = 10);

	DELETE FROM PopupPais WHERE CodigoPopup = 10

	UPDATE	PopupPais
	SET		Orden = (Orden - 1)
	WHERE	Orden > @ORDEN_CUPON

	SET	@CODIGO_POPUP	= 10;
	SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
	SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

	UPDATE	PopupPais
	SET		Orden = (Orden + 1)
	WHERE	Orden >= @ORDEN_SHOWROOM

	INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'PE', @ORDEN_SHOWROOM, 1);
END
GO
/*end*/

USE BelcorpPuertoRico
go

IF NOT EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN

DECLARE @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;

SET	@CODIGO_POPUP	= 10;
SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

UPDATE	PopupPais
SET		Orden = (Orden + 1)
WHERE	Orden >= @ORDEN_SHOWROOM

INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'PR', @ORDEN_SHOWROOM, 1);

END
GO
IF EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN
	DECLARE @ORDEN_CUPON INT, @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;
	SET @ORDEN_CUPON	= (SELECT Orden FROM PopupPais WHERE CodigoPopup = 10);

	DELETE FROM PopupPais WHERE CodigoPopup = 10

	UPDATE	PopupPais
	SET		Orden = (Orden - 1)
	WHERE	Orden > @ORDEN_CUPON

	SET	@CODIGO_POPUP	= 10;
	SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
	SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

	UPDATE	PopupPais
	SET		Orden = (Orden + 1)
	WHERE	Orden >= @ORDEN_SHOWROOM

	INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'PR', @ORDEN_SHOWROOM, 1);
END
GO
/*end*/

USE BelcorpSalvador
go

IF NOT EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN

DECLARE @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;

SET	@CODIGO_POPUP	= 10;
SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

UPDATE	PopupPais
SET		Orden = (Orden + 1)
WHERE	Orden >= @ORDEN_SHOWROOM

INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'SV', @ORDEN_SHOWROOM, 1);

END
GO
IF EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN
	DECLARE @ORDEN_CUPON INT, @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;
	SET @ORDEN_CUPON	= (SELECT Orden FROM PopupPais WHERE CodigoPopup = 10);

	DELETE FROM PopupPais WHERE CodigoPopup = 10

	UPDATE	PopupPais
	SET		Orden = (Orden - 1)
	WHERE	Orden > @ORDEN_CUPON

	SET	@CODIGO_POPUP	= 10;
	SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
	SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

	UPDATE	PopupPais
	SET		Orden = (Orden + 1)
	WHERE	Orden >= @ORDEN_SHOWROOM

	INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'SV', @ORDEN_SHOWROOM, 1);
END
GO
/*end*/

USE BelcorpVenezuela
go

IF NOT EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN

DECLARE @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;

SET	@CODIGO_POPUP	= 10;
SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

UPDATE	PopupPais
SET		Orden = (Orden + 1)
WHERE	Orden >= @ORDEN_SHOWROOM

INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'VE', @ORDEN_SHOWROOM, 1);

END
GO
IF EXISTS (SELECT 1 FROM PopupPais WHERE CodigoPopup = 10)
BEGIN
	DECLARE @ORDEN_CUPON INT, @CODIGO_POPUP INT, @ORDEN_SHOWROOM INT, @POPUPPAISID_SHOWROOM INT;
	SET @ORDEN_CUPON	= (SELECT Orden FROM PopupPais WHERE CodigoPopup = 10);

	DELETE FROM PopupPais WHERE CodigoPopup = 10

	UPDATE	PopupPais
	SET		Orden = (Orden - 1)
	WHERE	Orden > @ORDEN_CUPON

	SET	@CODIGO_POPUP	= 10;
	SET @ORDEN_SHOWROOM	= ((SELECT Orden FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));
	SET	@POPUPPAISID_SHOWROOM	= ((SELECT PopupPaisID FROM PopupPais WHERE RTRIM(LTRIM(Descripcion)) = 'Showroom'));

	UPDATE	PopupPais
	SET		Orden = (Orden + 1)
	WHERE	Orden >= @ORDEN_SHOWROOM

	INSERT INTO PopupPais VALUES(@CODIGO_POPUP, 'Cupón', 'VE', @ORDEN_SHOWROOM, 1);
END
GO