USE BelcorpPeru
GO

GO
IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrden'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrden INT NULL
	CONSTRAINT MobileOrden_def DEFAULT 0
END

GO

IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrdenBPT'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrdenBPT INT NULL
	CONSTRAINT MobileOrdenBPT_def DEFAULT 0
END
GO
/*END*/

USE BelcorpMexico
GO

GO
IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrden'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrden INT NULL
	CONSTRAINT MobileOrden_def DEFAULT 0
END

GO

IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrdenBPT'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrdenBPT INT NULL
	CONSTRAINT MobileOrdenBPT_def DEFAULT 0
END
GO
/*END*/

USE BelcorpColombia
GO

GO
IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrden'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrden INT NULL
	CONSTRAINT MobileOrden_def DEFAULT 0
END

GO

IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrdenBPT'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrdenBPT INT NULL
	CONSTRAINT MobileOrdenBPT_def DEFAULT 0
END
GO
/*END*/

USE BelcorpVenezuela
GO

GO
IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrden'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrden INT NULL
	CONSTRAINT MobileOrden_def DEFAULT 0
END

GO

IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrdenBPT'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrdenBPT INT NULL
	CONSTRAINT MobileOrdenBPT_def DEFAULT 0
END
GO
/*END*/

USE BelcorpSalvador
GO

GO
IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrden'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrden INT NULL
	CONSTRAINT MobileOrden_def DEFAULT 0
END

GO

IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrdenBPT'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrdenBPT INT NULL
	CONSTRAINT MobileOrdenBPT_def DEFAULT 0
END
GO
/*END*/

USE BelcorpPuertoRico
GO

GO
IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrden'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrden INT NULL
	CONSTRAINT MobileOrden_def DEFAULT 0
END

GO

IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrdenBPT'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrdenBPT INT NULL
	CONSTRAINT MobileOrdenBPT_def DEFAULT 0
END
GO
/*END*/

USE BelcorpPanama
GO

GO
IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrden'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrden INT NULL
	CONSTRAINT MobileOrden_def DEFAULT 0
END

GO

IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrdenBPT'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrdenBPT INT NULL
	CONSTRAINT MobileOrdenBPT_def DEFAULT 0
END
GO
/*END*/

USE BelcorpGuatemala
GO

GO
IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrden'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrden INT NULL
	CONSTRAINT MobileOrden_def DEFAULT 0
END

GO

IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrdenBPT'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrdenBPT INT NULL
	CONSTRAINT MobileOrdenBPT_def DEFAULT 0
END
GO
/*END*/

USE BelcorpEcuador
GO

GO
IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrden'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrden INT NULL
	CONSTRAINT MobileOrden_def DEFAULT 0
END

GO

IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrdenBPT'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrdenBPT INT NULL
	CONSTRAINT MobileOrdenBPT_def DEFAULT 0
END
GO
/*END*/

USE BelcorpDominicana
GO

GO
IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrden'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrden INT NULL
	CONSTRAINT MobileOrden_def DEFAULT 0
END

GO

IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrdenBPT'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrdenBPT INT NULL
	CONSTRAINT MobileOrdenBPT_def DEFAULT 0
END
GO
/*END*/

USE BelcorpCostaRica
GO

GO
IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrden'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrden INT NULL
	CONSTRAINT MobileOrden_def DEFAULT 0
END

GO

IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrdenBPT'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrdenBPT INT NULL
	CONSTRAINT MobileOrdenBPT_def DEFAULT 0
END
GO
/*END*/

USE BelcorpChile
GO

GO
IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrden'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrden INT NULL
	CONSTRAINT MobileOrden_def DEFAULT 0
END

GO

IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrdenBPT'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrdenBPT INT NULL
	CONSTRAINT MobileOrdenBPT_def DEFAULT 0
END
GO
/*END*/

USE BelcorpBolivia
GO

GO
IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrden'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrden INT NULL
	CONSTRAINT MobileOrden_def DEFAULT 0
END

GO

IF NOT EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'ConfiguracionPais'
	AND C.NAME = 'MobileOrdenBPT'
	)
BEGIN
	ALTER TABLE ConfiguracionPais
	ADD MobileOrdenBPT INT NULL
	CONSTRAINT MobileOrdenBPT_def DEFAULT 0
END
GO
/*END*/
