GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'PedidoSapId'))
BEGIN
    ALTER TABLE dbo.PedidoWeb
	DROP CONSTRAINT DF_PedidoWeb_PedidoSapId;

    ALTER TABLE dbo.PedidoWeb
	DROP COLUMN PedidoSapId;
END
GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.PedidoWeb
	DROP COLUMN VersionProl;
END
GO