USE BelcorpPeru
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdProductoDescripcion]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[UpdProductoDescripcion]
GO
CREATE PROCEDURE UpdProductoDescripcion
	@CampaniaID int,
	@CUV varchar(20),
	@Descripcion varchar(100),
	@PrecioProducto numeric(12,2),
	@FactorRepeticion int,
	@CodigoUsuario varchar(25),
	@RegaloDescripcion varchar(500) = NULL,
	@RegaloImagenUrl varchar(255)= NULL
AS
BEGIN TRY
	BEGIN TRAN

	IF EXISTS(	SELECT CAMPANIAID, CUV 
				FROM PRODUCTODESCRIPCION 
				WHERE CAMPANIAID = @CAMPANIAID AND CUV = @CUV)
		INSERT INTO LOGMATRIZCAMPANIA(CAMPANIAID, CUV, DESCRIPCION, PRECIO, FACTORREPETICION, CODIGOUSUARIOPROCESO, FECHAMODIFICACION)
		SELECT CAMPANIAID, CUV, DESCRIPCION, PRECIOPRODUCTO, FACTORREPETICION, @CODIGOUSUARIO, DBO.FNOBTENERFECHAHORAPAIS()
		FROM PRODUCTODESCRIPCION 
		WHERE CAMPANIAID = @CAMPANIAID 
		AND CUV = @CUV

	MERGE DBO.PRODUCTODESCRIPCION AS [TARGET]
	USING (
		SELECT 
		CAMPANIAID = @CAMPANIAID
		,CUV = @CUV
		,DESCRIPCION = @DESCRIPCION
		,PRECIOPRODUCTO = @PRECIOPRODUCTO
		,FACTORREPETICION = @FACTORREPETICION
		,REGALODESCRIPCION = @RegaloDescripcion
		,REGALOIMAGENURL = @RegaloImagenUrl
	)AS [SOURCE] 
	ON (
		[TARGET].CAMPANIAID = [SOURCE].CAMPANIAID
		AND [TARGET].CUV = [SOURCE].CUV
	)
	WHEN MATCHED THEN
		UPDATE 
		SET DESCRIPCION = [SOURCE].DESCRIPCION,
		PRECIOPRODUCTO = [SOURCE].PRECIOPRODUCTO,
		FACTORREPETICION = [SOURCE].FACTORREPETICION,
		REGALODESCRIPCION = [SOURCE].REGALODESCRIPCION,
		REGALOIMAGENURL = [SOURCE].REGALOIMAGENURL
	WHEN NOT MATCHED THEN
		INSERT (CAMPANIAID, CUV, DESCRIPCION,PRECIOPRODUCTO,FACTORREPETICION,REGALODESCRIPCION,REGALOIMAGENURL)
		VALUES ([SOURCE].CAMPANIAID, [SOURCE].CUV, [SOURCE].DESCRIPCION,[SOURCE].PRECIOPRODUCTO,[SOURCE].FACTORREPETICION,[SOURCE].REGALODESCRIPCION,[SOURCE].REGALOIMAGENURL);

	COMMIT TRAN;
END TRY
BEGIN CATCH
	ROLLBACK TRAN;
	THROW;
END CATCH
go

USE BelcorpMexico
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdProductoDescripcion]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[UpdProductoDescripcion]
GO
CREATE PROCEDURE UpdProductoDescripcion
	@CampaniaID int,
	@CUV varchar(20),
	@Descripcion varchar(100),
	@PrecioProducto numeric(12,2),
	@FactorRepeticion int,
	@CodigoUsuario varchar(25),
	@RegaloDescripcion varchar(500) = NULL,
	@RegaloImagenUrl varchar(255)= NULL
AS
BEGIN TRY
	BEGIN TRAN

	IF EXISTS(	SELECT CAMPANIAID, CUV 
				FROM PRODUCTODESCRIPCION 
				WHERE CAMPANIAID = @CAMPANIAID AND CUV = @CUV)
		INSERT INTO LOGMATRIZCAMPANIA(CAMPANIAID, CUV, DESCRIPCION, PRECIO, FACTORREPETICION, CODIGOUSUARIOPROCESO, FECHAMODIFICACION)
		SELECT CAMPANIAID, CUV, DESCRIPCION, PRECIOPRODUCTO, FACTORREPETICION, @CODIGOUSUARIO, DBO.FNOBTENERFECHAHORAPAIS()
		FROM PRODUCTODESCRIPCION 
		WHERE CAMPANIAID = @CAMPANIAID 
		AND CUV = @CUV

	MERGE DBO.PRODUCTODESCRIPCION AS [TARGET]
	USING (
		SELECT 
		CAMPANIAID = @CAMPANIAID
		,CUV = @CUV
		,DESCRIPCION = @DESCRIPCION
		,PRECIOPRODUCTO = @PRECIOPRODUCTO
		,FACTORREPETICION = @FACTORREPETICION
		,REGALODESCRIPCION = @RegaloDescripcion
		,REGALOIMAGENURL = @RegaloImagenUrl
	)AS [SOURCE] 
	ON (
		[TARGET].CAMPANIAID = [SOURCE].CAMPANIAID
		AND [TARGET].CUV = [SOURCE].CUV
	)
	WHEN MATCHED THEN
		UPDATE 
		SET DESCRIPCION = [SOURCE].DESCRIPCION,
		PRECIOPRODUCTO = [SOURCE].PRECIOPRODUCTO,
		FACTORREPETICION = [SOURCE].FACTORREPETICION,
		REGALODESCRIPCION = [SOURCE].REGALODESCRIPCION,
		REGALOIMAGENURL = [SOURCE].REGALOIMAGENURL
	WHEN NOT MATCHED THEN
		INSERT (CAMPANIAID, CUV, DESCRIPCION,PRECIOPRODUCTO,FACTORREPETICION,REGALODESCRIPCION,REGALOIMAGENURL)
		VALUES ([SOURCE].CAMPANIAID, [SOURCE].CUV, [SOURCE].DESCRIPCION,[SOURCE].PRECIOPRODUCTO,[SOURCE].FACTORREPETICION,[SOURCE].REGALODESCRIPCION,[SOURCE].REGALOIMAGENURL);

	COMMIT TRAN;
END TRY
BEGIN CATCH
	ROLLBACK TRAN;
	THROW;
END CATCH
go

USE BelcorpColombia
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdProductoDescripcion]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[UpdProductoDescripcion]
GO
CREATE PROCEDURE UpdProductoDescripcion
	@CampaniaID int,
	@CUV varchar(20),
	@Descripcion varchar(100),
	@PrecioProducto numeric(12,2),
	@FactorRepeticion int,
	@CodigoUsuario varchar(25),
	@RegaloDescripcion varchar(500) = NULL,
	@RegaloImagenUrl varchar(255)= NULL
AS
BEGIN TRY
	BEGIN TRAN

	IF EXISTS(	SELECT CAMPANIAID, CUV 
				FROM PRODUCTODESCRIPCION 
				WHERE CAMPANIAID = @CAMPANIAID AND CUV = @CUV)
		INSERT INTO LOGMATRIZCAMPANIA(CAMPANIAID, CUV, DESCRIPCION, PRECIO, FACTORREPETICION, CODIGOUSUARIOPROCESO, FECHAMODIFICACION)
		SELECT CAMPANIAID, CUV, DESCRIPCION, PRECIOPRODUCTO, FACTORREPETICION, @CODIGOUSUARIO, DBO.FNOBTENERFECHAHORAPAIS()
		FROM PRODUCTODESCRIPCION 
		WHERE CAMPANIAID = @CAMPANIAID 
		AND CUV = @CUV

	MERGE DBO.PRODUCTODESCRIPCION AS [TARGET]
	USING (
		SELECT 
		CAMPANIAID = @CAMPANIAID
		,CUV = @CUV
		,DESCRIPCION = @DESCRIPCION
		,PRECIOPRODUCTO = @PRECIOPRODUCTO
		,FACTORREPETICION = @FACTORREPETICION
		,REGALODESCRIPCION = @RegaloDescripcion
		,REGALOIMAGENURL = @RegaloImagenUrl
	)AS [SOURCE] 
	ON (
		[TARGET].CAMPANIAID = [SOURCE].CAMPANIAID
		AND [TARGET].CUV = [SOURCE].CUV
	)
	WHEN MATCHED THEN
		UPDATE 
		SET DESCRIPCION = [SOURCE].DESCRIPCION,
		PRECIOPRODUCTO = [SOURCE].PRECIOPRODUCTO,
		FACTORREPETICION = [SOURCE].FACTORREPETICION,
		REGALODESCRIPCION = [SOURCE].REGALODESCRIPCION,
		REGALOIMAGENURL = [SOURCE].REGALOIMAGENURL
	WHEN NOT MATCHED THEN
		INSERT (CAMPANIAID, CUV, DESCRIPCION,PRECIOPRODUCTO,FACTORREPETICION,REGALODESCRIPCION,REGALOIMAGENURL)
		VALUES ([SOURCE].CAMPANIAID, [SOURCE].CUV, [SOURCE].DESCRIPCION,[SOURCE].PRECIOPRODUCTO,[SOURCE].FACTORREPETICION,[SOURCE].REGALODESCRIPCION,[SOURCE].REGALOIMAGENURL);

	COMMIT TRAN;
END TRY
BEGIN CATCH
	ROLLBACK TRAN;
	THROW;
END CATCH
go

USE BelcorpSalvador
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdProductoDescripcion]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[UpdProductoDescripcion]
GO
CREATE PROCEDURE UpdProductoDescripcion
	@CampaniaID int,
	@CUV varchar(20),
	@Descripcion varchar(100),
	@PrecioProducto numeric(12,2),
	@FactorRepeticion int,
	@CodigoUsuario varchar(25),
	@RegaloDescripcion varchar(500) = NULL,
	@RegaloImagenUrl varchar(255)= NULL
AS
BEGIN TRY
	BEGIN TRAN

	IF EXISTS(	SELECT CAMPANIAID, CUV 
				FROM PRODUCTODESCRIPCION 
				WHERE CAMPANIAID = @CAMPANIAID AND CUV = @CUV)
		INSERT INTO LOGMATRIZCAMPANIA(CAMPANIAID, CUV, DESCRIPCION, PRECIO, FACTORREPETICION, CODIGOUSUARIOPROCESO, FECHAMODIFICACION)
		SELECT CAMPANIAID, CUV, DESCRIPCION, PRECIOPRODUCTO, FACTORREPETICION, @CODIGOUSUARIO, DBO.FNOBTENERFECHAHORAPAIS()
		FROM PRODUCTODESCRIPCION 
		WHERE CAMPANIAID = @CAMPANIAID 
		AND CUV = @CUV

	MERGE DBO.PRODUCTODESCRIPCION AS [TARGET]
	USING (
		SELECT 
		CAMPANIAID = @CAMPANIAID
		,CUV = @CUV
		,DESCRIPCION = @DESCRIPCION
		,PRECIOPRODUCTO = @PRECIOPRODUCTO
		,FACTORREPETICION = @FACTORREPETICION
		,REGALODESCRIPCION = @RegaloDescripcion
		,REGALOIMAGENURL = @RegaloImagenUrl
	)AS [SOURCE] 
	ON (
		[TARGET].CAMPANIAID = [SOURCE].CAMPANIAID
		AND [TARGET].CUV = [SOURCE].CUV
	)
	WHEN MATCHED THEN
		UPDATE 
		SET DESCRIPCION = [SOURCE].DESCRIPCION,
		PRECIOPRODUCTO = [SOURCE].PRECIOPRODUCTO,
		FACTORREPETICION = [SOURCE].FACTORREPETICION,
		REGALODESCRIPCION = [SOURCE].REGALODESCRIPCION,
		REGALOIMAGENURL = [SOURCE].REGALOIMAGENURL
	WHEN NOT MATCHED THEN
		INSERT (CAMPANIAID, CUV, DESCRIPCION,PRECIOPRODUCTO,FACTORREPETICION,REGALODESCRIPCION,REGALOIMAGENURL)
		VALUES ([SOURCE].CAMPANIAID, [SOURCE].CUV, [SOURCE].DESCRIPCION,[SOURCE].PRECIOPRODUCTO,[SOURCE].FACTORREPETICION,[SOURCE].REGALODESCRIPCION,[SOURCE].REGALOIMAGENURL);

	COMMIT TRAN;
END TRY
BEGIN CATCH
	ROLLBACK TRAN;
	THROW;
END CATCH
go

USE BelcorpPuertoRico
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdProductoDescripcion]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[UpdProductoDescripcion]
GO
CREATE PROCEDURE UpdProductoDescripcion
	@CampaniaID int,
	@CUV varchar(20),
	@Descripcion varchar(100),
	@PrecioProducto numeric(12,2),
	@FactorRepeticion int,
	@CodigoUsuario varchar(25),
	@RegaloDescripcion varchar(500) = NULL,
	@RegaloImagenUrl varchar(255)= NULL
AS
BEGIN TRY
	BEGIN TRAN

	IF EXISTS(	SELECT CAMPANIAID, CUV 
				FROM PRODUCTODESCRIPCION 
				WHERE CAMPANIAID = @CAMPANIAID AND CUV = @CUV)
		INSERT INTO LOGMATRIZCAMPANIA(CAMPANIAID, CUV, DESCRIPCION, PRECIO, FACTORREPETICION, CODIGOUSUARIOPROCESO, FECHAMODIFICACION)
		SELECT CAMPANIAID, CUV, DESCRIPCION, PRECIOPRODUCTO, FACTORREPETICION, @CODIGOUSUARIO, DBO.FNOBTENERFECHAHORAPAIS()
		FROM PRODUCTODESCRIPCION 
		WHERE CAMPANIAID = @CAMPANIAID 
		AND CUV = @CUV

	MERGE DBO.PRODUCTODESCRIPCION AS [TARGET]
	USING (
		SELECT 
		CAMPANIAID = @CAMPANIAID
		,CUV = @CUV
		,DESCRIPCION = @DESCRIPCION
		,PRECIOPRODUCTO = @PRECIOPRODUCTO
		,FACTORREPETICION = @FACTORREPETICION
		,REGALODESCRIPCION = @RegaloDescripcion
		,REGALOIMAGENURL = @RegaloImagenUrl
	)AS [SOURCE] 
	ON (
		[TARGET].CAMPANIAID = [SOURCE].CAMPANIAID
		AND [TARGET].CUV = [SOURCE].CUV
	)
	WHEN MATCHED THEN
		UPDATE 
		SET DESCRIPCION = [SOURCE].DESCRIPCION,
		PRECIOPRODUCTO = [SOURCE].PRECIOPRODUCTO,
		FACTORREPETICION = [SOURCE].FACTORREPETICION,
		REGALODESCRIPCION = [SOURCE].REGALODESCRIPCION,
		REGALOIMAGENURL = [SOURCE].REGALOIMAGENURL
	WHEN NOT MATCHED THEN
		INSERT (CAMPANIAID, CUV, DESCRIPCION,PRECIOPRODUCTO,FACTORREPETICION,REGALODESCRIPCION,REGALOIMAGENURL)
		VALUES ([SOURCE].CAMPANIAID, [SOURCE].CUV, [SOURCE].DESCRIPCION,[SOURCE].PRECIOPRODUCTO,[SOURCE].FACTORREPETICION,[SOURCE].REGALODESCRIPCION,[SOURCE].REGALOIMAGENURL);

	COMMIT TRAN;
END TRY
BEGIN CATCH
	ROLLBACK TRAN;
	THROW;
END CATCH
go

USE BelcorpPanama
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdProductoDescripcion]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[UpdProductoDescripcion]
GO
CREATE PROCEDURE UpdProductoDescripcion
	@CampaniaID int,
	@CUV varchar(20),
	@Descripcion varchar(100),
	@PrecioProducto numeric(12,2),
	@FactorRepeticion int,
	@CodigoUsuario varchar(25),
	@RegaloDescripcion varchar(500) = NULL,
	@RegaloImagenUrl varchar(255)= NULL
AS
BEGIN TRY
	BEGIN TRAN

	IF EXISTS(	SELECT CAMPANIAID, CUV 
				FROM PRODUCTODESCRIPCION 
				WHERE CAMPANIAID = @CAMPANIAID AND CUV = @CUV)
		INSERT INTO LOGMATRIZCAMPANIA(CAMPANIAID, CUV, DESCRIPCION, PRECIO, FACTORREPETICION, CODIGOUSUARIOPROCESO, FECHAMODIFICACION)
		SELECT CAMPANIAID, CUV, DESCRIPCION, PRECIOPRODUCTO, FACTORREPETICION, @CODIGOUSUARIO, DBO.FNOBTENERFECHAHORAPAIS()
		FROM PRODUCTODESCRIPCION 
		WHERE CAMPANIAID = @CAMPANIAID 
		AND CUV = @CUV

	MERGE DBO.PRODUCTODESCRIPCION AS [TARGET]
	USING (
		SELECT 
		CAMPANIAID = @CAMPANIAID
		,CUV = @CUV
		,DESCRIPCION = @DESCRIPCION
		,PRECIOPRODUCTO = @PRECIOPRODUCTO
		,FACTORREPETICION = @FACTORREPETICION
		,REGALODESCRIPCION = @RegaloDescripcion
		,REGALOIMAGENURL = @RegaloImagenUrl
	)AS [SOURCE] 
	ON (
		[TARGET].CAMPANIAID = [SOURCE].CAMPANIAID
		AND [TARGET].CUV = [SOURCE].CUV
	)
	WHEN MATCHED THEN
		UPDATE 
		SET DESCRIPCION = [SOURCE].DESCRIPCION,
		PRECIOPRODUCTO = [SOURCE].PRECIOPRODUCTO,
		FACTORREPETICION = [SOURCE].FACTORREPETICION,
		REGALODESCRIPCION = [SOURCE].REGALODESCRIPCION,
		REGALOIMAGENURL = [SOURCE].REGALOIMAGENURL
	WHEN NOT MATCHED THEN
		INSERT (CAMPANIAID, CUV, DESCRIPCION,PRECIOPRODUCTO,FACTORREPETICION,REGALODESCRIPCION,REGALOIMAGENURL)
		VALUES ([SOURCE].CAMPANIAID, [SOURCE].CUV, [SOURCE].DESCRIPCION,[SOURCE].PRECIOPRODUCTO,[SOURCE].FACTORREPETICION,[SOURCE].REGALODESCRIPCION,[SOURCE].REGALOIMAGENURL);

	COMMIT TRAN;
END TRY
BEGIN CATCH
	ROLLBACK TRAN;
	THROW;
END CATCH
go

USE BelcorpGuatemala
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdProductoDescripcion]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[UpdProductoDescripcion]
GO
CREATE PROCEDURE UpdProductoDescripcion
	@CampaniaID int,
	@CUV varchar(20),
	@Descripcion varchar(100),
	@PrecioProducto numeric(12,2),
	@FactorRepeticion int,
	@CodigoUsuario varchar(25),
	@RegaloDescripcion varchar(500) = NULL,
	@RegaloImagenUrl varchar(255)= NULL
AS
BEGIN TRY
	BEGIN TRAN

	IF EXISTS(	SELECT CAMPANIAID, CUV 
				FROM PRODUCTODESCRIPCION 
				WHERE CAMPANIAID = @CAMPANIAID AND CUV = @CUV)
		INSERT INTO LOGMATRIZCAMPANIA(CAMPANIAID, CUV, DESCRIPCION, PRECIO, FACTORREPETICION, CODIGOUSUARIOPROCESO, FECHAMODIFICACION)
		SELECT CAMPANIAID, CUV, DESCRIPCION, PRECIOPRODUCTO, FACTORREPETICION, @CODIGOUSUARIO, DBO.FNOBTENERFECHAHORAPAIS()
		FROM PRODUCTODESCRIPCION 
		WHERE CAMPANIAID = @CAMPANIAID 
		AND CUV = @CUV

	MERGE DBO.PRODUCTODESCRIPCION AS [TARGET]
	USING (
		SELECT 
		CAMPANIAID = @CAMPANIAID
		,CUV = @CUV
		,DESCRIPCION = @DESCRIPCION
		,PRECIOPRODUCTO = @PRECIOPRODUCTO
		,FACTORREPETICION = @FACTORREPETICION
		,REGALODESCRIPCION = @RegaloDescripcion
		,REGALOIMAGENURL = @RegaloImagenUrl
	)AS [SOURCE] 
	ON (
		[TARGET].CAMPANIAID = [SOURCE].CAMPANIAID
		AND [TARGET].CUV = [SOURCE].CUV
	)
	WHEN MATCHED THEN
		UPDATE 
		SET DESCRIPCION = [SOURCE].DESCRIPCION,
		PRECIOPRODUCTO = [SOURCE].PRECIOPRODUCTO,
		FACTORREPETICION = [SOURCE].FACTORREPETICION,
		REGALODESCRIPCION = [SOURCE].REGALODESCRIPCION,
		REGALOIMAGENURL = [SOURCE].REGALOIMAGENURL
	WHEN NOT MATCHED THEN
		INSERT (CAMPANIAID, CUV, DESCRIPCION,PRECIOPRODUCTO,FACTORREPETICION,REGALODESCRIPCION,REGALOIMAGENURL)
		VALUES ([SOURCE].CAMPANIAID, [SOURCE].CUV, [SOURCE].DESCRIPCION,[SOURCE].PRECIOPRODUCTO,[SOURCE].FACTORREPETICION,[SOURCE].REGALODESCRIPCION,[SOURCE].REGALOIMAGENURL);

	COMMIT TRAN;
END TRY
BEGIN CATCH
	ROLLBACK TRAN;
	THROW;
END CATCH
go

USE BelcorpEcuador
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdProductoDescripcion]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[UpdProductoDescripcion]
GO
CREATE PROCEDURE UpdProductoDescripcion
	@CampaniaID int,
	@CUV varchar(20),
	@Descripcion varchar(100),
	@PrecioProducto numeric(12,2),
	@FactorRepeticion int,
	@CodigoUsuario varchar(25),
	@RegaloDescripcion varchar(500) = NULL,
	@RegaloImagenUrl varchar(255)= NULL
AS
BEGIN TRY
	BEGIN TRAN

	IF EXISTS(	SELECT CAMPANIAID, CUV 
				FROM PRODUCTODESCRIPCION 
				WHERE CAMPANIAID = @CAMPANIAID AND CUV = @CUV)
		INSERT INTO LOGMATRIZCAMPANIA(CAMPANIAID, CUV, DESCRIPCION, PRECIO, FACTORREPETICION, CODIGOUSUARIOPROCESO, FECHAMODIFICACION)
		SELECT CAMPANIAID, CUV, DESCRIPCION, PRECIOPRODUCTO, FACTORREPETICION, @CODIGOUSUARIO, DBO.FNOBTENERFECHAHORAPAIS()
		FROM PRODUCTODESCRIPCION 
		WHERE CAMPANIAID = @CAMPANIAID 
		AND CUV = @CUV

	MERGE DBO.PRODUCTODESCRIPCION AS [TARGET]
	USING (
		SELECT 
		CAMPANIAID = @CAMPANIAID
		,CUV = @CUV
		,DESCRIPCION = @DESCRIPCION
		,PRECIOPRODUCTO = @PRECIOPRODUCTO
		,FACTORREPETICION = @FACTORREPETICION
		,REGALODESCRIPCION = @RegaloDescripcion
		,REGALOIMAGENURL = @RegaloImagenUrl
	)AS [SOURCE] 
	ON (
		[TARGET].CAMPANIAID = [SOURCE].CAMPANIAID
		AND [TARGET].CUV = [SOURCE].CUV
	)
	WHEN MATCHED THEN
		UPDATE 
		SET DESCRIPCION = [SOURCE].DESCRIPCION,
		PRECIOPRODUCTO = [SOURCE].PRECIOPRODUCTO,
		FACTORREPETICION = [SOURCE].FACTORREPETICION,
		REGALODESCRIPCION = [SOURCE].REGALODESCRIPCION,
		REGALOIMAGENURL = [SOURCE].REGALOIMAGENURL
	WHEN NOT MATCHED THEN
		INSERT (CAMPANIAID, CUV, DESCRIPCION,PRECIOPRODUCTO,FACTORREPETICION,REGALODESCRIPCION,REGALOIMAGENURL)
		VALUES ([SOURCE].CAMPANIAID, [SOURCE].CUV, [SOURCE].DESCRIPCION,[SOURCE].PRECIOPRODUCTO,[SOURCE].FACTORREPETICION,[SOURCE].REGALODESCRIPCION,[SOURCE].REGALOIMAGENURL);

	COMMIT TRAN;
END TRY
BEGIN CATCH
	ROLLBACK TRAN;
	THROW;
END CATCH
go

USE BelcorpDominicana
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdProductoDescripcion]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[UpdProductoDescripcion]
GO
CREATE PROCEDURE UpdProductoDescripcion
	@CampaniaID int,
	@CUV varchar(20),
	@Descripcion varchar(100),
	@PrecioProducto numeric(12,2),
	@FactorRepeticion int,
	@CodigoUsuario varchar(25),
	@RegaloDescripcion varchar(500) = NULL,
	@RegaloImagenUrl varchar(255)= NULL
AS
BEGIN TRY
	BEGIN TRAN

	IF EXISTS(	SELECT CAMPANIAID, CUV 
				FROM PRODUCTODESCRIPCION 
				WHERE CAMPANIAID = @CAMPANIAID AND CUV = @CUV)
		INSERT INTO LOGMATRIZCAMPANIA(CAMPANIAID, CUV, DESCRIPCION, PRECIO, FACTORREPETICION, CODIGOUSUARIOPROCESO, FECHAMODIFICACION)
		SELECT CAMPANIAID, CUV, DESCRIPCION, PRECIOPRODUCTO, FACTORREPETICION, @CODIGOUSUARIO, DBO.FNOBTENERFECHAHORAPAIS()
		FROM PRODUCTODESCRIPCION 
		WHERE CAMPANIAID = @CAMPANIAID 
		AND CUV = @CUV

	MERGE DBO.PRODUCTODESCRIPCION AS [TARGET]
	USING (
		SELECT 
		CAMPANIAID = @CAMPANIAID
		,CUV = @CUV
		,DESCRIPCION = @DESCRIPCION
		,PRECIOPRODUCTO = @PRECIOPRODUCTO
		,FACTORREPETICION = @FACTORREPETICION
		,REGALODESCRIPCION = @RegaloDescripcion
		,REGALOIMAGENURL = @RegaloImagenUrl
	)AS [SOURCE] 
	ON (
		[TARGET].CAMPANIAID = [SOURCE].CAMPANIAID
		AND [TARGET].CUV = [SOURCE].CUV
	)
	WHEN MATCHED THEN
		UPDATE 
		SET DESCRIPCION = [SOURCE].DESCRIPCION,
		PRECIOPRODUCTO = [SOURCE].PRECIOPRODUCTO,
		FACTORREPETICION = [SOURCE].FACTORREPETICION,
		REGALODESCRIPCION = [SOURCE].REGALODESCRIPCION,
		REGALOIMAGENURL = [SOURCE].REGALOIMAGENURL
	WHEN NOT MATCHED THEN
		INSERT (CAMPANIAID, CUV, DESCRIPCION,PRECIOPRODUCTO,FACTORREPETICION,REGALODESCRIPCION,REGALOIMAGENURL)
		VALUES ([SOURCE].CAMPANIAID, [SOURCE].CUV, [SOURCE].DESCRIPCION,[SOURCE].PRECIOPRODUCTO,[SOURCE].FACTORREPETICION,[SOURCE].REGALODESCRIPCION,[SOURCE].REGALOIMAGENURL);

	COMMIT TRAN;
END TRY
BEGIN CATCH
	ROLLBACK TRAN;
	THROW;
END CATCH
go

USE BelcorpCostaRica
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdProductoDescripcion]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[UpdProductoDescripcion]
GO
CREATE PROCEDURE UpdProductoDescripcion
	@CampaniaID int,
	@CUV varchar(20),
	@Descripcion varchar(100),
	@PrecioProducto numeric(12,2),
	@FactorRepeticion int,
	@CodigoUsuario varchar(25),
	@RegaloDescripcion varchar(500) = NULL,
	@RegaloImagenUrl varchar(255)= NULL
AS
BEGIN TRY
	BEGIN TRAN

	IF EXISTS(	SELECT CAMPANIAID, CUV 
				FROM PRODUCTODESCRIPCION 
				WHERE CAMPANIAID = @CAMPANIAID AND CUV = @CUV)
		INSERT INTO LOGMATRIZCAMPANIA(CAMPANIAID, CUV, DESCRIPCION, PRECIO, FACTORREPETICION, CODIGOUSUARIOPROCESO, FECHAMODIFICACION)
		SELECT CAMPANIAID, CUV, DESCRIPCION, PRECIOPRODUCTO, FACTORREPETICION, @CODIGOUSUARIO, DBO.FNOBTENERFECHAHORAPAIS()
		FROM PRODUCTODESCRIPCION 
		WHERE CAMPANIAID = @CAMPANIAID 
		AND CUV = @CUV

	MERGE DBO.PRODUCTODESCRIPCION AS [TARGET]
	USING (
		SELECT 
		CAMPANIAID = @CAMPANIAID
		,CUV = @CUV
		,DESCRIPCION = @DESCRIPCION
		,PRECIOPRODUCTO = @PRECIOPRODUCTO
		,FACTORREPETICION = @FACTORREPETICION
		,REGALODESCRIPCION = @RegaloDescripcion
		,REGALOIMAGENURL = @RegaloImagenUrl
	)AS [SOURCE] 
	ON (
		[TARGET].CAMPANIAID = [SOURCE].CAMPANIAID
		AND [TARGET].CUV = [SOURCE].CUV
	)
	WHEN MATCHED THEN
		UPDATE 
		SET DESCRIPCION = [SOURCE].DESCRIPCION,
		PRECIOPRODUCTO = [SOURCE].PRECIOPRODUCTO,
		FACTORREPETICION = [SOURCE].FACTORREPETICION,
		REGALODESCRIPCION = [SOURCE].REGALODESCRIPCION,
		REGALOIMAGENURL = [SOURCE].REGALOIMAGENURL
	WHEN NOT MATCHED THEN
		INSERT (CAMPANIAID, CUV, DESCRIPCION,PRECIOPRODUCTO,FACTORREPETICION,REGALODESCRIPCION,REGALOIMAGENURL)
		VALUES ([SOURCE].CAMPANIAID, [SOURCE].CUV, [SOURCE].DESCRIPCION,[SOURCE].PRECIOPRODUCTO,[SOURCE].FACTORREPETICION,[SOURCE].REGALODESCRIPCION,[SOURCE].REGALOIMAGENURL);

	COMMIT TRAN;
END TRY
BEGIN CATCH
	ROLLBACK TRAN;
	THROW;
END CATCH
go

USE BelcorpChile
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdProductoDescripcion]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[UpdProductoDescripcion]
GO
CREATE PROCEDURE UpdProductoDescripcion
	@CampaniaID int,
	@CUV varchar(20),
	@Descripcion varchar(100),
	@PrecioProducto numeric(12,2),
	@FactorRepeticion int,
	@CodigoUsuario varchar(25),
	@RegaloDescripcion varchar(500) = NULL,
	@RegaloImagenUrl varchar(255)= NULL
AS
BEGIN TRY
	BEGIN TRAN

	IF EXISTS(	SELECT CAMPANIAID, CUV 
				FROM PRODUCTODESCRIPCION 
				WHERE CAMPANIAID = @CAMPANIAID AND CUV = @CUV)
		INSERT INTO LOGMATRIZCAMPANIA(CAMPANIAID, CUV, DESCRIPCION, PRECIO, FACTORREPETICION, CODIGOUSUARIOPROCESO, FECHAMODIFICACION)
		SELECT CAMPANIAID, CUV, DESCRIPCION, PRECIOPRODUCTO, FACTORREPETICION, @CODIGOUSUARIO, DBO.FNOBTENERFECHAHORAPAIS()
		FROM PRODUCTODESCRIPCION 
		WHERE CAMPANIAID = @CAMPANIAID 
		AND CUV = @CUV

	MERGE DBO.PRODUCTODESCRIPCION AS [TARGET]
	USING (
		SELECT 
		CAMPANIAID = @CAMPANIAID
		,CUV = @CUV
		,DESCRIPCION = @DESCRIPCION
		,PRECIOPRODUCTO = @PRECIOPRODUCTO
		,FACTORREPETICION = @FACTORREPETICION
		,REGALODESCRIPCION = @RegaloDescripcion
		,REGALOIMAGENURL = @RegaloImagenUrl
	)AS [SOURCE] 
	ON (
		[TARGET].CAMPANIAID = [SOURCE].CAMPANIAID
		AND [TARGET].CUV = [SOURCE].CUV
	)
	WHEN MATCHED THEN
		UPDATE 
		SET DESCRIPCION = [SOURCE].DESCRIPCION,
		PRECIOPRODUCTO = [SOURCE].PRECIOPRODUCTO,
		FACTORREPETICION = [SOURCE].FACTORREPETICION,
		REGALODESCRIPCION = [SOURCE].REGALODESCRIPCION,
		REGALOIMAGENURL = [SOURCE].REGALOIMAGENURL
	WHEN NOT MATCHED THEN
		INSERT (CAMPANIAID, CUV, DESCRIPCION,PRECIOPRODUCTO,FACTORREPETICION,REGALODESCRIPCION,REGALOIMAGENURL)
		VALUES ([SOURCE].CAMPANIAID, [SOURCE].CUV, [SOURCE].DESCRIPCION,[SOURCE].PRECIOPRODUCTO,[SOURCE].FACTORREPETICION,[SOURCE].REGALODESCRIPCION,[SOURCE].REGALOIMAGENURL);

	COMMIT TRAN;
END TRY
BEGIN CATCH
	ROLLBACK TRAN;
	THROW;
END CATCH
go

USE BelcorpBolivia
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[UpdProductoDescripcion]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[UpdProductoDescripcion]
GO
CREATE PROCEDURE UpdProductoDescripcion
	@CampaniaID int,
	@CUV varchar(20),
	@Descripcion varchar(100),
	@PrecioProducto numeric(12,2),
	@FactorRepeticion int,
	@CodigoUsuario varchar(25),
	@RegaloDescripcion varchar(500) = NULL,
	@RegaloImagenUrl varchar(255)= NULL
AS
BEGIN TRY
	BEGIN TRAN

	IF EXISTS(	SELECT CAMPANIAID, CUV 
				FROM PRODUCTODESCRIPCION 
				WHERE CAMPANIAID = @CAMPANIAID AND CUV = @CUV)
		INSERT INTO LOGMATRIZCAMPANIA(CAMPANIAID, CUV, DESCRIPCION, PRECIO, FACTORREPETICION, CODIGOUSUARIOPROCESO, FECHAMODIFICACION)
		SELECT CAMPANIAID, CUV, DESCRIPCION, PRECIOPRODUCTO, FACTORREPETICION, @CODIGOUSUARIO, DBO.FNOBTENERFECHAHORAPAIS()
		FROM PRODUCTODESCRIPCION 
		WHERE CAMPANIAID = @CAMPANIAID 
		AND CUV = @CUV

	MERGE DBO.PRODUCTODESCRIPCION AS [TARGET]
	USING (
		SELECT 
		CAMPANIAID = @CAMPANIAID
		,CUV = @CUV
		,DESCRIPCION = @DESCRIPCION
		,PRECIOPRODUCTO = @PRECIOPRODUCTO
		,FACTORREPETICION = @FACTORREPETICION
		,REGALODESCRIPCION = @RegaloDescripcion
		,REGALOIMAGENURL = @RegaloImagenUrl
	)AS [SOURCE] 
	ON (
		[TARGET].CAMPANIAID = [SOURCE].CAMPANIAID
		AND [TARGET].CUV = [SOURCE].CUV
	)
	WHEN MATCHED THEN
		UPDATE 
		SET DESCRIPCION = [SOURCE].DESCRIPCION,
		PRECIOPRODUCTO = [SOURCE].PRECIOPRODUCTO,
		FACTORREPETICION = [SOURCE].FACTORREPETICION,
		REGALODESCRIPCION = [SOURCE].REGALODESCRIPCION,
		REGALOIMAGENURL = [SOURCE].REGALOIMAGENURL
	WHEN NOT MATCHED THEN
		INSERT (CAMPANIAID, CUV, DESCRIPCION,PRECIOPRODUCTO,FACTORREPETICION,REGALODESCRIPCION,REGALOIMAGENURL)
		VALUES ([SOURCE].CAMPANIAID, [SOURCE].CUV, [SOURCE].DESCRIPCION,[SOURCE].PRECIOPRODUCTO,[SOURCE].FACTORREPETICION,[SOURCE].REGALODESCRIPCION,[SOURCE].REGALOIMAGENURL);

	COMMIT TRAN;
END TRY
BEGIN CATCH
	ROLLBACK TRAN;
	THROW;
END CATCH
go

