GO
USE BelcorpPeru
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912'-- NUeva
GetFechasFacturacionConsultora '011871852', '201912' --Atigua
GetFechasFacturacionConsultora '042923680', '201912' --Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913' --Atigua
GetFechasFacturacionConsultora '009899545', '201912'-- Atigua
*/

CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1), @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));

      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

	/*OBTENEMOS LOS PARAMETROS DE CANTIDAD*/
	DECLARE  @IDCANTIDADFECHAFACTURACION INT=179
	DECLARE  @CODIGOANTERIORFECHAFACTURACION VARCHAR(16)='Anterior'
	DECLARE  @CODIGOPROXIMASFECHAFACTURACION VARCHAR(16)='Proxima'
	DECLARE  @VALORANTERIORFECHAFACTURACION INT
	DECLARE  @VALORPROXIMASFECHAFACTURACION INT

	SELECT @VALORANTERIORFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOANTERIORFECHAFACTURACION
	SELECT @VALORPROXIMASFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOPROXIMASFECHAFACTURACION


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
								  CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END),

             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !='' THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),

             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT ISNULL(@CAMPANIAPARTIDA,'')        CAMPANIAPARTIDA,
             ISNULL(@FACTURACION,'')              FACTURACION,
             ISNULL(@FECHALIMITEPAGOFINAL,'')    FECHALIMITEPAGO,
             ISNULL(@FECHAINICIOFACTURACION,'')   INICIOFACTURACION,
             ISNULL(@FECHAFINFACTURACION,'')      FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@VALORPROXIMASFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))CAMPANIAPARTIDA,CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS FACTURADAS(ANTERIORES)*/
      SELECT TOP (@VALORANTERIORFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)) CAMPANIAPARTIDA, dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO )
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
									dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO ) INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END






GO
USE BelcorpMexico
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912'-- NUeva
GetFechasFacturacionConsultora '011871852', '201912' --Atigua
GetFechasFacturacionConsultora '042923680', '201912' --Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913' --Atigua
GetFechasFacturacionConsultora '009899545', '201912'-- Atigua
*/

CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1), @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));

      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

	/*OBTENEMOS LOS PARAMETROS DE CANTIDAD*/
	DECLARE  @IDCANTIDADFECHAFACTURACION INT=179
	DECLARE  @CODIGOANTERIORFECHAFACTURACION VARCHAR(16)='Anterior'
	DECLARE  @CODIGOPROXIMASFECHAFACTURACION VARCHAR(16)='Proxima'
	DECLARE  @VALORANTERIORFECHAFACTURACION INT
	DECLARE  @VALORPROXIMASFECHAFACTURACION INT

	SELECT @VALORANTERIORFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOANTERIORFECHAFACTURACION
	SELECT @VALORPROXIMASFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOPROXIMASFECHAFACTURACION


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
								  CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END),

             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !='' THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),

             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT ISNULL(@CAMPANIAPARTIDA,'')        CAMPANIAPARTIDA,
             ISNULL(@FACTURACION,'')              FACTURACION,
             ISNULL(@FECHALIMITEPAGOFINAL,'')    FECHALIMITEPAGO,
             ISNULL(@FECHAINICIOFACTURACION,'')   INICIOFACTURACION,
             ISNULL(@FECHAFINFACTURACION,'')      FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@VALORPROXIMASFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))CAMPANIAPARTIDA,CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS FACTURADAS(ANTERIORES)*/
      SELECT TOP (@VALORANTERIORFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)) CAMPANIAPARTIDA, dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO )
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
									dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO ) INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END






GO
USE BelcorpColombia
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912'-- NUeva
GetFechasFacturacionConsultora '011871852', '201912' --Atigua
GetFechasFacturacionConsultora '042923680', '201912' --Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913' --Atigua
GetFechasFacturacionConsultora '009899545', '201912'-- Atigua
*/

CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1), @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));

      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

	/*OBTENEMOS LOS PARAMETROS DE CANTIDAD*/
	DECLARE  @IDCANTIDADFECHAFACTURACION INT=179
	DECLARE  @CODIGOANTERIORFECHAFACTURACION VARCHAR(16)='Anterior'
	DECLARE  @CODIGOPROXIMASFECHAFACTURACION VARCHAR(16)='Proxima'
	DECLARE  @VALORANTERIORFECHAFACTURACION INT
	DECLARE  @VALORPROXIMASFECHAFACTURACION INT

	SELECT @VALORANTERIORFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOANTERIORFECHAFACTURACION
	SELECT @VALORPROXIMASFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOPROXIMASFECHAFACTURACION


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
								  CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END),

             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !='' THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),

             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT ISNULL(@CAMPANIAPARTIDA,'')        CAMPANIAPARTIDA,
             ISNULL(@FACTURACION,'')              FACTURACION,
             ISNULL(@FECHALIMITEPAGOFINAL,'')    FECHALIMITEPAGO,
             ISNULL(@FECHAINICIOFACTURACION,'')   INICIOFACTURACION,
             ISNULL(@FECHAFINFACTURACION,'')      FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@VALORPROXIMASFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))CAMPANIAPARTIDA,CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS FACTURADAS(ANTERIORES)*/
      SELECT TOP (@VALORANTERIORFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)) CAMPANIAPARTIDA, dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO )
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
									dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO ) INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END






GO
USE BelcorpSalvador
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912'-- NUeva
GetFechasFacturacionConsultora '011871852', '201912' --Atigua
GetFechasFacturacionConsultora '042923680', '201912' --Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913' --Atigua
GetFechasFacturacionConsultora '009899545', '201912'-- Atigua
*/

CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1), @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));

      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

	/*OBTENEMOS LOS PARAMETROS DE CANTIDAD*/
	DECLARE  @IDCANTIDADFECHAFACTURACION INT=179
	DECLARE  @CODIGOANTERIORFECHAFACTURACION VARCHAR(16)='Anterior'
	DECLARE  @CODIGOPROXIMASFECHAFACTURACION VARCHAR(16)='Proxima'
	DECLARE  @VALORANTERIORFECHAFACTURACION INT
	DECLARE  @VALORPROXIMASFECHAFACTURACION INT

	SELECT @VALORANTERIORFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOANTERIORFECHAFACTURACION
	SELECT @VALORPROXIMASFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOPROXIMASFECHAFACTURACION


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
								  CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END),

             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !='' THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),

             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT ISNULL(@CAMPANIAPARTIDA,'')        CAMPANIAPARTIDA,
             ISNULL(@FACTURACION,'')              FACTURACION,
             ISNULL(@FECHALIMITEPAGOFINAL,'')    FECHALIMITEPAGO,
             ISNULL(@FECHAINICIOFACTURACION,'')   INICIOFACTURACION,
             ISNULL(@FECHAFINFACTURACION,'')      FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@VALORPROXIMASFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))CAMPANIAPARTIDA,CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS FACTURADAS(ANTERIORES)*/
      SELECT TOP (@VALORANTERIORFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)) CAMPANIAPARTIDA, dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO )
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
									dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO ) INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END






GO
USE BelcorpPuertoRico
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912'-- NUeva
GetFechasFacturacionConsultora '011871852', '201912' --Atigua
GetFechasFacturacionConsultora '042923680', '201912' --Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913' --Atigua
GetFechasFacturacionConsultora '009899545', '201912'-- Atigua
*/

CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1), @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));

      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

	/*OBTENEMOS LOS PARAMETROS DE CANTIDAD*/
	DECLARE  @IDCANTIDADFECHAFACTURACION INT=179
	DECLARE  @CODIGOANTERIORFECHAFACTURACION VARCHAR(16)='Anterior'
	DECLARE  @CODIGOPROXIMASFECHAFACTURACION VARCHAR(16)='Proxima'
	DECLARE  @VALORANTERIORFECHAFACTURACION INT
	DECLARE  @VALORPROXIMASFECHAFACTURACION INT

	SELECT @VALORANTERIORFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOANTERIORFECHAFACTURACION
	SELECT @VALORPROXIMASFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOPROXIMASFECHAFACTURACION


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
								  CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END),

             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !='' THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),

             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT ISNULL(@CAMPANIAPARTIDA,'')        CAMPANIAPARTIDA,
             ISNULL(@FACTURACION,'')              FACTURACION,
             ISNULL(@FECHALIMITEPAGOFINAL,'')    FECHALIMITEPAGO,
             ISNULL(@FECHAINICIOFACTURACION,'')   INICIOFACTURACION,
             ISNULL(@FECHAFINFACTURACION,'')      FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@VALORPROXIMASFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))CAMPANIAPARTIDA,CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS FACTURADAS(ANTERIORES)*/
      SELECT TOP (@VALORANTERIORFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)) CAMPANIAPARTIDA, dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO )
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
									dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO ) INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END






GO
USE BelcorpPanama
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912'-- NUeva
GetFechasFacturacionConsultora '011871852', '201912' --Atigua
GetFechasFacturacionConsultora '042923680', '201912' --Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913' --Atigua
GetFechasFacturacionConsultora '009899545', '201912'-- Atigua
*/

CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1), @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));

      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

	/*OBTENEMOS LOS PARAMETROS DE CANTIDAD*/
	DECLARE  @IDCANTIDADFECHAFACTURACION INT=179
	DECLARE  @CODIGOANTERIORFECHAFACTURACION VARCHAR(16)='Anterior'
	DECLARE  @CODIGOPROXIMASFECHAFACTURACION VARCHAR(16)='Proxima'
	DECLARE  @VALORANTERIORFECHAFACTURACION INT
	DECLARE  @VALORPROXIMASFECHAFACTURACION INT

	SELECT @VALORANTERIORFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOANTERIORFECHAFACTURACION
	SELECT @VALORPROXIMASFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOPROXIMASFECHAFACTURACION


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
								  CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END),

             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !='' THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),

             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT ISNULL(@CAMPANIAPARTIDA,'')        CAMPANIAPARTIDA,
             ISNULL(@FACTURACION,'')              FACTURACION,
             ISNULL(@FECHALIMITEPAGOFINAL,'')    FECHALIMITEPAGO,
             ISNULL(@FECHAINICIOFACTURACION,'')   INICIOFACTURACION,
             ISNULL(@FECHAFINFACTURACION,'')      FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@VALORPROXIMASFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))CAMPANIAPARTIDA,CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS FACTURADAS(ANTERIORES)*/
      SELECT TOP (@VALORANTERIORFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)) CAMPANIAPARTIDA, dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO )
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
									dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO ) INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END






GO
USE BelcorpGuatemala
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912'-- NUeva
GetFechasFacturacionConsultora '011871852', '201912' --Atigua
GetFechasFacturacionConsultora '042923680', '201912' --Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913' --Atigua
GetFechasFacturacionConsultora '009899545', '201912'-- Atigua
*/

CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1), @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));

      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

	/*OBTENEMOS LOS PARAMETROS DE CANTIDAD*/
	DECLARE  @IDCANTIDADFECHAFACTURACION INT=179
	DECLARE  @CODIGOANTERIORFECHAFACTURACION VARCHAR(16)='Anterior'
	DECLARE  @CODIGOPROXIMASFECHAFACTURACION VARCHAR(16)='Proxima'
	DECLARE  @VALORANTERIORFECHAFACTURACION INT
	DECLARE  @VALORPROXIMASFECHAFACTURACION INT

	SELECT @VALORANTERIORFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOANTERIORFECHAFACTURACION
	SELECT @VALORPROXIMASFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOPROXIMASFECHAFACTURACION


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
								  CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END),

             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !='' THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),

             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT ISNULL(@CAMPANIAPARTIDA,'')        CAMPANIAPARTIDA,
             ISNULL(@FACTURACION,'')              FACTURACION,
             ISNULL(@FECHALIMITEPAGOFINAL,'')    FECHALIMITEPAGO,
             ISNULL(@FECHAINICIOFACTURACION,'')   INICIOFACTURACION,
             ISNULL(@FECHAFINFACTURACION,'')      FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@VALORPROXIMASFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))CAMPANIAPARTIDA,CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS FACTURADAS(ANTERIORES)*/
      SELECT TOP (@VALORANTERIORFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)) CAMPANIAPARTIDA, dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO )
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
									dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO ) INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END






GO
USE BelcorpEcuador
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912'-- NUeva
GetFechasFacturacionConsultora '011871852', '201912' --Atigua
GetFechasFacturacionConsultora '042923680', '201912' --Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913' --Atigua
GetFechasFacturacionConsultora '009899545', '201912'-- Atigua
*/

CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1), @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));

      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

	/*OBTENEMOS LOS PARAMETROS DE CANTIDAD*/
	DECLARE  @IDCANTIDADFECHAFACTURACION INT=179
	DECLARE  @CODIGOANTERIORFECHAFACTURACION VARCHAR(16)='Anterior'
	DECLARE  @CODIGOPROXIMASFECHAFACTURACION VARCHAR(16)='Proxima'
	DECLARE  @VALORANTERIORFECHAFACTURACION INT
	DECLARE  @VALORPROXIMASFECHAFACTURACION INT

	SELECT @VALORANTERIORFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOANTERIORFECHAFACTURACION
	SELECT @VALORPROXIMASFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOPROXIMASFECHAFACTURACION


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
								  CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END),

             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !='' THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),

             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT ISNULL(@CAMPANIAPARTIDA,'')        CAMPANIAPARTIDA,
             ISNULL(@FACTURACION,'')              FACTURACION,
             ISNULL(@FECHALIMITEPAGOFINAL,'')    FECHALIMITEPAGO,
             ISNULL(@FECHAINICIOFACTURACION,'')   INICIOFACTURACION,
             ISNULL(@FECHAFINFACTURACION,'')      FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@VALORPROXIMASFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))CAMPANIAPARTIDA,CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS FACTURADAS(ANTERIORES)*/
      SELECT TOP (@VALORANTERIORFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)) CAMPANIAPARTIDA, dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO )
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
									dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO ) INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END






GO
USE BelcorpDominicana
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912'-- NUeva
GetFechasFacturacionConsultora '011871852', '201912' --Atigua
GetFechasFacturacionConsultora '042923680', '201912' --Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913' --Atigua
GetFechasFacturacionConsultora '009899545', '201912'-- Atigua
*/

CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1), @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));

      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

	/*OBTENEMOS LOS PARAMETROS DE CANTIDAD*/
	DECLARE  @IDCANTIDADFECHAFACTURACION INT=179
	DECLARE  @CODIGOANTERIORFECHAFACTURACION VARCHAR(16)='Anterior'
	DECLARE  @CODIGOPROXIMASFECHAFACTURACION VARCHAR(16)='Proxima'
	DECLARE  @VALORANTERIORFECHAFACTURACION INT
	DECLARE  @VALORPROXIMASFECHAFACTURACION INT

	SELECT @VALORANTERIORFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOANTERIORFECHAFACTURACION
	SELECT @VALORPROXIMASFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOPROXIMASFECHAFACTURACION


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
								  CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END),

             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !='' THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),

             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT ISNULL(@CAMPANIAPARTIDA,'')        CAMPANIAPARTIDA,
             ISNULL(@FACTURACION,'')              FACTURACION,
             ISNULL(@FECHALIMITEPAGOFINAL,'')    FECHALIMITEPAGO,
             ISNULL(@FECHAINICIOFACTURACION,'')   INICIOFACTURACION,
             ISNULL(@FECHAFINFACTURACION,'')      FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@VALORPROXIMASFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))CAMPANIAPARTIDA,CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS FACTURADAS(ANTERIORES)*/
      SELECT TOP (@VALORANTERIORFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)) CAMPANIAPARTIDA, dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO )
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
									dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO ) INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END






GO
USE BelcorpCostaRica
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912'-- NUeva
GetFechasFacturacionConsultora '011871852', '201912' --Atigua
GetFechasFacturacionConsultora '042923680', '201912' --Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913' --Atigua
GetFechasFacturacionConsultora '009899545', '201912'-- Atigua
*/

CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1), @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));

      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

	/*OBTENEMOS LOS PARAMETROS DE CANTIDAD*/
	DECLARE  @IDCANTIDADFECHAFACTURACION INT=179
	DECLARE  @CODIGOANTERIORFECHAFACTURACION VARCHAR(16)='Anterior'
	DECLARE  @CODIGOPROXIMASFECHAFACTURACION VARCHAR(16)='Proxima'
	DECLARE  @VALORANTERIORFECHAFACTURACION INT
	DECLARE  @VALORPROXIMASFECHAFACTURACION INT

	SELECT @VALORANTERIORFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOANTERIORFECHAFACTURACION
	SELECT @VALORPROXIMASFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOPROXIMASFECHAFACTURACION


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
								  CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END),

             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !='' THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),

             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT ISNULL(@CAMPANIAPARTIDA,'')        CAMPANIAPARTIDA,
             ISNULL(@FACTURACION,'')              FACTURACION,
             ISNULL(@FECHALIMITEPAGOFINAL,'')    FECHALIMITEPAGO,
             ISNULL(@FECHAINICIOFACTURACION,'')   INICIOFACTURACION,
             ISNULL(@FECHAFINFACTURACION,'')      FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@VALORPROXIMASFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))CAMPANIAPARTIDA,CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS FACTURADAS(ANTERIORES)*/
      SELECT TOP (@VALORANTERIORFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)) CAMPANIAPARTIDA, dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO )
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
									dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO ) INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END






GO
USE BelcorpChile
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912'-- NUeva
GetFechasFacturacionConsultora '011871852', '201912' --Atigua
GetFechasFacturacionConsultora '042923680', '201912' --Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913' --Atigua
GetFechasFacturacionConsultora '009899545', '201912'-- Atigua
*/

CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1), @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));

      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

	/*OBTENEMOS LOS PARAMETROS DE CANTIDAD*/
	DECLARE  @IDCANTIDADFECHAFACTURACION INT=179
	DECLARE  @CODIGOANTERIORFECHAFACTURACION VARCHAR(16)='Anterior'
	DECLARE  @CODIGOPROXIMASFECHAFACTURACION VARCHAR(16)='Proxima'
	DECLARE  @VALORANTERIORFECHAFACTURACION INT
	DECLARE  @VALORPROXIMASFECHAFACTURACION INT

	SELECT @VALORANTERIORFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOANTERIORFECHAFACTURACION
	SELECT @VALORPROXIMASFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOPROXIMASFECHAFACTURACION


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
								  CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END),

             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !='' THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),

             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT ISNULL(@CAMPANIAPARTIDA,'')        CAMPANIAPARTIDA,
             ISNULL(@FACTURACION,'')              FACTURACION,
             ISNULL(@FECHALIMITEPAGOFINAL,'')    FECHALIMITEPAGO,
             ISNULL(@FECHAINICIOFACTURACION,'')   INICIOFACTURACION,
             ISNULL(@FECHAFINFACTURACION,'')      FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@VALORPROXIMASFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))CAMPANIAPARTIDA,CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS FACTURADAS(ANTERIORES)*/
      SELECT TOP (@VALORANTERIORFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)) CAMPANIAPARTIDA, dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO )
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
									dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO ) INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END






GO
USE BelcorpBolivia
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912'-- NUeva
GetFechasFacturacionConsultora '011871852', '201912' --Atigua
GetFechasFacturacionConsultora '042923680', '201912' --Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913' --Atigua
GetFechasFacturacionConsultora '009899545', '201912'-- Atigua
*/

CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1), @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));

      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

	/*OBTENEMOS LOS PARAMETROS DE CANTIDAD*/
	DECLARE  @IDCANTIDADFECHAFACTURACION INT=179
	DECLARE  @CODIGOANTERIORFECHAFACTURACION VARCHAR(16)='Anterior'
	DECLARE  @CODIGOPROXIMASFECHAFACTURACION VARCHAR(16)='Proxima'
	DECLARE  @VALORANTERIORFECHAFACTURACION INT
	DECLARE  @VALORPROXIMASFECHAFACTURACION INT

	SELECT @VALORANTERIORFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOANTERIORFECHAFACTURACION
	SELECT @VALORPROXIMASFECHAFACTURACION=CAST(ISNULL(VALOR,'0') AS INT) FROM TABLALOGICADATOS  WHERE TABLALOGICAID=@IDCANTIDADFECHAFACTURACION and Codigo=@CODIGOPROXIMASFECHAFACTURACION


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
								  CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END),

             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !='' THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),

             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT ISNULL(@CAMPANIAPARTIDA,'')        CAMPANIAPARTIDA,
             ISNULL(@FACTURACION,'')              FACTURACION,
             ISNULL(@FECHALIMITEPAGOFINAL,'')    FECHALIMITEPAGO,
             ISNULL(@FECHAINICIOFACTURACION,'')   INICIOFACTURACION,
             ISNULL(@FECHAFINFACTURACION,'')      FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@VALORPROXIMASFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))CAMPANIAPARTIDA,CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS FACTURADAS(ANTERIORES)*/
      SELECT TOP (@VALORANTERIORFECHAFACTURACION) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)) CAMPANIAPARTIDA, dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO )
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
									dbo.GetFechaCronogramaFacturacion( od.FECHAFACTURADO ) INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO ON CO.REGIONID = CR.REGIONID AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END






GO
