GO
USE BelcorpPeru_MC
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO

/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912',6,6 NUeva
GetFechasFacturacionConsultora '011871852', '201912',6,6 Atigua
GetFechasFacturacionConsultora '042923680', '201912',6,6 Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913',6,6 Atigua
*/

---SELECT * FROM ODS.CONSULTORA WHERE NOMBRECOMPLETO LIKE '%ANGEL%' ORDER BY PRIMERNOMBRE DESC




CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
									-- select @CAMPANIASIGUIENTECODIGO
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));
--select @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =
			 CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION),
								   CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
								         /*WHEN CAST(GETDATE() AS DATE) >= CAST(CR.FECHAINICIOFACTURACION AS DATE)
                                         AND CAST(GETDATE() AS DATE)  <= CAST(CR.FECHAFINREFACTURACION AS DATE)
										 THEN ' - HOY' */
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END

							),
             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !=''
									  THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(
									CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR
									ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO
									ON CO.REGIONID = CR.REGIONID
									AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END


GO
USE BelcorpMexico_MC
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO

/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912',6,6 NUeva
GetFechasFacturacionConsultora '011871852', '201912',6,6 Atigua
GetFechasFacturacionConsultora '042923680', '201912',6,6 Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913',6,6 Atigua
*/

---SELECT * FROM ODS.CONSULTORA WHERE NOMBRECOMPLETO LIKE '%ANGEL%' ORDER BY PRIMERNOMBRE DESC




CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
									-- select @CAMPANIASIGUIENTECODIGO
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));
--select @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =
			 CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION),
								   CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
								         /*WHEN CAST(GETDATE() AS DATE) >= CAST(CR.FECHAINICIOFACTURACION AS DATE)
                                         AND CAST(GETDATE() AS DATE)  <= CAST(CR.FECHAFINREFACTURACION AS DATE)
										 THEN ' - HOY' */
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END

							),
             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !=''
									  THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(
									CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR
									ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO
									ON CO.REGIONID = CR.REGIONID
									AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END


GO
USE BelcorpColombia_MC
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO

/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912',6,6 NUeva
GetFechasFacturacionConsultora '011871852', '201912',6,6 Atigua
GetFechasFacturacionConsultora '042923680', '201912',6,6 Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913',6,6 Atigua
*/

---SELECT * FROM ODS.CONSULTORA WHERE NOMBRECOMPLETO LIKE '%ANGEL%' ORDER BY PRIMERNOMBRE DESC




CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
									-- select @CAMPANIASIGUIENTECODIGO
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));
--select @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =
			 CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION),
								   CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
								         /*WHEN CAST(GETDATE() AS DATE) >= CAST(CR.FECHAINICIOFACTURACION AS DATE)
                                         AND CAST(GETDATE() AS DATE)  <= CAST(CR.FECHAFINREFACTURACION AS DATE)
										 THEN ' - HOY' */
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END

							),
             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !=''
									  THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(
									CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR
									ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO
									ON CO.REGIONID = CR.REGIONID
									AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END


GO
USE BelcorpSalvador_MC
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO

/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912',6,6 NUeva
GetFechasFacturacionConsultora '011871852', '201912',6,6 Atigua
GetFechasFacturacionConsultora '042923680', '201912',6,6 Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913',6,6 Atigua
*/

---SELECT * FROM ODS.CONSULTORA WHERE NOMBRECOMPLETO LIKE '%ANGEL%' ORDER BY PRIMERNOMBRE DESC




CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
									-- select @CAMPANIASIGUIENTECODIGO
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));
--select @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =
			 CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION),
								   CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
								         /*WHEN CAST(GETDATE() AS DATE) >= CAST(CR.FECHAINICIOFACTURACION AS DATE)
                                         AND CAST(GETDATE() AS DATE)  <= CAST(CR.FECHAFINREFACTURACION AS DATE)
										 THEN ' - HOY' */
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END

							),
             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !=''
									  THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(
									CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR
									ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO
									ON CO.REGIONID = CR.REGIONID
									AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END


GO
USE BelcorpPuertoRico_MC
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO

/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912',6,6 NUeva
GetFechasFacturacionConsultora '011871852', '201912',6,6 Atigua
GetFechasFacturacionConsultora '042923680', '201912',6,6 Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913',6,6 Atigua
*/

---SELECT * FROM ODS.CONSULTORA WHERE NOMBRECOMPLETO LIKE '%ANGEL%' ORDER BY PRIMERNOMBRE DESC




CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
									-- select @CAMPANIASIGUIENTECODIGO
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));
--select @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =
			 CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION),
								   CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
								         /*WHEN CAST(GETDATE() AS DATE) >= CAST(CR.FECHAINICIOFACTURACION AS DATE)
                                         AND CAST(GETDATE() AS DATE)  <= CAST(CR.FECHAFINREFACTURACION AS DATE)
										 THEN ' - HOY' */
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END

							),
             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !=''
									  THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(
									CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR
									ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO
									ON CO.REGIONID = CR.REGIONID
									AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END


GO
USE BelcorpPanama_MC
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO

/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912',6,6 NUeva
GetFechasFacturacionConsultora '011871852', '201912',6,6 Atigua
GetFechasFacturacionConsultora '042923680', '201912',6,6 Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913',6,6 Atigua
*/

---SELECT * FROM ODS.CONSULTORA WHERE NOMBRECOMPLETO LIKE '%ANGEL%' ORDER BY PRIMERNOMBRE DESC




CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
									-- select @CAMPANIASIGUIENTECODIGO
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));
--select @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =
			 CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION),
								   CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
								         /*WHEN CAST(GETDATE() AS DATE) >= CAST(CR.FECHAINICIOFACTURACION AS DATE)
                                         AND CAST(GETDATE() AS DATE)  <= CAST(CR.FECHAFINREFACTURACION AS DATE)
										 THEN ' - HOY' */
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END

							),
             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !=''
									  THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(
									CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR
									ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO
									ON CO.REGIONID = CR.REGIONID
									AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END


GO
USE BelcorpGuatemala_MC
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO

/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912',6,6 NUeva
GetFechasFacturacionConsultora '011871852', '201912',6,6 Atigua
GetFechasFacturacionConsultora '042923680', '201912',6,6 Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913',6,6 Atigua
*/

---SELECT * FROM ODS.CONSULTORA WHERE NOMBRECOMPLETO LIKE '%ANGEL%' ORDER BY PRIMERNOMBRE DESC




CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
									-- select @CAMPANIASIGUIENTECODIGO
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));
--select @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =
			 CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION),
								   CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
								         /*WHEN CAST(GETDATE() AS DATE) >= CAST(CR.FECHAINICIOFACTURACION AS DATE)
                                         AND CAST(GETDATE() AS DATE)  <= CAST(CR.FECHAFINREFACTURACION AS DATE)
										 THEN ' - HOY' */
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END

							),
             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !=''
									  THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(
									CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR
									ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO
									ON CO.REGIONID = CR.REGIONID
									AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END


GO
USE BelcorpEcuador_MC
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO

/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912',6,6 NUeva
GetFechasFacturacionConsultora '011871852', '201912',6,6 Atigua
GetFechasFacturacionConsultora '042923680', '201912',6,6 Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913',6,6 Atigua
*/

---SELECT * FROM ODS.CONSULTORA WHERE NOMBRECOMPLETO LIKE '%ANGEL%' ORDER BY PRIMERNOMBRE DESC




CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
									-- select @CAMPANIASIGUIENTECODIGO
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));
--select @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =
			 CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION),
								   CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
								         /*WHEN CAST(GETDATE() AS DATE) >= CAST(CR.FECHAINICIOFACTURACION AS DATE)
                                         AND CAST(GETDATE() AS DATE)  <= CAST(CR.FECHAFINREFACTURACION AS DATE)
										 THEN ' - HOY' */
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END

							),
             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !=''
									  THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(
									CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR
									ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO
									ON CO.REGIONID = CR.REGIONID
									AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END


GO
USE BelcorpDominicana_MC
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO

/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912',6,6 NUeva
GetFechasFacturacionConsultora '011871852', '201912',6,6 Atigua
GetFechasFacturacionConsultora '042923680', '201912',6,6 Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913',6,6 Atigua
*/

---SELECT * FROM ODS.CONSULTORA WHERE NOMBRECOMPLETO LIKE '%ANGEL%' ORDER BY PRIMERNOMBRE DESC




CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
									-- select @CAMPANIASIGUIENTECODIGO
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));
--select @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =
			 CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION),
								   CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
								         /*WHEN CAST(GETDATE() AS DATE) >= CAST(CR.FECHAINICIOFACTURACION AS DATE)
                                         AND CAST(GETDATE() AS DATE)  <= CAST(CR.FECHAFINREFACTURACION AS DATE)
										 THEN ' - HOY' */
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END

							),
             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !=''
									  THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(
									CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR
									ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO
									ON CO.REGIONID = CR.REGIONID
									AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END


GO
USE BelcorpCostaRica_MC
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO

/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912',6,6 NUeva
GetFechasFacturacionConsultora '011871852', '201912',6,6 Atigua
GetFechasFacturacionConsultora '042923680', '201912',6,6 Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913',6,6 Atigua
*/

---SELECT * FROM ODS.CONSULTORA WHERE NOMBRECOMPLETO LIKE '%ANGEL%' ORDER BY PRIMERNOMBRE DESC




CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
									-- select @CAMPANIASIGUIENTECODIGO
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));
--select @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =
			 CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION),
								   CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
								         /*WHEN CAST(GETDATE() AS DATE) >= CAST(CR.FECHAINICIOFACTURACION AS DATE)
                                         AND CAST(GETDATE() AS DATE)  <= CAST(CR.FECHAFINREFACTURACION AS DATE)
										 THEN ' - HOY' */
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END

							),
             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !=''
									  THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(
									CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR
									ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO
									ON CO.REGIONID = CR.REGIONID
									AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END


GO
USE BelcorpChile_MC
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO

/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912',6,6 NUeva
GetFechasFacturacionConsultora '011871852', '201912',6,6 Atigua
GetFechasFacturacionConsultora '042923680', '201912',6,6 Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913',6,6 Atigua
*/

---SELECT * FROM ODS.CONSULTORA WHERE NOMBRECOMPLETO LIKE '%ANGEL%' ORDER BY PRIMERNOMBRE DESC




CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
									-- select @CAMPANIASIGUIENTECODIGO
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));
--select @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =
			 CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION),
								   CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
								         /*WHEN CAST(GETDATE() AS DATE) >= CAST(CR.FECHAINICIOFACTURACION AS DATE)
                                         AND CAST(GETDATE() AS DATE)  <= CAST(CR.FECHAFINREFACTURACION AS DATE)
										 THEN ' - HOY' */
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END

							),
             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !=''
									  THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(
									CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR
									ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO
									ON CO.REGIONID = CR.REGIONID
									AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END


GO
USE BelcorpBolivia_MC
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO

/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GetFechasFacturacionConsultora '043843672', '201912',6,6 NUeva
GetFechasFacturacionConsultora '011871852', '201912',6,6 Atigua
GetFechasFacturacionConsultora '042923680', '201912',6,6 Nueva con fechas de facturacion iguales
GetFechasFacturacionConsultora '000145807', '201913',6,6 Atigua
*/

---SELECT * FROM ODS.CONSULTORA WHERE NOMBRECOMPLETO LIKE '%ANGEL%' ORDER BY PRIMERNOMBRE DESC




CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
									-- select @CAMPANIASIGUIENTECODIGO
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO AS VARCHAR(6)));
--select @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)


      /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION =
			 CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION),
								   CASE  WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN ''
								         /*WHEN CAST(GETDATE() AS DATE) >= CAST(CR.FECHAINICIOFACTURACION AS DATE)
                                         AND CAST(GETDATE() AS DATE)  <= CAST(CR.FECHAFINREFACTURACION AS DATE)
										 THEN ' - HOY' */
										ELSE ' - ' + DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAFINREFACTURACION)
								   END

							),
             @FECHALIMITEPAGOFINAL = (CASE WHEN ISNULL(@FECHALIMITEPAGO,'') !=''
									  THEN DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO)
									  ELSE DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHACONFERENCIA) END),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
									CONCAT(dbo.GetFechaCronogramaFacturacion( CR.FECHAINICIOFACTURACION ), '',
									(CASE WHEN CR.FECHAINICIOFACTURACION=CR.FECHAFINREFACTURACION THEN '' ELSE (' - ' + dbo.GetFechaCronogramaFacturacion( CR.FECHAFINREFACTURACION ))end))
									FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHACONFERENCIA)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
									DBO.GETFECHACRONOGRAMAFACTURACION(
									CR.FECHAFINREFACTURACION) FINFACTURACION,
									CA.CODIGO,
									CR.CAMPANIAID
									FROM   ODS.CAMPANIA CA
									INNER JOIN ODS.CRONOGRAMA CR
									ON CR.CAMPANIAID = CA.CAMPANIAID
									INNER JOIN ODS.CONSULTORA CO
									ON CO.REGIONID = CR.REGIONID
									AND CO.ZONAID = CR.ZONAID
									INNER JOIN ODS.PEDIDO OD ON OD.CONSULTORAID=CO.CONSULTORAID AND CA.CAMPANIAID=OD.CAMPANIAID
									WHERE  CO.CODIGO = @CONSULTORA
									AND CA.CODIGO < @CAMPANIAACTUAL
									ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END


GO
