GO
USE BelcorpPeru
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GETFECHASFACTURACIONCONSULTORA '036190809', 201912,6,6

*/
CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
  /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      --SELECT * FROM ODS.CONSULTORA WHERE CODIGO='036190809'
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO
                                                       AS
                                                       VARCHAR(6)));
      --SELECT @ULTIMACAMPANAFACTURADA
      --SELECT @CAMPANIASIGUIENTECODIGO
      --SELECT @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

      --SELECT @FECHALIMITEPAGO
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION = CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION), ' - ', CASE
                            WHEN CAST(GETDATE() AS DATE) >= CAST(
                                 CR.FECHAINICIOFACTURACION AS DATE)
                                 AND CAST(GETDATE() AS DATE) <= CAST(
                                     CR.FECHAFINREFACTURACION AS DATE)
                            THEN 'HOY'
                            ELSE DBO.GETFECHACRONOGRAMAFACTURACION(
                                 CR.FECHAFINREFACTURACION)
                            END),
             @FECHALIMITEPAGOFINAL =
             DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
                                    CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
                                     CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAFINREFACTURACION))FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION
                                     ,
DBO.GETFECHACRONOGRAMAFACTURACION(
CR.FECHAFINREFACTURACION) FINFACTURACION,
CA.CODIGO,
CR.CAMPANIAID
FROM   ODS.CAMPANIA CA
INNER JOIN ODS.CRONOGRAMA CR
ON CR.CAMPANIAID = CA.CAMPANIAID
INNER JOIN ODS.CONSULTORA CO
ON CO.REGIONID = CR.REGIONID
AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA
AND CA.CODIGO < @CAMPANIAACTUAL
ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END

GO
USE BelcorpMexico
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GETFECHASFACTURACIONCONSULTORA '036190809', 201912,6,6

*/
CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
  /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      --SELECT * FROM ODS.CONSULTORA WHERE CODIGO='036190809'
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO
                                                       AS
                                                       VARCHAR(6)));
      --SELECT @ULTIMACAMPANAFACTURADA
      --SELECT @CAMPANIASIGUIENTECODIGO
      --SELECT @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

      --SELECT @FECHALIMITEPAGO
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION = CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION), ' - ', CASE
                            WHEN CAST(GETDATE() AS DATE) >= CAST(
                                 CR.FECHAINICIOFACTURACION AS DATE)
                                 AND CAST(GETDATE() AS DATE) <= CAST(
                                     CR.FECHAFINREFACTURACION AS DATE)
                            THEN 'HOY'
                            ELSE DBO.GETFECHACRONOGRAMAFACTURACION(
                                 CR.FECHAFINREFACTURACION)
                            END),
             @FECHALIMITEPAGOFINAL =
             DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
                                    CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
                                     CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAFINREFACTURACION))FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION
                                     ,
DBO.GETFECHACRONOGRAMAFACTURACION(
CR.FECHAFINREFACTURACION) FINFACTURACION,
CA.CODIGO,
CR.CAMPANIAID
FROM   ODS.CAMPANIA CA
INNER JOIN ODS.CRONOGRAMA CR
ON CR.CAMPANIAID = CA.CAMPANIAID
INNER JOIN ODS.CONSULTORA CO
ON CO.REGIONID = CR.REGIONID
AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA
AND CA.CODIGO < @CAMPANIAACTUAL
ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END

GO
USE BelcorpColombia
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GETFECHASFACTURACIONCONSULTORA '036190809', 201912,6,6

*/
CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
  /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      --SELECT * FROM ODS.CONSULTORA WHERE CODIGO='036190809'
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO
                                                       AS
                                                       VARCHAR(6)));
      --SELECT @ULTIMACAMPANAFACTURADA
      --SELECT @CAMPANIASIGUIENTECODIGO
      --SELECT @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

      --SELECT @FECHALIMITEPAGO
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION = CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION), ' - ', CASE
                            WHEN CAST(GETDATE() AS DATE) >= CAST(
                                 CR.FECHAINICIOFACTURACION AS DATE)
                                 AND CAST(GETDATE() AS DATE) <= CAST(
                                     CR.FECHAFINREFACTURACION AS DATE)
                            THEN 'HOY'
                            ELSE DBO.GETFECHACRONOGRAMAFACTURACION(
                                 CR.FECHAFINREFACTURACION)
                            END),
             @FECHALIMITEPAGOFINAL =
             DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
                                    CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
                                     CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAFINREFACTURACION))FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION
                                     ,
DBO.GETFECHACRONOGRAMAFACTURACION(
CR.FECHAFINREFACTURACION) FINFACTURACION,
CA.CODIGO,
CR.CAMPANIAID
FROM   ODS.CAMPANIA CA
INNER JOIN ODS.CRONOGRAMA CR
ON CR.CAMPANIAID = CA.CAMPANIAID
INNER JOIN ODS.CONSULTORA CO
ON CO.REGIONID = CR.REGIONID
AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA
AND CA.CODIGO < @CAMPANIAACTUAL
ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END

GO
USE BelcorpSalvador
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GETFECHASFACTURACIONCONSULTORA '036190809', 201912,6,6

*/
CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
  /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      --SELECT * FROM ODS.CONSULTORA WHERE CODIGO='036190809'
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO
                                                       AS
                                                       VARCHAR(6)));
      --SELECT @ULTIMACAMPANAFACTURADA
      --SELECT @CAMPANIASIGUIENTECODIGO
      --SELECT @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

      --SELECT @FECHALIMITEPAGO
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION = CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION), ' - ', CASE
                            WHEN CAST(GETDATE() AS DATE) >= CAST(
                                 CR.FECHAINICIOFACTURACION AS DATE)
                                 AND CAST(GETDATE() AS DATE) <= CAST(
                                     CR.FECHAFINREFACTURACION AS DATE)
                            THEN 'HOY'
                            ELSE DBO.GETFECHACRONOGRAMAFACTURACION(
                                 CR.FECHAFINREFACTURACION)
                            END),
             @FECHALIMITEPAGOFINAL =
             DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
                                    CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
                                     CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAFINREFACTURACION))FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION
                                     ,
DBO.GETFECHACRONOGRAMAFACTURACION(
CR.FECHAFINREFACTURACION) FINFACTURACION,
CA.CODIGO,
CR.CAMPANIAID
FROM   ODS.CAMPANIA CA
INNER JOIN ODS.CRONOGRAMA CR
ON CR.CAMPANIAID = CA.CAMPANIAID
INNER JOIN ODS.CONSULTORA CO
ON CO.REGIONID = CR.REGIONID
AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA
AND CA.CODIGO < @CAMPANIAACTUAL
ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END

GO
USE BelcorpPuertoRico
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GETFECHASFACTURACIONCONSULTORA '036190809', 201912,6,6

*/
CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
  /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      --SELECT * FROM ODS.CONSULTORA WHERE CODIGO='036190809'
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO
                                                       AS
                                                       VARCHAR(6)));
      --SELECT @ULTIMACAMPANAFACTURADA
      --SELECT @CAMPANIASIGUIENTECODIGO
      --SELECT @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

      --SELECT @FECHALIMITEPAGO
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION = CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION), ' - ', CASE
                            WHEN CAST(GETDATE() AS DATE) >= CAST(
                                 CR.FECHAINICIOFACTURACION AS DATE)
                                 AND CAST(GETDATE() AS DATE) <= CAST(
                                     CR.FECHAFINREFACTURACION AS DATE)
                            THEN 'HOY'
                            ELSE DBO.GETFECHACRONOGRAMAFACTURACION(
                                 CR.FECHAFINREFACTURACION)
                            END),
             @FECHALIMITEPAGOFINAL =
             DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
                                    CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
                                     CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAFINREFACTURACION))FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION
                                     ,
DBO.GETFECHACRONOGRAMAFACTURACION(
CR.FECHAFINREFACTURACION) FINFACTURACION,
CA.CODIGO,
CR.CAMPANIAID
FROM   ODS.CAMPANIA CA
INNER JOIN ODS.CRONOGRAMA CR
ON CR.CAMPANIAID = CA.CAMPANIAID
INNER JOIN ODS.CONSULTORA CO
ON CO.REGIONID = CR.REGIONID
AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA
AND CA.CODIGO < @CAMPANIAACTUAL
ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END

GO
USE BelcorpPanama
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GETFECHASFACTURACIONCONSULTORA '036190809', 201912,6,6

*/
CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
  /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      --SELECT * FROM ODS.CONSULTORA WHERE CODIGO='036190809'
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO
                                                       AS
                                                       VARCHAR(6)));
      --SELECT @ULTIMACAMPANAFACTURADA
      --SELECT @CAMPANIASIGUIENTECODIGO
      --SELECT @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

      --SELECT @FECHALIMITEPAGO
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION = CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION), ' - ', CASE
                            WHEN CAST(GETDATE() AS DATE) >= CAST(
                                 CR.FECHAINICIOFACTURACION AS DATE)
                                 AND CAST(GETDATE() AS DATE) <= CAST(
                                     CR.FECHAFINREFACTURACION AS DATE)
                            THEN 'HOY'
                            ELSE DBO.GETFECHACRONOGRAMAFACTURACION(
                                 CR.FECHAFINREFACTURACION)
                            END),
             @FECHALIMITEPAGOFINAL =
             DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
                                    CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
                                     CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAFINREFACTURACION))FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION
                                     ,
DBO.GETFECHACRONOGRAMAFACTURACION(
CR.FECHAFINREFACTURACION) FINFACTURACION,
CA.CODIGO,
CR.CAMPANIAID
FROM   ODS.CAMPANIA CA
INNER JOIN ODS.CRONOGRAMA CR
ON CR.CAMPANIAID = CA.CAMPANIAID
INNER JOIN ODS.CONSULTORA CO
ON CO.REGIONID = CR.REGIONID
AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA
AND CA.CODIGO < @CAMPANIAACTUAL
ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END

GO
USE BelcorpGuatemala
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GETFECHASFACTURACIONCONSULTORA '036190809', 201912,6,6

*/
CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
  /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      --SELECT * FROM ODS.CONSULTORA WHERE CODIGO='036190809'
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO
                                                       AS
                                                       VARCHAR(6)));
      --SELECT @ULTIMACAMPANAFACTURADA
      --SELECT @CAMPANIASIGUIENTECODIGO
      --SELECT @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

      --SELECT @FECHALIMITEPAGO
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION = CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION), ' - ', CASE
                            WHEN CAST(GETDATE() AS DATE) >= CAST(
                                 CR.FECHAINICIOFACTURACION AS DATE)
                                 AND CAST(GETDATE() AS DATE) <= CAST(
                                     CR.FECHAFINREFACTURACION AS DATE)
                            THEN 'HOY'
                            ELSE DBO.GETFECHACRONOGRAMAFACTURACION(
                                 CR.FECHAFINREFACTURACION)
                            END),
             @FECHALIMITEPAGOFINAL =
             DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
                                    CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
                                     CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAFINREFACTURACION))FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION
                                     ,
DBO.GETFECHACRONOGRAMAFACTURACION(
CR.FECHAFINREFACTURACION) FINFACTURACION,
CA.CODIGO,
CR.CAMPANIAID
FROM   ODS.CAMPANIA CA
INNER JOIN ODS.CRONOGRAMA CR
ON CR.CAMPANIAID = CA.CAMPANIAID
INNER JOIN ODS.CONSULTORA CO
ON CO.REGIONID = CR.REGIONID
AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA
AND CA.CODIGO < @CAMPANIAACTUAL
ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END

GO
USE BelcorpEcuador
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GETFECHASFACTURACIONCONSULTORA '036190809', 201912,6,6

*/
CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
  /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      --SELECT * FROM ODS.CONSULTORA WHERE CODIGO='036190809'
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO
                                                       AS
                                                       VARCHAR(6)));
      --SELECT @ULTIMACAMPANAFACTURADA
      --SELECT @CAMPANIASIGUIENTECODIGO
      --SELECT @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

      --SELECT @FECHALIMITEPAGO
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION = CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION), ' - ', CASE
                            WHEN CAST(GETDATE() AS DATE) >= CAST(
                                 CR.FECHAINICIOFACTURACION AS DATE)
                                 AND CAST(GETDATE() AS DATE) <= CAST(
                                     CR.FECHAFINREFACTURACION AS DATE)
                            THEN 'HOY'
                            ELSE DBO.GETFECHACRONOGRAMAFACTURACION(
                                 CR.FECHAFINREFACTURACION)
                            END),
             @FECHALIMITEPAGOFINAL =
             DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
                                    CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
                                     CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAFINREFACTURACION))FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION
                                     ,
DBO.GETFECHACRONOGRAMAFACTURACION(
CR.FECHAFINREFACTURACION) FINFACTURACION,
CA.CODIGO,
CR.CAMPANIAID
FROM   ODS.CAMPANIA CA
INNER JOIN ODS.CRONOGRAMA CR
ON CR.CAMPANIAID = CA.CAMPANIAID
INNER JOIN ODS.CONSULTORA CO
ON CO.REGIONID = CR.REGIONID
AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA
AND CA.CODIGO < @CAMPANIAACTUAL
ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END

GO
USE BelcorpDominicana
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GETFECHASFACTURACIONCONSULTORA '036190809', 201912,6,6

*/
CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
  /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      --SELECT * FROM ODS.CONSULTORA WHERE CODIGO='036190809'
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO
                                                       AS
                                                       VARCHAR(6)));
      --SELECT @ULTIMACAMPANAFACTURADA
      --SELECT @CAMPANIASIGUIENTECODIGO
      --SELECT @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

      --SELECT @FECHALIMITEPAGO
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION = CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION), ' - ', CASE
                            WHEN CAST(GETDATE() AS DATE) >= CAST(
                                 CR.FECHAINICIOFACTURACION AS DATE)
                                 AND CAST(GETDATE() AS DATE) <= CAST(
                                     CR.FECHAFINREFACTURACION AS DATE)
                            THEN 'HOY'
                            ELSE DBO.GETFECHACRONOGRAMAFACTURACION(
                                 CR.FECHAFINREFACTURACION)
                            END),
             @FECHALIMITEPAGOFINAL =
             DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
                                    CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
                                     CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAFINREFACTURACION))FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION
                                     ,
DBO.GETFECHACRONOGRAMAFACTURACION(
CR.FECHAFINREFACTURACION) FINFACTURACION,
CA.CODIGO,
CR.CAMPANIAID
FROM   ODS.CAMPANIA CA
INNER JOIN ODS.CRONOGRAMA CR
ON CR.CAMPANIAID = CA.CAMPANIAID
INNER JOIN ODS.CONSULTORA CO
ON CO.REGIONID = CR.REGIONID
AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA
AND CA.CODIGO < @CAMPANIAACTUAL
ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END

GO
USE BelcorpCostaRica
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GETFECHASFACTURACIONCONSULTORA '036190809', 201912,6,6

*/
CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
  /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      --SELECT * FROM ODS.CONSULTORA WHERE CODIGO='036190809'
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO
                                                       AS
                                                       VARCHAR(6)));
      --SELECT @ULTIMACAMPANAFACTURADA
      --SELECT @CAMPANIASIGUIENTECODIGO
      --SELECT @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

      --SELECT @FECHALIMITEPAGO
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION = CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION), ' - ', CASE
                            WHEN CAST(GETDATE() AS DATE) >= CAST(
                                 CR.FECHAINICIOFACTURACION AS DATE)
                                 AND CAST(GETDATE() AS DATE) <= CAST(
                                     CR.FECHAFINREFACTURACION AS DATE)
                            THEN 'HOY'
                            ELSE DBO.GETFECHACRONOGRAMAFACTURACION(
                                 CR.FECHAFINREFACTURACION)
                            END),
             @FECHALIMITEPAGOFINAL =
             DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
                                    CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
                                     CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAFINREFACTURACION))FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION
                                     ,
DBO.GETFECHACRONOGRAMAFACTURACION(
CR.FECHAFINREFACTURACION) FINFACTURACION,
CA.CODIGO,
CR.CAMPANIAID
FROM   ODS.CAMPANIA CA
INNER JOIN ODS.CRONOGRAMA CR
ON CR.CAMPANIAID = CA.CAMPANIAID
INNER JOIN ODS.CONSULTORA CO
ON CO.REGIONID = CR.REGIONID
AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA
AND CA.CODIGO < @CAMPANIAACTUAL
ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END

GO
USE BelcorpChile
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GETFECHASFACTURACIONCONSULTORA '036190809', 201912,6,6

*/
CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
  /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      --SELECT * FROM ODS.CONSULTORA WHERE CODIGO='036190809'
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO
                                                       AS
                                                       VARCHAR(6)));
      --SELECT @ULTIMACAMPANAFACTURADA
      --SELECT @CAMPANIASIGUIENTECODIGO
      --SELECT @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

      --SELECT @FECHALIMITEPAGO
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION = CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION), ' - ', CASE
                            WHEN CAST(GETDATE() AS DATE) >= CAST(
                                 CR.FECHAINICIOFACTURACION AS DATE)
                                 AND CAST(GETDATE() AS DATE) <= CAST(
                                     CR.FECHAFINREFACTURACION AS DATE)
                            THEN 'HOY'
                            ELSE DBO.GETFECHACRONOGRAMAFACTURACION(
                                 CR.FECHAFINREFACTURACION)
                            END),
             @FECHALIMITEPAGOFINAL =
             DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
                                    CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
                                     CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAFINREFACTURACION))FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION
                                     ,
DBO.GETFECHACRONOGRAMAFACTURACION(
CR.FECHAFINREFACTURACION) FINFACTURACION,
CA.CODIGO,
CR.CAMPANIAID
FROM   ODS.CAMPANIA CA
INNER JOIN ODS.CRONOGRAMA CR
ON CR.CAMPANIAID = CA.CAMPANIAID
INNER JOIN ODS.CONSULTORA CO
ON CO.REGIONID = CR.REGIONID
AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA
AND CA.CODIGO < @CAMPANIAACTUAL
ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END

GO
USE BelcorpBolivia
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GETFECHASFACTURACIONCONSULTORA]')
		   AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[GETFECHASFACTURACIONCONSULTORA]
GO


/*
CREADO POR : PAQUIRRI SEPERAK
FECHA : 22/07/2019
GETFECHASFACTURACIONCONSULTORA '036190809', 201912,6,6

*/
CREATE PROCEDURE [DBO].[GETFECHASFACTURACIONCONSULTORA]
@CONSULTORA       VARCHAR (16),
@CAMPANIAACTUAL   INT,
@CANTIDADANTERIOR INT,
@CANTIDADPROXIMA  INT
AS
  BEGIN
  /*OBTENEMOS LA CAMPAÑA ACTUAL*/
      --SELECT * FROM ODS.CONSULTORA WHERE CODIGO='036190809'
      SET LANGUAGE ESPAÑOL;

      DECLARE @FECHALIMITEPAGO SMALLDATETIME
      DECLARE @FECHALIMITEPAGOFINAL VARCHAR(64)
      DECLARE @FECHAINICIOFACTURACION VARCHAR(64)
      DECLARE @FECHAFINFACTURACION VARCHAR(64)
      DECLARE @ZONAID INT
      DECLARE @REGIONID INT
      DECLARE @ULTIMACAMPANAFACTURADA INT
      DECLARE @TIPOFACTURACION CHAR(2)
      DECLARE @CONSULTORAID BIGINT
      DECLARE @CAMPANIASIGUIENTECODIGO INT
      DECLARE @CAMPANIASIGUIENTEID INT
      DECLARE @FACTURACION VARCHAR(64)
      DECLARE @CAMPANIAPARTIDA VARCHAR(8)

      SELECT @ZONAID = ISNULL(ZONAID, 0),
             @REGIONID = ISNULL(REGIONID, 0),
             @CONSULTORAID = ISNULL(CONSULTORAID, 0),
             @ULTIMACAMPANAFACTURADA = ISNULL(ULTIMACAMPANAFACTURADA, 0),
             @TIPOFACTURACION = ISNULL(TIPOFACTURACION, 'FA')
      FROM   ODS.CONSULTORA WITH(NOLOCK)
      WHERE  CODIGO = @CONSULTORA;

      /* SE TOMA EN CUENTA LA FECHA DE VENCIMIENTO SOBRE LA ULTIMA CAMPAÑA FACTURADA */
      SET @CAMPANIASIGUIENTECODIGO = IIF(@TIPOFACTURACION = 'FA',
      DBO.FNADDCAMPANIAANDNUMERO(NULL, @ULTIMACAMPANAFACTURADA, 1),
                                     @ULTIMACAMPANAFACTURADA);
      SET @CAMPANIASIGUIENTEID = (SELECT TOP 1 CAMPANIAID
                                  FROM   ODS.CAMPANIA
                                  WHERE  CODIGO = CAST(@CAMPANIASIGUIENTECODIGO
                                                       AS
                                                       VARCHAR(6)));
      --SELECT @ULTIMACAMPANAFACTURADA
      --SELECT @CAMPANIASIGUIENTECODIGO
      --SELECT @CAMPANIASIGUIENTEID
      SET @FECHALIMITEPAGO = (SELECT FECHACONFERENCIA
                              FROM   ODS.CRONOGRAMA
                              WHERE  CAMPANIAID = @CAMPANIASIGUIENTEID
                                     AND REGIONID = @REGIONID
                                     AND ZONAID = @ZONAID
                                     AND ESTADOACTIVO = 1)

      --SELECT @FECHALIMITEPAGO
      SELECT @CAMPANIAPARTIDA = CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2)),
             @FACTURACION = CONCAT(DBO.GETFECHACRONOGRAMAFACTURACION(
                                   CR.FECHAINICIOFACTURACION), ' - ', CASE
                            WHEN CAST(GETDATE() AS DATE) >= CAST(
                                 CR.FECHAINICIOFACTURACION AS DATE)
                                 AND CAST(GETDATE() AS DATE) <= CAST(
                                     CR.FECHAFINREFACTURACION AS DATE)
                            THEN 'HOY'
                            ELSE DBO.GETFECHACRONOGRAMAFACTURACION(
                                 CR.FECHAFINREFACTURACION)
                            END),
             @FECHALIMITEPAGOFINAL =
             DBO.GETFECHACRONOGRAMAFACTURACION(@FECHALIMITEPAGO),
             @FECHAINICIOFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                       CR.FECHAINICIOFACTURACION),
             @FECHAFINFACTURACION = DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION)
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO = @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO DESC

      SELECT @CAMPANIAPARTIDA        CAMPANIAPARTIDA,
             @FACTURACION            FACTURACION,
             @FECHALIMITEPAGOFINAL   FECHALIMITEPAGO,
             @FECHAINICIOFACTURACION INICIOFACTURACION,
             @FECHAFINFACTURACION    FINFACTURACION

      /*CAMPAÑAS MAYORES */
      SELECT TOP (@CANTIDADPROXIMA) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                    CAMPANIAPARTIDA,
                                    CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION))FACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAINICIOFACTURACION)INICIOFACTURACION,
                                    DBO.GETFECHACRONOGRAMAFACTURACION(
                                    CR.FECHAFINREFACTURACION) FINFACTURACION,
                                    CA.CODIGO,
                                    CR.CAMPANIAID
      FROM   ODS.CAMPANIA CA
             INNER JOIN ODS.CRONOGRAMA CR
                     ON CR.CAMPANIAID = CA.CAMPANIAID
             INNER JOIN ODS.CONSULTORA CO
                     ON CO.REGIONID = CR.REGIONID
                        AND CO.ZONAID = CR.ZONAID
      WHERE  CO.CODIGO = @CONSULTORA
             AND CA.CODIGO > @CAMPANIAACTUAL
      ORDER  BY CA.CODIGO

      /*CAMPAÑAS MENORES*/
      SELECT TOP (@CANTIDADANTERIOR) CONCAT('C-', SUBSTRING(CA.CODIGO, 5, 2))
                                     CAMPANIAPARTIDA,
                                     CONCAT(
      DBO.GETFECHACRONOGRAMAFACTURACION(CR.FECHAINICIOFACTURACION), ' - ',
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAFINREFACTURACION))FACTURACION,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHALIMITEPAGO)       FECHALIMITEPAGO,
                                     DBO.GETFECHACRONOGRAMAFACTURACION(
                                     CR.FECHAINICIOFACTURACION)INICIOFACTURACION
                                     ,
DBO.GETFECHACRONOGRAMAFACTURACION(
CR.FECHAFINREFACTURACION) FINFACTURACION,
CA.CODIGO,
CR.CAMPANIAID
FROM   ODS.CAMPANIA CA
INNER JOIN ODS.CRONOGRAMA CR
ON CR.CAMPANIAID = CA.CAMPANIAID
INNER JOIN ODS.CONSULTORA CO
ON CO.REGIONID = CR.REGIONID
AND CO.ZONAID = CR.ZONAID
WHERE  CO.CODIGO = @CONSULTORA
AND CA.CODIGO < @CAMPANIAACTUAL
ORDER  BY CA.CODIGO DESC

SET LANGUAGE US_ENGLISH;
END

GO
