USE BelcorpPeru
GO

/*    
CREADO POR  : PAQUIRRI SEPERAK    
FECHA : 20190520  
DESCRIPCIÓN : SE AGREGARON 2 CAMPOS MÁS ARCHIVOMOBILE,URLMOBILE, ESTOS CAMPOS SERÁN USADOS POR EL APP SOLAMENTE 
Getbannerbycampania  201907
*/ 
ALTER PROC [dbo].[Getbannerbycampania] 
@CAMPANIAID INT 
AS 
    SELECT BAN.CAMPANIAID, 
           BAN.BANNERID, 
           BAN.GRUPOBANNERID, 
           BAN.ORDEN, 
           BAN.TITULO, 
           BAN.ARCHIVO, 
           REPLACE(BAN.URL, '*', '&')                         URL, 
           BAN.FLAGGRUPOCONSULTORA, 
           BAN.FLAGCONSULTORANUEVA, 
           ISNULL(GBAN.TIEMPOROTACION, 0)                     TIEMPOROTACION, 
           ISNULL(BAN.TIPOCONTENIDO, 0)                       TIPOCONTENIDO, 
           ISNULL(BAN.TIPOACCION, 0)                          TIPOACCION, 
           ISNULL(BAN.PAGINANUEVA, 1)                         PAGINANUEVA, 
           ISNULL(BAN.TITULOCOMENTARIO, '')                   TITULOCOMENTARIO, 
           ISNULL(BAN.TEXTOCOMENTARIO, '')                    TEXTOCOMENTARIO, 
           ISNULL(BAN.CUVPEDIDO, '')                          CUVPEDIDO, 
           ISNULL(BAN.CANTCUVPEDIDO, '')                      CANTCUVPEDIDO, 
           (SELECT NOMBRE 
            FROM   GRUPOBANNERBASE GBBASE 
            WHERE  GBBASE.GRUPOBANNERID = GBAN.GRUPOBANNERID) NOMBRE, 
           BAN.ARCHIVOMOBILE, 
           BAN.URLMOBILE 
    FROM   DBO.BANNER BAN WITH(NOLOCK) 
           LEFT JOIN GRUPOBANNER GBAN WITH(NOLOCK) 
                  ON BAN.CAMPANIAID = GBAN.CAMPANIAID 
                     AND BAN.GRUPOBANNERID = GBAN.GRUPOBANNERID 
    WHERE  BAN.CAMPANIAID = @CAMPANIAID 
    ORDER  BY BAN.BANNERID 

    SELECT BP.BANNERID, 
           BP.PAISID, 
           ISNULL(SEGMENTO, -1)          AS SEGMENTO, 
           ISNULL(CONFIGURACIONZONA, '') AS CONFIGURACIONZONA 
    FROM   DBO.BANNERPAIS BP WITH(NOLOCK) 
           LEFT JOIN DBO.BANNERPAISSEGMENTOZONA BPSZ WITH(NOLOCK) 
                  ON BP.CAMPANIAID = BPSZ.CAMPANIAID 
                     AND BP.BANNERID = BPSZ.BANNERID 
                     AND BP.PAISID = BPSZ.PAISID 
    WHERE  BP.CAMPANIAID = @CAMPANIAID 
    ORDER  BY BP.BANNERID, 
              BP.PAISID 
GO