//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Portal.Consultoras.Web.ServicePROLConsultas {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsConsultaSoap", Namespace="http://tempuri.org/")]
    public partial class wsConsulta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarCargaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaJobProlOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaJobStockProlOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaArchivoStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback FechasPaisOperationCompleted;
        
        private System.Threading.SendOrPostCallback FechasPaisJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback HorasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerUnidadesReservadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaLogErrorEtlOperationCompleted;
        
        private System.Threading.SendOrPostCallback EjecutarJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback DetenerJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback AnalizadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback EjecutarSqlOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaOfertaProlOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReporteStockxZonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback FileDetalleExplotadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubirFtpOperationCompleted;
        
        private System.Threading.SendOrPostCallback WsDisponibilidadProlOperationCompleted;
        
        private System.Threading.SendOrPostCallback WsIStockFicticioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaProlSapOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsConsulta() {
            this.Url = global::Portal.Consultoras.Web.Properties.Settings.Default.Portal_Consultoras_Web_ServicePROLConsultas_wsConsulta;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaStockCompletedEventHandler ConsultaStockCompleted;
        
        /// <remarks/>
        public event ConsultarCargaCompletedEventHandler ConsultarCargaCompleted;
        
        /// <remarks/>
        public event ConsultaJobProlCompletedEventHandler ConsultaJobProlCompleted;
        
        /// <remarks/>
        public event ConsultaJobStockProlCompletedEventHandler ConsultaJobStockProlCompleted;
        
        /// <remarks/>
        public event ConsultaArchivoStockCompletedEventHandler ConsultaArchivoStockCompleted;
        
        /// <remarks/>
        public event FechasPaisCompletedEventHandler FechasPaisCompleted;
        
        /// <remarks/>
        public event FechasPaisJobCompletedEventHandler FechasPaisJobCompleted;
        
        /// <remarks/>
        public event HorasCompletedEventHandler HorasCompleted;
        
        /// <remarks/>
        public event ObtenerUnidadesReservadasCompletedEventHandler ObtenerUnidadesReservadasCompleted;
        
        /// <remarks/>
        public event ConsultaLogErrorEtlCompletedEventHandler ConsultaLogErrorEtlCompleted;
        
        /// <remarks/>
        public event EjecutarJobCompletedEventHandler EjecutarJobCompleted;
        
        /// <remarks/>
        public event DetenerJobCompletedEventHandler DetenerJobCompleted;
        
        /// <remarks/>
        public event AnalizadorCompletedEventHandler AnalizadorCompleted;
        
        /// <remarks/>
        public event EjecutarSqlCompletedEventHandler EjecutarSqlCompleted;
        
        /// <remarks/>
        public event ListaOfertaProlCompletedEventHandler ListaOfertaProlCompleted;
        
        /// <remarks/>
        public event ReporteStockxZonaCompletedEventHandler ReporteStockxZonaCompleted;
        
        /// <remarks/>
        public event FileDetalleExplotadoCompletedEventHandler FileDetalleExplotadoCompleted;
        
        /// <remarks/>
        public event SubirFtpCompletedEventHandler SubirFtpCompleted;
        
        /// <remarks/>
        public event WsDisponibilidadProlCompletedEventHandler WsDisponibilidadProlCompleted;
        
        /// <remarks/>
        public event WsIStockFicticioCompletedEventHandler WsIStockFicticioCompleted;
        
        /// <remarks/>
        public event ConsultaProlSapCompletedEventHandler ConsultaProlSapCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Lista[] ConsultaStock(string codsap, string pais) {
            object[] results = this.Invoke("ConsultaStock", new object[] {
                        codsap,
                        pais});
            return ((Lista[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaStockAsync(string codsap, string pais) {
            this.ConsultaStockAsync(codsap, pais, null);
        }
        
        /// <remarks/>
        public void ConsultaStockAsync(string codsap, string pais, object userState) {
            if ((this.ConsultaStockOperationCompleted == null)) {
                this.ConsultaStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaStockOperationCompleted);
            }
            this.InvokeAsync("ConsultaStock", new object[] {
                        codsap,
                        pais}, this.ConsultaStockOperationCompleted, userState);
        }
        
        private void OnConsultaStockOperationCompleted(object arg) {
            if ((this.ConsultaStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaStockCompleted(this, new ConsultaStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarCarga", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ControlCarga[] ConsultarCarga(string pais) {
            object[] results = this.Invoke("ConsultarCarga", new object[] {
                        pais});
            return ((ControlCarga[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCargaAsync(string pais) {
            this.ConsultarCargaAsync(pais, null);
        }
        
        /// <remarks/>
        public void ConsultarCargaAsync(string pais, object userState) {
            if ((this.ConsultarCargaOperationCompleted == null)) {
                this.ConsultarCargaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCargaOperationCompleted);
            }
            this.InvokeAsync("ConsultarCarga", new object[] {
                        pais}, this.ConsultarCargaOperationCompleted, userState);
        }
        
        private void OnConsultarCargaOperationCompleted(object arg) {
            if ((this.ConsultarCargaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCargaCompleted(this, new ConsultarCargaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaJobProl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LogCarga[] ConsultaJobProl(string pais, string fecha) {
            object[] results = this.Invoke("ConsultaJobProl", new object[] {
                        pais,
                        fecha});
            return ((LogCarga[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaJobProlAsync(string pais, string fecha) {
            this.ConsultaJobProlAsync(pais, fecha, null);
        }
        
        /// <remarks/>
        public void ConsultaJobProlAsync(string pais, string fecha, object userState) {
            if ((this.ConsultaJobProlOperationCompleted == null)) {
                this.ConsultaJobProlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaJobProlOperationCompleted);
            }
            this.InvokeAsync("ConsultaJobProl", new object[] {
                        pais,
                        fecha}, this.ConsultaJobProlOperationCompleted, userState);
        }
        
        private void OnConsultaJobProlOperationCompleted(object arg) {
            if ((this.ConsultaJobProlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaJobProlCompleted(this, new ConsultaJobProlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaJobStockProl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LogCarga[] ConsultaJobStockProl(string pais, string fecha) {
            object[] results = this.Invoke("ConsultaJobStockProl", new object[] {
                        pais,
                        fecha});
            return ((LogCarga[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaJobStockProlAsync(string pais, string fecha) {
            this.ConsultaJobStockProlAsync(pais, fecha, null);
        }
        
        /// <remarks/>
        public void ConsultaJobStockProlAsync(string pais, string fecha, object userState) {
            if ((this.ConsultaJobStockProlOperationCompleted == null)) {
                this.ConsultaJobStockProlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaJobStockProlOperationCompleted);
            }
            this.InvokeAsync("ConsultaJobStockProl", new object[] {
                        pais,
                        fecha}, this.ConsultaJobStockProlOperationCompleted, userState);
        }
        
        private void OnConsultaJobStockProlOperationCompleted(object arg) {
            if ((this.ConsultaJobStockProlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaJobStockProlCompleted(this, new ConsultaJobStockProlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaArchivoStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ArchivoStock[] ConsultaArchivoStock(string pais, string fecha, string hora) {
            object[] results = this.Invoke("ConsultaArchivoStock", new object[] {
                        pais,
                        fecha,
                        hora});
            return ((ArchivoStock[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaArchivoStockAsync(string pais, string fecha, string hora) {
            this.ConsultaArchivoStockAsync(pais, fecha, hora, null);
        }
        
        /// <remarks/>
        public void ConsultaArchivoStockAsync(string pais, string fecha, string hora, object userState) {
            if ((this.ConsultaArchivoStockOperationCompleted == null)) {
                this.ConsultaArchivoStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaArchivoStockOperationCompleted);
            }
            this.InvokeAsync("ConsultaArchivoStock", new object[] {
                        pais,
                        fecha,
                        hora}, this.ConsultaArchivoStockOperationCompleted, userState);
        }
        
        private void OnConsultaArchivoStockOperationCompleted(object arg) {
            if ((this.ConsultaArchivoStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaArchivoStockCompleted(this, new ConsultaArchivoStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FechasPais", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] FechasPais(string pais) {
            object[] results = this.Invoke("FechasPais", new object[] {
                        pais});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void FechasPaisAsync(string pais) {
            this.FechasPaisAsync(pais, null);
        }
        
        /// <remarks/>
        public void FechasPaisAsync(string pais, object userState) {
            if ((this.FechasPaisOperationCompleted == null)) {
                this.FechasPaisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFechasPaisOperationCompleted);
            }
            this.InvokeAsync("FechasPais", new object[] {
                        pais}, this.FechasPaisOperationCompleted, userState);
        }
        
        private void OnFechasPaisOperationCompleted(object arg) {
            if ((this.FechasPaisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FechasPaisCompleted(this, new FechasPaisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FechasPaisJob", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] FechasPaisJob(string pais) {
            object[] results = this.Invoke("FechasPaisJob", new object[] {
                        pais});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void FechasPaisJobAsync(string pais) {
            this.FechasPaisJobAsync(pais, null);
        }
        
        /// <remarks/>
        public void FechasPaisJobAsync(string pais, object userState) {
            if ((this.FechasPaisJobOperationCompleted == null)) {
                this.FechasPaisJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFechasPaisJobOperationCompleted);
            }
            this.InvokeAsync("FechasPaisJob", new object[] {
                        pais}, this.FechasPaisJobOperationCompleted, userState);
        }
        
        private void OnFechasPaisJobOperationCompleted(object arg) {
            if ((this.FechasPaisJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FechasPaisJobCompleted(this, new FechasPaisJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Horas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Horas(string pais, string fecha) {
            object[] results = this.Invoke("Horas", new object[] {
                        pais,
                        fecha});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void HorasAsync(string pais, string fecha) {
            this.HorasAsync(pais, fecha, null);
        }
        
        /// <remarks/>
        public void HorasAsync(string pais, string fecha, object userState) {
            if ((this.HorasOperationCompleted == null)) {
                this.HorasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHorasOperationCompleted);
            }
            this.InvokeAsync("Horas", new object[] {
                        pais,
                        fecha}, this.HorasOperationCompleted, userState);
        }
        
        private void OnHorasOperationCompleted(object arg) {
            if ((this.HorasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HorasCompleted(this, new HorasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerUnidadesReservadas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StockReservado[] ObtenerUnidadesReservadas(string pais, string codsap) {
            object[] results = this.Invoke("ObtenerUnidadesReservadas", new object[] {
                        pais,
                        codsap});
            return ((StockReservado[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerUnidadesReservadasAsync(string pais, string codsap) {
            this.ObtenerUnidadesReservadasAsync(pais, codsap, null);
        }
        
        /// <remarks/>
        public void ObtenerUnidadesReservadasAsync(string pais, string codsap, object userState) {
            if ((this.ObtenerUnidadesReservadasOperationCompleted == null)) {
                this.ObtenerUnidadesReservadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerUnidadesReservadasOperationCompleted);
            }
            this.InvokeAsync("ObtenerUnidadesReservadas", new object[] {
                        pais,
                        codsap}, this.ObtenerUnidadesReservadasOperationCompleted, userState);
        }
        
        private void OnObtenerUnidadesReservadasOperationCompleted(object arg) {
            if ((this.ObtenerUnidadesReservadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerUnidadesReservadasCompleted(this, new ObtenerUnidadesReservadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaLogErrorEtl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LogError[] ConsultaLogErrorEtl(string pais, string fecha) {
            object[] results = this.Invoke("ConsultaLogErrorEtl", new object[] {
                        pais,
                        fecha});
            return ((LogError[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaLogErrorEtlAsync(string pais, string fecha) {
            this.ConsultaLogErrorEtlAsync(pais, fecha, null);
        }
        
        /// <remarks/>
        public void ConsultaLogErrorEtlAsync(string pais, string fecha, object userState) {
            if ((this.ConsultaLogErrorEtlOperationCompleted == null)) {
                this.ConsultaLogErrorEtlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaLogErrorEtlOperationCompleted);
            }
            this.InvokeAsync("ConsultaLogErrorEtl", new object[] {
                        pais,
                        fecha}, this.ConsultaLogErrorEtlOperationCompleted, userState);
        }
        
        private void OnConsultaLogErrorEtlOperationCompleted(object arg) {
            if ((this.ConsultaLogErrorEtlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaLogErrorEtlCompleted(this, new ConsultaLogErrorEtlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EjecutarJob", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EjecutarJob(string pais, string packagename) {
            object[] results = this.Invoke("EjecutarJob", new object[] {
                        pais,
                        packagename});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EjecutarJobAsync(string pais, string packagename) {
            this.EjecutarJobAsync(pais, packagename, null);
        }
        
        /// <remarks/>
        public void EjecutarJobAsync(string pais, string packagename, object userState) {
            if ((this.EjecutarJobOperationCompleted == null)) {
                this.EjecutarJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEjecutarJobOperationCompleted);
            }
            this.InvokeAsync("EjecutarJob", new object[] {
                        pais,
                        packagename}, this.EjecutarJobOperationCompleted, userState);
        }
        
        private void OnEjecutarJobOperationCompleted(object arg) {
            if ((this.EjecutarJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EjecutarJobCompleted(this, new EjecutarJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DetenerJob", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DetenerJob(string pais, string packagename) {
            object[] results = this.Invoke("DetenerJob", new object[] {
                        pais,
                        packagename});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DetenerJobAsync(string pais, string packagename) {
            this.DetenerJobAsync(pais, packagename, null);
        }
        
        /// <remarks/>
        public void DetenerJobAsync(string pais, string packagename, object userState) {
            if ((this.DetenerJobOperationCompleted == null)) {
                this.DetenerJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDetenerJobOperationCompleted);
            }
            this.InvokeAsync("DetenerJob", new object[] {
                        pais,
                        packagename}, this.DetenerJobOperationCompleted, userState);
        }
        
        private void OnDetenerJobOperationCompleted(object arg) {
            if ((this.DetenerJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DetenerJobCompleted(this, new DetenerJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Analizador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Analizador(string pais, string sql) {
            object[] results = this.Invoke("Analizador", new object[] {
                        pais,
                        sql});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AnalizadorAsync(string pais, string sql) {
            this.AnalizadorAsync(pais, sql, null);
        }
        
        /// <remarks/>
        public void AnalizadorAsync(string pais, string sql, object userState) {
            if ((this.AnalizadorOperationCompleted == null)) {
                this.AnalizadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAnalizadorOperationCompleted);
            }
            this.InvokeAsync("Analizador", new object[] {
                        pais,
                        sql}, this.AnalizadorOperationCompleted, userState);
        }
        
        private void OnAnalizadorOperationCompleted(object arg) {
            if ((this.AnalizadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AnalizadorCompleted(this, new AnalizadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EjecutarSql", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EjecutarSql(string pais, string sql) {
            object[] results = this.Invoke("EjecutarSql", new object[] {
                        pais,
                        sql});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EjecutarSqlAsync(string pais, string sql) {
            this.EjecutarSqlAsync(pais, sql, null);
        }
        
        /// <remarks/>
        public void EjecutarSqlAsync(string pais, string sql, object userState) {
            if ((this.EjecutarSqlOperationCompleted == null)) {
                this.EjecutarSqlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEjecutarSqlOperationCompleted);
            }
            this.InvokeAsync("EjecutarSql", new object[] {
                        pais,
                        sql}, this.EjecutarSqlOperationCompleted, userState);
        }
        
        private void OnEjecutarSqlOperationCompleted(object arg) {
            if ((this.EjecutarSqlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EjecutarSqlCompleted(this, new EjecutarSqlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListaOfertaProl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OfertaProl[] ListaOfertaProl(string pais, string periodo, string codproducto) {
            object[] results = this.Invoke("ListaOfertaProl", new object[] {
                        pais,
                        periodo,
                        codproducto});
            return ((OfertaProl[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaOfertaProlAsync(string pais, string periodo, string codproducto) {
            this.ListaOfertaProlAsync(pais, periodo, codproducto, null);
        }
        
        /// <remarks/>
        public void ListaOfertaProlAsync(string pais, string periodo, string codproducto, object userState) {
            if ((this.ListaOfertaProlOperationCompleted == null)) {
                this.ListaOfertaProlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaOfertaProlOperationCompleted);
            }
            this.InvokeAsync("ListaOfertaProl", new object[] {
                        pais,
                        periodo,
                        codproducto}, this.ListaOfertaProlOperationCompleted, userState);
        }
        
        private void OnListaOfertaProlOperationCompleted(object arg) {
            if ((this.ListaOfertaProlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaOfertaProlCompleted(this, new ListaOfertaProlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReporteStockxZona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReportStockxZona[] ReporteStockxZona(string pais, string periodo, string region) {
            object[] results = this.Invoke("ReporteStockxZona", new object[] {
                        pais,
                        periodo,
                        region});
            return ((ReportStockxZona[])(results[0]));
        }
        
        /// <remarks/>
        public void ReporteStockxZonaAsync(string pais, string periodo, string region) {
            this.ReporteStockxZonaAsync(pais, periodo, region, null);
        }
        
        /// <remarks/>
        public void ReporteStockxZonaAsync(string pais, string periodo, string region, object userState) {
            if ((this.ReporteStockxZonaOperationCompleted == null)) {
                this.ReporteStockxZonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReporteStockxZonaOperationCompleted);
            }
            this.InvokeAsync("ReporteStockxZona", new object[] {
                        pais,
                        periodo,
                        region}, this.ReporteStockxZonaOperationCompleted, userState);
        }
        
        private void OnReporteStockxZonaOperationCompleted(object arg) {
            if ((this.ReporteStockxZonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReporteStockxZonaCompleted(this, new ReporteStockxZonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FileDetalleExplotado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DetallePedido[] FileDetalleExplotado(string rutacabecera, string rutadetalle, string pais) {
            object[] results = this.Invoke("FileDetalleExplotado", new object[] {
                        rutacabecera,
                        rutadetalle,
                        pais});
            return ((DetallePedido[])(results[0]));
        }
        
        /// <remarks/>
        public void FileDetalleExplotadoAsync(string rutacabecera, string rutadetalle, string pais) {
            this.FileDetalleExplotadoAsync(rutacabecera, rutadetalle, pais, null);
        }
        
        /// <remarks/>
        public void FileDetalleExplotadoAsync(string rutacabecera, string rutadetalle, string pais, object userState) {
            if ((this.FileDetalleExplotadoOperationCompleted == null)) {
                this.FileDetalleExplotadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFileDetalleExplotadoOperationCompleted);
            }
            this.InvokeAsync("FileDetalleExplotado", new object[] {
                        rutacabecera,
                        rutadetalle,
                        pais}, this.FileDetalleExplotadoOperationCompleted, userState);
        }
        
        private void OnFileDetalleExplotadoOperationCompleted(object arg) {
            if ((this.FileDetalleExplotadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FileDetalleExplotadoCompleted(this, new FileDetalleExplotadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubirFtp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SubirFtp(string servidor, string rutaorigen, string rutadestino, string usuario, string password) {
            this.Invoke("SubirFtp", new object[] {
                        servidor,
                        rutaorigen,
                        rutadestino,
                        usuario,
                        password});
        }
        
        /// <remarks/>
        public void SubirFtpAsync(string servidor, string rutaorigen, string rutadestino, string usuario, string password) {
            this.SubirFtpAsync(servidor, rutaorigen, rutadestino, usuario, password, null);
        }
        
        /// <remarks/>
        public void SubirFtpAsync(string servidor, string rutaorigen, string rutadestino, string usuario, string password, object userState) {
            if ((this.SubirFtpOperationCompleted == null)) {
                this.SubirFtpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubirFtpOperationCompleted);
            }
            this.InvokeAsync("SubirFtp", new object[] {
                        servidor,
                        rutaorigen,
                        rutadestino,
                        usuario,
                        password}, this.SubirFtpOperationCompleted, userState);
        }
        
        private void OnSubirFtpOperationCompleted(object arg) {
            if ((this.SubirFtpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubirFtpCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WsDisponibilidadProl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DispoProl[] WsDisponibilidadProl(string Pais, string ejecucion) {
            object[] results = this.Invoke("WsDisponibilidadProl", new object[] {
                        Pais,
                        ejecucion});
            return ((DispoProl[])(results[0]));
        }
        
        /// <remarks/>
        public void WsDisponibilidadProlAsync(string Pais, string ejecucion) {
            this.WsDisponibilidadProlAsync(Pais, ejecucion, null);
        }
        
        /// <remarks/>
        public void WsDisponibilidadProlAsync(string Pais, string ejecucion, object userState) {
            if ((this.WsDisponibilidadProlOperationCompleted == null)) {
                this.WsDisponibilidadProlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsDisponibilidadProlOperationCompleted);
            }
            this.InvokeAsync("WsDisponibilidadProl", new object[] {
                        Pais,
                        ejecucion}, this.WsDisponibilidadProlOperationCompleted, userState);
        }
        
        private void OnWsDisponibilidadProlOperationCompleted(object arg) {
            if ((this.WsDisponibilidadProlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsDisponibilidadProlCompleted(this, new WsDisponibilidadProlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WsIStockFicticio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RptStock[] WsIStockFicticio(string pais, string codperiodo, string codsap, int cantidad, string tipostock) {
            object[] results = this.Invoke("WsIStockFicticio", new object[] {
                        pais,
                        codperiodo,
                        codsap,
                        cantidad,
                        tipostock});
            return ((RptStock[])(results[0]));
        }
        
        /// <remarks/>
        public void WsIStockFicticioAsync(string pais, string codperiodo, string codsap, int cantidad, string tipostock) {
            this.WsIStockFicticioAsync(pais, codperiodo, codsap, cantidad, tipostock, null);
        }
        
        /// <remarks/>
        public void WsIStockFicticioAsync(string pais, string codperiodo, string codsap, int cantidad, string tipostock, object userState) {
            if ((this.WsIStockFicticioOperationCompleted == null)) {
                this.WsIStockFicticioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWsIStockFicticioOperationCompleted);
            }
            this.InvokeAsync("WsIStockFicticio", new object[] {
                        pais,
                        codperiodo,
                        codsap,
                        cantidad,
                        tipostock}, this.WsIStockFicticioOperationCompleted, userState);
        }
        
        private void OnWsIStockFicticioOperationCompleted(object arg) {
            if ((this.WsIStockFicticioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WsIStockFicticioCompleted(this, new WsIStockFicticioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaProlSap", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Respuesta ConsultaProlSap(string pais, string fecha) {
            object[] results = this.Invoke("ConsultaProlSap", new object[] {
                        pais,
                        fecha});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaProlSapAsync(string pais, string fecha) {
            this.ConsultaProlSapAsync(pais, fecha, null);
        }
        
        /// <remarks/>
        public void ConsultaProlSapAsync(string pais, string fecha, object userState) {
            if ((this.ConsultaProlSapOperationCompleted == null)) {
                this.ConsultaProlSapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaProlSapOperationCompleted);
            }
            this.InvokeAsync("ConsultaProlSap", new object[] {
                        pais,
                        fecha}, this.ConsultaProlSapOperationCompleted, userState);
        }
        
        private void OnConsultaProlSapOperationCompleted(object arg) {
            if ((this.ConsultaProlSapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaProlSapCompleted(this, new ConsultaProlSapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Lista {
        
        private int codsapField;
        
        private int estadoField;
        
        /// <remarks/>
        public int Codsap {
            get {
                return this.codsapField;
            }
            set {
                this.codsapField = value;
            }
        }
        
        /// <remarks/>
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Respuesta {
        
        private string tipoField;
        
        private string descripcionField;
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RptStock {
        
        private string codperiodoField;
        
        private string codsapField;
        
        private string cantidadField;
        
        private string tipostockField;
        
        private System.DateTime fechaingresoField;
        
        /// <remarks/>
        public string codperiodo {
            get {
                return this.codperiodoField;
            }
            set {
                this.codperiodoField = value;
            }
        }
        
        /// <remarks/>
        public string codsap {
            get {
                return this.codsapField;
            }
            set {
                this.codsapField = value;
            }
        }
        
        /// <remarks/>
        public string cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        public string tipostock {
            get {
                return this.tipostockField;
            }
            set {
                this.tipostockField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaingreso {
            get {
                return this.fechaingresoField;
            }
            set {
                this.fechaingresoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DispoProl {
        
        private string fechaprocesoField;
        
        private string activaprolField;
        
        private string ejecutoautomaField;
        
        private string observacionField;
        
        /// <remarks/>
        public string fechaproceso {
            get {
                return this.fechaprocesoField;
            }
            set {
                this.fechaprocesoField = value;
            }
        }
        
        /// <remarks/>
        public string activaprol {
            get {
                return this.activaprolField;
            }
            set {
                this.activaprolField = value;
            }
        }
        
        /// <remarks/>
        public string ejecutoautoma {
            get {
                return this.ejecutoautomaField;
            }
            set {
                this.ejecutoautomaField = value;
            }
        }
        
        /// <remarks/>
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DetallePedido {
        
        private string abrvField;
        
        private string serieField;
        
        private string numpedidoField;
        
        private string cuvField;
        
        private string cantField;
        
        private string cuv_rField;
        
        private string correlativoField;
        
        /// <remarks/>
        public string abrv {
            get {
                return this.abrvField;
            }
            set {
                this.abrvField = value;
            }
        }
        
        /// <remarks/>
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        public string numpedido {
            get {
                return this.numpedidoField;
            }
            set {
                this.numpedidoField = value;
            }
        }
        
        /// <remarks/>
        public string cuv {
            get {
                return this.cuvField;
            }
            set {
                this.cuvField = value;
            }
        }
        
        /// <remarks/>
        public string cant {
            get {
                return this.cantField;
            }
            set {
                this.cantField = value;
            }
        }
        
        /// <remarks/>
        public string cuv_r {
            get {
                return this.cuv_rField;
            }
            set {
                this.cuv_rField = value;
            }
        }
        
        /// <remarks/>
        public string correlativo {
            get {
                return this.correlativoField;
            }
            set {
                this.correlativoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReportStockxZona {
        
        private string campaniaField;
        
        private string regionField;
        
        private string zonaField;
        
        private string codsapField;
        
        private string reservadoField;
        
        private string consumidoField;
        
        /// <remarks/>
        public string campania {
            get {
                return this.campaniaField;
            }
            set {
                this.campaniaField = value;
            }
        }
        
        /// <remarks/>
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string zona {
            get {
                return this.zonaField;
            }
            set {
                this.zonaField = value;
            }
        }
        
        /// <remarks/>
        public string codsap {
            get {
                return this.codsapField;
            }
            set {
                this.codsapField = value;
            }
        }
        
        /// <remarks/>
        public string reservado {
            get {
                return this.reservadoField;
            }
            set {
                this.reservadoField = value;
            }
        }
        
        /// <remarks/>
        public string consumido {
            get {
                return this.consumidoField;
            }
            set {
                this.consumidoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OfertaProl {
        
        private string nombreField;
        
        private string codigoventaField;
        
        private string descripcionproductoField;
        
        private string urlImagenField;
        
        private string urlVideoField;
        
        private string esVideoField;
        
        private string subCategoriaField;
        
        private string codigoMarcaField;
        
        private string campaniaField;
        
        private string paisField;
        
        private string activoField;
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string codigoventa {
            get {
                return this.codigoventaField;
            }
            set {
                this.codigoventaField = value;
            }
        }
        
        /// <remarks/>
        public string descripcionproducto {
            get {
                return this.descripcionproductoField;
            }
            set {
                this.descripcionproductoField = value;
            }
        }
        
        /// <remarks/>
        public string UrlImagen {
            get {
                return this.urlImagenField;
            }
            set {
                this.urlImagenField = value;
            }
        }
        
        /// <remarks/>
        public string UrlVideo {
            get {
                return this.urlVideoField;
            }
            set {
                this.urlVideoField = value;
            }
        }
        
        /// <remarks/>
        public string EsVideo {
            get {
                return this.esVideoField;
            }
            set {
                this.esVideoField = value;
            }
        }
        
        /// <remarks/>
        public string SubCategoria {
            get {
                return this.subCategoriaField;
            }
            set {
                this.subCategoriaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoMarca {
            get {
                return this.codigoMarcaField;
            }
            set {
                this.codigoMarcaField = value;
            }
        }
        
        /// <remarks/>
        public string Campania {
            get {
                return this.campaniaField;
            }
            set {
                this.campaniaField = value;
            }
        }
        
        /// <remarks/>
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        public string Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LogError {
        
        private string procesoField;
        
        private string mensajeField;
        
        private string pasoField;
        
        private string subpasoField;
        
        /// <remarks/>
        public string proceso {
            get {
                return this.procesoField;
            }
            set {
                this.procesoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string paso {
            get {
                return this.pasoField;
            }
            set {
                this.pasoField = value;
            }
        }
        
        /// <remarks/>
        public string subpaso {
            get {
                return this.subpasoField;
            }
            set {
                this.subpasoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StockReservado {
        
        private string codsapField;
        
        private string cantidadField;
        
        /// <remarks/>
        public string Codsap {
            get {
                return this.codsapField;
            }
            set {
                this.codsapField = value;
            }
        }
        
        /// <remarks/>
        public string Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ArchivoStock {
        
        private string codsapField;
        
        private string stockactualField;
        
        private string stocknuevoField;
        
        private string operacionField;
        
        /// <remarks/>
        public string codsap {
            get {
                return this.codsapField;
            }
            set {
                this.codsapField = value;
            }
        }
        
        /// <remarks/>
        public string stockactual {
            get {
                return this.stockactualField;
            }
            set {
                this.stockactualField = value;
            }
        }
        
        /// <remarks/>
        public string stocknuevo {
            get {
                return this.stocknuevoField;
            }
            set {
                this.stocknuevoField = value;
            }
        }
        
        /// <remarks/>
        public string operacion {
            get {
                return this.operacionField;
            }
            set {
                this.operacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LogCarga {
        
        private string paisField;
        
        private string procesoField;
        
        private string estadoField;
        
        private string fechaField;
        
        private string inicioField;
        
        private string finalizacionField;
        
        private string duracionField;
        
        /// <remarks/>
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        public string proceso {
            get {
                return this.procesoField;
            }
            set {
                this.procesoField = value;
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public string inicio {
            get {
                return this.inicioField;
            }
            set {
                this.inicioField = value;
            }
        }
        
        /// <remarks/>
        public string finalizacion {
            get {
                return this.finalizacionField;
            }
            set {
                this.finalizacionField = value;
            }
        }
        
        /// <remarks/>
        public string duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ControlCarga {
        
        private string paisField;
        
        private string fechaField;
        
        private string fechastockField;
        
        /// <remarks/>
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public string fechastock {
            get {
                return this.fechastockField;
            }
            set {
                this.fechastockField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultaStockCompletedEventHandler(object sender, ConsultaStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Lista[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Lista[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultarCargaCompletedEventHandler(object sender, ConsultarCargaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCargaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCargaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ControlCarga[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ControlCarga[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultaJobProlCompletedEventHandler(object sender, ConsultaJobProlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaJobProlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaJobProlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LogCarga[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LogCarga[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultaJobStockProlCompletedEventHandler(object sender, ConsultaJobStockProlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaJobStockProlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaJobStockProlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LogCarga[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LogCarga[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultaArchivoStockCompletedEventHandler(object sender, ConsultaArchivoStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaArchivoStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaArchivoStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ArchivoStock[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArchivoStock[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FechasPaisCompletedEventHandler(object sender, FechasPaisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FechasPaisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FechasPaisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FechasPaisJobCompletedEventHandler(object sender, FechasPaisJobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FechasPaisJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FechasPaisJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void HorasCompletedEventHandler(object sender, HorasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HorasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HorasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerUnidadesReservadasCompletedEventHandler(object sender, ObtenerUnidadesReservadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerUnidadesReservadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerUnidadesReservadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StockReservado[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StockReservado[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultaLogErrorEtlCompletedEventHandler(object sender, ConsultaLogErrorEtlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaLogErrorEtlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaLogErrorEtlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LogError[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LogError[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void EjecutarJobCompletedEventHandler(object sender, EjecutarJobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EjecutarJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EjecutarJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DetenerJobCompletedEventHandler(object sender, DetenerJobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DetenerJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DetenerJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AnalizadorCompletedEventHandler(object sender, AnalizadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AnalizadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AnalizadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void EjecutarSqlCompletedEventHandler(object sender, EjecutarSqlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EjecutarSqlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EjecutarSqlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ListaOfertaProlCompletedEventHandler(object sender, ListaOfertaProlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaOfertaProlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaOfertaProlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OfertaProl[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OfertaProl[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ReporteStockxZonaCompletedEventHandler(object sender, ReporteStockxZonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReporteStockxZonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReporteStockxZonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReportStockxZona[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReportStockxZona[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FileDetalleExplotadoCompletedEventHandler(object sender, FileDetalleExplotadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FileDetalleExplotadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FileDetalleExplotadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DetallePedido[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DetallePedido[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SubirFtpCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WsDisponibilidadProlCompletedEventHandler(object sender, WsDisponibilidadProlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsDisponibilidadProlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsDisponibilidadProlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DispoProl[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DispoProl[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WsIStockFicticioCompletedEventHandler(object sender, WsIStockFicticioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WsIStockFicticioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WsIStockFicticioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RptStock[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RptStock[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultaProlSapCompletedEventHandler(object sender, ConsultaProlSapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaProlSapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaProlSapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591