USE PROLPE
GO
ALTER  PROCEDURE OBTENER_PRECIO_PACK_ESTRATEGIA_ (@LISTA_CODVTA AS VARCHAR(6),@LISTA_CANT AS VARCHAR(6), @PERIODO AS VARCHAR(6))

	AS
	
	BEGIN TRY

	 --
	 -- SETEA CONFIGURACION PROL
	 
	 

	 DECLARE @MONTOGANANCIA DECIMAL(10,2)

	 CREATE TABLE #PEDIDO

	 (

	 CODVTA VARCHAR(6) COLLATE DATABASE_DEFAULT,

	 CANT_SOL INT, 

	 COD_CUPON VARCHAR(6) COLLATE DATABASE_DEFAULT,

	 CUPON_AUTO VARCHAR(1) COLLATE DATABASE_DEFAULT, 

	 ESTADO VARCHAR(2),

	 DIFERENCIA INT,

	 EXIG_VENTA DECIMAL(18,2),

	 IND_EXIG INT

	 PRIMARY KEY (CODVTA)

	 )

	 
	 
	 INSERT INTO #PEDIDO

	 SELECT P.COLA CODVTA, SUM(CONVERT(INT,P.COLB)) CANT_SOL, NULL COD_CUPON, NULL CUPON_AUTO,NULL ESTADO,NULL DIFERENCIA,NULL EXIG_VENTA,NULL IND_EXIG

	 FROM FN_SPLITEAR(@LISTA_CODVTA,@LISTA_CANT,'|') P

	 GROUP BY P.COLA 


	 --Inserta datos de cupones ingresados

	INSERT #PEDIDO

	SELECT PM.COD_VENTA CODVTA, 1 CANTIDAD, CHP.COD_CUPON COD_CUPON, '1' CUPON_AUTO ,NULL ESTADO,NULL DIFERENCIA,NULL EXIG_VENTA,NULL IND_EXIG

	FROM --CUP_CUPONES_REGISTRADAS CCP,

	CUP_HOMOLOGACION_PROL CHP,

	PRL_MATRIZ PM,#PEDIDO P

	WHERE --CCP.COD_CUPON = CHP.COD_CUPON  AND 
		   
	PM.COD_PERIODO = @PERIODO

	AND PM.COD_VENTA = CHP.COD_VENTA

	AND CHP.COD_CUPON=P.CODVTA

	---

	 	
	 -- CREA TABLA A DEVOLVER CON CUADRE DE OFERTA

	 --

	 CREATE TABLE #CUADRE_OFERTA

	 (

	 CODVTA VARCHAR(6) COLLATE DATABASE_DEFAULT,

	 CODSAP VARCHAR(20) COLLATE DATABASE_DEFAULT,

	 DESCRIP VARCHAR(80) COLLATE DATABASE_DEFAULT,

	 PRECIO_UNITARIO DECIMAL(12,2),

	 CANTIDAD INT,

	 SUBTOTAL DECIMAL(12,2),

	 DIGITABLE INT,

	 ESTRATEGIA INT,

	 NUMERO_OFERTA INT,

	 LINEA_OFERTA INT,

	 COD_OBSERVACION VARCHAR(2) COLLATE DATABASE_DEFAULT,

	 DES_OBSERVACION VARCHAR(800) COLLATE DATABASE_DEFAULT,

	 CODVTA_REEMPLAZO_A VARCHAR(6) COLLATE DATABASE_DEFAULT,

	 CODVTA_REEMPLAZO_D VARCHAR(6) COLLATE DATABASE_DEFAULT,

	 CODVTA_ORIGINAL VARCHAR(6) COLLATE DATABASE_DEFAULT,

	 COD_CUPON VARCHAR(6) COLLATE DATABASE_DEFAULT,

	 CUPON_AUTO VARCHAR(1) COLLATE DATABASE_DEFAULT,

	 OBSERVACION VARCHAR(800) COLLATE DATABASE_DEFAULT,

	 COD_CATALOGO VARCHAR(3) COLLATE DATABASE_DEFAULT,

	 CODPADRE VARCHAR(6) COLLATE DATABASE_DEFAULT,

	 NUMERO_NIVEL INT NULL,

	 EXIG_VENTA DECIMAL (16,2),

	 IND_EXIG INT,

	 FACTOR_REPETICION INT NULL,



	 IND_COMI INT,

	 IND_APOR_MONT_ESCA INT,

	 OID_PRODUCTO INT,

	 TIPO_OFERTA INT,

	 UNEG_OID_UNID_NEGO INT,

	 NEGO_OID_NEGO INT,

	 IMP_PREC_PUBL DECIMAL(12,2) NULL,

	 SECCION_FACT INT NULL,

	 PRD_OID_MARCA INT,

	 PRE_CATAL  DECIMAL(12,2) NULL,

	 NUMERO_GRUPO INT

     )




	 INSERT INTO #CUADRE_OFERTA

	 SELECT PM.COD_VENTA CODVTA, PM.COD_PRODUCTO CODSAP, PM.DES_PRODUCTO DESCRIP, PM.PRE_CATAL PRECIO_UNITARIO, P.CANT_SOL * PM.FACTOR_REPETICION CANTIDAD, 

	        (PM.PRE_CATAL* P.CANT_SOL) SUBTOTAL, PM.DIGITABLE,PM.OID_ESTRATEGIA ESTRATEGIA,-- 2001 ESTRATEGIA, 

	        PM.NUMERO_OFERTA, PM.LINEA_OFERTA, NULL COD_OBSERVACION, NULL DES_OBSERVACION, NULL CODVTA_REEMPLAZO_A, NULL CODVTA_REEMPLAZO_D, NULL CODVTA_ORIGINAL,

	        (CASE WHEN P.COD_CUPON IS NULL THEN NULL ELSE P.COD_CUPON END) COD_CUPON, (CASE WHEN P.COD_CUPON IS NULL THEN NULL ELSE P.CUPON_AUTO END) CUPON_AUTO

	     ,NULL OBSERVACION,COD_CATALOGO,NULL CODPADRE,PM.NUMERO_NIVEL, (CASE WHEN P.EXIG_VENTA IS NULL THEN NULL ELSE P.EXIG_VENTA END) EXIG_VENTA  , (CASE WHEN P.IND_EXIG IS NULL THEN NULL ELSE P.IND_EXIG END) IND_EXIG,

		 PM.FACTOR_REPETICION,PM.IND_COMI,PM.IND_APOR_MONT_ESCA,PM.OID_PRODUCTO,PM.TIPO_OFERTA,PM.UNEG_OID_UNID_NEGO,PM.NEGO_OID_NEGO,PM.IMP_PREC_PUBL* PM.FACTOR_REPETICION  IMP_PREC_PUBL,PM.SECCION_FACT,PM.PRD_OID_MARCA,PM.PRE_CATAL*PM.FACTOR_REPETICION, NULL NUMERO_GRUPO

	      FROM PRL_MATRIZ PM  WITH (NOLOCK), 

	           #PEDIDO P

	     WHERE PM.COD_PERIODO = @PERIODO

	       AND PM.OID_ESTRATEGIA =2001

	       AND PM.DIGITABLE = 1

	       AND PM.COD_VENTA = P.CODVTA

		   AND PM.FACTOR_REPETICION >=1
	
	
	
	 INSERT INTO #CUADRE_OFERTA

	 SELECT PMO.COD_VENTA CODVTA, PMO.COD_PRODUCTO CODSAP, PMO.DES_PRODUCTO DESCRIP, PMO.PRECIO_UNITARIO PRECIO_UNITARIO, P.CANT_SOL * PMO.FACTOR_REPETICION CANTIDAD, 

	        --(PMO.PRECIO_UNITARIO * PMO.FACTOR_REPETICION * P.CANT_SOL) SUBTOTAL
			(PMO.PRE_CATAL*P.CANT_SOL) SUBTOTAL
			, PMO.DIGITABLE,PM.OID_ESTRATEGIA ESTRATEGIA, --2002 ESTRATEGIA, 

	        PMO.NUMERO_OFERTA, PMO.LINEA_OFERTA, NULL COD_OBSERVACION, NULL DES_OBSERVACION, NULL CODVTA_REEMPLAZO_A, NULL CODVTA_REEMPLAZO_D, NULL CODVTA_ORIGINAL,

	        (CASE WHEN P.COD_CUPON IS NULL THEN NULL ELSE P.COD_CUPON END) COD_CUPON, (CASE WHEN P.COD_CUPON IS NULL THEN NULL ELSE P.CUPON_AUTO END) CUPON_AUTO,

	     NULL OBSERVACION,PM.COD_CATALOGO,P.CODVTA CODPADRE,PM.NUMERO_NIVEL , (CASE WHEN P.EXIG_VENTA IS NULL THEN NULL ELSE P.EXIG_VENTA END) EXIG_VENTA, (CASE WHEN P.IND_EXIG IS NULL THEN NULL ELSE P.IND_EXIG END) IND_EXIG,PM.FACTOR_REPETICION,

		 PMO.IND_COMI,PMO.IND_APOR_MONT_ESCA,PMO.OID_PRODUCTO,PMO.TIPO_OFERTA,PMO.UNEG_OID_UNID_NEGO,PMO.NEGO_OID_NEGO,PMO.IMP_PREC_PUBL  IMP_PREC_PUBL,PMO.SECCION_FACT,PMO.PRD_OID_MARCA,PMO.PRE_CATAL,NULL NUMERO_GRUPO

	      FROM PRL_MATRIZ PM, 

	           #PEDIDO P, 

	           PRL_MATRIZ PMO

	     WHERE PM.COD_PERIODO = @PERIODO

	       AND PM.OID_ESTRATEGIA IN(2002,2009,2006)

	       AND PM.DIGITABLE = 1 

	       AND PM.COD_VENTA = P.CODVTA

	       AND PMO.COD_PERIODO = @PERIODO

	       AND PMO.OID_ESTRATEGIA IN(2002 ,2009,2006)

	       AND PM.NUMERO_OFERTA = PMO.NUMERO_OFERTA

	       AND PM.OID_ESTRATEGIA = PMO.OID_ESTRATEGIA

	     ORDER BY PMO.NUMERO_OFERTA, PMO.LINEA_OFERTA 

     --
	 
	 INSERT INTO #CUADRE_OFERTA

	 SELECT DISTINCT PM.COD_VENTA CODVTA, NULL CODSAP, NULL DESCRIP, PMO.PRECIO_UNITARIO PRECIO_UNITARIO, (CASE WHEN PO.FACTOR_CUADRE IS NULL THEN P.CANT_SOL ELSE PO.FACTOR_CUADRE END) * PMO.FACTOR_REPETICION CANTIDAD, 

	        (PMO.PRECIO_UNITARIO * PMO.FACTOR_REPETICION *  (CASE WHEN PO.FACTOR_CUADRE IS NULL THEN P.CANT_SOL ELSE PO.FACTOR_CUADRE END)) SUBTOTAL, PMO.DIGITABLE,PM.OID_ESTRATEGIA ESTRATEGIA, --2002 ESTRATEGIA, 

	        PMO.NUMERO_OFERTA, NULL LINEA_OFERTA, NULL COD_OBSERVACION, NULL DES_OBSERVACION, NULL CODVTA_REEMPLAZO_A, NULL CODVTA_REEMPLAZO_D, NULL CODVTA_ORIGINAL,

	        (CASE WHEN P.COD_CUPON IS NULL THEN NULL ELSE P.COD_CUPON END) COD_CUPON, (CASE WHEN P.COD_CUPON IS NULL THEN NULL ELSE P.CUPON_AUTO END) CUPON_AUTO,

	     NULL OBSERVACION,PM.COD_CATALOGO,P.CODVTA CODPADRE,PM.NUMERO_NIVEL , (CASE WHEN P.EXIG_VENTA IS NULL THEN NULL ELSE P.EXIG_VENTA END) EXIG_VENTA, (CASE WHEN P.IND_EXIG IS NULL THEN NULL ELSE P.IND_EXIG END) IND_EXIG,PM.FACTOR_REPETICION,

		 PM.IND_COMI,PM.IND_APOR_MONT_ESCA,PM.OID_PRODUCTO,PM.TIPO_OFERTA,PM.UNEG_OID_UNID_NEGO,PM.NEGO_OID_NEGO,PMO.IMP_PREC_PUBL* PMO.FACTOR_REPETICION *(CASE WHEN PO.FACTOR_CUADRE IS NULL THEN P.CANT_SOL ELSE PO.FACTOR_CUADRE END)  IMP_PREC_PUBL,PM.SECCION_FACT,PM.PRD_OID_MARCA,NULL PRE_CATAL,PMO.NUMERO_GRUPO

	      FROM PRL_MATRIZ PM, 

	           #PEDIDO P, 

	           PRL_MATRIZ PMO,
			   
			   PRL_OFERTAS PO

	     WHERE PM.COD_PERIODO = @PERIODO

	       AND PM.OID_ESTRATEGIA IN(2003)

	       AND PM.DIGITABLE = 1 

	       AND PM.COD_VENTA = P.CODVTA

	       AND PMO.COD_PERIODO = @PERIODO

	       AND PMO.OID_ESTRATEGIA IN(2003)

	       AND PM.NUMERO_OFERTA = PMO.NUMERO_OFERTA

	       AND PM.OID_ESTRATEGIA = PMO.OID_ESTRATEGIA

		   AND PO.COD_PERIODO=@PERIODO

		   AND PO.OID_ESTRATEGIA =2003

		   AND PO.NUMERO_OFERTA = PMO.NUMERO_OFERTA

		   AND PO.NUMERO_OFERTA = PM.NUMERO_OFERTA
		   
		   AND PO.NUMERO_GRUPO	= PMO.NUMERO_GRUPO

--SELECT * FROM #CUADRE_OFERTA RETURN

DECLARE @VALORIZADO DECIMAL(10,2)


SET @VALORIZADO=(SELECT SUM(PRECIO*CANTIDAD) FROM (

	SELECT 

	DISTINCT PM.COD_PRODUCTO,MAX(PM.PRECIO_UNITARIO) PRECIO,C.CANTIDAD CANTIDAD FROM

	PRL_MATRIZ PM WITH(NOLOCK) INNER JOIN #CUADRE_OFERTA C ON PM.COD_PRODUCTO=C.CODSAP AND PM.COD_PERIODO=@PERIODO WHERE PM.COD_CATALOGO <>24

	AND PM.DIGITABLE=1 AND OID_ESTRATEGIA=2001 AND PM.FACTOR_REPETICION=1

	GROUP BY PM.COD_PRODUCTO,C.CANTIDAD)T)

	
	IF((SELECT SUM(SUBTOTAL)  FROM #CUADRE_OFERTA CO) IS NULL) 
	SELECT '_X' AS CODVTA,'0' AS SUBTOTAL ,0 MONTOGANANCIA
	ELSE


	
	SELECT '_X' AS CODVTA,
	--SUM(CASE WHEN ESTRATEGIA=2002 AND FACTOR_REPETICION>1 THEN PRE_CATAL ELSE  SUBTOTAL END)  AS SUBTOTAL,
	SUM(SUBTOTAL)  AS SUBTOTAL,
	ISNULL(SUM(IMP_PREC_PUBL-SUBTOTAL),0) MONTO FROM  #CUADRE_OFERTA CO 
	


	SELECT DISTINCT P.FACT_CUADRE [NIVEL],P.PRECIO_UNITARIO [PRECIO] FROM PRL_PRODUCTOS_NIVEL P (NOLOCK) INNER JOIN #CUADRE_OFERTA C ON P.NUMERO_NIVEL=C.NUMERO_NIVEL AND  P.COD_PERIODO=@PERIODO

	
	END TRY
	BEGIN CATCH
		SELECT '_X' AS CODVTA,'-1' AS SUBTOTAL ,0 MONTOGANANCIA
	END CATCH
	

