ALTER PROCEDURE P_PRODUCTO_ESTRATEGIA
(
@COD_PERIODO VARCHAR(6)
,@COD_CONSULTORA VARCHAR(12)
,@CUV VARCHAR(6)
)
AS

SET NOCOUNT ON;

SELECT 
		CODIGO_ESTRATEGIA
		,ESTRATEGIA
		,COD_VENTA_HIJO CUV
		,GRUPO,CODIGO_SAP
		,SUM(CANTIDAD) CANTIDAD
		,SUM(PRECIO_UNITARIO) PRECIO_UNITARIO
		,SUM(PRECIO_VALORIZADO) PRECIO_VALORIZADO
		,ORDEN
		,DIGITABLE
		,FACTOR_CUADRE
		,DESCRIPCION,IDMARCA

FROM (

		SELECT 
			PM.OID_ESTRATEGIA CODIGO_ESTRATEGIA
			,PMO.DES_ESTRATEGIA ESTRATEGIA
			,CASE WHEN PMO.COD_PRODUCTO=PM.COD_PRODUCTO THEN PM.COD_VENTA ELSE PMO.COD_VENTA END CUV
			,ISNULL(PMO.NUMERO_GRUPO,0) GRUPO
			,PMO.COD_PRODUCTO CODIGO_SAP
			,ISNULL(PMO.FACTOR_REPETICION,1) CANTIDAD
			,(PMO.PRECIO_UNITARIO) PRECIO_UNITARIO
			,(PMO.IMP_PREC_PUBL) PRECIO_VALORIZADO
			,CASE WHEN PMO.COD_PRODUCTO=PM.COD_PRODUCTO THEN PM.LINEA_OFERTA ELSE PMO.LINEA_OFERTA END ORDEN
			,PMO.DIGITABLE DIGITABLE
			,PMO.COD_VENTA COD_VENTA_HIJO
			,CAST(ISNULL(PO.FACTOR_CUADRE,1) AS INT) FACTOR_CUADRE
			,PMO.DES_PRODUCTO DESCRIPCION
			,PMO.PRD_OID_MARCA IDMARCA

		FROM PRL_MATRIZ PM WITH (NOLOCK) 
		
		INNER JOIN PRL_MATRIZ PMO 
			ON PM.OID_ESTRATEGIA=PMO.OID_ESTRATEGIA 
			AND PM.COD_PERIODO=PMO.COD_PERIODO 
			AND PM.NUMERO_OFERTA = PMO.NUMERO_OFERTA

		LEFT JOIN PRL_OFERTAS PO WITH (NOLOCK) 
			ON PO.COD_PERIODO=PM.COD_PERIODO 
			AND PO.COD_PERIODO=PMO.COD_PERIODO 
			AND PO.OID_ESTRATEGIA=PM.OID_ESTRATEGIA 
			AND PO.OID_ESTRATEGIA=PMO.OID_ESTRATEGIA
			AND PO.NUMERO_OFERTA=PM.NUMERO_OFERTA 
			AND PO.NUMERO_OFERTA=PMO.NUMERO_OFERTA 
			AND PO.NUMERO_GRUPO=PMO.NUMERO_GRUPO

		WHERE PMO.COD_PERIODO=@COD_PERIODO 
			AND PM.COD_VENTA=@CUV

) T

GROUP BY 
	CODIGO_ESTRATEGIA
	,ESTRATEGIA
	,CUV
	,GRUPO
	,CODIGO_SAP
	,ORDEN
	,DIGITABLE
	,COD_VENTA_HIJO
	,FACTOR_CUADRE
	,DESCRIPCION
	,IDMARCA

ORDER BY GRUPO, ORDEN

SET NOCOUNT OFF;
