GO
IF (NOT EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ValidacionAutomaticaPROLLog' AND COLUMN_NAME = 'EsDeuda'))
BEGIN
    ALTER TABLE dbo.ValidacionAutomaticaPROLLog
	ADD EsDeuda BIT CONSTRAINT DF_ValidacionAutomaticaPROLLog_EsDeuda DEFAULT(0) NOT NULL;
END
IF (NOT EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ValidacionAutomaticaPROLLog' AND COLUMN_NAME = 'MontoDeuda'))
BEGIN
    ALTER TABLE dbo.ValidacionAutomaticaPROLLog
	ADD MontoDeuda MONEY CONSTRAINT DF_ValidacionAutomaticaPROLLog_MontoDeuda DEFAULT(0) NOT NULL;
END
GO