//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pelnx2138:7003/ssiccclespdp/services/ProcesoMAEActualizaFlagImpBoletasWebS" +
        "ervice", ConfigurationName="ServiceActualizarFlagBoletaImpresa.ProcesoMAEActualizaFlagImpBoletasWebServiceImp" +
        "l")]
    public interface ProcesoMAEActualizaFlagImpBoletasWebServiceImpl {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://impl.ws.mae.spusicc.service.ssicc.belcorp.biz) del mensaje actualizaFlagImpBoletasRequest no coincide con el valor predeterminado (http://pelnx2138:7003/ssiccclespdp/services/ProcesoMAEActualizaFlagImpBoletasWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ErrorActualizarFlagImpBoleta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ConsultoraFlagImpBoleta))]
        Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.actualizaFlagImpBoletasResponse actualizaFlagImpBoletas(Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.actualizaFlagImpBoletasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.actualizaFlagImpBoletasResponse> actualizaFlagImpBoletasAsync(Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.actualizaFlagImpBoletasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:consultoraFlagImpBoleta.beans.ws.web.mae.spusicc.ssicc.belcorp.biz")]
    public partial class ConsultoraFlagImpBoleta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoConsultoraField;
        
        private string indImprimeBoletaField;
        
        private string indImprimePaqueteField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigoConsultora {
            get {
                return this.codigoConsultoraField;
            }
            set {
                this.codigoConsultoraField = value;
                this.RaisePropertyChanged("codigoConsultora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string indImprimeBoleta {
            get {
                return this.indImprimeBoletaField;
            }
            set {
                this.indImprimeBoletaField = value;
                this.RaisePropertyChanged("indImprimeBoleta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string indImprimePaquete {
            get {
                return this.indImprimePaqueteField;
            }
            set {
                this.indImprimePaqueteField = value;
                this.RaisePropertyChanged("indImprimePaquete");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:errorActualizarFlagImpBoleta.beans.ws.web.mae.spusicc.ssicc.belcorp.biz")]
    public partial class ErrorActualizarFlagImpBoleta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoConsultoraField;
        
        private string mensajeErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigoConsultora {
            get {
                return this.codigoConsultoraField;
            }
            set {
                this.codigoConsultoraField = value;
                this.RaisePropertyChanged("codigoConsultora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("mensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:actualizarFlagImpBoletaResultado.beans.ws.web.mae.spusicc.ssicc.belcorp.biz")]
    public partial class ActualizarFlagImpBoletaResultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> estadoField;
        
        private ErrorActualizarFlagImpBoleta[] listaErrorField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ErrorActualizarFlagImpBoleta[] listaError {
            get {
                return this.listaErrorField;
            }
            set {
                this.listaErrorField = value;
                this.RaisePropertyChanged("listaError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizaFlagImpBoletas", WrapperNamespace="http://impl.ws.mae.spusicc.service.ssicc.belcorp.biz", IsWrapped=true)]
    public partial class actualizaFlagImpBoletasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.ConsultoraFlagImpBoleta[] consultoraFlagImpBoletas;
        
        public actualizaFlagImpBoletasRequest() {
        }
        
        public actualizaFlagImpBoletasRequest(Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.ConsultoraFlagImpBoleta[] consultoraFlagImpBoletas) {
            this.consultoraFlagImpBoletas = consultoraFlagImpBoletas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizaFlagImpBoletasResponse", WrapperNamespace="http://pelnx2138:7003/ssiccclespdp/services/ProcesoMAEActualizaFlagImpBoletasWebS" +
        "ervice", IsWrapped=true)]
    public partial class actualizaFlagImpBoletasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.ActualizarFlagImpBoletaResultado actualizaFlagImpBoletasReturn;
        
        public actualizaFlagImpBoletasResponse() {
        }
        
        public actualizaFlagImpBoletasResponse(Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.ActualizarFlagImpBoletaResultado actualizaFlagImpBoletasReturn) {
            this.actualizaFlagImpBoletasReturn = actualizaFlagImpBoletasReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProcesoMAEActualizaFlagImpBoletasWebServiceImplChannel : Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.ProcesoMAEActualizaFlagImpBoletasWebServiceImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcesoMAEActualizaFlagImpBoletasWebServiceImplClient : System.ServiceModel.ClientBase<Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.ProcesoMAEActualizaFlagImpBoletasWebServiceImpl>, Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.ProcesoMAEActualizaFlagImpBoletasWebServiceImpl {
        
        public ProcesoMAEActualizaFlagImpBoletasWebServiceImplClient() {
        }
        
        public ProcesoMAEActualizaFlagImpBoletasWebServiceImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcesoMAEActualizaFlagImpBoletasWebServiceImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcesoMAEActualizaFlagImpBoletasWebServiceImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcesoMAEActualizaFlagImpBoletasWebServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.actualizaFlagImpBoletasResponse Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.ProcesoMAEActualizaFlagImpBoletasWebServiceImpl.actualizaFlagImpBoletas(Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.actualizaFlagImpBoletasRequest request) {
            return base.Channel.actualizaFlagImpBoletas(request);
        }
        
        public Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.ActualizarFlagImpBoletaResultado actualizaFlagImpBoletas(Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.ConsultoraFlagImpBoleta[] consultoraFlagImpBoletas) {
            Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.actualizaFlagImpBoletasRequest inValue = new Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.actualizaFlagImpBoletasRequest();
            inValue.consultoraFlagImpBoletas = consultoraFlagImpBoletas;
            Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.actualizaFlagImpBoletasResponse retVal = ((Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.ProcesoMAEActualizaFlagImpBoletasWebServiceImpl)(this)).actualizaFlagImpBoletas(inValue);
            return retVal.actualizaFlagImpBoletasReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.actualizaFlagImpBoletasResponse> Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.ProcesoMAEActualizaFlagImpBoletasWebServiceImpl.actualizaFlagImpBoletasAsync(Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.actualizaFlagImpBoletasRequest request) {
            return base.Channel.actualizaFlagImpBoletasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.actualizaFlagImpBoletasResponse> actualizaFlagImpBoletasAsync(Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.ConsultoraFlagImpBoleta[] consultoraFlagImpBoletas) {
            Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.actualizaFlagImpBoletasRequest inValue = new Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.actualizaFlagImpBoletasRequest();
            inValue.consultoraFlagImpBoletas = consultoraFlagImpBoletas;
            return ((Portal.Consultoras.Data.ServiceActualizarFlagBoletaImpresa.ProcesoMAEActualizaFlagImpBoletasWebServiceImpl)(this)).actualizaFlagImpBoletasAsync(inValue);
        }
    }
}
