//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Portal.Consultoras.Web.ServiceCatalogosIssuu {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MulticatalogoWebServiceSoap", Namespace="http://Belcorp.WebServices/MulticatalogoService")]
    public partial class MulticatalogoWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCatalogosPublicadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNumeroPedidosPendientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPedidoPendienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPedidoPendienteDetalleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPedidoPendienteConsolidadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdPedidoPendienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPedidoEnviadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPedidoEnviadoDetalleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MulticatalogoWebService() {
            this.Url = global::Portal.Consultoras.Web.Properties.Settings.Default.Portal_Consultoras_Web_ServiceCatalogosIssuu_MulticatalogoWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCatalogosPublicadosCompletedEventHandler GetCatalogosPublicadosCompleted;
        
        /// <remarks/>
        public event GetNumeroPedidosPendientesCompletedEventHandler GetNumeroPedidosPendientesCompleted;
        
        /// <remarks/>
        public event GetPedidoPendienteCompletedEventHandler GetPedidoPendienteCompleted;
        
        /// <remarks/>
        public event GetPedidoPendienteDetalleCompletedEventHandler GetPedidoPendienteDetalleCompleted;
        
        /// <remarks/>
        public event GetPedidoPendienteConsolidadoCompletedEventHandler GetPedidoPendienteConsolidadoCompleted;
        
        /// <remarks/>
        public event UpdPedidoPendienteCompletedEventHandler UpdPedidoPendienteCompleted;
        
        /// <remarks/>
        public event GetPedidoEnviadoCompletedEventHandler GetPedidoEnviadoCompleted;
        
        /// <remarks/>
        public event GetPedidoEnviadoDetalleCompletedEventHandler GetPedidoEnviadoDetalleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Belcorp.WebServices/MulticatalogoService/GetCatalogosPublicados", RequestNamespace="http://Belcorp.WebServices/MulticatalogoService", ResponseNamespace="http://Belcorp.WebServices/MulticatalogoService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Catalogo[] GetCatalogosPublicados(string codigoFuente, string prefijoISOPais, string anoCampana) {
            object[] results = this.Invoke("GetCatalogosPublicados", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        anoCampana});
            return ((Catalogo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCatalogosPublicadosAsync(string codigoFuente, string prefijoISOPais, string anoCampana) {
            this.GetCatalogosPublicadosAsync(codigoFuente, prefijoISOPais, anoCampana, null);
        }
        
        /// <remarks/>
        public void GetCatalogosPublicadosAsync(string codigoFuente, string prefijoISOPais, string anoCampana, object userState) {
            if ((this.GetCatalogosPublicadosOperationCompleted == null)) {
                this.GetCatalogosPublicadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCatalogosPublicadosOperationCompleted);
            }
            this.InvokeAsync("GetCatalogosPublicados", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        anoCampana}, this.GetCatalogosPublicadosOperationCompleted, userState);
        }
        
        private void OnGetCatalogosPublicadosOperationCompleted(object arg) {
            if ((this.GetCatalogosPublicadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCatalogosPublicadosCompleted(this, new GetCatalogosPublicadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Belcorp.WebServices/MulticatalogoService/GetNumeroPedidosPendientes", RequestNamespace="http://Belcorp.WebServices/MulticatalogoService", ResponseNamespace="http://Belcorp.WebServices/MulticatalogoService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetNumeroPedidosPendientes(string codigoFuente, string prefijoISOPais, string codigoPerfil, string codigo, string anoCampana) {
            object[] results = this.Invoke("GetNumeroPedidosPendientes", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        codigoPerfil,
                        codigo,
                        anoCampana});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetNumeroPedidosPendientesAsync(string codigoFuente, string prefijoISOPais, string codigoPerfil, string codigo, string anoCampana) {
            this.GetNumeroPedidosPendientesAsync(codigoFuente, prefijoISOPais, codigoPerfil, codigo, anoCampana, null);
        }
        
        /// <remarks/>
        public void GetNumeroPedidosPendientesAsync(string codigoFuente, string prefijoISOPais, string codigoPerfil, string codigo, string anoCampana, object userState) {
            if ((this.GetNumeroPedidosPendientesOperationCompleted == null)) {
                this.GetNumeroPedidosPendientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNumeroPedidosPendientesOperationCompleted);
            }
            this.InvokeAsync("GetNumeroPedidosPendientes", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        codigoPerfil,
                        codigo,
                        anoCampana}, this.GetNumeroPedidosPendientesOperationCompleted, userState);
        }
        
        private void OnGetNumeroPedidosPendientesOperationCompleted(object arg) {
            if ((this.GetNumeroPedidosPendientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNumeroPedidosPendientesCompleted(this, new GetNumeroPedidosPendientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Belcorp.WebServices/MulticatalogoService/GetPedidoPendiente", RequestNamespace="http://Belcorp.WebServices/MulticatalogoService", ResponseNamespace="http://Belcorp.WebServices/MulticatalogoService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pedido[] GetPedidoPendiente(string codigoFuente, string prefijoISOPais, string codigoPerfil, string codigo, string anoCampana) {
            object[] results = this.Invoke("GetPedidoPendiente", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        codigoPerfil,
                        codigo,
                        anoCampana});
            return ((Pedido[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPedidoPendienteAsync(string codigoFuente, string prefijoISOPais, string codigoPerfil, string codigo, string anoCampana) {
            this.GetPedidoPendienteAsync(codigoFuente, prefijoISOPais, codigoPerfil, codigo, anoCampana, null);
        }
        
        /// <remarks/>
        public void GetPedidoPendienteAsync(string codigoFuente, string prefijoISOPais, string codigoPerfil, string codigo, string anoCampana, object userState) {
            if ((this.GetPedidoPendienteOperationCompleted == null)) {
                this.GetPedidoPendienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPedidoPendienteOperationCompleted);
            }
            this.InvokeAsync("GetPedidoPendiente", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        codigoPerfil,
                        codigo,
                        anoCampana}, this.GetPedidoPendienteOperationCompleted, userState);
        }
        
        private void OnGetPedidoPendienteOperationCompleted(object arg) {
            if ((this.GetPedidoPendienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPedidoPendienteCompleted(this, new GetPedidoPendienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Belcorp.WebServices/MulticatalogoService/GetPedidoPendienteDetalle", RequestNamespace="http://Belcorp.WebServices/MulticatalogoService", ResponseNamespace="http://Belcorp.WebServices/MulticatalogoService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PedidoDetalle[] GetPedidoPendienteDetalle(string codigoFuente, string prefijoISOPais, long idPedido) {
            object[] results = this.Invoke("GetPedidoPendienteDetalle", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        idPedido});
            return ((PedidoDetalle[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPedidoPendienteDetalleAsync(string codigoFuente, string prefijoISOPais, long idPedido) {
            this.GetPedidoPendienteDetalleAsync(codigoFuente, prefijoISOPais, idPedido, null);
        }
        
        /// <remarks/>
        public void GetPedidoPendienteDetalleAsync(string codigoFuente, string prefijoISOPais, long idPedido, object userState) {
            if ((this.GetPedidoPendienteDetalleOperationCompleted == null)) {
                this.GetPedidoPendienteDetalleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPedidoPendienteDetalleOperationCompleted);
            }
            this.InvokeAsync("GetPedidoPendienteDetalle", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        idPedido}, this.GetPedidoPendienteDetalleOperationCompleted, userState);
        }
        
        private void OnGetPedidoPendienteDetalleOperationCompleted(object arg) {
            if ((this.GetPedidoPendienteDetalleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPedidoPendienteDetalleCompleted(this, new GetPedidoPendienteDetalleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Belcorp.WebServices/MulticatalogoService/GetPedidoPendienteConsolidado", RequestNamespace="http://Belcorp.WebServices/MulticatalogoService", ResponseNamespace="http://Belcorp.WebServices/MulticatalogoService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PedidoDetalle[] GetPedidoPendienteConsolidado(string codigoFuente, string prefijoISOPais, string codigoPerfil, string codigo, string anoCampana) {
            object[] results = this.Invoke("GetPedidoPendienteConsolidado", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        codigoPerfil,
                        codigo,
                        anoCampana});
            return ((PedidoDetalle[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPedidoPendienteConsolidadoAsync(string codigoFuente, string prefijoISOPais, string codigoPerfil, string codigo, string anoCampana) {
            this.GetPedidoPendienteConsolidadoAsync(codigoFuente, prefijoISOPais, codigoPerfil, codigo, anoCampana, null);
        }
        
        /// <remarks/>
        public void GetPedidoPendienteConsolidadoAsync(string codigoFuente, string prefijoISOPais, string codigoPerfil, string codigo, string anoCampana, object userState) {
            if ((this.GetPedidoPendienteConsolidadoOperationCompleted == null)) {
                this.GetPedidoPendienteConsolidadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPedidoPendienteConsolidadoOperationCompleted);
            }
            this.InvokeAsync("GetPedidoPendienteConsolidado", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        codigoPerfil,
                        codigo,
                        anoCampana}, this.GetPedidoPendienteConsolidadoOperationCompleted, userState);
        }
        
        private void OnGetPedidoPendienteConsolidadoOperationCompleted(object arg) {
            if ((this.GetPedidoPendienteConsolidadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPedidoPendienteConsolidadoCompleted(this, new GetPedidoPendienteConsolidadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Belcorp.WebServices/MulticatalogoService/UpdPedidoPendiente", RequestNamespace="http://Belcorp.WebServices/MulticatalogoService", ResponseNamespace="http://Belcorp.WebServices/MulticatalogoService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdPedidoPendiente(string codigoFuente, string prefijoISOPais, PedidoDetalle[] pedidoDetalle) {
            object[] results = this.Invoke("UpdPedidoPendiente", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        pedidoDetalle});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdPedidoPendienteAsync(string codigoFuente, string prefijoISOPais, PedidoDetalle[] pedidoDetalle) {
            this.UpdPedidoPendienteAsync(codigoFuente, prefijoISOPais, pedidoDetalle, null);
        }
        
        /// <remarks/>
        public void UpdPedidoPendienteAsync(string codigoFuente, string prefijoISOPais, PedidoDetalle[] pedidoDetalle, object userState) {
            if ((this.UpdPedidoPendienteOperationCompleted == null)) {
                this.UpdPedidoPendienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdPedidoPendienteOperationCompleted);
            }
            this.InvokeAsync("UpdPedidoPendiente", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        pedidoDetalle}, this.UpdPedidoPendienteOperationCompleted, userState);
        }
        
        private void OnUpdPedidoPendienteOperationCompleted(object arg) {
            if ((this.UpdPedidoPendienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdPedidoPendienteCompleted(this, new UpdPedidoPendienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Belcorp.WebServices/MulticatalogoService/GetPedidoEnviado", RequestNamespace="http://Belcorp.WebServices/MulticatalogoService", ResponseNamespace="http://Belcorp.WebServices/MulticatalogoService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pedido[] GetPedidoEnviado(string codigoFuente, string prefijoISOPais, string codigoPerfil, string codigo, string anoCampana) {
            object[] results = this.Invoke("GetPedidoEnviado", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        codigoPerfil,
                        codigo,
                        anoCampana});
            return ((Pedido[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPedidoEnviadoAsync(string codigoFuente, string prefijoISOPais, string codigoPerfil, string codigo, string anoCampana) {
            this.GetPedidoEnviadoAsync(codigoFuente, prefijoISOPais, codigoPerfil, codigo, anoCampana, null);
        }
        
        /// <remarks/>
        public void GetPedidoEnviadoAsync(string codigoFuente, string prefijoISOPais, string codigoPerfil, string codigo, string anoCampana, object userState) {
            if ((this.GetPedidoEnviadoOperationCompleted == null)) {
                this.GetPedidoEnviadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPedidoEnviadoOperationCompleted);
            }
            this.InvokeAsync("GetPedidoEnviado", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        codigoPerfil,
                        codigo,
                        anoCampana}, this.GetPedidoEnviadoOperationCompleted, userState);
        }
        
        private void OnGetPedidoEnviadoOperationCompleted(object arg) {
            if ((this.GetPedidoEnviadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPedidoEnviadoCompleted(this, new GetPedidoEnviadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Belcorp.WebServices/MulticatalogoService/GetPedidoEnviadoDetalle", RequestNamespace="http://Belcorp.WebServices/MulticatalogoService", ResponseNamespace="http://Belcorp.WebServices/MulticatalogoService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PedidoDetalle[] GetPedidoEnviadoDetalle(string codigoFuente, string prefijoISOPais, long idPedido) {
            object[] results = this.Invoke("GetPedidoEnviadoDetalle", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        idPedido});
            return ((PedidoDetalle[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPedidoEnviadoDetalleAsync(string codigoFuente, string prefijoISOPais, long idPedido) {
            this.GetPedidoEnviadoDetalleAsync(codigoFuente, prefijoISOPais, idPedido, null);
        }
        
        /// <remarks/>
        public void GetPedidoEnviadoDetalleAsync(string codigoFuente, string prefijoISOPais, long idPedido, object userState) {
            if ((this.GetPedidoEnviadoDetalleOperationCompleted == null)) {
                this.GetPedidoEnviadoDetalleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPedidoEnviadoDetalleOperationCompleted);
            }
            this.InvokeAsync("GetPedidoEnviadoDetalle", new object[] {
                        codigoFuente,
                        prefijoISOPais,
                        idPedido}, this.GetPedidoEnviadoDetalleOperationCompleted, userState);
        }
        
        private void OnGetPedidoEnviadoDetalleOperationCompleted(object arg) {
            if ((this.GetPedidoEnviadoDetalleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPedidoEnviadoDetalleCompleted(this, new GetPedidoEnviadoDetalleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Belcorp.WebServices/MulticatalogoService")]
    public partial class Catalogo {
        
        private string codigoFuenteField;
        
        private long idCatalogoField;
        
        private long idPaisField;
        
        private long idFuenteField;
        
        private string anoCampanaField;
        
        private string descripcionCatalogoField;
        
        private string documentIDField;
        
        private int ordenField;
        
        private long idMarcaCatalogoField;
        
        private string estadoField;
        
        private string descripcionPaisField;
        
        private string descripcionFuenteField;
        
        private string marcaCatalogoField;
        
        private string descripcionMarcaCatalogoField;
        
        private string skinURLField;
        
        /// <remarks/>
        public string codigoFuente {
            get {
                return this.codigoFuenteField;
            }
            set {
                this.codigoFuenteField = value;
            }
        }
        
        /// <remarks/>
        public long idCatalogo {
            get {
                return this.idCatalogoField;
            }
            set {
                this.idCatalogoField = value;
            }
        }
        
        /// <remarks/>
        public long IdPais {
            get {
                return this.idPaisField;
            }
            set {
                this.idPaisField = value;
            }
        }
        
        /// <remarks/>
        public long IdFuente {
            get {
                return this.idFuenteField;
            }
            set {
                this.idFuenteField = value;
            }
        }
        
        /// <remarks/>
        public string AnoCampana {
            get {
                return this.anoCampanaField;
            }
            set {
                this.anoCampanaField = value;
            }
        }
        
        /// <remarks/>
        public string DescripcionCatalogo {
            get {
                return this.descripcionCatalogoField;
            }
            set {
                this.descripcionCatalogoField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public int orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
            }
        }
        
        /// <remarks/>
        public long IdMarcaCatalogo {
            get {
                return this.idMarcaCatalogoField;
            }
            set {
                this.idMarcaCatalogoField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string DescripcionPais {
            get {
                return this.descripcionPaisField;
            }
            set {
                this.descripcionPaisField = value;
            }
        }
        
        /// <remarks/>
        public string DescripcionFuente {
            get {
                return this.descripcionFuenteField;
            }
            set {
                this.descripcionFuenteField = value;
            }
        }
        
        /// <remarks/>
        public string marcaCatalogo {
            get {
                return this.marcaCatalogoField;
            }
            set {
                this.marcaCatalogoField = value;
            }
        }
        
        /// <remarks/>
        public string DescripcionMarcaCatalogo {
            get {
                return this.descripcionMarcaCatalogoField;
            }
            set {
                this.descripcionMarcaCatalogoField = value;
            }
        }
        
        /// <remarks/>
        public string SkinURL {
            get {
                return this.skinURLField;
            }
            set {
                this.skinURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Belcorp.WebServices/MulticatalogoService")]
    public partial class PedidoDetalle {
        
        private int idPedidoDetalleField;
        
        private string codigoMarcaCatalogoField;
        
        private int cantidadGuardadaField;
        
        private int cantidadSolicitadaField;
        
        private int cantidadAprobadaField;
        
        private decimal totalSolicitadaField;
        
        private decimal totalAprobadaField;
        
        private decimal totalGuardadaField;
        
        private string estadoPedidoField;
        
        private string codigoVentaField;
        
        private string descripcionProductoField;
        
        private decimal precioUnitarioField;
        
        private int factorRepeticionField;
        
        /// <remarks/>
        public int IdPedidoDetalle {
            get {
                return this.idPedidoDetalleField;
            }
            set {
                this.idPedidoDetalleField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoMarcaCatalogo {
            get {
                return this.codigoMarcaCatalogoField;
            }
            set {
                this.codigoMarcaCatalogoField = value;
            }
        }
        
        /// <remarks/>
        public int CantidadGuardada {
            get {
                return this.cantidadGuardadaField;
            }
            set {
                this.cantidadGuardadaField = value;
            }
        }
        
        /// <remarks/>
        public int CantidadSolicitada {
            get {
                return this.cantidadSolicitadaField;
            }
            set {
                this.cantidadSolicitadaField = value;
            }
        }
        
        /// <remarks/>
        public int CantidadAprobada {
            get {
                return this.cantidadAprobadaField;
            }
            set {
                this.cantidadAprobadaField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalSolicitada {
            get {
                return this.totalSolicitadaField;
            }
            set {
                this.totalSolicitadaField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalAprobada {
            get {
                return this.totalAprobadaField;
            }
            set {
                this.totalAprobadaField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalGuardada {
            get {
                return this.totalGuardadaField;
            }
            set {
                this.totalGuardadaField = value;
            }
        }
        
        /// <remarks/>
        public string EstadoPedido {
            get {
                return this.estadoPedidoField;
            }
            set {
                this.estadoPedidoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoVenta {
            get {
                return this.codigoVentaField;
            }
            set {
                this.codigoVentaField = value;
            }
        }
        
        /// <remarks/>
        public string DescripcionProducto {
            get {
                return this.descripcionProductoField;
            }
            set {
                this.descripcionProductoField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrecioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
            }
        }
        
        /// <remarks/>
        public int FactorRepeticion {
            get {
                return this.factorRepeticionField;
            }
            set {
                this.factorRepeticionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Belcorp.WebServices/MulticatalogoService")]
    public partial class Pedido {
        
        private long idPedidoField;
        
        private long idUsuarioField;
        
        private System.DateTime fechaPedidoField;
        
        private string anoCampanaField;
        
        private decimal montoConsolidadoField;
        
        private decimal montoConsolidadoAprobadoField;
        
        private int cantidadProductosSolicitadosField;
        
        private int cantidadProductosAprobadosField;
        
        private string codClientePortalField;
        
        /// <remarks/>
        public long idPedido {
            get {
                return this.idPedidoField;
            }
            set {
                this.idPedidoField = value;
            }
        }
        
        /// <remarks/>
        public long IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaPedido {
            get {
                return this.fechaPedidoField;
            }
            set {
                this.fechaPedidoField = value;
            }
        }
        
        /// <remarks/>
        public string AnoCampana {
            get {
                return this.anoCampanaField;
            }
            set {
                this.anoCampanaField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoConsolidado {
            get {
                return this.montoConsolidadoField;
            }
            set {
                this.montoConsolidadoField = value;
            }
        }
        
        /// <remarks/>
        public decimal MontoConsolidadoAprobado {
            get {
                return this.montoConsolidadoAprobadoField;
            }
            set {
                this.montoConsolidadoAprobadoField = value;
            }
        }
        
        /// <remarks/>
        public int cantidadProductosSolicitados {
            get {
                return this.cantidadProductosSolicitadosField;
            }
            set {
                this.cantidadProductosSolicitadosField = value;
            }
        }
        
        /// <remarks/>
        public int CantidadProductosAprobados {
            get {
                return this.cantidadProductosAprobadosField;
            }
            set {
                this.cantidadProductosAprobadosField = value;
            }
        }
        
        /// <remarks/>
        public string codClientePortal {
            get {
                return this.codClientePortalField;
            }
            set {
                this.codClientePortalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCatalogosPublicadosCompletedEventHandler(object sender, GetCatalogosPublicadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCatalogosPublicadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCatalogosPublicadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Catalogo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Catalogo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetNumeroPedidosPendientesCompletedEventHandler(object sender, GetNumeroPedidosPendientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNumeroPedidosPendientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNumeroPedidosPendientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPedidoPendienteCompletedEventHandler(object sender, GetPedidoPendienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPedidoPendienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPedidoPendienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pedido[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pedido[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPedidoPendienteDetalleCompletedEventHandler(object sender, GetPedidoPendienteDetalleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPedidoPendienteDetalleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPedidoPendienteDetalleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PedidoDetalle[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PedidoDetalle[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPedidoPendienteConsolidadoCompletedEventHandler(object sender, GetPedidoPendienteConsolidadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPedidoPendienteConsolidadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPedidoPendienteConsolidadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PedidoDetalle[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PedidoDetalle[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdPedidoPendienteCompletedEventHandler(object sender, UpdPedidoPendienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdPedidoPendienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdPedidoPendienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPedidoEnviadoCompletedEventHandler(object sender, GetPedidoEnviadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPedidoEnviadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPedidoEnviadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pedido[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pedido[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPedidoEnviadoDetalleCompletedEventHandler(object sender, GetPedidoEnviadoDetalleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPedidoEnviadoDetalleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPedidoEnviadoDetalleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PedidoDetalle[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PedidoDetalle[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591