USE [BelcorpPeru_BPT]
GO

IF EXISTS(
	SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'CONFIGURACIONPAISDETALLE'
	AND C.NAME = 'BloqueoRevistaImpresa'
	)
BEGIN
PRINT 'Removing Column BloqueoRevistaImpresa to ConfiguracionPaisDetalle'
	ALTER TABLE CONFIGURACIONPAISDETALLE DROP CONSTRAINT DF_BloqueoRevistaImpresa_0
	ALTER TABLE CONFIGURACIONPAISDETALLE DROP COLUMN BloqueoRevistaImpresa
END
