USE BelcorpBolivia
GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'LogCargaPedido' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.LogCargaPedido
	DROP COLUMN VersionProl;
END
GO
/*end*/

USE BelcorpChile
GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'LogCargaPedido' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.LogCargaPedido
	DROP COLUMN VersionProl;
END
GO
/*end*/

USE BelcorpColombia
GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'LogCargaPedido' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.LogCargaPedido
	DROP COLUMN VersionProl;
END
GO
/*end*/

USE BelcorpCostaRica
GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'LogCargaPedido' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.LogCargaPedido
	DROP COLUMN VersionProl;
END
GO
/*end*/

USE BelcorpDominicana
GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'LogCargaPedido' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.LogCargaPedido
	DROP COLUMN VersionProl;
END
GO
/*end*/

USE BelcorpEcuador
GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'LogCargaPedido' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.LogCargaPedido
	DROP COLUMN VersionProl;
END
GO
/*end*/

USE BelcorpGuatemala
GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'LogCargaPedido' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.LogCargaPedido
	DROP COLUMN VersionProl;
END
GO
/*end*/

USE BelcorpMexico
GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'LogCargaPedido' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.LogCargaPedido
	DROP COLUMN VersionProl;
END
GO
/*end*/

USE BelcorpPanama
GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'LogCargaPedido' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.LogCargaPedido
	DROP COLUMN VersionProl;
END
GO
/*end*/

USE BelcorpPeru
GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'LogCargaPedido' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.LogCargaPedido
	DROP COLUMN VersionProl;
END
GO
/*end*/

USE BelcorpPuertoRico
GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'LogCargaPedido' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.LogCargaPedido
	DROP COLUMN VersionProl;
END
GO
/*end*/

USE BelcorpSalvador
GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'LogCargaPedido' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.LogCargaPedido
	DROP COLUMN VersionProl;
END
GO