GO
USE BelcorpPeru
GO

IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='MG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'LMG'
	where CODIGO='MG'
END

GO
USE BelcorpMexico
GO

IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='MG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'LMG'
	where CODIGO='MG'
END

GO
USE BelcorpColombia
GO

IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='MG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'LMG'
	where CODIGO='MG'
END

GO
USE BelcorpSalvador
GO

IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='MG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'LMG'
	where CODIGO='MG'
END

GO
USE BelcorpPuertoRico
GO

IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='MG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'LMG'
	where CODIGO='MG'
END

GO
USE BelcorpPanama
GO

IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='MG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'LMG'
	where CODIGO='MG'
END

GO
USE BelcorpGuatemala
GO

IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='MG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'LMG'
	where CODIGO='MG'
END

GO
USE BelcorpEcuador
GO

IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='MG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'LMG'
	where CODIGO='MG'
END

GO
USE BelcorpDominicana
GO

IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='MG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'LMG'
	where CODIGO='MG'
END

GO
USE BelcorpCostaRica
GO

IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='MG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'LMG'
	where CODIGO='MG'
END

GO
USE BelcorpChile
GO

IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='MG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'LMG'
	where CODIGO='MG'
END

GO
USE BelcorpBolivia
GO

IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='MG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'LMG'
	where CODIGO='MG'
END

GO
