USE BelcorpPeru
GO

IF	EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION = 'REVISTA DIGITAL'
	)
BEGIN
	PRINT 'DELETING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	DELETE TL
	FROM TABLALOGICA TL
	WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'
END

USE BelcorpMexico
GO

IF	EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION = 'REVISTA DIGITAL'
	)
BEGIN
	PRINT 'DELETING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	DELETE TL
	FROM TABLALOGICA TL
	WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'
END

USE BelcorpColombia
GO

IF	EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION = 'REVISTA DIGITAL'
	)
BEGIN
	PRINT 'DELETING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	DELETE TL
	FROM TABLALOGICA TL
	WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'
END

USE BelcorpVenezuela
GO

IF	EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION = 'REVISTA DIGITAL'
	)
BEGIN
	PRINT 'DELETING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	DELETE TL
	FROM TABLALOGICA TL
	WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'
END

USE BelcorpSalvador
GO

IF	EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION = 'REVISTA DIGITAL'
	)
BEGIN
	PRINT 'DELETING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	DELETE TL
	FROM TABLALOGICA TL
	WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'
END

USE BelcorpPuertoRico
GO

IF	EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION = 'REVISTA DIGITAL'
	)
BEGIN
	PRINT 'DELETING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	DELETE TL
	FROM TABLALOGICA TL
	WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'
END

USE BelcorpPanama
GO

IF	EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION = 'REVISTA DIGITAL'
	)
BEGIN
	PRINT 'DELETING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	DELETE TL
	FROM TABLALOGICA TL
	WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'
END

USE BelcorpGuatemala
GO

IF	EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION = 'REVISTA DIGITAL'
	)
BEGIN
	PRINT 'DELETING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	DELETE TL
	FROM TABLALOGICA TL
	WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'
END

USE BelcorpEcuador
GO

IF	EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION = 'REVISTA DIGITAL'
	)
BEGIN
	PRINT 'DELETING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	DELETE TL
	FROM TABLALOGICA TL
	WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'
END

USE BelcorpDominicana
GO

IF	EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION = 'REVISTA DIGITAL'
	)
BEGIN
	PRINT 'DELETING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	DELETE TL
	FROM TABLALOGICA TL
	WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'
END

USE BelcorpCostaRica
GO

IF	EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION = 'REVISTA DIGITAL'
	)
BEGIN
	PRINT 'DELETING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	DELETE TL
	FROM TABLALOGICA TL
	WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'
END

USE BelcorpChile
GO

IF	EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION = 'REVISTA DIGITAL'
	)
BEGIN
	PRINT 'DELETING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	DELETE TL
	FROM TABLALOGICA TL
	WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'
END

USE BelcorpBolivia
GO

IF	EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION = 'REVISTA DIGITAL'
	)
BEGIN
	PRINT 'DELETING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	DELETE TL
	FROM TABLALOGICA TL
	WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'
END

