USE  [BelcorpMexico]
GO

IF EXISTS( SELECT * FROM permiso WHERE permisoId = 1071)
BEGIN
	UPDATE RolPermiso SET ACTIVO = 0 WHERE PERMISOID =1071;
	UPDATE RolPermiso SET ACTIVO = 0 WHERE  PERMISOID =1071;
END
GO

IF EXISTS( SELECT * FROM permiso WHERE permisoId = 1072)
BEGIN
	UPDATE RolPermiso SET ACTIVO = 0 WHERE PERMISOID =1072;
	UPDATE RolPermiso SET ACTIVO = 0 WHERE  PERMISOID =1072;
END
GO

IF EXISTS( SELECT * FROM permiso WHERE permisoId = 1073)
BEGIN
	UPDATE RolPermiso SET ACTIVO = 0 WHERE PERMISOID =1073;
	UPDATE RolPermiso SET ACTIVO = 0 WHERE  PERMISOID =1073;
END
GO

IF EXISTS( SELECT * FROM permiso WHERE permisoId = 1074)
BEGIN
	UPDATE RolPermiso SET ACTIVO = 0 WHERE PERMISOID =1074;
	UPDATE RolPermiso SET ACTIVO = 0 WHERE  PERMISOID =1074;
END
GO

DECLARE @ID INT = 0;
IF NOT EXISTS (SELECT * FROM permiso WHERE  descripcion = 'PRIVACIDAD DE DATOS')
BEGIN
	SET @ID = (SELECT COUNT(*)+1 FROM permiso)	
	INSERT INTO Permiso VALUES(@ID ,'PRIVACIDAD DE DATOS',1041,2,'JavaScript/PopUpPrivacidadDatos',0,'Footer',NULL,0,0,0,1,NULL)
	INSERT INTO RolPermiso VALUES (1,@ID,1,1)
END





