
USE BelcorpPeru
GO

DELETE FROM [dbo].[CDRWebDescripcion] 
WHERE EntidadSSIC = 'Observacion' AND Tipo = 'Motivo'
AND CodigoSSIC IN 
('SPVD-50',
'SPVD-32',
'SPVD-18',
'SPVD-45',
'SPVD-63',
'SPVD-64',
'SPVD-65',
'SPVD-69',
'SPVD-8',
'SPVD-9',
'SPVD-62',
'SPVD-23',
'SPVD-22',
'SPVD-60',
'SPVD-13',
'SPVD-14',
'SPVD-15',
'SPVD-5',
'SPVD-12',
'SPVD-7',
'SPVD-3',
'SPVC-1',
'SPVC-11',
'SPVC-12',
'SPVC-14',
'SPVC-15',
'SPVC-16',
'SPVC-17',
'SPVC-18',
'SPVC-19',
'SPVC-2',
'SPVC-20',
'SPVC-3',
'SPVC-4',
'SPVC-5',
'SPVC-6',
'SPVC-7',
'SPVC-8',
'SPVC-9',
'SPVD-1',
'SPVD-2',
'SPVD-33',
'SPVD-52',
'SPVD-47',
'SPVD-35',
'SPVD-6',
'SPVD-67',
'SPVD-76',
'SPVD-56')
GO


INSERT INTO [dbo].[CDRWebDescripcion] 
(CodigoSSIC,EntidadSSIC,Tipo,Descripcion)
VALUES 
('SPVD-50','Observacion','Motivo','El código del producto ingresado figura asociado a otro producto.Contáctanos a través de Chat para evaluar tu caso.'),
('SPVD-31','Observacion','Motivo','El código ingresado no existe o no está disponible para esta campaña.'),
('SPVD-32','Observacion','Motivo','El código ingresado no existe o no ha sido solicitado en este pedido.'),
('SPVD-18','Observacion','Motivo','Elíge un producto de igual o mayor valor (S/.) al producto que deseas cambiar.'),
('SPVD-45','Observacion','Motivo','Motivo inválido, modifícalo.'),
('SPVD-63','Observacion','Motivo','Pedido facturado fuera de fecha, puedes elegir otra solución.'),
('SPVD-64','Observacion','Motivo','Presentas recurrencia en estas solicitudes, Contáctanos a través del chat para evaluar tu caso.'),
('SPVD-65','Observacion','Motivo','Presentas recurrencia en estas solicitudes, Contáctanos a través del chat para evaluar tu caso.'),
('SPVD-69','Observacion','Motivo','Presentas recurrencia en estas solicitudes, Contáctanos a través del chat para evaluar tu caso.'),
('SPVD-8','Observacion','Motivo','Presentas recurrencia en estas solicitudes, Contáctanos a través del chat para evaluar tu caso.'),
('SPVD-9','Observacion','Motivo','Presentas recurrencia en estas solicitudes, Contáctanos a través del chat para evaluar tu caso.'),
('SPVD-62','Observacion','Motivo','Producto de expofertas no disponible para cambios y devoluciones.'),
('SPVD-23','Observacion','Motivo','Producto no disponible para cambios y devoluciones  porque es condición para recibir una bonificación.'),
('SPVD-22','Observacion','Motivo','Producto no disponible para cambios y devoluciones  porque solicitaste su atención en un reclamo anterior. '),
('SPVD-60','Observacion','Motivo','Producto no disponible para cambios y devoluciones  porque solicitaste su atención en un reclamo anterior. '),
('SPVD-13','Observacion','Motivo','Producto no disponible para cambios y devoluciones por este medio, Contáctanos a través del CHAT para evaluar tu caso.'),
('SPVD-14','Observacion','Motivo','Producto no disponible para cambios y devoluciones por este medio, Contáctanos a través del CHAT para evaluar tu caso.'),
('SPVD-15','Observacion','Motivo','Producto no disponible para cambios y devoluciones por este medio, Contáctanos a través del CHAT para evaluar tu caso.'),
('SPVD-5','Observacion','Motivo','Producto no disponible para cambios y devoluciones por este medio, Contáctanos a través del CHAT para evaluar tu caso.'),
('SPVD-12','Observacion','Motivo','Producto no disponible para cambios y devoluciones.'),
('SPVD-7','Observacion','Motivo','Producto no tienes unidades disponibles para su atención'),
('SPVD-3','Observacion','Motivo','Revisa el detalle de tu pedido, el producto no figura registrado en esta campaña.'),
('SPVC-1','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-11','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-12','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-14','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-15','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-16','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-17','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-18','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-19','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-2','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-20','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-3','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-4','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-5','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-6','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-7','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-8','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVC-9','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVD-1','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVD-2','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVD-33','Observacion','Motivo','Revisa los datos ingresados.'),
('SPVD-52','Observacion','Motivo','Solución inválida, modifícala'),
('SPVD-47','Observacion','Motivo','Tu pedido ha sido chequeado al 100%'),
('SPVD-35','Observacion','Motivo','Tu solicitud baja el mínimo permitido para la facturación de tu pedido. Cambia de solución.'),
('SPVD-6','Observacion','Motivo','Tu solicitud se encuentra fuera de fecha para poder ser atendida.'),
('SPVD-67','Observacion','Motivo','Tu solicitud se encuentra fuera de fecha para poder ser atendida.'),
('SPVD-76','Observacion','Motivo','Tu solicitud se encuentra fuera de fecha para poder ser atendida.'),
('SPVD-56','Observacion','Motivo','Ya tienes una operación realizada, Contáctanos a través del Chat para evaluar tu caso.')