USE [BelcorpBolivia]
GO
IF NOT EXISTS(SELECT 1 FROM ROLPERMISO WHERE PERMISOID=(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES'))
BEGIN
	DECLARE @ROLID INT 
	DECLARE @PERMISOID INT 
	SET @ROLID = 1
	SET @PERMISOID = (SELECT P.PERMISOID FROM PERMISO P WITH(NOLOCK) WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES')
	INSERT INTO RolPermiso(RolID, PermisoID, Activo, Mostrar) VALUES(@RolID, @PERMISOID, 0, 1)
END

GO
USE [BelcorpChile]
GO
IF NOT EXISTS(SELECT 1 FROM ROLPERMISO WHERE PERMISOID=(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES'))
BEGIN
	DECLARE @ROLID INT 
	DECLARE @PERMISOID INT 
	SET @ROLID = 1
	SET @PERMISOID = (SELECT P.PERMISOID FROM PERMISO P WITH(NOLOCK) WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES')
	INSERT INTO RolPermiso(RolID, PermisoID, Activo, Mostrar) VALUES(@RolID, @PERMISOID, 0, 1)
END

GO
USE [BelcorpColombia]
GO
IF NOT EXISTS(SELECT 1 FROM ROLPERMISO WHERE PERMISOID=(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES'))
BEGIN
	DECLARE @ROLID INT 
	DECLARE @PERMISOID INT 
	SET @ROLID = 1
	SET @PERMISOID = (SELECT P.PERMISOID FROM PERMISO P WITH(NOLOCK) WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES')
	INSERT INTO RolPermiso(RolID, PermisoID, Activo, Mostrar) VALUES(@RolID, @PERMISOID, 0, 1)
END

GO
USE [BelcorpCostaRica]
GO
IF NOT EXISTS(SELECT 1 FROM ROLPERMISO WHERE PERMISOID=(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES'))
BEGIN
	DECLARE @ROLID INT 
	DECLARE @PERMISOID INT 
	SET @ROLID = 1
	SET @PERMISOID = (SELECT P.PERMISOID FROM PERMISO P WITH(NOLOCK) WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES')
	INSERT INTO RolPermiso(RolID, PermisoID, Activo, Mostrar) VALUES(@RolID, @PERMISOID, 0, 1)
END

GO
USE [BelcorpDominicana]
GO
IF NOT EXISTS(SELECT 1 FROM ROLPERMISO WHERE PERMISOID=(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES'))
BEGIN
	DECLARE @ROLID INT 
	DECLARE @PERMISOID INT 
	SET @ROLID = 1
	SET @PERMISOID = (SELECT P.PERMISOID FROM PERMISO P WITH(NOLOCK) WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES')
	INSERT INTO RolPermiso(RolID, PermisoID, Activo, Mostrar) VALUES(@RolID, @PERMISOID, 0, 1)
END

GO
USE [BelcorpEcuador]
GO
IF NOT EXISTS(SELECT 1 FROM ROLPERMISO WHERE PERMISOID=(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES'))
BEGIN
	DECLARE @ROLID INT 
	DECLARE @PERMISOID INT 
	SET @ROLID = 1
	SET @PERMISOID = (SELECT P.PERMISOID FROM PERMISO P WITH(NOLOCK) WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES')
	INSERT INTO RolPermiso(RolID, PermisoID, Activo, Mostrar) VALUES(@RolID, @PERMISOID, 0, 1)
END

GO
USE [BelcorpGuatemala]
GO
IF NOT EXISTS(SELECT 1 FROM ROLPERMISO WHERE PERMISOID=(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES'))
BEGIN
	DECLARE @ROLID INT 
	DECLARE @PERMISOID INT 
	SET @ROLID = 1
	SET @PERMISOID = (SELECT P.PERMISOID FROM PERMISO P WITH(NOLOCK) WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES')
	INSERT INTO RolPermiso(RolID, PermisoID, Activo, Mostrar) VALUES(@RolID, @PERMISOID, 0, 1)
END

GO
USE [BelcorpMexico]
GO
IF NOT EXISTS(SELECT 1 FROM ROLPERMISO WHERE PERMISOID=(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES'))
BEGIN
	DECLARE @ROLID INT 
	DECLARE @PERMISOID INT 
	SET @ROLID = 1
	SET @PERMISOID = (SELECT P.PERMISOID FROM PERMISO P WITH(NOLOCK) WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES')
	INSERT INTO RolPermiso(RolID, PermisoID, Activo, Mostrar) VALUES(@RolID, @PERMISOID, 0, 1)
END

GO
USE [BelcorpPanama]
GO
IF NOT EXISTS(SELECT 1 FROM ROLPERMISO WHERE PERMISOID=(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES'))
BEGIN
	DECLARE @ROLID INT 
	DECLARE @PERMISOID INT 
	SET @ROLID = 1
	SET @PERMISOID = (SELECT P.PERMISOID FROM PERMISO P WITH(NOLOCK) WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES')
	INSERT INTO RolPermiso(RolID, PermisoID, Activo, Mostrar) VALUES(@RolID, @PERMISOID, 0, 1)
END

GO
USE [BelcorpPeru]
GO
IF NOT EXISTS(SELECT 1 FROM ROLPERMISO WHERE PERMISOID=(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES'))
BEGIN
	DECLARE @ROLID INT 
	DECLARE @PERMISOID INT 
	SET @ROLID = 1
	SET @PERMISOID = (SELECT P.PERMISOID FROM PERMISO P WITH(NOLOCK) WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES')
	INSERT INTO RolPermiso(RolID, PermisoID, Activo, Mostrar) VALUES(@RolID, @PERMISOID, 0, 1)
END

GO
USE [BelcorpPuertoRico]
GO
IF NOT EXISTS(SELECT 1 FROM ROLPERMISO WHERE PERMISOID=(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES'))
BEGIN
	DECLARE @ROLID INT 
	DECLARE @PERMISOID INT 
	SET @ROLID = 1
	SET @PERMISOID = (SELECT P.PERMISOID FROM PERMISO P WITH(NOLOCK) WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES')
	INSERT INTO RolPermiso(RolID, PermisoID, Activo, Mostrar) VALUES(@RolID, @PERMISOID, 0, 1)
END

GO
USE [BelcorpSalvador]
GO
IF NOT EXISTS(SELECT 1 FROM ROLPERMISO WHERE PERMISOID=(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES'))
BEGIN
	DECLARE @ROLID INT 
	DECLARE @PERMISOID INT 
	SET @ROLID = 1
	SET @PERMISOID = (SELECT P.PERMISOID FROM PERMISO P WITH(NOLOCK) WHERE DESCRIPCION = 'FECHAS DE PROMOCIONES')
	INSERT INTO RolPermiso(RolID, PermisoID, Activo, Mostrar) VALUES(@RolID, @PERMISOID, 0, 1)
END

GO
