USE BelcorpBolivia
GO
IF NOT EXISTS (
	SELECT * 
    FROM PERMISO 
    WHERE IDPADRE = 81 AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
) 
BEGIN 
	DECLARE @PERMISOID INT 
	DECLARE @ORDENITEM INT 

	SELECT @PERMISOID = MAX(PERMISOID) + 1 
	FROM   PERMISO 

	SELECT @ORDENITEM = MAX(ORDENITEM) + 1 
	FROM   PERMISO 
	WHERE  PERMISOID IN (SELECT PERMISOID 
						FROM   ROLPERMISO 
						WHERE  ROLID = 3) 
			AND IDPADRE = 81 

	INSERT INTO PERMISO (
		PERMISOID, 
		DESCRIPCION, 
		IDPADRE, 
		ORDENITEM, 
		URLITEM, 
		PAGINANUEVA, 
		POSICION, 
		URLIMAGEN, 
		ESSOLOIMAGEN, 
		ESMENUESPECIAL, 
		ESSERVICIOS, 
		ESPRINCIPAL, 
		CODIGO
	) 
	VALUES(
		@PERMISOID, 
		'ADMINISTRADOR DE ACTUALIZACIÓN DE DATOS', 
		81, 
		@ORDENITEM, 
		'Bienvenida/ReporteValidacionDatos', 
		0, 
		'HEADER', 
		'', 
		0, 
		0, 
		0, 
		0, 
		NULL
	) 

	INSERT INTO ROLPERMISO (ROLID, PERMISOID, ACTIVO, MOSTRAR) 
	VALUES (3, @PERMISOID, 1, 1) 

    PRINT( 'REALIZÒ EL REGISTRO EN BOLIVIA ' ) 
END 
ELSE 
BEGIN 
	PRINT( 'NO SE REALIZÒ EL REGISTRO PORQUE YA EXISTE EL DATO EN BOLIVIA' ) 
END
GO

USE BelcorpChile
GO
IF NOT EXISTS (
	SELECT * 
    FROM PERMISO 
    WHERE IDPADRE = 81 AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
) 
BEGIN 
	DECLARE @PERMISOID INT 
	DECLARE @ORDENITEM INT 

	SELECT @PERMISOID = MAX(PERMISOID) + 1 
	FROM   PERMISO 

	SELECT @ORDENITEM = MAX(ORDENITEM) + 1 
	FROM   PERMISO 
	WHERE  PERMISOID IN (SELECT PERMISOID 
						FROM   ROLPERMISO 
						WHERE  ROLID = 3) 
			AND IDPADRE = 81 

	INSERT INTO PERMISO (
		PERMISOID, 
		DESCRIPCION, 
		IDPADRE, 
		ORDENITEM, 
		URLITEM, 
		PAGINANUEVA, 
		POSICION, 
		URLIMAGEN, 
		ESSOLOIMAGEN, 
		ESMENUESPECIAL, 
		ESSERVICIOS, 
		ESPRINCIPAL, 
		CODIGO
	) 
	VALUES(
		@PERMISOID, 
		'ADMINISTRADOR DE ACTUALIZACIÓN DE DATOS', 
		81, 
		@ORDENITEM, 
		'Bienvenida/ReporteValidacionDatos', 
		0, 
		'HEADER', 
		'', 
		0, 
		0, 
		0, 
		0, 
		NULL
	) 

	INSERT INTO ROLPERMISO (ROLID, PERMISOID, ACTIVO, MOSTRAR) 
	VALUES (3, @PERMISOID, 1, 1) 

    PRINT( 'REALIZÒ EL REGISTRO EN CHILE ' ) 
END 
ELSE 
BEGIN 
	PRINT( 'NO SE REALIZÒ EL REGISTRO PORQUE YA EXISTE EL DATO EN CHILE' ) 
END
GO

USE BelcorpColombia
GO
IF NOT EXISTS (
	SELECT * 
    FROM PERMISO 
    WHERE IDPADRE = 81 AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
) 
BEGIN 
	DECLARE @PERMISOID INT 
	DECLARE @ORDENITEM INT 

	SELECT @PERMISOID = MAX(PERMISOID) + 1 
	FROM   PERMISO 

	SELECT @ORDENITEM = MAX(ORDENITEM) + 1 
	FROM   PERMISO 
	WHERE  PERMISOID IN (SELECT PERMISOID 
						FROM   ROLPERMISO 
						WHERE  ROLID = 3) 
			AND IDPADRE = 81 

	INSERT INTO PERMISO (
		PERMISOID, 
		DESCRIPCION, 
		IDPADRE, 
		ORDENITEM, 
		URLITEM, 
		PAGINANUEVA, 
		POSICION, 
		URLIMAGEN, 
		ESSOLOIMAGEN, 
		ESMENUESPECIAL, 
		ESSERVICIOS, 
		ESPRINCIPAL, 
		CODIGO
	) 
	VALUES(
		@PERMISOID, 
		'ADMINISTRADOR DE ACTUALIZACIÓN DE DATOS', 
		81, 
		@ORDENITEM, 
		'Bienvenida/ReporteValidacionDatos', 
		0, 
		'HEADER', 
		'', 
		0, 
		0, 
		0, 
		0, 
		NULL
	) 

	INSERT INTO ROLPERMISO (ROLID, PERMISOID, ACTIVO, MOSTRAR) 
	VALUES (3, @PERMISOID, 1, 1) 

    PRINT( 'REALIZÒ EL REGISTRO EN COLOMBIA ' ) 
END 
ELSE 
BEGIN 
	PRINT( 'NO SE REALIZÒ EL REGISTRO PORQUE YA EXISTE EL DATO EN COLOMBIA' ) 
END
GO

USE BelcorpCostaRica
GO
IF NOT EXISTS (
	SELECT * 
    FROM PERMISO 
    WHERE IDPADRE = 81 AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
) 
BEGIN 
	DECLARE @PERMISOID INT 
	DECLARE @ORDENITEM INT 

	SELECT @PERMISOID = MAX(PERMISOID) + 1 
	FROM   PERMISO 

	SELECT @ORDENITEM = MAX(ORDENITEM) + 1 
	FROM   PERMISO 
	WHERE  PERMISOID IN (SELECT PERMISOID 
						FROM   ROLPERMISO 
						WHERE  ROLID = 3) 
			AND IDPADRE = 81 

	INSERT INTO PERMISO (
		PERMISOID, 
		DESCRIPCION, 
		IDPADRE, 
		ORDENITEM, 
		URLITEM, 
		PAGINANUEVA, 
		POSICION, 
		URLIMAGEN, 
		ESSOLOIMAGEN, 
		ESMENUESPECIAL, 
		ESSERVICIOS, 
		ESPRINCIPAL, 
		CODIGO
	) 
	VALUES(
		@PERMISOID, 
		'ADMINISTRADOR DE ACTUALIZACIÓN DE DATOS', 
		81, 
		@ORDENITEM, 
		'Bienvenida/ReporteValidacionDatos', 
		0, 
		'HEADER', 
		'', 
		0, 
		0, 
		0, 
		0, 
		NULL
	) 

	INSERT INTO ROLPERMISO (ROLID, PERMISOID, ACTIVO, MOSTRAR) 
	VALUES (3, @PERMISOID, 1, 1) 

    PRINT( 'REALIZÒ EL REGISTRO EN COSTA RICA ' ) 
END 
ELSE 
BEGIN 
	PRINT( 'NO SE REALIZÒ EL REGISTRO PORQUE YA EXISTE EL DATO EN COSTA RICA' ) 
END
GO

USE BelcorpDominicana
GO
IF NOT EXISTS (
	SELECT * 
    FROM PERMISO 
    WHERE IDPADRE = 81 AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
) 
BEGIN 
	DECLARE @PERMISOID INT 
	DECLARE @ORDENITEM INT 

	SELECT @PERMISOID = MAX(PERMISOID) + 1 
	FROM   PERMISO 

	SELECT @ORDENITEM = MAX(ORDENITEM) + 1 
	FROM   PERMISO 
	WHERE  PERMISOID IN (SELECT PERMISOID 
						FROM   ROLPERMISO 
						WHERE  ROLID = 3) 
			AND IDPADRE = 81 

	INSERT INTO PERMISO (
		PERMISOID, 
		DESCRIPCION, 
		IDPADRE, 
		ORDENITEM, 
		URLITEM, 
		PAGINANUEVA, 
		POSICION, 
		URLIMAGEN, 
		ESSOLOIMAGEN, 
		ESMENUESPECIAL, 
		ESSERVICIOS, 
		ESPRINCIPAL, 
		CODIGO
	) 
	VALUES(
		@PERMISOID, 
		'ADMINISTRADOR DE ACTUALIZACIÓN DE DATOS', 
		81, 
		@ORDENITEM, 
		'Bienvenida/ReporteValidacionDatos', 
		0, 
		'HEADER', 
		'', 
		0, 
		0, 
		0, 
		0, 
		NULL
	) 

	INSERT INTO ROLPERMISO (ROLID, PERMISOID, ACTIVO, MOSTRAR) 
	VALUES (3, @PERMISOID, 1, 1) 

    PRINT( 'REALIZÒ EL REGISTRO EN DOMINICANA ' ) 
END 
ELSE 
BEGIN 
	PRINT( 'NO SE REALIZÒ EL REGISTRO PORQUE YA EXISTE EL DATO EN DOMINICANA' ) 
END
GO

USE BelcorpEcuador
GO
IF NOT EXISTS (
	SELECT * 
    FROM PERMISO 
    WHERE IDPADRE = 81 AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
) 
BEGIN 
	DECLARE @PERMISOID INT 
	DECLARE @ORDENITEM INT 

	SELECT @PERMISOID = MAX(PERMISOID) + 1 
	FROM   PERMISO 

	SELECT @ORDENITEM = MAX(ORDENITEM) + 1 
	FROM   PERMISO 
	WHERE  PERMISOID IN (SELECT PERMISOID 
						FROM   ROLPERMISO 
						WHERE  ROLID = 3) 
			AND IDPADRE = 81 

	INSERT INTO PERMISO (
		PERMISOID, 
		DESCRIPCION, 
		IDPADRE, 
		ORDENITEM, 
		URLITEM, 
		PAGINANUEVA, 
		POSICION, 
		URLIMAGEN, 
		ESSOLOIMAGEN, 
		ESMENUESPECIAL, 
		ESSERVICIOS, 
		ESPRINCIPAL, 
		CODIGO
	) 
	VALUES(
		@PERMISOID, 
		'ADMINISTRADOR DE ACTUALIZACIÓN DE DATOS', 
		81, 
		@ORDENITEM, 
		'Bienvenida/ReporteValidacionDatos', 
		0, 
		'HEADER', 
		'', 
		0, 
		0, 
		0, 
		0, 
		NULL
	) 

	INSERT INTO ROLPERMISO (ROLID, PERMISOID, ACTIVO, MOSTRAR) 
	VALUES (3, @PERMISOID, 1, 1) 

    PRINT( 'REALIZÒ EL REGISTRO EN ECUADOR ' ) 
END 
ELSE 
BEGIN 
	PRINT( 'NO SE REALIZÒ EL REGISTRO PORQUE YA EXISTE EL DATO EN ECUADOR' ) 
END
GO

USE BelcorpGuatemala
GO
IF NOT EXISTS (
	SELECT * 
    FROM PERMISO 
    WHERE IDPADRE = 81 AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
) 
BEGIN 
	DECLARE @PERMISOID INT 
	DECLARE @ORDENITEM INT 

	SELECT @PERMISOID = MAX(PERMISOID) + 1 
	FROM   PERMISO 

	SELECT @ORDENITEM = MAX(ORDENITEM) + 1 
	FROM   PERMISO 
	WHERE  PERMISOID IN (SELECT PERMISOID 
						FROM   ROLPERMISO 
						WHERE  ROLID = 3) 
			AND IDPADRE = 81 

	INSERT INTO PERMISO (
		PERMISOID, 
		DESCRIPCION, 
		IDPADRE, 
		ORDENITEM, 
		URLITEM, 
		PAGINANUEVA, 
		POSICION, 
		URLIMAGEN, 
		ESSOLOIMAGEN, 
		ESMENUESPECIAL, 
		ESSERVICIOS, 
		ESPRINCIPAL, 
		CODIGO
	) 
	VALUES(
		@PERMISOID, 
		'ADMINISTRADOR DE ACTUALIZACIÓN DE DATOS', 
		81, 
		@ORDENITEM, 
		'Bienvenida/ReporteValidacionDatos', 
		0, 
		'HEADER', 
		'', 
		0, 
		0, 
		0, 
		0, 
		NULL
	) 

	INSERT INTO ROLPERMISO (ROLID, PERMISOID, ACTIVO, MOSTRAR) 
	VALUES (3, @PERMISOID, 1, 1) 

    PRINT( 'REALIZÒ EL REGISTRO EN GUATEMALA ' ) 
END 
ELSE 
BEGIN 
	PRINT( 'NO SE REALIZÒ EL REGISTRO PORQUE YA EXISTE EL DATO EN GUATEMALA' ) 
END
GO

USE BelcorpMexico
GO
IF NOT EXISTS (
	SELECT * 
    FROM PERMISO 
    WHERE IDPADRE = 81 AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
) 
BEGIN 
	DECLARE @PERMISOID INT 
	DECLARE @ORDENITEM INT 

	SELECT @PERMISOID = MAX(PERMISOID) + 1 
	FROM   PERMISO 

	SELECT @ORDENITEM = MAX(ORDENITEM) + 1 
	FROM   PERMISO 
	WHERE  PERMISOID IN (SELECT PERMISOID 
						FROM   ROLPERMISO 
						WHERE  ROLID = 3) 
			AND IDPADRE = 81 

	INSERT INTO PERMISO (
		PERMISOID, 
		DESCRIPCION, 
		IDPADRE, 
		ORDENITEM, 
		URLITEM, 
		PAGINANUEVA, 
		POSICION, 
		URLIMAGEN, 
		ESSOLOIMAGEN, 
		ESMENUESPECIAL, 
		ESSERVICIOS, 
		ESPRINCIPAL, 
		CODIGO
	) 
	VALUES(
		@PERMISOID, 
		'ADMINISTRADOR DE ACTUALIZACIÓN DE DATOS', 
		81, 
		@ORDENITEM, 
		'Bienvenida/ReporteValidacionDatos', 
		0, 
		'HEADER', 
		'', 
		0, 
		0, 
		0, 
		0, 
		NULL
	) 

	INSERT INTO ROLPERMISO (ROLID, PERMISOID, ACTIVO, MOSTRAR) 
	VALUES (3, @PERMISOID, 1, 1) 

    PRINT( 'REALIZÒ EL REGISTRO EN MEXICO ' ) 
END 
ELSE 
BEGIN 
	PRINT( 'NO SE REALIZÒ EL REGISTRO PORQUE YA EXISTE EL DATO EN MEXICO' ) 
END
GO

USE BelcorpPanama
GO
IF NOT EXISTS (
	SELECT * 
    FROM PERMISO 
    WHERE IDPADRE = 81 AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
) 
BEGIN 
	DECLARE @PERMISOID INT 
	DECLARE @ORDENITEM INT 

	SELECT @PERMISOID = MAX(PERMISOID) + 1 
	FROM   PERMISO 

	SELECT @ORDENITEM = MAX(ORDENITEM) + 1 
	FROM   PERMISO 
	WHERE  PERMISOID IN (SELECT PERMISOID 
						FROM   ROLPERMISO 
						WHERE  ROLID = 3) 
			AND IDPADRE = 81 

	INSERT INTO PERMISO (
		PERMISOID, 
		DESCRIPCION, 
		IDPADRE, 
		ORDENITEM, 
		URLITEM, 
		PAGINANUEVA, 
		POSICION, 
		URLIMAGEN, 
		ESSOLOIMAGEN, 
		ESMENUESPECIAL, 
		ESSERVICIOS, 
		ESPRINCIPAL, 
		CODIGO
	) 
	VALUES(
		@PERMISOID, 
		'ADMINISTRADOR DE ACTUALIZACIÓN DE DATOS', 
		81, 
		@ORDENITEM, 
		'Bienvenida/ReporteValidacionDatos', 
		0, 
		'HEADER', 
		'', 
		0, 
		0, 
		0, 
		0, 
		NULL
	) 

	INSERT INTO ROLPERMISO (ROLID, PERMISOID, ACTIVO, MOSTRAR) 
	VALUES (3, @PERMISOID, 1, 1) 

    PRINT( 'REALIZÒ EL REGISTRO EN PANAMA ' ) 
END 
ELSE 
BEGIN 
	PRINT( 'NO SE REALIZÒ EL REGISTRO PORQUE YA EXISTE EL DATO EN PANAMA' ) 
END
GO

USE BelcorpPeru
GO
IF NOT EXISTS (
	SELECT * 
    FROM PERMISO 
    WHERE IDPADRE = 81 AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
) 
BEGIN 
	DECLARE @PERMISOID INT 
	DECLARE @ORDENITEM INT 

	SELECT @PERMISOID = MAX(PERMISOID) + 1 
	FROM   PERMISO 

	SELECT @ORDENITEM = MAX(ORDENITEM) + 1 
	FROM   PERMISO 
	WHERE  PERMISOID IN (SELECT PERMISOID 
						FROM   ROLPERMISO 
						WHERE  ROLID = 3) 
			AND IDPADRE = 81 

	INSERT INTO PERMISO (
		PERMISOID, 
		DESCRIPCION, 
		IDPADRE, 
		ORDENITEM, 
		URLITEM, 
		PAGINANUEVA, 
		POSICION, 
		URLIMAGEN, 
		ESSOLOIMAGEN, 
		ESMENUESPECIAL, 
		ESSERVICIOS, 
		ESPRINCIPAL, 
		CODIGO
	) 
	VALUES(
		@PERMISOID, 
		'ADMINISTRADOR DE ACTUALIZACIÓN DE DATOS', 
		81, 
		@ORDENITEM, 
		'Bienvenida/ReporteValidacionDatos', 
		0, 
		'HEADER', 
		'', 
		0, 
		0, 
		0, 
		0, 
		NULL
	) 

	INSERT INTO ROLPERMISO (ROLID, PERMISOID, ACTIVO, MOSTRAR) 
	VALUES (3, @PERMISOID, 1, 1) 

    PRINT( 'REALIZÒ EL REGISTRO EN PERU ' ) 
END 
ELSE 
BEGIN 
	PRINT( 'NO SE REALIZÒ EL REGISTRO PORQUE YA EXISTE EL DATO EN PERU' ) 
END
GO

USE BelcorpPuertoRico
GO
IF NOT EXISTS (
	SELECT * 
    FROM PERMISO 
    WHERE IDPADRE = 81 AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
) 
BEGIN 
	DECLARE @PERMISOID INT 
	DECLARE @ORDENITEM INT 

	SELECT @PERMISOID = MAX(PERMISOID) + 1 
	FROM   PERMISO 

	SELECT @ORDENITEM = MAX(ORDENITEM) + 1 
	FROM   PERMISO 
	WHERE  PERMISOID IN (SELECT PERMISOID 
						FROM   ROLPERMISO 
						WHERE  ROLID = 3) 
			AND IDPADRE = 81 

	INSERT INTO PERMISO (
		PERMISOID, 
		DESCRIPCION, 
		IDPADRE, 
		ORDENITEM, 
		URLITEM, 
		PAGINANUEVA, 
		POSICION, 
		URLIMAGEN, 
		ESSOLOIMAGEN, 
		ESMENUESPECIAL, 
		ESSERVICIOS, 
		ESPRINCIPAL, 
		CODIGO
	) 
	VALUES(
		@PERMISOID, 
		'ADMINISTRADOR DE ACTUALIZACIÓN DE DATOS', 
		81, 
		@ORDENITEM, 
		'Bienvenida/ReporteValidacionDatos', 
		0, 
		'HEADER', 
		'', 
		0, 
		0, 
		0, 
		0, 
		NULL
	) 

	INSERT INTO ROLPERMISO (ROLID, PERMISOID, ACTIVO, MOSTRAR) 
	VALUES (3, @PERMISOID, 1, 1) 

    PRINT( 'REALIZÒ EL REGISTRO EN PUERTO RICO ' ) 
END 
ELSE 
BEGIN 
	PRINT( 'NO SE REALIZÒ EL REGISTRO PORQUE YA EXISTE EL DATO EN PUERTO RICO' ) 
END
GO

USE BelcorpSalvador
GO
IF NOT EXISTS (
	SELECT * 
    FROM PERMISO 
    WHERE IDPADRE = 81 AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
) 
BEGIN 
	DECLARE @PERMISOID INT 
	DECLARE @ORDENITEM INT 

	SELECT @PERMISOID = MAX(PERMISOID) + 1 
	FROM   PERMISO 

	SELECT @ORDENITEM = MAX(ORDENITEM) + 1 
	FROM   PERMISO 
	WHERE  PERMISOID IN (SELECT PERMISOID 
						FROM   ROLPERMISO 
						WHERE  ROLID = 3) 
			AND IDPADRE = 81 

	INSERT INTO PERMISO (
		PERMISOID, 
		DESCRIPCION, 
		IDPADRE, 
		ORDENITEM, 
		URLITEM, 
		PAGINANUEVA, 
		POSICION, 
		URLIMAGEN, 
		ESSOLOIMAGEN, 
		ESMENUESPECIAL, 
		ESSERVICIOS, 
		ESPRINCIPAL, 
		CODIGO
	) 
	VALUES(
		@PERMISOID, 
		'ADMINISTRADOR DE ACTUALIZACIÓN DE DATOS', 
		81, 
		@ORDENITEM, 
		'Bienvenida/ReporteValidacionDatos', 
		0, 
		'HEADER', 
		'', 
		0, 
		0, 
		0, 
		0, 
		NULL
	) 

	INSERT INTO ROLPERMISO (ROLID, PERMISOID, ACTIVO, MOSTRAR) 
	VALUES (3, @PERMISOID, 1, 1) 

    PRINT( 'REALIZÒ EL REGISTRO EN SALVADOR ' ) 
END 
ELSE 
BEGIN 
	PRINT( 'NO SE REALIZÒ EL REGISTRO PORQUE YA EXISTE EL DATO EN SALVADOR' ) 
END
GO