USE BelcorpBolivia
GO
IF EXISTS (SELECT * 
           FROM   SYS.OBJECTS 
           WHERE  OBJECT_ID = OBJECT_ID(N'[DBO].[GetActualizarValidacionDatos]') 
                  AND TYPE IN ( N'P', N'PC' )) 
  DROP PROCEDURE [DBO].[GetActualizarValidacionDatos]
GO
/* 
CREADO POR  : PAQUIRRI SEPERAK 
FECHA :    28/03/2019 
DESCRIPCIÓN : ACTUALIZA LA IP EL DISPOSITIVO CON EL QUE SE ESTÁ TRABAJANDO 
*/ 
CREATE PROCEDURE GetActualizarValidacionDatos
	@ISMOBILE         BIT, 
	@CODIGOCONSULTORA VARCHAR(32), 
	@IPDISPOSITIVO    VARCHAR(32), 
	@CODIGOUSUARIO    VARCHAR(32), 
	@TIPOENVIO1       VARCHAR(32), 
	@TIPOENVIO2       VARCHAR(32) 
AS 
BEGIN 
    IF ( @TIPOENVIO1 = 'TODO' ) 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE(), 
                DISPOSITIVO = @ISMOBILE 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
    END 
    ELSE 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                DISPOSITIVO = @ISMOBILE, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE() 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
                AND TIPOENVIO IN ( @TIPOENVIO1, @TIPOENVIO2 ) 
    END 
END
GO 

USE BelcorpChile
GO
IF EXISTS (SELECT * 
           FROM   SYS.OBJECTS 
           WHERE  OBJECT_ID = OBJECT_ID(N'[DBO].[GetActualizarValidacionDatos]') 
                  AND TYPE IN ( N'P', N'PC' )) 
  DROP PROCEDURE [DBO].[GetActualizarValidacionDatos]
GO
/* 
CREADO POR  : PAQUIRRI SEPERAK 
FECHA :    28/03/2019 
DESCRIPCIÓN : ACTUALIZA LA IP EL DISPOSITIVO CON EL QUE SE ESTÁ TRABAJANDO 
*/ 
CREATE PROCEDURE GetActualizarValidacionDatos
	@ISMOBILE         BIT, 
	@CODIGOCONSULTORA VARCHAR(32), 
	@IPDISPOSITIVO    VARCHAR(32), 
	@CODIGOUSUARIO    VARCHAR(32), 
	@TIPOENVIO1       VARCHAR(32), 
	@TIPOENVIO2       VARCHAR(32) 
AS 
BEGIN 
    IF ( @TIPOENVIO1 = 'TODO' ) 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE(), 
                DISPOSITIVO = @ISMOBILE 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
    END 
    ELSE 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                DISPOSITIVO = @ISMOBILE, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE() 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
                AND TIPOENVIO IN ( @TIPOENVIO1, @TIPOENVIO2 ) 
    END 
END
GO 

USE BelcorpColombia
GO
IF EXISTS (SELECT * 
           FROM   SYS.OBJECTS 
           WHERE  OBJECT_ID = OBJECT_ID(N'[DBO].[GetActualizarValidacionDatos]') 
                  AND TYPE IN ( N'P', N'PC' )) 
  DROP PROCEDURE [DBO].[GetActualizarValidacionDatos]
GO
/* 
CREADO POR  : PAQUIRRI SEPERAK 
FECHA :    28/03/2019 
DESCRIPCIÓN : ACTUALIZA LA IP EL DISPOSITIVO CON EL QUE SE ESTÁ TRABAJANDO 
*/ 
CREATE PROCEDURE GetActualizarValidacionDatos
	@ISMOBILE         BIT, 
	@CODIGOCONSULTORA VARCHAR(32), 
	@IPDISPOSITIVO    VARCHAR(32), 
	@CODIGOUSUARIO    VARCHAR(32), 
	@TIPOENVIO1       VARCHAR(32), 
	@TIPOENVIO2       VARCHAR(32) 
AS 
BEGIN 
    IF ( @TIPOENVIO1 = 'TODO' ) 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE(), 
                DISPOSITIVO = @ISMOBILE 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
    END 
    ELSE 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                DISPOSITIVO = @ISMOBILE, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE() 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
                AND TIPOENVIO IN ( @TIPOENVIO1, @TIPOENVIO2 ) 
    END 
END
GO 

USE BelcorpCostaRica
GO
IF EXISTS (SELECT * 
           FROM   SYS.OBJECTS 
           WHERE  OBJECT_ID = OBJECT_ID(N'[DBO].[GetActualizarValidacionDatos]') 
                  AND TYPE IN ( N'P', N'PC' )) 
  DROP PROCEDURE [DBO].[GetActualizarValidacionDatos]
GO
/* 
CREADO POR  : PAQUIRRI SEPERAK 
FECHA :    28/03/2019 
DESCRIPCIÓN : ACTUALIZA LA IP EL DISPOSITIVO CON EL QUE SE ESTÁ TRABAJANDO 
*/ 
CREATE PROCEDURE GetActualizarValidacionDatos
	@ISMOBILE         BIT, 
	@CODIGOCONSULTORA VARCHAR(32), 
	@IPDISPOSITIVO    VARCHAR(32), 
	@CODIGOUSUARIO    VARCHAR(32), 
	@TIPOENVIO1       VARCHAR(32), 
	@TIPOENVIO2       VARCHAR(32) 
AS 
BEGIN 
    IF ( @TIPOENVIO1 = 'TODO' ) 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE(), 
                DISPOSITIVO = @ISMOBILE 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
    END 
    ELSE 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                DISPOSITIVO = @ISMOBILE, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE() 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
                AND TIPOENVIO IN ( @TIPOENVIO1, @TIPOENVIO2 ) 
    END 
END
GO 

USE BelcorpDominicana
GO
IF EXISTS (SELECT * 
           FROM   SYS.OBJECTS 
           WHERE  OBJECT_ID = OBJECT_ID(N'[DBO].[GetActualizarValidacionDatos]') 
                  AND TYPE IN ( N'P', N'PC' )) 
  DROP PROCEDURE [DBO].[GetActualizarValidacionDatos]
GO
/* 
CREADO POR  : PAQUIRRI SEPERAK 
FECHA :    28/03/2019 
DESCRIPCIÓN : ACTUALIZA LA IP EL DISPOSITIVO CON EL QUE SE ESTÁ TRABAJANDO 
*/ 
CREATE PROCEDURE GetActualizarValidacionDatos
	@ISMOBILE         BIT, 
	@CODIGOCONSULTORA VARCHAR(32), 
	@IPDISPOSITIVO    VARCHAR(32), 
	@CODIGOUSUARIO    VARCHAR(32), 
	@TIPOENVIO1       VARCHAR(32), 
	@TIPOENVIO2       VARCHAR(32) 
AS 
BEGIN 
    IF ( @TIPOENVIO1 = 'TODO' ) 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE(), 
                DISPOSITIVO = @ISMOBILE 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
    END 
    ELSE 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                DISPOSITIVO = @ISMOBILE, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE() 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
                AND TIPOENVIO IN ( @TIPOENVIO1, @TIPOENVIO2 ) 
    END 
END
GO 

USE BelcorpEcuador
GO
IF EXISTS (SELECT * 
           FROM   SYS.OBJECTS 
           WHERE  OBJECT_ID = OBJECT_ID(N'[DBO].[GetActualizarValidacionDatos]') 
                  AND TYPE IN ( N'P', N'PC' )) 
  DROP PROCEDURE [DBO].[GetActualizarValidacionDatos]
GO
/* 
CREADO POR  : PAQUIRRI SEPERAK 
FECHA :    28/03/2019 
DESCRIPCIÓN : ACTUALIZA LA IP EL DISPOSITIVO CON EL QUE SE ESTÁ TRABAJANDO 
*/ 
CREATE PROCEDURE GetActualizarValidacionDatos
	@ISMOBILE         BIT, 
	@CODIGOCONSULTORA VARCHAR(32), 
	@IPDISPOSITIVO    VARCHAR(32), 
	@CODIGOUSUARIO    VARCHAR(32), 
	@TIPOENVIO1       VARCHAR(32), 
	@TIPOENVIO2       VARCHAR(32) 
AS 
BEGIN 
    IF ( @TIPOENVIO1 = 'TODO' ) 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE(), 
                DISPOSITIVO = @ISMOBILE 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
    END 
    ELSE 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                DISPOSITIVO = @ISMOBILE, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE() 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
                AND TIPOENVIO IN ( @TIPOENVIO1, @TIPOENVIO2 ) 
    END 
END
GO 

USE BelcorpGuatemala
GO
IF EXISTS (SELECT * 
           FROM   SYS.OBJECTS 
           WHERE  OBJECT_ID = OBJECT_ID(N'[DBO].[GetActualizarValidacionDatos]') 
                  AND TYPE IN ( N'P', N'PC' )) 
  DROP PROCEDURE [DBO].[GetActualizarValidacionDatos]
GO
/* 
CREADO POR  : PAQUIRRI SEPERAK 
FECHA :    28/03/2019 
DESCRIPCIÓN : ACTUALIZA LA IP EL DISPOSITIVO CON EL QUE SE ESTÁ TRABAJANDO 
*/ 
CREATE PROCEDURE GetActualizarValidacionDatos
	@ISMOBILE         BIT, 
	@CODIGOCONSULTORA VARCHAR(32), 
	@IPDISPOSITIVO    VARCHAR(32), 
	@CODIGOUSUARIO    VARCHAR(32), 
	@TIPOENVIO1       VARCHAR(32), 
	@TIPOENVIO2       VARCHAR(32) 
AS 
BEGIN 
    IF ( @TIPOENVIO1 = 'TODO' ) 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE(), 
                DISPOSITIVO = @ISMOBILE 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
    END 
    ELSE 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                DISPOSITIVO = @ISMOBILE, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE() 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
                AND TIPOENVIO IN ( @TIPOENVIO1, @TIPOENVIO2 ) 
    END 
END
GO 

USE BelcorpMexico
GO
IF EXISTS (SELECT * 
           FROM   SYS.OBJECTS 
           WHERE  OBJECT_ID = OBJECT_ID(N'[DBO].[GetActualizarValidacionDatos]') 
                  AND TYPE IN ( N'P', N'PC' )) 
  DROP PROCEDURE [DBO].[GetActualizarValidacionDatos]
GO
/* 
CREADO POR  : PAQUIRRI SEPERAK 
FECHA :    28/03/2019 
DESCRIPCIÓN : ACTUALIZA LA IP EL DISPOSITIVO CON EL QUE SE ESTÁ TRABAJANDO 
*/ 
CREATE PROCEDURE GetActualizarValidacionDatos
	@ISMOBILE         BIT, 
	@CODIGOCONSULTORA VARCHAR(32), 
	@IPDISPOSITIVO    VARCHAR(32), 
	@CODIGOUSUARIO    VARCHAR(32), 
	@TIPOENVIO1       VARCHAR(32), 
	@TIPOENVIO2       VARCHAR(32) 
AS 
BEGIN 
    IF ( @TIPOENVIO1 = 'TODO' ) 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE(), 
                DISPOSITIVO = @ISMOBILE 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
    END 
    ELSE 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                DISPOSITIVO = @ISMOBILE, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE() 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
                AND TIPOENVIO IN ( @TIPOENVIO1, @TIPOENVIO2 ) 
    END 
END
GO 

USE BelcorpPanama
GO
IF EXISTS (SELECT * 
           FROM   SYS.OBJECTS 
           WHERE  OBJECT_ID = OBJECT_ID(N'[DBO].[GetActualizarValidacionDatos]') 
                  AND TYPE IN ( N'P', N'PC' )) 
  DROP PROCEDURE [DBO].[GetActualizarValidacionDatos]
GO
/* 
CREADO POR  : PAQUIRRI SEPERAK 
FECHA :    28/03/2019 
DESCRIPCIÓN : ACTUALIZA LA IP EL DISPOSITIVO CON EL QUE SE ESTÁ TRABAJANDO 
*/ 
CREATE PROCEDURE GetActualizarValidacionDatos
	@ISMOBILE         BIT, 
	@CODIGOCONSULTORA VARCHAR(32), 
	@IPDISPOSITIVO    VARCHAR(32), 
	@CODIGOUSUARIO    VARCHAR(32), 
	@TIPOENVIO1       VARCHAR(32), 
	@TIPOENVIO2       VARCHAR(32) 
AS 
BEGIN 
    IF ( @TIPOENVIO1 = 'TODO' ) 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE(), 
                DISPOSITIVO = @ISMOBILE 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
    END 
    ELSE 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                DISPOSITIVO = @ISMOBILE, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE() 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
                AND TIPOENVIO IN ( @TIPOENVIO1, @TIPOENVIO2 ) 
    END 
END
GO 

USE BelcorpPeru
GO
IF EXISTS (SELECT * 
           FROM   SYS.OBJECTS 
           WHERE  OBJECT_ID = OBJECT_ID(N'[DBO].[GetActualizarValidacionDatos]') 
                  AND TYPE IN ( N'P', N'PC' )) 
  DROP PROCEDURE [DBO].[GetActualizarValidacionDatos]
GO
/* 
CREADO POR  : PAQUIRRI SEPERAK 
FECHA :    28/03/2019 
DESCRIPCIÓN : ACTUALIZA LA IP EL DISPOSITIVO CON EL QUE SE ESTÁ TRABAJANDO 
*/ 
CREATE PROCEDURE GetActualizarValidacionDatos
	@ISMOBILE         BIT, 
	@CODIGOCONSULTORA VARCHAR(32), 
	@IPDISPOSITIVO    VARCHAR(32), 
	@CODIGOUSUARIO    VARCHAR(32), 
	@TIPOENVIO1       VARCHAR(32), 
	@TIPOENVIO2       VARCHAR(32) 
AS 
BEGIN 
    IF ( @TIPOENVIO1 = 'TODO' ) 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE(), 
                DISPOSITIVO = @ISMOBILE 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
    END 
    ELSE 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                DISPOSITIVO = @ISMOBILE, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE() 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
                AND TIPOENVIO IN ( @TIPOENVIO1, @TIPOENVIO2 ) 
    END 
END
GO 

USE BelcorpPuertoRico
GO
IF EXISTS (SELECT * 
           FROM   SYS.OBJECTS 
           WHERE  OBJECT_ID = OBJECT_ID(N'[DBO].[GetActualizarValidacionDatos]') 
                  AND TYPE IN ( N'P', N'PC' )) 
  DROP PROCEDURE [DBO].[GetActualizarValidacionDatos]
GO
/* 
CREADO POR  : PAQUIRRI SEPERAK 
FECHA :    28/03/2019 
DESCRIPCIÓN : ACTUALIZA LA IP EL DISPOSITIVO CON EL QUE SE ESTÁ TRABAJANDO 
*/ 
CREATE PROCEDURE GetActualizarValidacionDatos
	@ISMOBILE         BIT, 
	@CODIGOCONSULTORA VARCHAR(32), 
	@IPDISPOSITIVO    VARCHAR(32), 
	@CODIGOUSUARIO    VARCHAR(32), 
	@TIPOENVIO1       VARCHAR(32), 
	@TIPOENVIO2       VARCHAR(32) 
AS 
BEGIN 
    IF ( @TIPOENVIO1 = 'TODO' ) 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE(), 
                DISPOSITIVO = @ISMOBILE 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
    END 
    ELSE 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                DISPOSITIVO = @ISMOBILE, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE() 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
                AND TIPOENVIO IN ( @TIPOENVIO1, @TIPOENVIO2 ) 
    END 
END
GO 

USE BelcorpSalvador
GO
IF EXISTS (SELECT * 
           FROM   SYS.OBJECTS 
           WHERE  OBJECT_ID = OBJECT_ID(N'[DBO].[GetActualizarValidacionDatos]') 
                  AND TYPE IN ( N'P', N'PC' )) 
  DROP PROCEDURE [DBO].[GetActualizarValidacionDatos]
GO
/* 
CREADO POR  : PAQUIRRI SEPERAK 
FECHA :    28/03/2019 
DESCRIPCIÓN : ACTUALIZA LA IP EL DISPOSITIVO CON EL QUE SE ESTÁ TRABAJANDO 
*/ 
CREATE PROCEDURE GetActualizarValidacionDatos
	@ISMOBILE         BIT, 
	@CODIGOCONSULTORA VARCHAR(32), 
	@IPDISPOSITIVO    VARCHAR(32), 
	@CODIGOUSUARIO    VARCHAR(32), 
	@TIPOENVIO1       VARCHAR(32), 
	@TIPOENVIO2       VARCHAR(32) 
AS 
BEGIN 
    IF ( @TIPOENVIO1 = 'TODO' ) 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE(), 
                DISPOSITIVO = @ISMOBILE 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
    END 
    ELSE 
    BEGIN 
        UPDATE VALIDACIONDATOS 
        SET    IPDISPOSITIVO = @IPDISPOSITIVO, 
                DISPOSITIVO = @ISMOBILE, 
                USUARIOMODIFICACION = @CODIGOCONSULTORA, 
                FECHAMODIFICACION = GETDATE() 
        WHERE  CODIGOUSUARIO = @CODIGOCONSULTORA 
                AND TIPOENVIO IN ( @TIPOENVIO1, @TIPOENVIO2 ) 
    END 
END
GO 