//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
// 
#pragma warning disable 1591

namespace Portal.Consultoras.Web.ServicesCalculosPROL {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicesCalculoPrecioNivelesSoap", Namespace="http://tempuri.org/")]
    public partial class ServicesCalculoPrecioNiveles : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CalculoOfertasNivelesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculoMontosProlOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicesCalculoPrecioNiveles() {
            this.Url = global::Portal.Consultoras.Web.Properties.Settings.Default.Portal_Consultoras_Web_ServicesCalculosPROL_ServicesCalculoPrecioNiveles;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CalculoOfertasNivelesCompletedEventHandler CalculoOfertasNivelesCompleted;
        
        /// <remarks/>
        public event CalculoMontosProlCompletedEventHandler CalculoMontosProlCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculoOfertasNiveles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ObjProductosNiveles[] CalculoOfertasNiveles(string pais, string periodo, string codigoconsultora, string zona, System.Data.DataTable lstProductos) {
            object[] results = this.Invoke("CalculoOfertasNiveles", new object[] {
                        pais,
                        periodo,
                        codigoconsultora,
                        zona,
                        lstProductos});
            return ((ObjProductosNiveles[])(results[0]));
        }
        
        /// <remarks/>
        public void CalculoOfertasNivelesAsync(string pais, string periodo, string codigoconsultora, string zona, System.Data.DataTable lstProductos) {
            this.CalculoOfertasNivelesAsync(pais, periodo, codigoconsultora, zona, lstProductos, null);
        }
        
        /// <remarks/>
        public void CalculoOfertasNivelesAsync(string pais, string periodo, string codigoconsultora, string zona, System.Data.DataTable lstProductos, object userState) {
            if ((this.CalculoOfertasNivelesOperationCompleted == null)) {
                this.CalculoOfertasNivelesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculoOfertasNivelesOperationCompleted);
            }
            this.InvokeAsync("CalculoOfertasNiveles", new object[] {
                        pais,
                        periodo,
                        codigoconsultora,
                        zona,
                        lstProductos}, this.CalculoOfertasNivelesOperationCompleted, userState);
        }
        
        private void OnCalculoOfertasNivelesOperationCompleted(object arg) {
            if ((this.CalculoOfertasNivelesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculoOfertasNivelesCompleted(this, new CalculoOfertasNivelesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculoMontosProl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ObjMontosProl[] CalculoMontosProl(string pais, string periodo, string codigoconsultora, string zona, System.Data.DataTable lstProductos) {
            object[] results = this.Invoke("CalculoMontosProl", new object[] {
                        pais,
                        periodo,
                        codigoconsultora,
                        zona,
                        lstProductos});
            return ((ObjMontosProl[])(results[0]));
        }
        
        /// <remarks/>
        public void CalculoMontosProlAsync(string pais, string periodo, string codigoconsultora, string zona, System.Data.DataTable lstProductos) {
            this.CalculoMontosProlAsync(pais, periodo, codigoconsultora, zona, lstProductos, null);
        }
        
        /// <remarks/>
        public void CalculoMontosProlAsync(string pais, string periodo, string codigoconsultora, string zona, System.Data.DataTable lstProductos, object userState) {
            if ((this.CalculoMontosProlOperationCompleted == null)) {
                this.CalculoMontosProlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculoMontosProlOperationCompleted);
            }
            this.InvokeAsync("CalculoMontosProl", new object[] {
                        pais,
                        periodo,
                        codigoconsultora,
                        zona,
                        lstProductos}, this.CalculoMontosProlOperationCompleted, userState);
        }
        
        private void OnCalculoMontosProlOperationCompleted(object arg) {
            if ((this.CalculoMontosProlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculoMontosProlCompleted(this, new CalculoMontosProlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjProductosNiveles {
        
        private string cuvField;
        
        private string idnivelField;
        
        private decimal precioField;
        
        /// <comentarios/>
        public string cuv {
            get {
                return this.cuvField;
            }
            set {
                this.cuvField = value;
            }
        }
        
        /// <comentarios/>
        public string idnivel {
            get {
                return this.idnivelField;
            }
            set {
                this.idnivelField = value;
            }
        }
        
        /// <comentarios/>
        public decimal precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjMontosProl {
        
        private string montoTotalDescuentoField;
        
        private string montoEscalaField;
        
        /// <comentarios/>
        public string MontoTotalDescuento {
            get {
                return this.montoTotalDescuentoField;
            }
            set {
                this.montoTotalDescuentoField = value;
            }
        }
        
        /// <comentarios/>
        public string MontoEscala {
            get {
                return this.montoEscalaField;
            }
            set {
                this.montoEscalaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CalculoOfertasNivelesCompletedEventHandler(object sender, CalculoOfertasNivelesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculoOfertasNivelesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculoOfertasNivelesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ObjProductosNiveles[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ObjProductosNiveles[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CalculoMontosProlCompletedEventHandler(object sender, CalculoMontosProlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculoMontosProlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculoMontosProlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ObjMontosProl[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ObjMontosProl[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591