USE [BelcorpBolivia];
GO
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[EliminarArchivoCsv]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].EliminarArchivoCsv
GO

CREATE PROCEDURE dbo.EliminarArchivoCsv 
@COMUNICADOID INT 
AS 
  BEGIN 
      DECLARE @SEGMENTACIONID INT 

      SELECT @SEGMENTACIONID = SEGMENTACIONID 
      FROM   COMUNICADO 
      WHERE  COMUNICADOID = @COMUNICADOID 

      UPDATE COMUNICADO 
      SET    NOMBREARCHIVOCCV = NULL, 
             SEGMENTACIONCONSULTORA = NULL, 
             SEGMENTACIONREGIONZONA = NULL, 
             SEGMENTACIONESTADOACTIVIDAD = NULL,
			 SEGMENTACIONID=NULL
      WHERE  COMUNICADOID = @COMUNICADOID 

      DELETE FROM SEGMENTACIONCOMUNICADO 
      WHERE  SEGMENTACIONID = @SEGMENTACIONID 
  END 
GO
USE [BelcorpChile];
GO
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[EliminarArchivoCsv]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].EliminarArchivoCsv
GO

CREATE PROCEDURE dbo.EliminarArchivoCsv 
@COMUNICADOID INT 
AS 
  BEGIN 
      DECLARE @SEGMENTACIONID INT 

      SELECT @SEGMENTACIONID = SEGMENTACIONID 
      FROM   COMUNICADO 
      WHERE  COMUNICADOID = @COMUNICADOID 

      UPDATE COMUNICADO 
      SET    NOMBREARCHIVOCCV = NULL, 
             SEGMENTACIONCONSULTORA = NULL, 
             SEGMENTACIONREGIONZONA = NULL, 
             SEGMENTACIONESTADOACTIVIDAD = NULL,
			 SEGMENTACIONID=NULL
      WHERE  COMUNICADOID = @COMUNICADOID 

      DELETE FROM SEGMENTACIONCOMUNICADO 
      WHERE  SEGMENTACIONID = @SEGMENTACIONID 
  END 
GO
USE [BelcorpColombia];
GO
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[EliminarArchivoCsv]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].EliminarArchivoCsv
GO

CREATE PROCEDURE dbo.EliminarArchivoCsv 
@COMUNICADOID INT 
AS 
  BEGIN 
      DECLARE @SEGMENTACIONID INT 

      SELECT @SEGMENTACIONID = SEGMENTACIONID 
      FROM   COMUNICADO 
      WHERE  COMUNICADOID = @COMUNICADOID 

      UPDATE COMUNICADO 
      SET    NOMBREARCHIVOCCV = NULL, 
             SEGMENTACIONCONSULTORA = NULL, 
             SEGMENTACIONREGIONZONA = NULL, 
             SEGMENTACIONESTADOACTIVIDAD = NULL,
			 SEGMENTACIONID=NULL
      WHERE  COMUNICADOID = @COMUNICADOID 

      DELETE FROM SEGMENTACIONCOMUNICADO 
      WHERE  SEGMENTACIONID = @SEGMENTACIONID 
  END 
GO
USE [BelcorpCostaRica];
GO
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[EliminarArchivoCsv]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].EliminarArchivoCsv
GO

CREATE PROCEDURE dbo.EliminarArchivoCsv 
@COMUNICADOID INT 
AS 
  BEGIN 
      DECLARE @SEGMENTACIONID INT 

      SELECT @SEGMENTACIONID = SEGMENTACIONID 
      FROM   COMUNICADO 
      WHERE  COMUNICADOID = @COMUNICADOID 

      UPDATE COMUNICADO 
      SET    NOMBREARCHIVOCCV = NULL, 
             SEGMENTACIONCONSULTORA = NULL, 
             SEGMENTACIONREGIONZONA = NULL, 
             SEGMENTACIONESTADOACTIVIDAD = NULL,
			 SEGMENTACIONID=NULL
      WHERE  COMUNICADOID = @COMUNICADOID 

      DELETE FROM SEGMENTACIONCOMUNICADO 
      WHERE  SEGMENTACIONID = @SEGMENTACIONID 
  END 
GO
USE [BelcorpDominicana];
GO
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[EliminarArchivoCsv]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].EliminarArchivoCsv
GO

CREATE PROCEDURE dbo.EliminarArchivoCsv 
@COMUNICADOID INT 
AS 
  BEGIN 
      DECLARE @SEGMENTACIONID INT 

      SELECT @SEGMENTACIONID = SEGMENTACIONID 
      FROM   COMUNICADO 
      WHERE  COMUNICADOID = @COMUNICADOID 

      UPDATE COMUNICADO 
      SET    NOMBREARCHIVOCCV = NULL, 
             SEGMENTACIONCONSULTORA = NULL, 
             SEGMENTACIONREGIONZONA = NULL, 
             SEGMENTACIONESTADOACTIVIDAD = NULL,
			 SEGMENTACIONID=NULL
      WHERE  COMUNICADOID = @COMUNICADOID 

      DELETE FROM SEGMENTACIONCOMUNICADO 
      WHERE  SEGMENTACIONID = @SEGMENTACIONID 
  END 
GO
USE [BelcorpEcuador];
GO
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[EliminarArchivoCsv]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].EliminarArchivoCsv
GO

CREATE PROCEDURE dbo.EliminarArchivoCsv 
@COMUNICADOID INT 
AS 
  BEGIN 
      DECLARE @SEGMENTACIONID INT 

      SELECT @SEGMENTACIONID = SEGMENTACIONID 
      FROM   COMUNICADO 
      WHERE  COMUNICADOID = @COMUNICADOID 

      UPDATE COMUNICADO 
      SET    NOMBREARCHIVOCCV = NULL, 
             SEGMENTACIONCONSULTORA = NULL, 
             SEGMENTACIONREGIONZONA = NULL, 
             SEGMENTACIONESTADOACTIVIDAD = NULL,
			 SEGMENTACIONID=NULL
      WHERE  COMUNICADOID = @COMUNICADOID 

      DELETE FROM SEGMENTACIONCOMUNICADO 
      WHERE  SEGMENTACIONID = @SEGMENTACIONID 
  END 
GO
USE [BelcorpGuatemala];
GO
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[EliminarArchivoCsv]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].EliminarArchivoCsv
GO

CREATE PROCEDURE dbo.EliminarArchivoCsv 
@COMUNICADOID INT 
AS 
  BEGIN 
      DECLARE @SEGMENTACIONID INT 

      SELECT @SEGMENTACIONID = SEGMENTACIONID 
      FROM   COMUNICADO 
      WHERE  COMUNICADOID = @COMUNICADOID 

      UPDATE COMUNICADO 
      SET    NOMBREARCHIVOCCV = NULL, 
             SEGMENTACIONCONSULTORA = NULL, 
             SEGMENTACIONREGIONZONA = NULL, 
             SEGMENTACIONESTADOACTIVIDAD = NULL,
			 SEGMENTACIONID=NULL
      WHERE  COMUNICADOID = @COMUNICADOID 

      DELETE FROM SEGMENTACIONCOMUNICADO 
      WHERE  SEGMENTACIONID = @SEGMENTACIONID 
  END 
GO
USE [BelcorpMexico];
GO
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[EliminarArchivoCsv]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].EliminarArchivoCsv
GO

CREATE PROCEDURE dbo.EliminarArchivoCsv 
@COMUNICADOID INT 
AS 
  BEGIN 
      DECLARE @SEGMENTACIONID INT 

      SELECT @SEGMENTACIONID = SEGMENTACIONID 
      FROM   COMUNICADO 
      WHERE  COMUNICADOID = @COMUNICADOID 

      UPDATE COMUNICADO 
      SET    NOMBREARCHIVOCCV = NULL, 
             SEGMENTACIONCONSULTORA = NULL, 
             SEGMENTACIONREGIONZONA = NULL, 
             SEGMENTACIONESTADOACTIVIDAD = NULL,
			 SEGMENTACIONID=NULL
      WHERE  COMUNICADOID = @COMUNICADOID 

      DELETE FROM SEGMENTACIONCOMUNICADO 
      WHERE  SEGMENTACIONID = @SEGMENTACIONID 
  END 
GO
USE [BelcorpPanama];
GO
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[EliminarArchivoCsv]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].EliminarArchivoCsv
GO

CREATE PROCEDURE dbo.EliminarArchivoCsv 
@COMUNICADOID INT 
AS 
  BEGIN 
      DECLARE @SEGMENTACIONID INT 

      SELECT @SEGMENTACIONID = SEGMENTACIONID 
      FROM   COMUNICADO 
      WHERE  COMUNICADOID = @COMUNICADOID 

      UPDATE COMUNICADO 
      SET    NOMBREARCHIVOCCV = NULL, 
             SEGMENTACIONCONSULTORA = NULL, 
             SEGMENTACIONREGIONZONA = NULL, 
             SEGMENTACIONESTADOACTIVIDAD = NULL,
			 SEGMENTACIONID=NULL
      WHERE  COMUNICADOID = @COMUNICADOID 

      DELETE FROM SEGMENTACIONCOMUNICADO 
      WHERE  SEGMENTACIONID = @SEGMENTACIONID 
  END 
GO
USE [BelcorpPeru];
GO
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[EliminarArchivoCsv]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].EliminarArchivoCsv
GO

CREATE PROCEDURE dbo.EliminarArchivoCsv 
@COMUNICADOID INT 
AS 
  BEGIN 
      DECLARE @SEGMENTACIONID INT 

      SELECT @SEGMENTACIONID = SEGMENTACIONID 
      FROM   COMUNICADO 
      WHERE  COMUNICADOID = @COMUNICADOID 

      UPDATE COMUNICADO 
      SET    NOMBREARCHIVOCCV = NULL, 
             SEGMENTACIONCONSULTORA = NULL, 
             SEGMENTACIONREGIONZONA = NULL, 
             SEGMENTACIONESTADOACTIVIDAD = NULL,
			 SEGMENTACIONID=NULL
      WHERE  COMUNICADOID = @COMUNICADOID 

      DELETE FROM SEGMENTACIONCOMUNICADO 
      WHERE  SEGMENTACIONID = @SEGMENTACIONID 
  END 
GO
USE [BelcorpPuertoRico];
GO
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[EliminarArchivoCsv]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].EliminarArchivoCsv
GO

CREATE PROCEDURE dbo.EliminarArchivoCsv 
@COMUNICADOID INT 
AS 
  BEGIN 
      DECLARE @SEGMENTACIONID INT 

      SELECT @SEGMENTACIONID = SEGMENTACIONID 
      FROM   COMUNICADO 
      WHERE  COMUNICADOID = @COMUNICADOID 

      UPDATE COMUNICADO 
      SET    NOMBREARCHIVOCCV = NULL, 
             SEGMENTACIONCONSULTORA = NULL, 
             SEGMENTACIONREGIONZONA = NULL, 
             SEGMENTACIONESTADOACTIVIDAD = NULL,
			 SEGMENTACIONID=NULL
      WHERE  COMUNICADOID = @COMUNICADOID 

      DELETE FROM SEGMENTACIONCOMUNICADO 
      WHERE  SEGMENTACIONID = @SEGMENTACIONID 
  END 
GO
USE [BelcorpSalvador];
GO
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[EliminarArchivoCsv]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].EliminarArchivoCsv
GO

CREATE PROCEDURE dbo.EliminarArchivoCsv 
@COMUNICADOID INT 
AS 
  BEGIN 
      DECLARE @SEGMENTACIONID INT 

      SELECT @SEGMENTACIONID = SEGMENTACIONID 
      FROM   COMUNICADO 
      WHERE  COMUNICADOID = @COMUNICADOID 

      UPDATE COMUNICADO 
      SET    NOMBREARCHIVOCCV = NULL, 
             SEGMENTACIONCONSULTORA = NULL, 
             SEGMENTACIONREGIONZONA = NULL, 
             SEGMENTACIONESTADOACTIVIDAD = NULL,
			 SEGMENTACIONID=NULL
      WHERE  COMUNICADOID = @COMUNICADOID 

      DELETE FROM SEGMENTACIONCOMUNICADO 
      WHERE  SEGMENTACIONID = @SEGMENTACIONID 
  END 
GO
