//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Consultoras.Web.ValidacionesUnete {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RfcParameter", Namespace="http://schemas.datacontract.org/2004/07/CORP.BEL.Unete.SI.ServiceContract.Inputs")]
    [System.SerializableAttribute()]
    public partial class RfcParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnioNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnioNacimiento {
            get {
                return this.AnioNacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.AnioNacimientoField, value) != true)) {
                    this.AnioNacimientoField = value;
                    this.RaisePropertyChanged("AnioNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaNacimiento {
            get {
                return this.DiaNacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaNacimientoField, value) != true)) {
                    this.DiaNacimientoField = value;
                    this.RaisePropertyChanged("DiaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MesNacimiento {
            get {
                return this.MesNacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.MesNacimientoField, value) != true)) {
                    this.MesNacimientoField = value;
                    this.RaisePropertyChanged("MesNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RfcResponse", Namespace="http://schemas.datacontract.org/2004/07/CORP.BEL.Unete.SI.ServiceContract.Outputs" +
        "")]
    [System.SerializableAttribute()]
    public partial class RfcResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RfcNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RfcNumber {
            get {
                return this.RfcNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RfcNumberField, value) != true)) {
                    this.RfcNumberField = value;
                    this.RaisePropertyChanged("RfcNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailParameter", Namespace="http://schemas.datacontract.org/2004/07/CORP.BEL.Unete.SI.ServiceContract.Inputs")]
    [System.SerializableAttribute()]
    public partial class EmailParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoIsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoSeccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactoUneteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoPostulanteField;
              
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EvaluacionCrediticiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Portal.Consultoras.Web.ValidacionesUnete.EnumsMarca MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParametroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TieneExperienciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Portal.Consultoras.Web.ValidacionesUnete.EnumsTipoEmail TipoEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlSiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoIso {
            get {
                return this.CodigoIsoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoIsoField, value) != true)) {
                    this.CodigoIsoField = value;
                    this.RaisePropertyChanged("CodigoIso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSeccion {
            get {
                return this.CodigoSeccionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoSeccionField, value) != true)) {
                    this.CodigoSeccionField = value;
                    this.RaisePropertyChanged("CodigoSeccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactoUnete {
            get {
                return this.ContactoUneteField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactoUneteField, value) != true)) {
                    this.ContactoUneteField = value;
                    this.RaisePropertyChanged("ContactoUnete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronicoPostulante {
            get {
                return this.CorreoElectronicoPostulanteField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoPostulanteField, value) != true)) {
                    this.CorreoElectronicoPostulanteField = value;
                    this.RaisePropertyChanged("CorreoElectronicoPostulante");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((object.ReferenceEquals(this.EdadField, value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }

        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EvaluacionCrediticia {
            get {
                return this.EvaluacionCrediticiaField;
            }
            set {
                if ((object.ReferenceEquals(this.EvaluacionCrediticiaField, value) != true)) {
                    this.EvaluacionCrediticiaField = value;
                    this.RaisePropertyChanged("EvaluacionCrediticia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaNacimientoField, value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Portal.Consultoras.Web.ValidacionesUnete.EnumsMarca Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((this.MarcaField.Equals(value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDestinatario {
            get {
                return this.NombreDestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDestinatarioField, value) != true)) {
                    this.NombreDestinatarioField = value;
                    this.RaisePropertyChanged("NombreDestinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parametro {
            get {
                return this.ParametroField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametroField, value) != true)) {
                    this.ParametroField = value;
                    this.RaisePropertyChanged("Parametro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TieneExperiencia {
            get {
                return this.TieneExperienciaField;
            }
            set {
                if ((object.ReferenceEquals(this.TieneExperienciaField, value) != true)) {
                    this.TieneExperienciaField = value;
                    this.RaisePropertyChanged("TieneExperiencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Portal.Consultoras.Web.ValidacionesUnete.EnumsTipoEmail TipoEmail {
            get {
                return this.TipoEmailField;
            }
            set {
                if ((this.TipoEmailField.Equals(value) != true)) {
                    this.TipoEmailField = value;
                    this.RaisePropertyChanged("TipoEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoMensaje {
            get {
                return this.TipoMensajeField;
            }
            set {
                if ((this.TipoMensajeField.Equals(value) != true)) {
                    this.TipoMensajeField = value;
                    this.RaisePropertyChanged("TipoMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlSite {
            get {
                return this.UrlSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlSiteField, value) != true)) {
                    this.UrlSiteField = value;
                    this.RaisePropertyChanged("UrlSite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.Marca", Namespace="http://schemas.datacontract.org/2004/07/CORP.BEL.Unete.Utils")]
    public enum EnumsMarca : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ninguna = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Esika = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lbel = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.TipoEmail", Namespace="http://schemas.datacontract.org/2004/07/CORP.BEL.Unete.Utils")]
    public enum EnumsTipoEmail : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rechazo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Confirmacion = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotificacionGz = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotificacionSe = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RechazoBuro = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValidacionesUnete.IValidacionesUnete")]
    public interface IValidacionesUnete {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacionesUnete/ConstruirRfc", ReplyAction="http://tempuri.org/IValidacionesUnete/ConstruirRfcResponse")]
        Portal.Consultoras.Web.ValidacionesUnete.RfcResponse ConstruirRfc(Portal.Consultoras.Web.ValidacionesUnete.RfcParameter parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacionesUnete/ConstruirRfc", ReplyAction="http://tempuri.org/IValidacionesUnete/ConstruirRfcResponse")]
        System.Threading.Tasks.Task<Portal.Consultoras.Web.ValidacionesUnete.RfcResponse> ConstruirRfcAsync(Portal.Consultoras.Web.ValidacionesUnete.RfcParameter parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacionesUnete/EnviarEmail", ReplyAction="http://tempuri.org/IValidacionesUnete/EnviarEmailResponse")]
        void EnviarEmail(Portal.Consultoras.Web.ValidacionesUnete.EmailParameter parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacionesUnete/EnviarEmail", ReplyAction="http://tempuri.org/IValidacionesUnete/EnviarEmailResponse")]
        System.Threading.Tasks.Task EnviarEmailAsync(Portal.Consultoras.Web.ValidacionesUnete.EmailParameter parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacionesUnete/ValidarCedulaEcuador", ReplyAction="http://tempuri.org/IValidacionesUnete/ValidarCedulaEcuadorResponse")]
        bool ValidarCedulaEcuador(string numeroDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacionesUnete/ValidarCedulaEcuador", ReplyAction="http://tempuri.org/IValidacionesUnete/ValidarCedulaEcuadorResponse")]
        System.Threading.Tasks.Task<bool> ValidarCedulaEcuadorAsync(string numeroDocumento);
      
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValidacionesUneteChannel : Portal.Consultoras.Web.ValidacionesUnete.IValidacionesUnete, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidacionesUneteClient : System.ServiceModel.ClientBase<Portal.Consultoras.Web.ValidacionesUnete.IValidacionesUnete>, Portal.Consultoras.Web.ValidacionesUnete.IValidacionesUnete {
        
        public ValidacionesUneteClient() {
        }
        
        public ValidacionesUneteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidacionesUneteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidacionesUneteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidacionesUneteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Portal.Consultoras.Web.ValidacionesUnete.RfcResponse ConstruirRfc(Portal.Consultoras.Web.ValidacionesUnete.RfcParameter parametro) {
            return base.Channel.ConstruirRfc(parametro);
        }
        
        public System.Threading.Tasks.Task<Portal.Consultoras.Web.ValidacionesUnete.RfcResponse> ConstruirRfcAsync(Portal.Consultoras.Web.ValidacionesUnete.RfcParameter parametro) {
            return base.Channel.ConstruirRfcAsync(parametro);
        }
        
        public void EnviarEmail(Portal.Consultoras.Web.ValidacionesUnete.EmailParameter parametro) {
            base.Channel.EnviarEmail(parametro);
        }
        
        public System.Threading.Tasks.Task EnviarEmailAsync(Portal.Consultoras.Web.ValidacionesUnete.EmailParameter parametro) {
            return base.Channel.EnviarEmailAsync(parametro);
        }
        
        public bool ValidarCedulaEcuador(string numeroDocumento) {
            return base.Channel.ValidarCedulaEcuador(numeroDocumento);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarCedulaEcuadorAsync(string numeroDocumento) {
            return base.Channel.ValidarCedulaEcuadorAsync(numeroDocumento);
        }
        
    }
}
