USE BelcorpPeru
GO

DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0

SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = TL.TABLALOGICAID
FROM TABLALOGICA TL
WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'

IF	EXISTS(
	SELECT TLD.*
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
	)
BEGIN
	PRINT 'DELETING TABLALOGICADATOS ''Catálogos'''

	DELETE TLD
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
END

USE BelcorpMexico
GO

DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0

SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = TL.TABLALOGICAID
FROM TABLALOGICA TL
WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'

IF	EXISTS(
	SELECT TLD.*
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
	)
BEGIN
	PRINT 'DELETING TABLALOGICADATOS ''Catálogos'''

	DELETE TLD
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
END

USE BelcorpColombia
GO

DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0

SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = TL.TABLALOGICAID
FROM TABLALOGICA TL
WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'

IF	EXISTS(
	SELECT TLD.*
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
	)
BEGIN
	PRINT 'DELETING TABLALOGICADATOS ''Catálogos'''

	DELETE TLD
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
END

USE BelcorpVenezuela
GO

DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0

SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = TL.TABLALOGICAID
FROM TABLALOGICA TL
WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'

IF	EXISTS(
	SELECT TLD.*
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
	)
BEGIN
	PRINT 'DELETING TABLALOGICADATOS ''Catálogos'''

	DELETE TLD
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
END

USE BelcorpSalvador
GO

DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0

SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = TL.TABLALOGICAID
FROM TABLALOGICA TL
WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'

IF	EXISTS(
	SELECT TLD.*
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
	)
BEGIN
	PRINT 'DELETING TABLALOGICADATOS ''Catálogos'''

	DELETE TLD
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
END

USE BelcorpPuertoRico
GO

DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0

SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = TL.TABLALOGICAID
FROM TABLALOGICA TL
WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'

IF	EXISTS(
	SELECT TLD.*
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
	)
BEGIN
	PRINT 'DELETING TABLALOGICADATOS ''Catálogos'''

	DELETE TLD
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
END

USE BelcorpPanama
GO

DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0

SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = TL.TABLALOGICAID
FROM TABLALOGICA TL
WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'

IF	EXISTS(
	SELECT TLD.*
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
	)
BEGIN
	PRINT 'DELETING TABLALOGICADATOS ''Catálogos'''

	DELETE TLD
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
END

USE BelcorpGuatemala
GO

DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0

SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = TL.TABLALOGICAID
FROM TABLALOGICA TL
WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'

IF	EXISTS(
	SELECT TLD.*
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
	)
BEGIN
	PRINT 'DELETING TABLALOGICADATOS ''Catálogos'''

	DELETE TLD
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
END

USE BelcorpEcuador
GO

DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0

SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = TL.TABLALOGICAID
FROM TABLALOGICA TL
WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'

IF	EXISTS(
	SELECT TLD.*
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
	)
BEGIN
	PRINT 'DELETING TABLALOGICADATOS ''Catálogos'''

	DELETE TLD
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
END

USE BelcorpDominicana
GO

DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0

SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = TL.TABLALOGICAID
FROM TABLALOGICA TL
WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'

IF	EXISTS(
	SELECT TLD.*
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
	)
BEGIN
	PRINT 'DELETING TABLALOGICADATOS ''Catálogos'''

	DELETE TLD
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
END

USE BelcorpCostaRica
GO

DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0

SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = TL.TABLALOGICAID
FROM TABLALOGICA TL
WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'

IF	EXISTS(
	SELECT TLD.*
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
	)
BEGIN
	PRINT 'DELETING TABLALOGICADATOS ''Catálogos'''

	DELETE TLD
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
END

USE BelcorpChile
GO

DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0

SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = TL.TABLALOGICAID
FROM TABLALOGICA TL
WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'

IF	EXISTS(
	SELECT TLD.*
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
	)
BEGIN
	PRINT 'DELETING TABLALOGICADATOS ''Catálogos'''

	DELETE TLD
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
END

USE BelcorpBolivia
GO

DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0

SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = TL.TABLALOGICAID
FROM TABLALOGICA TL
WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'

IF	EXISTS(
	SELECT TLD.*
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
	)
BEGIN
	PRINT 'DELETING TABLALOGICADATOS ''Catálogos'''

	DELETE TLD
	FROM TABLALOGICADATOS TLD
	WHERE TABLALOGICAID = @ID_TABLA_LOGICA_REVISTA_DIGITAL
	AND CODIGO = 'Catálogos'
END

