USE [BelcorpPeru_BPT]
GO

IF	EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION = 'REVISTA DIGITAL'
	)
BEGIN
	PRINT 'DELETING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	DELETE TL
	FROM TABLALOGICA TL
	WHERE TL.DESCRIPCION = 'REVISTA DIGITAL'
END