USE BelcorpPeru
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortal')
	ALTER TABLE dbo.LogIngresoPortal DROP COLUMN Canal
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortalError')
	ALTER TABLE dbo.LogIngresoPortalError DROP COLUMN Canal
GO

USE BelcorpMexico
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortal')
	ALTER TABLE dbo.LogIngresoPortal DROP COLUMN Canal
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortalError')
	ALTER TABLE dbo.LogIngresoPortalError DROP COLUMN Canal
GO

USE BelcorpColombia
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortal')
	ALTER TABLE dbo.LogIngresoPortal DROP COLUMN Canal
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortalError')
	ALTER TABLE dbo.LogIngresoPortalError DROP COLUMN Canal
GO

USE BelcorpVenezuela
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortal')
	ALTER TABLE dbo.LogIngresoPortal DROP COLUMN Canal
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortalError')
	ALTER TABLE dbo.LogIngresoPortalError DROP COLUMN Canal
GO

USE BelcorpSalvador
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortal')
	ALTER TABLE dbo.LogIngresoPortal DROP COLUMN Canal
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortalError')
	ALTER TABLE dbo.LogIngresoPortalError DROP COLUMN Canal
GO

USE BelcorpPuertoRico
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortal')
	ALTER TABLE dbo.LogIngresoPortal DROP COLUMN Canal
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortalError')
	ALTER TABLE dbo.LogIngresoPortalError DROP COLUMN Canal
GO

USE BelcorpPanama
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortal')
	ALTER TABLE dbo.LogIngresoPortal DROP COLUMN Canal
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortalError')
	ALTER TABLE dbo.LogIngresoPortalError DROP COLUMN Canal
GO

USE BelcorpGuatemala
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortal')
	ALTER TABLE dbo.LogIngresoPortal DROP COLUMN Canal
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortalError')
	ALTER TABLE dbo.LogIngresoPortalError DROP COLUMN Canal
GO

USE BelcorpEcuador
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortal')
	ALTER TABLE dbo.LogIngresoPortal DROP COLUMN Canal
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortalError')
	ALTER TABLE dbo.LogIngresoPortalError DROP COLUMN Canal
GO

USE BelcorpDominicana
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortal')
	ALTER TABLE dbo.LogIngresoPortal DROP COLUMN Canal
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortalError')
	ALTER TABLE dbo.LogIngresoPortalError DROP COLUMN Canal
GO

USE BelcorpCostaRica
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortal')
	ALTER TABLE dbo.LogIngresoPortal DROP COLUMN Canal
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortalError')
	ALTER TABLE dbo.LogIngresoPortalError DROP COLUMN Canal
GO

USE BelcorpChile
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortal')
	ALTER TABLE dbo.LogIngresoPortal DROP COLUMN Canal
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortalError')
	ALTER TABLE dbo.LogIngresoPortalError DROP COLUMN Canal
GO

USE BelcorpBolivia
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortal')
	ALTER TABLE dbo.LogIngresoPortal DROP COLUMN Canal
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Canal' AND TABLE_NAME = 'LogIngresoPortalError')
	ALTER TABLE dbo.LogIngresoPortalError DROP COLUMN Canal
GO

