USE BelcorpPeru
GO

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Campania'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Campania
END
ALTER TABLE ContenidoAppDeta
  ADD Campania INT;

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Region'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Region
END
ALTER TABLE ContenidoAppDeta
  ADD Region VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Zona'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Zona
END
ALTER TABLE ContenidoAppDeta
  ADD Zona VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Seccion'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Seccion
END
ALTER TABLE ContenidoAppDeta
  ADD Seccion VARCHAR(50);

GO

USE BelcorpMexico
GO

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Campania'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Campania
END
ALTER TABLE ContenidoAppDeta
  ADD Campania INT;

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Region'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Region
END
ALTER TABLE ContenidoAppDeta
  ADD Region VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Zona'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Zona
END
ALTER TABLE ContenidoAppDeta
  ADD Zona VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Seccion'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Seccion
END
ALTER TABLE ContenidoAppDeta
  ADD Seccion VARCHAR(50);

GO

USE BelcorpColombia
GO

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Campania'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Campania
END
ALTER TABLE ContenidoAppDeta
  ADD Campania INT;

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Region'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Region
END
ALTER TABLE ContenidoAppDeta
  ADD Region VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Zona'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Zona
END
ALTER TABLE ContenidoAppDeta
  ADD Zona VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Seccion'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Seccion
END
ALTER TABLE ContenidoAppDeta
  ADD Seccion VARCHAR(50);

GO

USE BelcorpSalvador
GO

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Campania'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Campania
END
ALTER TABLE ContenidoAppDeta
  ADD Campania INT;

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Region'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Region
END
ALTER TABLE ContenidoAppDeta
  ADD Region VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Zona'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Zona
END
ALTER TABLE ContenidoAppDeta
  ADD Zona VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Seccion'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Seccion
END
ALTER TABLE ContenidoAppDeta
  ADD Seccion VARCHAR(50);

GO

USE BelcorpPuertoRico
GO

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Campania'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Campania
END
ALTER TABLE ContenidoAppDeta
  ADD Campania INT;

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Region'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Region
END
ALTER TABLE ContenidoAppDeta
  ADD Region VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Zona'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Zona
END
ALTER TABLE ContenidoAppDeta
  ADD Zona VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Seccion'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Seccion
END
ALTER TABLE ContenidoAppDeta
  ADD Seccion VARCHAR(50);

GO

USE BelcorpPanama
GO

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Campania'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Campania
END
ALTER TABLE ContenidoAppDeta
  ADD Campania INT;

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Region'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Region
END
ALTER TABLE ContenidoAppDeta
  ADD Region VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Zona'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Zona
END
ALTER TABLE ContenidoAppDeta
  ADD Zona VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Seccion'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Seccion
END
ALTER TABLE ContenidoAppDeta
  ADD Seccion VARCHAR(50);

GO

USE BelcorpGuatemala
GO

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Campania'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Campania
END
ALTER TABLE ContenidoAppDeta
  ADD Campania INT;

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Region'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Region
END
ALTER TABLE ContenidoAppDeta
  ADD Region VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Zona'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Zona
END
ALTER TABLE ContenidoAppDeta
  ADD Zona VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Seccion'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Seccion
END
ALTER TABLE ContenidoAppDeta
  ADD Seccion VARCHAR(50);

GO

USE BelcorpEcuador
GO

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Campania'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Campania
END
ALTER TABLE ContenidoAppDeta
  ADD Campania INT;

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Region'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Region
END
ALTER TABLE ContenidoAppDeta
  ADD Region VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Zona'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Zona
END
ALTER TABLE ContenidoAppDeta
  ADD Zona VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Seccion'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Seccion
END
ALTER TABLE ContenidoAppDeta
  ADD Seccion VARCHAR(50);

GO

USE BelcorpDominicana
GO

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Campania'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Campania
END
ALTER TABLE ContenidoAppDeta
  ADD Campania INT;

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Region'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Region
END
ALTER TABLE ContenidoAppDeta
  ADD Region VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Zona'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Zona
END
ALTER TABLE ContenidoAppDeta
  ADD Zona VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Seccion'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Seccion
END
ALTER TABLE ContenidoAppDeta
  ADD Seccion VARCHAR(50);

GO

USE BelcorpCostaRica
GO

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Campania'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Campania
END
ALTER TABLE ContenidoAppDeta
  ADD Campania INT;

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Region'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Region
END
ALTER TABLE ContenidoAppDeta
  ADD Region VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Zona'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Zona
END
ALTER TABLE ContenidoAppDeta
  ADD Zona VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Seccion'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Seccion
END
ALTER TABLE ContenidoAppDeta
  ADD Seccion VARCHAR(50);

GO

USE BelcorpChile
GO

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Campania'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Campania
END
ALTER TABLE ContenidoAppDeta
  ADD Campania INT;

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Region'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Region
END
ALTER TABLE ContenidoAppDeta
  ADD Region VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Zona'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Zona
END
ALTER TABLE ContenidoAppDeta
  ADD Zona VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Seccion'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Seccion
END
ALTER TABLE ContenidoAppDeta
  ADD Seccion VARCHAR(50);

GO

USE BelcorpBolivia
GO

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Campania'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Campania
END
ALTER TABLE ContenidoAppDeta
  ADD Campania INT;

IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Region'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Region
END
ALTER TABLE ContenidoAppDeta
  ADD Region VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Zona'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Zona
END
ALTER TABLE ContenidoAppDeta
  ADD Zona VARCHAR(50);


IF(EXISTS(SELECT * FROM SYS.COLUMNS C JOIN SYS.OBJECTS  O ON C.[OBJECT_ID] = O.[OBJECT_ID] WHERE  O.TYPE = 'U' AND O.NAME = 'ContenidoAppDeta' AND C.NAME = 'Seccion'))
BEGIN 
	ALTER TABLE ContenidoAppDeta
	DROP COLUMN Seccion
END
ALTER TABLE ContenidoAppDeta
  ADD Seccion VARCHAR(50);

GO