//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Consultoras.Web.ServiceOferta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEShowRoomOferta", Namespace="http://schemas.datacontract.org/2004/07/Portal.Consultoras.Entities.ShowRoom")]
    [System.SerializableAttribute()]
    public partial class BEShowRoomOferta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CampaniaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadIncrementaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoCampaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoEstrategiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTipoOfertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConfiguracionOfertaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionLegalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsSubCampaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FlagAgotadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FlagHabilitarProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FlagRevistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISOPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenMiniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IncrementaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MarcaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NroOrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OfertaShowRoomIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioOfertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioValorizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TieneVariedadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipNegocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoOfertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoOfertaSisIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnidadesPermitidasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioRegistroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUV {
            get {
                return this.CUVField;
            }
            set {
                if ((object.ReferenceEquals(this.CUVField, value) != true)) {
                    this.CUVField = value;
                    this.RaisePropertyChanged("CUV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CampaniaID {
            get {
                return this.CampaniaIDField;
            }
            set {
                if ((this.CampaniaIDField.Equals(value) != true)) {
                    this.CampaniaIDField = value;
                    this.RaisePropertyChanged("CampaniaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadIncrementa {
            get {
                return this.CantidadIncrementaField;
            }
            set {
                if ((this.CantidadIncrementaField.Equals(value) != true)) {
                    this.CantidadIncrementaField = value;
                    this.RaisePropertyChanged("CantidadIncrementa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaID {
            get {
                return this.CategoriaIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaIDField, value) != true)) {
                    this.CategoriaIDField = value;
                    this.RaisePropertyChanged("CategoriaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCampania {
            get {
                return this.CodigoCampaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoCampaniaField, value) != true)) {
                    this.CodigoCampaniaField = value;
                    this.RaisePropertyChanged("CodigoCampania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCategoria {
            get {
                return this.CodigoCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoCategoriaField, value) != true)) {
                    this.CodigoCategoriaField = value;
                    this.RaisePropertyChanged("CodigoCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoEstrategia {
            get {
                return this.CodigoEstrategiaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoEstrategiaField, value) != true)) {
                    this.CodigoEstrategiaField = value;
                    this.RaisePropertyChanged("CodigoEstrategia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoProducto {
            get {
                return this.CodigoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoProductoField, value) != true)) {
                    this.CodigoProductoField = value;
                    this.RaisePropertyChanged("CodigoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTipoOferta {
            get {
                return this.CodigoTipoOfertaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTipoOfertaField, value) != true)) {
                    this.CodigoTipoOfertaField = value;
                    this.RaisePropertyChanged("CodigoTipoOferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConfiguracionOfertaID {
            get {
                return this.ConfiguracionOfertaIDField;
            }
            set {
                if ((this.ConfiguracionOfertaIDField.Equals(value) != true)) {
                    this.ConfiguracionOfertaIDField = value;
                    this.RaisePropertyChanged("ConfiguracionOfertaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionCategoria {
            get {
                return this.DescripcionCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionCategoriaField, value) != true)) {
                    this.DescripcionCategoriaField = value;
                    this.RaisePropertyChanged("DescripcionCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionLegal {
            get {
                return this.DescripcionLegalField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionLegalField, value) != true)) {
                    this.DescripcionLegalField = value;
                    this.RaisePropertyChanged("DescripcionLegal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsSubCampania {
            get {
                return this.EsSubCampaniaField;
            }
            set {
                if ((this.EsSubCampaniaField.Equals(value) != true)) {
                    this.EsSubCampaniaField = value;
                    this.RaisePropertyChanged("EsSubCampania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FlagAgotado {
            get {
                return this.FlagAgotadoField;
            }
            set {
                if ((this.FlagAgotadoField.Equals(value) != true)) {
                    this.FlagAgotadoField = value;
                    this.RaisePropertyChanged("FlagAgotado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlagHabilitarProducto {
            get {
                return this.FlagHabilitarProductoField;
            }
            set {
                if ((this.FlagHabilitarProductoField.Equals(value) != true)) {
                    this.FlagHabilitarProductoField = value;
                    this.RaisePropertyChanged("FlagHabilitarProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FlagRevista {
            get {
                return this.FlagRevistaField;
            }
            set {
                if ((this.FlagRevistaField.Equals(value) != true)) {
                    this.FlagRevistaField = value;
                    this.RaisePropertyChanged("FlagRevista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISOPais {
            get {
                return this.ISOPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.ISOPaisField, value) != true)) {
                    this.ISOPaisField = value;
                    this.RaisePropertyChanged("ISOPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagenMini {
            get {
                return this.ImagenMiniField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenMiniField, value) != true)) {
                    this.ImagenMiniField = value;
                    this.RaisePropertyChanged("ImagenMini");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagenProducto {
            get {
                return this.ImagenProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenProductoField, value) != true)) {
                    this.ImagenProductoField = value;
                    this.RaisePropertyChanged("ImagenProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Incrementa {
            get {
                return this.IncrementaField;
            }
            set {
                if ((this.IncrementaField.Equals(value) != true)) {
                    this.IncrementaField = value;
                    this.RaisePropertyChanged("Incrementa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarcaID {
            get {
                return this.MarcaIDField;
            }
            set {
                if ((this.MarcaIDField.Equals(value) != true)) {
                    this.MarcaIDField = value;
                    this.RaisePropertyChanged("MarcaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NroOrden {
            get {
                return this.NroOrdenField;
            }
            set {
                if ((this.NroOrdenField.Equals(value) != true)) {
                    this.NroOrdenField = value;
                    this.RaisePropertyChanged("NroOrden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfertaShowRoomID {
            get {
                return this.OfertaShowRoomIDField;
            }
            set {
                if ((this.OfertaShowRoomIDField.Equals(value) != true)) {
                    this.OfertaShowRoomIDField = value;
                    this.RaisePropertyChanged("OfertaShowRoomID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioOferta {
            get {
                return this.PrecioOfertaField;
            }
            set {
                if ((this.PrecioOfertaField.Equals(value) != true)) {
                    this.PrecioOfertaField = value;
                    this.RaisePropertyChanged("PrecioOferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioValorizado {
            get {
                return this.PrecioValorizadoField;
            }
            set {
                if ((this.PrecioValorizadoField.Equals(value) != true)) {
                    this.PrecioValorizadoField = value;
                    this.RaisePropertyChanged("PrecioValorizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockInicial {
            get {
                return this.StockInicialField;
            }
            set {
                if ((this.StockInicialField.Equals(value) != true)) {
                    this.StockInicialField = value;
                    this.RaisePropertyChanged("StockInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockResultado {
            get {
                return this.StockResultadoField;
            }
            set {
                if ((this.StockResultadoField.Equals(value) != true)) {
                    this.StockResultadoField = value;
                    this.RaisePropertyChanged("StockResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TieneVariedad {
            get {
                return this.TieneVariedadField;
            }
            set {
                if ((this.TieneVariedadField.Equals(value) != true)) {
                    this.TieneVariedadField = value;
                    this.RaisePropertyChanged("TieneVariedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipNegocio {
            get {
                return this.TipNegocioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipNegocioField, value) != true)) {
                    this.TipNegocioField = value;
                    this.RaisePropertyChanged("TipNegocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoOferta {
            get {
                return this.TipoOfertaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoOfertaField, value) != true)) {
                    this.TipoOfertaField = value;
                    this.RaisePropertyChanged("TipoOferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoOfertaSisID {
            get {
                return this.TipoOfertaSisIDField;
            }
            set {
                if ((this.TipoOfertaSisIDField.Equals(value) != true)) {
                    this.TipoOfertaSisIDField = value;
                    this.RaisePropertyChanged("TipoOfertaSisID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnidadesPermitidas {
            get {
                return this.UnidadesPermitidasField;
            }
            set {
                if ((this.UnidadesPermitidasField.Equals(value) != true)) {
                    this.UnidadesPermitidasField = value;
                    this.RaisePropertyChanged("UnidadesPermitidas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioModificacion {
            get {
                return this.UsuarioModificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioModificacionField, value) != true)) {
                    this.UsuarioModificacionField = value;
                    this.RaisePropertyChanged("UsuarioModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioRegistro {
            get {
                return this.UsuarioRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioRegistroField, value) != true)) {
                    this.UsuarioRegistroField = value;
                    this.RaisePropertyChanged("UsuarioRegistro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceOferta.IOfertaService")]
    public interface IOfertaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/GetShowRoomOfertasConsultora", ReplyAction="http://tempuri.org/IOfertaService/GetShowRoomOfertasConsultoraResponse")]
        Portal.Consultoras.Web.ServiceOferta.BEShowRoomOferta[] GetShowRoomOfertasConsultora(int paisID, int campaniaID, string codigoConsultora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/GetShowRoomOfertasConsultora", ReplyAction="http://tempuri.org/IOfertaService/GetShowRoomOfertasConsultoraResponse")]
        System.Threading.Tasks.Task<Portal.Consultoras.Web.ServiceOferta.BEShowRoomOferta[]> GetShowRoomOfertasConsultoraAsync(int paisID, int campaniaID, string codigoConsultora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/GetProductosCompraPorCompra", ReplyAction="http://tempuri.org/IOfertaService/GetProductosCompraPorCompraResponse")]
        Portal.Consultoras.Web.ServiceOferta.BEShowRoomOferta[] GetProductosCompraPorCompra(int paisId, int EventoID, int CampaniaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/GetProductosCompraPorCompra", ReplyAction="http://tempuri.org/IOfertaService/GetProductosCompraPorCompraResponse")]
        System.Threading.Tasks.Task<Portal.Consultoras.Web.ServiceOferta.BEShowRoomOferta[]> GetProductosCompraPorCompraAsync(int paisId, int EventoID, int CampaniaID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOfertaServiceChannel : Portal.Consultoras.Web.ServiceOferta.IOfertaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OfertaServiceClient : System.ServiceModel.ClientBase<Portal.Consultoras.Web.ServiceOferta.IOfertaService>, Portal.Consultoras.Web.ServiceOferta.IOfertaService {
        
        public OfertaServiceClient() {
        }
        
        public OfertaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OfertaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfertaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfertaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Portal.Consultoras.Web.ServiceOferta.BEShowRoomOferta[] GetShowRoomOfertasConsultora(int paisID, int campaniaID, string codigoConsultora) {
            return base.Channel.GetShowRoomOfertasConsultora(paisID, campaniaID, codigoConsultora);
        }
        
        public System.Threading.Tasks.Task<Portal.Consultoras.Web.ServiceOferta.BEShowRoomOferta[]> GetShowRoomOfertasConsultoraAsync(int paisID, int campaniaID, string codigoConsultora) {
            return base.Channel.GetShowRoomOfertasConsultoraAsync(paisID, campaniaID, codigoConsultora);
        }
        
        public Portal.Consultoras.Web.ServiceOferta.BEShowRoomOferta[] GetProductosCompraPorCompra(int paisId, int EventoID, int CampaniaID) {
            return base.Channel.GetProductosCompraPorCompra(paisId, EventoID, CampaniaID);
        }
        
        public System.Threading.Tasks.Task<Portal.Consultoras.Web.ServiceOferta.BEShowRoomOferta[]> GetProductosCompraPorCompraAsync(int paisId, int EventoID, int CampaniaID) {
            return base.Channel.GetProductosCompraPorCompraAsync(paisId, EventoID, CampaniaID);
        }
    }
}
