GO
IF (EXISTS(
	SELECT 1 
	FROM INFORMATION_SCHEMA.COLUMNS 
	WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'PedidoWebDetalle' AND COLUMN_NAME = 'EsBackOrder'
))
BEGIN
	ALTER TABLE dbo.PedidoWebDetalle
	DROP COLUMN EsBackOrder;
END
GO
IF (EXISTS(
	SELECT 1 
	FROM INFORMATION_SCHEMA.COLUMNS 
	WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'PedidoWebDetalle' AND COLUMN_NAME = 'AceptoBackOrder'
))
BEGIN
	ALTER TABLE dbo.PedidoWebDetalle
	DROP COLUMN AceptoBackOrder;
END
GO