USE BelcorpPeru
GO

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_GRUPOARTICULO') DROP SYNONYM [ods].[SAP_GRUPOARTICULO]
CREATE SYNONYM [ods].[SAP_GRUPOARTICULO] FOR [ODS_CR].[dbo].[SAP_GRUPOARTICULO]

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_LINEA') DROP SYNONYM [ods].[SAP_LINEA]
CREATE SYNONYM [ods].[SAP_LINEA] FOR [ODS_CR].[dbo].[SAP_LINEA]

GO

USE BelcorpMexico
GO

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_GRUPOARTICULO') DROP SYNONYM [ods].[SAP_GRUPOARTICULO]
CREATE SYNONYM [ods].[SAP_GRUPOARTICULO] FOR [ODS_CR].[dbo].[SAP_GRUPOARTICULO]

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_LINEA') DROP SYNONYM [ods].[SAP_LINEA]
CREATE SYNONYM [ods].[SAP_LINEA] FOR [ODS_CR].[dbo].[SAP_LINEA]

GO

USE BelcorpColombia
GO

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_GRUPOARTICULO') DROP SYNONYM [ods].[SAP_GRUPOARTICULO]
CREATE SYNONYM [ods].[SAP_GRUPOARTICULO] FOR [ODS_CR].[dbo].[SAP_GRUPOARTICULO]

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_LINEA') DROP SYNONYM [ods].[SAP_LINEA]
CREATE SYNONYM [ods].[SAP_LINEA] FOR [ODS_CR].[dbo].[SAP_LINEA]

GO

USE BelcorpSalvador
GO

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_GRUPOARTICULO') DROP SYNONYM [ods].[SAP_GRUPOARTICULO]
CREATE SYNONYM [ods].[SAP_GRUPOARTICULO] FOR [ODS_CR].[dbo].[SAP_GRUPOARTICULO]

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_LINEA') DROP SYNONYM [ods].[SAP_LINEA]
CREATE SYNONYM [ods].[SAP_LINEA] FOR [ODS_CR].[dbo].[SAP_LINEA]

GO

USE BelcorpPuertoRico
GO

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_GRUPOARTICULO') DROP SYNONYM [ods].[SAP_GRUPOARTICULO]
CREATE SYNONYM [ods].[SAP_GRUPOARTICULO] FOR [ODS_CR].[dbo].[SAP_GRUPOARTICULO]

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_LINEA') DROP SYNONYM [ods].[SAP_LINEA]
CREATE SYNONYM [ods].[SAP_LINEA] FOR [ODS_CR].[dbo].[SAP_LINEA]

GO

USE BelcorpPanama
GO

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_GRUPOARTICULO') DROP SYNONYM [ods].[SAP_GRUPOARTICULO]
CREATE SYNONYM [ods].[SAP_GRUPOARTICULO] FOR [ODS_CR].[dbo].[SAP_GRUPOARTICULO]

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_LINEA') DROP SYNONYM [ods].[SAP_LINEA]
CREATE SYNONYM [ods].[SAP_LINEA] FOR [ODS_CR].[dbo].[SAP_LINEA]

GO

USE BelcorpGuatemala
GO

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_GRUPOARTICULO') DROP SYNONYM [ods].[SAP_GRUPOARTICULO]
CREATE SYNONYM [ods].[SAP_GRUPOARTICULO] FOR [ODS_CR].[dbo].[SAP_GRUPOARTICULO]

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_LINEA') DROP SYNONYM [ods].[SAP_LINEA]
CREATE SYNONYM [ods].[SAP_LINEA] FOR [ODS_CR].[dbo].[SAP_LINEA]

GO

USE BelcorpEcuador
GO

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_GRUPOARTICULO') DROP SYNONYM [ods].[SAP_GRUPOARTICULO]
CREATE SYNONYM [ods].[SAP_GRUPOARTICULO] FOR [ODS_CR].[dbo].[SAP_GRUPOARTICULO]

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_LINEA') DROP SYNONYM [ods].[SAP_LINEA]
CREATE SYNONYM [ods].[SAP_LINEA] FOR [ODS_CR].[dbo].[SAP_LINEA]

GO

USE BelcorpDominicana
GO

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_GRUPOARTICULO') DROP SYNONYM [ods].[SAP_GRUPOARTICULO]
CREATE SYNONYM [ods].[SAP_GRUPOARTICULO] FOR [ODS_CR].[dbo].[SAP_GRUPOARTICULO]

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_LINEA') DROP SYNONYM [ods].[SAP_LINEA]
CREATE SYNONYM [ods].[SAP_LINEA] FOR [ODS_CR].[dbo].[SAP_LINEA]

GO

USE BelcorpCostaRica
GO

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_GRUPOARTICULO') DROP SYNONYM [ods].[SAP_GRUPOARTICULO]
CREATE SYNONYM [ods].[SAP_GRUPOARTICULO] FOR [ODS_CR].[dbo].[SAP_GRUPOARTICULO]

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_LINEA') DROP SYNONYM [ods].[SAP_LINEA]
CREATE SYNONYM [ods].[SAP_LINEA] FOR [ODS_CR].[dbo].[SAP_LINEA]

GO

USE BelcorpChile
GO

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_GRUPOARTICULO') DROP SYNONYM [ods].[SAP_GRUPOARTICULO]
CREATE SYNONYM [ods].[SAP_GRUPOARTICULO] FOR [ODS_CR].[dbo].[SAP_GRUPOARTICULO]

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_LINEA') DROP SYNONYM [ods].[SAP_LINEA]
CREATE SYNONYM [ods].[SAP_LINEA] FOR [ODS_CR].[dbo].[SAP_LINEA]

GO

USE BelcorpBolivia
GO

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_GRUPOARTICULO') DROP SYNONYM [ods].[SAP_GRUPOARTICULO]
CREATE SYNONYM [ods].[SAP_GRUPOARTICULO] FOR [ODS_CR].[dbo].[SAP_GRUPOARTICULO]

IF EXISTS (SELECT * from sys.synonyms WHERE name = 'SAP_LINEA') DROP SYNONYM [ods].[SAP_LINEA]
CREATE SYNONYM [ods].[SAP_LINEA] FOR [ODS_CR].[dbo].[SAP_LINEA]

GO

