GO
IF EXISTS(
	SELECT 1
	FROM INFORMATION_SCHEMA.ROUTINES 
	WHERE SPECIFIC_NAME = 'InsOrUpdOfertaShowRoom' AND SPECIFIC_SCHEMA = 'ShowRoom' AND Routine_Type = 'PROCEDURE'
)
BEGIN
    DROP PROCEDURE ShowRoom.InsOrUpdOfertaShowRoom
END
GO