USE BelcorpBolivia
GO
DELETE  FROM ROLPERMISO WHERE PERMISOID IN ( select PERMISOID  FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS')

DELETE FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
GO

USE BelcorpChile
GO
DELETE  FROM ROLPERMISO WHERE PERMISOID IN ( select PERMISOID  FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS')

DELETE FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
GO

USE BelcorpColombia
GO
DELETE  FROM ROLPERMISO WHERE PERMISOID IN ( select PERMISOID  FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS')

DELETE FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
GO

USE BelcorpCostaRica
GO
DELETE  FROM ROLPERMISO WHERE PERMISOID IN ( select PERMISOID  FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS')

DELETE FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
GO

USE BelcorpDominicana
GO
DELETE  FROM ROLPERMISO WHERE PERMISOID IN ( select PERMISOID  FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS')

DELETE FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
GO

USE BelcorpEcuador
GO
DELETE  FROM ROLPERMISO WHERE PERMISOID IN ( select PERMISOID  FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS')

DELETE FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
GO

USE BelcorpGuatemala
GO
DELETE  FROM ROLPERMISO WHERE PERMISOID IN ( select PERMISOID  FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS')

DELETE FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
GO

USE BelcorpMexico
GO
DELETE  FROM ROLPERMISO WHERE PERMISOID IN ( select PERMISOID  FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS')

DELETE FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
GO

USE BelcorpPanama
GO
DELETE  FROM ROLPERMISO WHERE PERMISOID IN ( select PERMISOID  FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS')

DELETE FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
GO

USE BelcorpPeru
GO
DELETE  FROM ROLPERMISO WHERE PERMISOID IN ( select PERMISOID  FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS')

DELETE FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
GO

USE BelcorpPuertoRico
GO
DELETE  FROM ROLPERMISO WHERE PERMISOID IN ( select PERMISOID  FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS')

DELETE FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
GO

USE BelcorpSalvador
GO
DELETE  FROM ROLPERMISO WHERE PERMISOID IN ( select PERMISOID  FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS')

DELETE FROM   PERMISO  WHERE  IDPADRE = 81 
AND URLITEM = 'BIENVENIDA/REPORTEVALIDACIONDATOS'
GO