//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Consultoras.Web.ValidacionCrediticia {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InValidacionCrediticiaDTO", Namespace="http://schemas.datacontract.org/2004/07/Belcorp.FFVV.Aplicacion.Principal.DTO.Val" +
        "idacionCrediticia.In")]
    [System.SerializableAttribute()]
    public partial class InValidacionCrediticiaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoIdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.documentoField, value) != true)) {
                    this.documentoField = value;
                    this.RaisePropertyChanged("documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numDocumento {
            get {
                return this.numDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.numDocumentoField, value) != true)) {
                    this.numDocumentoField = value;
                    this.RaisePropertyChanged("numDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serie {
            get {
                return this.serieField;
            }
            set {
                if ((object.ReferenceEquals(this.serieField, value) != true)) {
                    this.serieField = value;
                    this.RaisePropertyChanged("serie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoIdentificacionField, value) != true)) {
                    this.tipoIdentificacionField = value;
                    this.RaisePropertyChanged("tipoIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zona {
            get {
                return this.zonaField;
            }
            set {
                if ((object.ReferenceEquals(this.zonaField, value) != true)) {
                    this.zonaField = value;
                    this.RaisePropertyChanged("zona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutResponse", Namespace="http://schemas.datacontract.org/2004/07/Belcorp.FFVV.Aplicacion.Principal.DTO.Bas" +
        "e.Out")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Portal.Consultoras.Web.ValidacionCrediticia.OutValidacionCrediticiaDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Portal.Consultoras.Web.ValidacionCrediticia.OutListaOfOutValidacionCrediticiaDTOOutValidacionCrediticiaBloqueoXL2naAvS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Portal.Consultoras.Web.ValidacionCrediticia.OutValidacionCrediticiaLista))]
    public partial class OutResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoErrorField, value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionError {
            get {
                return this.DescripcionErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionErrorField, value) != true)) {
                    this.DescripcionErrorField = value;
                    this.RaisePropertyChanged("DescripcionError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError {
            get {
                return this.HasErrorField;
            }
            set {
                if ((this.HasErrorField.Equals(value) != true)) {
                    this.HasErrorField = value;
                    this.RaisePropertyChanged("HasError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutValidacionCrediticiaDTO", Namespace="http://schemas.datacontract.org/2004/07/Belcorp.FFVV.Aplicacion.Principal.DTO.Val" +
        "idacionCrediticia.Out")]
    [System.SerializableAttribute()]
    public partial class OutValidacionCrediticiaDTO : Portal.Consultoras.Web.ValidacionCrediticia.OutResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampanaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoConsultoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeudaBelcorpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeudaEntidadCrediticiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocIdentidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UltimaCampanaFacturadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValoracionBelcorpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Portal.Consultoras.Web.ValidacionCrediticia.ConsultarDCResult consultarDCResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Portal.Consultoras.Web.ValidacionCrediticia.tDeuda[] deudasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primerNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoMonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Portal.Consultoras.Web.ValidacionCrediticia.tValoracion[] valoracionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampanaIngreso {
            get {
                return this.CampanaIngresoField;
            }
            set {
                if ((object.ReferenceEquals(this.CampanaIngresoField, value) != true)) {
                    this.CampanaIngresoField = value;
                    this.RaisePropertyChanged("CampanaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoConsultora {
            get {
                return this.CodigoConsultoraField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoConsultoraField, value) != true)) {
                    this.CodigoConsultoraField = value;
                    this.RaisePropertyChanged("CodigoConsultora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeudaBelcorp {
            get {
                return this.DeudaBelcorpField;
            }
            set {
                if ((object.ReferenceEquals(this.DeudaBelcorpField, value) != true)) {
                    this.DeudaBelcorpField = value;
                    this.RaisePropertyChanged("DeudaBelcorp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeudaEntidadCrediticia {
            get {
                return this.DeudaEntidadCrediticiaField;
            }
            set {
                if ((object.ReferenceEquals(this.DeudaEntidadCrediticiaField, value) != true)) {
                    this.DeudaEntidadCrediticiaField = value;
                    this.RaisePropertyChanged("DeudaEntidadCrediticia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocIdentidad {
            get {
                return this.DocIdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.DocIdentidadField, value) != true)) {
                    this.DocIdentidadField = value;
                    this.RaisePropertyChanged("DocIdentidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seccion {
            get {
                return this.SeccionField;
            }
            set {
                if ((object.ReferenceEquals(this.SeccionField, value) != true)) {
                    this.SeccionField = value;
                    this.RaisePropertyChanged("Seccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UltimaCampanaFacturada {
            get {
                return this.UltimaCampanaFacturadaField;
            }
            set {
                if ((object.ReferenceEquals(this.UltimaCampanaFacturadaField, value) != true)) {
                    this.UltimaCampanaFacturadaField = value;
                    this.RaisePropertyChanged("UltimaCampanaFacturada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValoracionBelcorp {
            get {
                return this.ValoracionBelcorpField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoracionBelcorpField, value) != true)) {
                    this.ValoracionBelcorpField = value;
                    this.RaisePropertyChanged("ValoracionBelcorp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zona {
            get {
                return this.ZonaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonaField, value) != true)) {
                    this.ZonaField = value;
                    this.RaisePropertyChanged("Zona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Portal.Consultoras.Web.ValidacionCrediticia.ConsultarDCResult consultarDCResult {
            get {
                return this.consultarDCResultField;
            }
            set {
                if ((object.ReferenceEquals(this.consultarDCResultField, value) != true)) {
                    this.consultarDCResultField = value;
                    this.RaisePropertyChanged("consultarDCResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Portal.Consultoras.Web.ValidacionCrediticia.tDeuda[] deudas {
            get {
                return this.deudasField;
            }
            set {
                if ((object.ReferenceEquals(this.deudasField, value) != true)) {
                    this.deudasField = value;
                    this.RaisePropertyChanged("deudas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadoCliente {
            get {
                return this.estadoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoClienteField, value) != true)) {
                    this.estadoClienteField = value;
                    this.RaisePropertyChanged("estadoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primerApellidoField, value) != true)) {
                    this.primerApellidoField = value;
                    this.RaisePropertyChanged("primerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primerNombre {
            get {
                return this.primerNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.primerNombreField, value) != true)) {
                    this.primerNombreField = value;
                    this.RaisePropertyChanged("primerNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoApellidoField, value) != true)) {
                    this.segundoApellidoField = value;
                    this.RaisePropertyChanged("segundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoNombreField, value) != true)) {
                    this.segundoNombreField = value;
                    this.RaisePropertyChanged("segundoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoMonedaField, value) != true)) {
                    this.tipoMonedaField = value;
                    this.RaisePropertyChanged("tipoMoneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Portal.Consultoras.Web.ValidacionCrediticia.tValoracion[] valoracion {
            get {
                return this.valoracionField;
            }
            set {
                if ((object.ReferenceEquals(this.valoracionField, value) != true)) {
                    this.valoracionField = value;
                    this.RaisePropertyChanged("valoracion");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutListaOfOutValidacionCrediticiaDTOOutValidacionCrediticiaBloqueoXL2naAvS", Namespace="http://schemas.datacontract.org/2004/07/Belcorp.FFVV.Aplicacion.Principal.DTO.Bas" +
        "e.Out")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Portal.Consultoras.Web.ValidacionCrediticia.OutValidacionCrediticiaLista))]
    public partial class OutListaOfOutValidacionCrediticiaDTOOutValidacionCrediticiaBloqueoXL2naAvS : Portal.Consultoras.Web.ValidacionCrediticia.OutResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Portal.Consultoras.Web.ValidacionCrediticia.OutValidacionCrediticiaBloqueo[] AnotherHitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Portal.Consultoras.Web.ValidacionCrediticia.OutValidacionCrediticiaDTO[] HitsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Portal.Consultoras.Web.ValidacionCrediticia.OutValidacionCrediticiaBloqueo[] AnotherHits {
            get {
                return this.AnotherHitsField;
            }
            set {
                if ((object.ReferenceEquals(this.AnotherHitsField, value) != true)) {
                    this.AnotherHitsField = value;
                    this.RaisePropertyChanged("AnotherHits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Portal.Consultoras.Web.ValidacionCrediticia.OutValidacionCrediticiaDTO[] Hits {
            get {
                return this.HitsField;
            }
            set {
                if ((object.ReferenceEquals(this.HitsField, value) != true)) {
                    this.HitsField = value;
                    this.RaisePropertyChanged("Hits");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutValidacionCrediticiaLista", Namespace="http://schemas.datacontract.org/2004/07/Belcorp.FFVV.Aplicacion.Principal.DTO.Val" +
        "idacionCrediticia.Out")]
    [System.SerializableAttribute()]
    public partial class OutValidacionCrediticiaLista : Portal.Consultoras.Web.ValidacionCrediticia.OutListaOfOutValidacionCrediticiaDTOOutValidacionCrediticiaBloqueoXL2naAvS {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutValidacionCrediticiaBloqueo", Namespace="http://schemas.datacontract.org/2004/07/Belcorp.FFVV.Aplicacion.Principal.DTO.Val" +
        "idacionCrediticia.Out")]
    [System.SerializableAttribute()]
    public partial class OutValidacionCrediticiaBloqueo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoBloqueoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoBloqueoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoBloqueo {
            get {
                return this.MotivoBloqueoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoBloqueoField, value) != true)) {
                    this.MotivoBloqueoField = value;
                    this.RaisePropertyChanged("MotivoBloqueo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoBloqueo {
            get {
                return this.TipoBloqueoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoBloqueoField, value) != true)) {
                    this.TipoBloqueoField = value;
                    this.RaisePropertyChanged("TipoBloqueo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultarDCResult", Namespace="http://schemas.datacontract.org/2004/07/Belcorp.FFVV.Aplicacion.Principal.DTO.Val" +
        "idacionCrediticia.Out")]
    [System.SerializableAttribute()]
    public partial class ConsultarDCResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumDocumento {
            get {
                return this.NumDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumDocumentoField, value) != true)) {
                    this.NumDocumentoField = value;
                    this.RaisePropertyChanged("NumDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tDeuda", Namespace="http://schemas.datacontract.org/2004/07/Belcorp.FFVV.Aplicacion.Principal.DTO.Val" +
        "idacionCrediticia.Out")]
    [System.SerializableAttribute()]
    public partial class tDeuda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string entidadCrediticiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Portal.Consultoras.Web.ValidacionCrediticia.tMoneda monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> montoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string entidadCrediticia {
            get {
                return this.entidadCrediticiaField;
            }
            set {
                if ((object.ReferenceEquals(this.entidadCrediticiaField, value) != true)) {
                    this.entidadCrediticiaField = value;
                    this.RaisePropertyChanged("entidadCrediticia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Portal.Consultoras.Web.ValidacionCrediticia.tMoneda moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((object.ReferenceEquals(this.monedaField, value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tValoracion", Namespace="http://schemas.datacontract.org/2004/07/Belcorp.FFVV.Aplicacion.Principal.DTO.Val" +
        "idacionCrediticia.Out")]
    [System.SerializableAttribute()]
    public partial class tValoracion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoField, value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                if ((object.ReferenceEquals(this.valorField, value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tMoneda", Namespace="http://schemas.datacontract.org/2004/07/Belcorp.FFVV.Aplicacion.Principal.DTO.Val" +
        "idacionCrediticia.Out")]
    [System.SerializableAttribute()]
    public partial class tMoneda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoISOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoISOPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string simboloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoISO {
            get {
                return this.codigoISOField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoISOField, value) != true)) {
                    this.codigoISOField = value;
                    this.RaisePropertyChanged("codigoISO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoISOPais {
            get {
                return this.codigoISOPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoISOPaisField, value) != true)) {
                    this.codigoISOPaisField = value;
                    this.RaisePropertyChanged("codigoISOPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string simbolo {
            get {
                return this.simboloField;
            }
            set {
                if ((object.ReferenceEquals(this.simboloField, value) != true)) {
                    this.simboloField = value;
                    this.RaisePropertyChanged("simbolo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValidacionCrediticia.IValidacionCrediticia")]
    public interface IValidacionCrediticia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacionCrediticia/GetValidacionCrediticia", ReplyAction="http://tempuri.org/IValidacionCrediticia/GetValidacionCrediticiaResponse")]
        Portal.Consultoras.Web.ValidacionCrediticia.OutValidacionCrediticiaLista GetValidacionCrediticia(Portal.Consultoras.Web.ValidacionCrediticia.InValidacionCrediticiaDTO input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacionCrediticia/GetValidacionCrediticia", ReplyAction="http://tempuri.org/IValidacionCrediticia/GetValidacionCrediticiaResponse")]
        System.Threading.Tasks.Task<Portal.Consultoras.Web.ValidacionCrediticia.OutValidacionCrediticiaLista> GetValidacionCrediticiaAsync(Portal.Consultoras.Web.ValidacionCrediticia.InValidacionCrediticiaDTO input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacionCrediticia/GetValidacionCrediticiaExterna", ReplyAction="http://tempuri.org/IValidacionCrediticia/GetValidacionCrediticiaExternaResponse")]
        Portal.Consultoras.Web.ValidacionCrediticia.OutValidacionCrediticiaDTO GetValidacionCrediticiaExterna(Portal.Consultoras.Web.ValidacionCrediticia.InValidacionCrediticiaDTO input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacionCrediticia/GetValidacionCrediticiaExterna", ReplyAction="http://tempuri.org/IValidacionCrediticia/GetValidacionCrediticiaExternaResponse")]
        System.Threading.Tasks.Task<Portal.Consultoras.Web.ValidacionCrediticia.OutValidacionCrediticiaDTO> GetValidacionCrediticiaExternaAsync(Portal.Consultoras.Web.ValidacionCrediticia.InValidacionCrediticiaDTO input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValidacionCrediticiaChannel : Portal.Consultoras.Web.ValidacionCrediticia.IValidacionCrediticia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidacionCrediticiaClient : System.ServiceModel.ClientBase<Portal.Consultoras.Web.ValidacionCrediticia.IValidacionCrediticia>, Portal.Consultoras.Web.ValidacionCrediticia.IValidacionCrediticia {
        
        public ValidacionCrediticiaClient() {
        }
        
        public ValidacionCrediticiaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidacionCrediticiaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidacionCrediticiaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidacionCrediticiaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Portal.Consultoras.Web.ValidacionCrediticia.OutValidacionCrediticiaLista GetValidacionCrediticia(Portal.Consultoras.Web.ValidacionCrediticia.InValidacionCrediticiaDTO input) {
            return base.Channel.GetValidacionCrediticia(input);
        }
        
        public System.Threading.Tasks.Task<Portal.Consultoras.Web.ValidacionCrediticia.OutValidacionCrediticiaLista> GetValidacionCrediticiaAsync(Portal.Consultoras.Web.ValidacionCrediticia.InValidacionCrediticiaDTO input) {
            return base.Channel.GetValidacionCrediticiaAsync(input);
        }
        
        public Portal.Consultoras.Web.ValidacionCrediticia.OutValidacionCrediticiaDTO GetValidacionCrediticiaExterna(Portal.Consultoras.Web.ValidacionCrediticia.InValidacionCrediticiaDTO input) {
            return base.Channel.GetValidacionCrediticiaExterna(input);
        }
        
        public System.Threading.Tasks.Task<Portal.Consultoras.Web.ValidacionCrediticia.OutValidacionCrediticiaDTO> GetValidacionCrediticiaExternaAsync(Portal.Consultoras.Web.ValidacionCrediticia.InValidacionCrediticiaDTO input) {
            return base.Channel.GetValidacionCrediticiaExternaAsync(input);
        }
    }
}
