//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Consultoras.Web.ServiceAsesoraOnline {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEAsesoraOnline", Namespace="http://schemas.datacontract.org/2004/07/Portal.Consultoras.Entities.AsesoraOnline" +
        "")]
    [System.SerializableAttribute()]
    public partial class BEAsesoraOnline : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoConsultoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MasCatalogosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipsGestionClientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipsMasClientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipsVentasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoConsultora {
            get {
                return this.CodigoConsultoraField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoConsultoraField, value) != true)) {
                    this.CodigoConsultoraField = value;
                    this.RaisePropertyChanged("CodigoConsultora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCreacionField, value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaModificacionField, value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MasCatalogos {
            get {
                return this.MasCatalogosField;
            }
            set {
                if ((this.MasCatalogosField.Equals(value) != true)) {
                    this.MasCatalogosField = value;
                    this.RaisePropertyChanged("MasCatalogos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origen {
            get {
                return this.OrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigenField, value) != true)) {
                    this.OrigenField = value;
                    this.RaisePropertyChanged("Origen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipsGestionClientes {
            get {
                return this.TipsGestionClientesField;
            }
            set {
                if ((this.TipsGestionClientesField.Equals(value) != true)) {
                    this.TipsGestionClientesField = value;
                    this.RaisePropertyChanged("TipsGestionClientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipsMasClientes {
            get {
                return this.TipsMasClientesField;
            }
            set {
                if ((this.TipsMasClientesField.Equals(value) != true)) {
                    this.TipsMasClientesField = value;
                    this.RaisePropertyChanged("TipsMasClientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipsVentas {
            get {
                return this.TipsVentasField;
            }
            set {
                if ((this.TipsVentasField.Equals(value) != true)) {
                    this.TipsVentasField = value;
                    this.RaisePropertyChanged("TipsVentas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAsesoraOnline.IAsesoraOnlineService")]
    public interface IAsesoraOnlineService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsesoraOnlineService/EnviarFormulario", ReplyAction="http://tempuri.org/IAsesoraOnlineService/EnviarFormularioResponse")]
        int EnviarFormulario(string paisISO, Portal.Consultoras.Web.ServiceAsesoraOnline.BEAsesoraOnline entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsesoraOnlineService/EnviarFormulario", ReplyAction="http://tempuri.org/IAsesoraOnlineService/EnviarFormularioResponse")]
        System.Threading.Tasks.Task<int> EnviarFormularioAsync(string paisISO, Portal.Consultoras.Web.ServiceAsesoraOnline.BEAsesoraOnline entidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAsesoraOnlineServiceChannel : Portal.Consultoras.Web.ServiceAsesoraOnline.IAsesoraOnlineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsesoraOnlineServiceClient : System.ServiceModel.ClientBase<Portal.Consultoras.Web.ServiceAsesoraOnline.IAsesoraOnlineService>, Portal.Consultoras.Web.ServiceAsesoraOnline.IAsesoraOnlineService {
        
        public AsesoraOnlineServiceClient() {
        }
        
        public AsesoraOnlineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsesoraOnlineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsesoraOnlineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsesoraOnlineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int EnviarFormulario(string paisISO, Portal.Consultoras.Web.ServiceAsesoraOnline.BEAsesoraOnline entidad) {
            return base.Channel.EnviarFormulario(paisISO, entidad);
        }
        
        public System.Threading.Tasks.Task<int> EnviarFormularioAsync(string paisISO, Portal.Consultoras.Web.ServiceAsesoraOnline.BEAsesoraOnline entidad) {
            return base.Channel.EnviarFormularioAsync(paisISO, entidad);
        }
    }
}
