USE BelcorpPeru
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[GetProductoDescripcionByCUVandCampania]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO
CREATE PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP
	UNION ALL
	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))
END
go

USE BelcorpMexico
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[GetProductoDescripcionByCUVandCampania]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO
CREATE PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP
	UNION ALL
	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))
END
go

USE BelcorpColombia
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[GetProductoDescripcionByCUVandCampania]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO
CREATE PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP
	UNION ALL
	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))
END
go

USE BelcorpSalvador
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[GetProductoDescripcionByCUVandCampania]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO
CREATE PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP
	UNION ALL
	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))
END
go

USE BelcorpPuertoRico
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[GetProductoDescripcionByCUVandCampania]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO
CREATE PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP
	UNION ALL
	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))
END
go

USE BelcorpPanama
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[GetProductoDescripcionByCUVandCampania]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO
CREATE PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP
	UNION ALL
	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))
END
go

USE BelcorpGuatemala
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[GetProductoDescripcionByCUVandCampania]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO
CREATE PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP
	UNION ALL
	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))
END
go

USE BelcorpEcuador
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[GetProductoDescripcionByCUVandCampania]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO
CREATE PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP
	UNION ALL
	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))
END
go

USE BelcorpDominicana
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[GetProductoDescripcionByCUVandCampania]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO
CREATE PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP
	UNION ALL
	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))
END
go

USE BelcorpCostaRica
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[GetProductoDescripcionByCUVandCampania]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO
CREATE PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP
	UNION ALL
	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))
END
go

USE BelcorpChile
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[GetProductoDescripcionByCUVandCampania]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO
CREATE PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP
	UNION ALL
	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))
END
go

USE BelcorpBolivia
GO

IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[GetProductoDescripcionByCUVandCampania]') 
	AND type in (N'P', N'PC')
) 
DROP PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
GO
CREATE PROCEDURE [dbo].[GetProductoDescripcionByCUVandCampania]
@CampaniaID int, 
@CUV varchar(20) 
AS
BEGIN
	SELECT 
	PC.*,
	MC.IDMATRIZCOMERCIAL
	FROM 
	(SELECT 
	P.DESCRIPCION, 
	CAMPANIAID= P.ANOCAMPANIA, 
	P.CUV, 
	PRECIOPRODUCTO = P.PRECIOUNITARIO, 
	P.FACTORREPETICION,
	REGALODESCRIPCION = '',
	REGALOIMAGENURL = '',
	SAP = ISNULL(CODIGOPRODUCTO,'')
	FROM ODS.PRODUCTOCOMERCIAL P 
	WHERE P.ANOCAMPANIA = @CAMPANIAID 
	AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))) PC
	LEFT JOIN MATRIZCOMERCIAL MC ON PC.SAP = MC.CODIGOSAP
	UNION ALL
	SELECT P.DESCRIPCION, 
	P.CAMPANIAID, 
	P.CUV,
	P.PRECIOPRODUCTO,
	P.FACTORREPETICION,
	REGALODESCRIPCION=ISNULL(REGALODESCRIPCION,''),
	REGALOIMAGENURL=ISNULL(REGALOIMAGENURL,''),
	SAP = '',
	IDMATRIZCOMERCIAL = ''
	FROM DBO.PRODUCTODESCRIPCION P
	WHERE P.CAMPANIAID = @CAMPANIAID AND LTRIM(RTRIM(P.CUV)) = LTRIM(RTRIM(@CUV))
END
go

