GO
IF (NOT EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'PedidoSapId'))
BEGIN
    ALTER TABLE dbo.PedidoWeb
	ADD PedidoSapId BIGINT NOT NULL
	CONSTRAINT DF_PedidoWeb_PedidoSapId DEFAULT 0;
END
GO
IF (NOT EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'PedidoWeb' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.PedidoWeb
	ADD VersionProl TINYINT NULL;
END
GO