GO
USE BelcorpPeru
GO
IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='LMG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'MG'
	where CODIGO='LMG'
END

GO
USE BelcorpMexico
GO
IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='LMG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'MG'
	where CODIGO='LMG'
END

GO
USE BelcorpColombia
GO
IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='LMG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'MG'
	where CODIGO='LMG'
END

GO
USE BelcorpSalvador
GO
IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='LMG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'MG'
	where CODIGO='LMG'
END

GO
USE BelcorpPuertoRico
GO
IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='LMG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'MG'
	where CODIGO='LMG'
END

GO
USE BelcorpPanama
GO
IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='LMG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'MG'
	where CODIGO='LMG'
END

GO
USE BelcorpGuatemala
GO
IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='LMG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'MG'
	where CODIGO='LMG'
END

GO
USE BelcorpEcuador
GO
IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='LMG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'MG'
	where CODIGO='LMG'
END

GO
USE BelcorpDominicana
GO
IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='LMG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'MG'
	where CODIGO='LMG'
END

GO
USE BelcorpCostaRica
GO
IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='LMG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'MG'
	where CODIGO='LMG'
END

GO
USE BelcorpChile
GO
IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='LMG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'MG'
	where CODIGO='LMG'
END

GO
USE BelcorpBolivia
GO
IF (EXISTS(SELECT * FROM CONFIGURACIONPAIS WHERE CODIGO='LMG'))
BEGIN
	Update CONFIGURACIONPAIS
	set CODIGO = 'MG'
	where CODIGO='LMG'
END

GO
