USE BELCORPPERU_BPT
GO

DECLARE @REVISTA_DIGITAL_ID INT = 3
--
DECLARE @LOGO_MENU_OFERTAS_ACTIVA VARCHAR(50) = 'LogoMenuOfertasActiva'
DECLARE @URL_LOGO_ACTIVA VARCHAR(800) = 'https://preview.ibb.co/mA4FJR/gif_clubganamas.gif'
--
DECLARE @LOGO_MENU_OFERTAS_NO_ACTIVA VARCHAR(50) = 'LogoMenuOfertasNoActiva'
DECLARE @URL_LOGO_NO_ACTIVA VARCHAR(800) = 'https://preview.ibb.co/jqQcXm/gif_ganamas.gif'

IF NOT EXISTS(
SELECT 1
FROM CONFIGURACIONPAISDATOS CPD
WHERE CPD.CONFIGURACIONPAISID =@REVISTA_DIGITAL_ID
AND CPD.CODIGO = @LOGO_MENU_OFERTAS_ACTIVA
)
BEGIN
	PRINT 'INSERTANDO ' + @LOGO_MENU_OFERTAS_ACTIVA + ' EN CONFIGURACIONPAISDATOS'
	INSERT INTO CONFIGURACIONPAISDATOS(
	ConfiguracionPaisID
	,Codigo
	,CampaniaID
	,Valor1
	,Valor2
	,Valor3
	,Descripcion
	,Estado
	)
	VALUES(
	@REVISTA_DIGITAL_ID
	,@LOGO_MENU_OFERTAS_ACTIVA
	,0
	,@URL_LOGO_ACTIVA
	,''
	,''
	,'Logo del menu ofertas cuando el estado es activa que se asignara en todo sb2'
	,1
	)
END

IF NOT EXISTS(
SELECT 1
FROM CONFIGURACIONPAISDATOS CPD
WHERE CPD.CONFIGURACIONPAISID =@REVISTA_DIGITAL_ID
AND CPD.CODIGO = @LOGO_MENU_OFERTAS_NO_ACTIVA
)
BEGIN
	PRINT 'INSERTANDO ' + @LOGO_MENU_OFERTAS_NO_ACTIVA + ' EN CONFIGURACIONPAISDATOS'
	INSERT INTO CONFIGURACIONPAISDATOS(
	ConfiguracionPaisID
	,Codigo
	,CampaniaID
	,Valor1
	,Valor2
	,Valor3
	,Descripcion
	,Estado
	)
	VALUES(
	@REVISTA_DIGITAL_ID
	,@LOGO_MENU_OFERTAS_NO_ACTIVA
	,0
	,@URL_LOGO_NO_ACTIVA
	,''
	,''
	,'Logo del menu ofertas cuando el estado es no activa que se asignara en todo sb2'
	,1
	)
END

