



 DECLARE @statament1 varchar(2000)='USE [?];IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
 WHERE TABLE_NAME = ''tablalogica'')
 BEGIN 
 IF EXISTS  (SELECT * FROM TABLALOGICA WHERE TABLALOGICAID =156)
 BEGIN
 DELETE FROM TABLALOGICA WHERE TABLALOGICAID =156
 DELETE FROM INTO TABLALOGICADATOS  WHERE TABLALOGICAID =156
 END
 END'

 EXEC sp_MSForEachDB  @statament1 
