USE BelcorpBolivia;
GO
 IF NOT EXISTS  (SELECT * FROM TABLALOGICA WHERE TABLALOGICAID =156)
 BEGIN
    INSERT INTO TABLALOGICA  VALUES (156,'Campanas AppCatalogo');
    INSERT INTO TABLALOGICADATOS  VALUES (15601,156,01,'Campanas Atras',5);
    INSERT INTO TABLALOGICADATOS  VALUES (15602,156,02,'Campanas Adelante',2);
 END
GO
USE BelcorpChile;
GO
 IF NOT EXISTS  (SELECT * FROM TABLALOGICA WHERE TABLALOGICAID =156)
 BEGIN
    INSERT INTO TABLALOGICA  VALUES (156,'Campanas AppCatalogo');
    INSERT INTO TABLALOGICADATOS  VALUES (15601,156,01,'Campanas Atras',5);
    INSERT INTO TABLALOGICADATOS  VALUES (15602,156,02,'Campanas Adelante',2);
 END
GO
USE BelcorpColombia;
GO
 IF NOT EXISTS  (SELECT * FROM TABLALOGICA WHERE TABLALOGICAID =156)
 BEGIN
    INSERT INTO TABLALOGICA  VALUES (156,'Campanas AppCatalogo');
    INSERT INTO TABLALOGICADATOS  VALUES (15601,156,01,'Campanas Atras',5);
    INSERT INTO TABLALOGICADATOS  VALUES (15602,156,02,'Campanas Adelante',2);
 END
GO
USE BelcorpCostaRica;
GO
 IF NOT EXISTS  (SELECT * FROM TABLALOGICA WHERE TABLALOGICAID =156)
 BEGIN
    INSERT INTO TABLALOGICA  VALUES (156,'Campanas AppCatalogo');
    INSERT INTO TABLALOGICADATOS  VALUES (15601,156,01,'Campanas Atras',5);
    INSERT INTO TABLALOGICADATOS  VALUES (15602,156,02,'Campanas Adelante',2);
 END
GO
USE BelcorpDominicana;
GO
 IF NOT EXISTS  (SELECT * FROM TABLALOGICA WHERE TABLALOGICAID =156)
 BEGIN
    INSERT INTO TABLALOGICA  VALUES (156,'Campanas AppCatalogo');
    INSERT INTO TABLALOGICADATOS  VALUES (15601,156,01,'Campanas Atras',5);
    INSERT INTO TABLALOGICADATOS  VALUES (15602,156,02,'Campanas Adelante',2);
 END
GO
USE BelcorpEcuador;
GO
 IF NOT EXISTS  (SELECT * FROM TABLALOGICA WHERE TABLALOGICAID =156)
 BEGIN
    INSERT INTO TABLALOGICA  VALUES (156,'Campanas AppCatalogo');
    INSERT INTO TABLALOGICADATOS  VALUES (15601,156,01,'Campanas Atras',5);
    INSERT INTO TABLALOGICADATOS  VALUES (15602,156,02,'Campanas Adelante',2);
 END
GO
USE BelcorpGuatemala;
GO
 IF NOT EXISTS  (SELECT * FROM TABLALOGICA WHERE TABLALOGICAID =156)
 BEGIN
    INSERT INTO TABLALOGICA  VALUES (156,'Campanas AppCatalogo');
    INSERT INTO TABLALOGICADATOS  VALUES (15601,156,01,'Campanas Atras',5);
    INSERT INTO TABLALOGICADATOS  VALUES (15602,156,02,'Campanas Adelante',2);
 END
GO
USE BelcorpMexico;
GO
 IF NOT EXISTS  (SELECT * FROM TABLALOGICA WHERE TABLALOGICAID =156)
 BEGIN
    INSERT INTO TABLALOGICA  VALUES (156,'Campanas AppCatalogo');
    INSERT INTO TABLALOGICADATOS  VALUES (15601,156,01,'Campanas Atras',5);
    INSERT INTO TABLALOGICADATOS  VALUES (15602,156,02,'Campanas Adelante',2);
 END
GO
USE BelcorpPanama;
GO
 IF NOT EXISTS  (SELECT * FROM TABLALOGICA WHERE TABLALOGICAID =156)
 BEGIN
    INSERT INTO TABLALOGICA  VALUES (156,'Campanas AppCatalogo');
    INSERT INTO TABLALOGICADATOS  VALUES (15601,156,01,'Campanas Atras',5);
    INSERT INTO TABLALOGICADATOS  VALUES (15602,156,02,'Campanas Adelante',2);
 END
GO
USE BelcorpPeru;
GO
 IF NOT EXISTS  (SELECT * FROM TABLALOGICA WHERE TABLALOGICAID =156)
 BEGIN
    INSERT INTO TABLALOGICA  VALUES (156,'Campanas AppCatalogo');
    INSERT INTO TABLALOGICADATOS  VALUES (15601,156,01,'Campanas Atras',5);
    INSERT INTO TABLALOGICADATOS  VALUES (15602,156,02,'Campanas Adelante',2);
 END
GO
USE BelcorpPuertoRico;
GO
 IF NOT EXISTS  (SELECT * FROM TABLALOGICA WHERE TABLALOGICAID =156)
 BEGIN
    INSERT INTO TABLALOGICA  VALUES (156,'Campanas AppCatalogo');
    INSERT INTO TABLALOGICADATOS  VALUES (15601,156,01,'Campanas Atras',5);
    INSERT INTO TABLALOGICADATOS  VALUES (15602,156,02,'Campanas Adelante',2);
 END
GO
USE BelcorpSalvador;
GO
 IF NOT EXISTS  (SELECT * FROM TABLALOGICA WHERE TABLALOGICAID =156)
 BEGIN
    INSERT INTO TABLALOGICA  VALUES (156,'Campanas AppCatalogo');
    INSERT INTO TABLALOGICADATOS  VALUES (15601,156,01,'Campanas Atras',5);
    INSERT INTO TABLALOGICADATOS  VALUES (15602,156,02,'Campanas Adelante',2);
 END
GO
