USE BelcorpPeru
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilOrigen' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilOrigen] BIT
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilFin' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilFin] BIT
END
GO

USE BelcorpMexico
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilOrigen' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilOrigen] BIT
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilFin' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilFin] BIT
END
GO

USE BelcorpColombia
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilOrigen' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilOrigen] BIT
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilFin' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilFin] BIT
END
GO

USE BelcorpVenezuela
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilOrigen' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilOrigen] BIT
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilFin' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilFin] BIT
END
GO

USE BelcorpSalvador
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilOrigen' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilOrigen] BIT
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilFin' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilFin] BIT
END
GO

USE BelcorpPuertoRico
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilOrigen' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilOrigen] BIT
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilFin' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilFin] BIT
END
GO

USE BelcorpPanama
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilOrigen' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilOrigen] BIT
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilFin' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilFin] BIT
END
GO

USE BelcorpGuatemala
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilOrigen' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilOrigen] BIT
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilFin' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilFin] BIT
END
GO

USE BelcorpEcuador
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilOrigen' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilOrigen] BIT
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilFin' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilFin] BIT
END
GO

USE BelcorpDominicana
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilOrigen' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilOrigen] BIT
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilFin' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilFin] BIT
END
GO

USE BelcorpCostaRica
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilOrigen' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilOrigen] BIT
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilFin' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilFin] BIT
END
GO

USE BelcorpChile
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilOrigen' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilOrigen] BIT
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilFin' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilFin] BIT
END
GO

USE BelcorpBolivia
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilOrigen' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilOrigen] BIT
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'EsMovilFin' AND TABLE_NAME = 'CDRWeb')
BEGIN
	ALTER TABLE [dbo].[CDRWeb] ADD [EsMovilFin] BIT
END
GO