USE BelcorpPeru
GO

IF	NOT EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION LIKE '%REVISTA DIGITAL%'
	)
BEGIN
	DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0
	
	SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = MAX(TABLALOGICAID) + 1 
	FROM TABLALOGICA

	PRINT 'INSERTING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	INSERT INTO TABLALOGICA(
	TablaLogicaID
	,Descripcion
	)
	VALUES(
	@ID_TABLA_LOGICA_REVISTA_DIGITAL
	,'REVISTA DIGITAL'
	)
END

USE BelcorpMexico
GO

IF	NOT EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION LIKE '%REVISTA DIGITAL%'
	)
BEGIN
	DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0
	
	SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = MAX(TABLALOGICAID) + 1 
	FROM TABLALOGICA

	PRINT 'INSERTING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	INSERT INTO TABLALOGICA(
	TablaLogicaID
	,Descripcion
	)
	VALUES(
	@ID_TABLA_LOGICA_REVISTA_DIGITAL
	,'REVISTA DIGITAL'
	)
END

USE BelcorpColombia
GO

IF	NOT EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION LIKE '%REVISTA DIGITAL%'
	)
BEGIN
	DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0
	
	SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = MAX(TABLALOGICAID) + 1 
	FROM TABLALOGICA

	PRINT 'INSERTING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	INSERT INTO TABLALOGICA(
	TablaLogicaID
	,Descripcion
	)
	VALUES(
	@ID_TABLA_LOGICA_REVISTA_DIGITAL
	,'REVISTA DIGITAL'
	)
END

USE BelcorpVenezuela
GO

IF	NOT EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION LIKE '%REVISTA DIGITAL%'
	)
BEGIN
	DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0
	
	SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = MAX(TABLALOGICAID) + 1 
	FROM TABLALOGICA

	PRINT 'INSERTING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	INSERT INTO TABLALOGICA(
	TablaLogicaID
	,Descripcion
	)
	VALUES(
	@ID_TABLA_LOGICA_REVISTA_DIGITAL
	,'REVISTA DIGITAL'
	)
END

USE BelcorpSalvador
GO

IF	NOT EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION LIKE '%REVISTA DIGITAL%'
	)
BEGIN
	DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0
	
	SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = MAX(TABLALOGICAID) + 1 
	FROM TABLALOGICA

	PRINT 'INSERTING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	INSERT INTO TABLALOGICA(
	TablaLogicaID
	,Descripcion
	)
	VALUES(
	@ID_TABLA_LOGICA_REVISTA_DIGITAL
	,'REVISTA DIGITAL'
	)
END

USE BelcorpPuertoRico
GO

IF	NOT EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION LIKE '%REVISTA DIGITAL%'
	)
BEGIN
	DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0
	
	SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = MAX(TABLALOGICAID) + 1 
	FROM TABLALOGICA

	PRINT 'INSERTING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	INSERT INTO TABLALOGICA(
	TablaLogicaID
	,Descripcion
	)
	VALUES(
	@ID_TABLA_LOGICA_REVISTA_DIGITAL
	,'REVISTA DIGITAL'
	)
END

USE BelcorpPanama
GO

IF	NOT EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION LIKE '%REVISTA DIGITAL%'
	)
BEGIN
	DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0
	
	SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = MAX(TABLALOGICAID) + 1 
	FROM TABLALOGICA

	PRINT 'INSERTING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	INSERT INTO TABLALOGICA(
	TablaLogicaID
	,Descripcion
	)
	VALUES(
	@ID_TABLA_LOGICA_REVISTA_DIGITAL
	,'REVISTA DIGITAL'
	)
END

USE BelcorpGuatemala
GO

IF	NOT EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION LIKE '%REVISTA DIGITAL%'
	)
BEGIN
	DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0
	
	SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = MAX(TABLALOGICAID) + 1 
	FROM TABLALOGICA

	PRINT 'INSERTING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	INSERT INTO TABLALOGICA(
	TablaLogicaID
	,Descripcion
	)
	VALUES(
	@ID_TABLA_LOGICA_REVISTA_DIGITAL
	,'REVISTA DIGITAL'
	)
END

USE BelcorpEcuador
GO

IF	NOT EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION LIKE '%REVISTA DIGITAL%'
	)
BEGIN
	DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0
	
	SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = MAX(TABLALOGICAID) + 1 
	FROM TABLALOGICA

	PRINT 'INSERTING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	INSERT INTO TABLALOGICA(
	TablaLogicaID
	,Descripcion
	)
	VALUES(
	@ID_TABLA_LOGICA_REVISTA_DIGITAL
	,'REVISTA DIGITAL'
	)
END

USE BelcorpDominicana
GO

IF	NOT EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION LIKE '%REVISTA DIGITAL%'
	)
BEGIN
	DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0
	
	SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = MAX(TABLALOGICAID) + 1 
	FROM TABLALOGICA

	PRINT 'INSERTING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	INSERT INTO TABLALOGICA(
	TablaLogicaID
	,Descripcion
	)
	VALUES(
	@ID_TABLA_LOGICA_REVISTA_DIGITAL
	,'REVISTA DIGITAL'
	)
END

USE BelcorpCostaRica
GO

IF	NOT EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION LIKE '%REVISTA DIGITAL%'
	)
BEGIN
	DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0
	
	SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = MAX(TABLALOGICAID) + 1 
	FROM TABLALOGICA

	PRINT 'INSERTING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	INSERT INTO TABLALOGICA(
	TablaLogicaID
	,Descripcion
	)
	VALUES(
	@ID_TABLA_LOGICA_REVISTA_DIGITAL
	,'REVISTA DIGITAL'
	)
END

USE BelcorpChile
GO

IF	NOT EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION LIKE '%REVISTA DIGITAL%'
	)
BEGIN
	DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0
	
	SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = MAX(TABLALOGICAID) + 1 
	FROM TABLALOGICA

	PRINT 'INSERTING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	INSERT INTO TABLALOGICA(
	TablaLogicaID
	,Descripcion
	)
	VALUES(
	@ID_TABLA_LOGICA_REVISTA_DIGITAL
	,'REVISTA DIGITAL'
	)
END

USE BelcorpBolivia
GO

IF	NOT EXISTS(
	SELECT 1
	FROM TABLALOGICA
	WHERE DESCRIPCION LIKE '%REVISTA DIGITAL%'
	)
BEGIN
	DECLARE @ID_TABLA_LOGICA_REVISTA_DIGITAL INT = 0
	
	SELECT @ID_TABLA_LOGICA_REVISTA_DIGITAL = MAX(TABLALOGICAID) + 1 
	FROM TABLALOGICA

	PRINT 'INSERTING ''REVISTA DIGITAL'' FROM TABLALOGICA'

	INSERT INTO TABLALOGICA(
	TablaLogicaID
	,Descripcion
	)
	VALUES(
	@ID_TABLA_LOGICA_REVISTA_DIGITAL
	,'REVISTA DIGITAL'
	)
END

