USE BELCORPPERU_BPT
GO

DECLARE @REVISTA_DIGITAL_ID INT = 3
--
DECLARE @LOGO_MENU_OFERTAS_ACTIVA VARCHAR(50) = 'LogoMenuOfertasActiva'
--
DECLARE @LOGO_MENU_OFERTAS_NO_ACTIVA VARCHAR(50) = 'LogoMenuOfertasNoActiva'

IF EXISTS(
SELECT 1
FROM CONFIGURACIONPAISDATOS CPD
WHERE CPD.CONFIGURACIONPAISID =@REVISTA_DIGITAL_ID
AND CPD.CODIGO = @LOGO_MENU_OFERTAS_ACTIVA
)
BEGIN
	PRINT 'ELIMINANDO ' + @LOGO_MENU_OFERTAS_ACTIVA + ' DE CONFIGURACIONPAISDATOS'

	DELETE CPD
	FROM CONFIGURACIONPAISDATOS CPD
	WHERE CPD.CONFIGURACIONPAISID =@REVISTA_DIGITAL_ID
	AND CPD.CODIGO = @LOGO_MENU_OFERTAS_ACTIVA
END

IF EXISTS(
SELECT 1
FROM CONFIGURACIONPAISDATOS CPD
WHERE CPD.CONFIGURACIONPAISID =@REVISTA_DIGITAL_ID
AND CPD.CODIGO = @LOGO_MENU_OFERTAS_NO_ACTIVA
)
BEGIN
	PRINT 'ELIMINANDO ' + @LOGO_MENU_OFERTAS_NO_ACTIVA + ' DE CONFIGURACIONPAISDATOS'
	
	DELETE CPD
	FROM CONFIGURACIONPAISDATOS CPD
	WHERE CPD.CONFIGURACIONPAISID =@REVISTA_DIGITAL_ID
	AND CPD.CODIGO = @LOGO_MENU_OFERTAS_NO_ACTIVA
END

