//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Consultoras.Web.WsFuncionesSoap {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsFuncionesSoap.WsFuncionesSoap")]
    public interface WsFuncionesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerMatrizProl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Portal.Consultoras.Web.WsFuncionesSoap.SetDatos ObtenerMatrizProl(string pais, string campana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerMatrizProl", ReplyAction="*")]
        System.Threading.Tasks.Task<Portal.Consultoras.Web.WsFuncionesSoap.SetDatos> ObtenerMatrizProlAsync(string pais, string campana);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDatos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataSet dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Data.DataSet data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsFuncionesSoapChannel : Portal.Consultoras.Web.WsFuncionesSoap.WsFuncionesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsFuncionesSoapClient : System.ServiceModel.ClientBase<Portal.Consultoras.Web.WsFuncionesSoap.WsFuncionesSoap>, Portal.Consultoras.Web.WsFuncionesSoap.WsFuncionesSoap {
        
        public WsFuncionesSoapClient() {
        }
        
        public WsFuncionesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsFuncionesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsFuncionesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsFuncionesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Portal.Consultoras.Web.WsFuncionesSoap.SetDatos ObtenerMatrizProl(string pais, string campana) {
            return base.Channel.ObtenerMatrizProl(pais, campana);
        }
        
        public System.Threading.Tasks.Task<Portal.Consultoras.Web.WsFuncionesSoap.SetDatos> ObtenerMatrizProlAsync(string pais, string campana) {
            return base.Channel.ObtenerMatrizProlAsync(pais, campana);
        }
    }
}
