GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'LogCargaPedido' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.LogCargaPedido
	DROP COLUMN VersionProl;
END
GO