GO
IF (EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ValidacionAutomaticaPROL' AND COLUMN_NAME = 'VersionProl'))
BEGIN
    ALTER TABLE dbo.ValidacionAutomaticaPROL
	DROP COLUMN VersionProl;
END
GO