USE BelcorpPeru
GO

IF not exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
	ALTER TABLE dbo.MenuApp ADD VigenciaNueva date NULL;
END

USE BelcorpMexico
GO

IF not exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
	ALTER TABLE dbo.MenuApp ADD VigenciaNueva date NULL;
END


USE BelcorpColombia
GO

IF not exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
	ALTER TABLE dbo.MenuApp ADD VigenciaNueva date NULL;
END

USE BelcorpSalvador
GO

IF not exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
	ALTER TABLE dbo.MenuApp ADD VigenciaNueva date NULL;
END

USE BelcorpPuertoRico
GO

IF not exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
	ALTER TABLE dbo.MenuApp ADD VigenciaNueva date NULL;
END

USE BelcorpPanama
GO

IF not exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
	ALTER TABLE dbo.MenuApp ADD VigenciaNueva date NULL;
END

USE BelcorpGuatemala
GO

IF not exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
	ALTER TABLE dbo.MenuApp ADD VigenciaNueva date NULL;
END

USE BelcorpEcuador
GO

IF not exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
	ALTER TABLE dbo.MenuApp ADD VigenciaNueva date NULL;
END

USE BelcorpDominicana
GO

IF not exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
	ALTER TABLE dbo.MenuApp ADD VigenciaNueva date NULL;
END

USE BelcorpCostaRica
GO

IF not exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
	ALTER TABLE dbo.MenuApp ADD VigenciaNueva date NULL;
END

USE BelcorpChile
GO

IF not exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
	ALTER TABLE dbo.MenuApp ADD VigenciaNueva date NULL;
END

USE BelcorpBolivia
GO

IF not exists(SELECT TABLE_CATALOG FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'VigenciaNueva' AND TABLE_NAME = 'MenuApp')
BEGIN
	ALTER TABLE dbo.MenuApp ADD VigenciaNueva date NULL;
END