use [BelcorpBolivia]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

/*CREAMOS LA NUEVA OPCIÒN EN MENU SAC PARA EL PERFIL ADMSAC*/
IF  EXISTS (SELECT * 
			   FROM   PERMISO 
			   WHERE DESCRIPCION =@PERMISO) 

BEGIN
--SELECT * FROM PERMISO WHERE DESCRIPCION =@PERMISO
DELETE FROM PERMISO WHERE DESCRIPCION =@PERMISO
SELECT 'EL REGISTRO FUE ELIMINADO'
END
ELSE
BEGIN
SELECT 'EL REGISTRO NO SE ELIMINÒ'
END
go

use [BelcorpChile]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

/*CREAMOS LA NUEVA OPCIÒN EN MENU SAC PARA EL PERFIL ADMSAC*/
IF  EXISTS (SELECT * 
			   FROM   PERMISO 
			   WHERE DESCRIPCION =@PERMISO) 

BEGIN
--SELECT * FROM PERMISO WHERE DESCRIPCION =@PERMISO
DELETE FROM PERMISO WHERE DESCRIPCION =@PERMISO
SELECT 'EL REGISTRO FUE ELIMINADO'
END
ELSE
BEGIN
SELECT 'EL REGISTRO NO SE ELIMINÒ'
END
go

use [BelcorpColombia]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

/*CREAMOS LA NUEVA OPCIÒN EN MENU SAC PARA EL PERFIL ADMSAC*/
IF  EXISTS (SELECT * 
			   FROM   PERMISO 
			   WHERE DESCRIPCION =@PERMISO) 

BEGIN
--SELECT * FROM PERMISO WHERE DESCRIPCION =@PERMISO
DELETE FROM PERMISO WHERE DESCRIPCION =@PERMISO
SELECT 'EL REGISTRO FUE ELIMINADO'
END
ELSE
BEGIN
SELECT 'EL REGISTRO NO SE ELIMINÒ'
END
go

use [BelcorpCostaRica]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

/*CREAMOS LA NUEVA OPCIÒN EN MENU SAC PARA EL PERFIL ADMSAC*/
IF  EXISTS (SELECT * 
			   FROM   PERMISO 
			   WHERE DESCRIPCION =@PERMISO) 

BEGIN
--SELECT * FROM PERMISO WHERE DESCRIPCION =@PERMISO
DELETE FROM PERMISO WHERE DESCRIPCION =@PERMISO
SELECT 'EL REGISTRO FUE ELIMINADO'
END
ELSE
BEGIN
SELECT 'EL REGISTRO NO SE ELIMINÒ'
END
go

use [BelcorpDominicana]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

/*CREAMOS LA NUEVA OPCIÒN EN MENU SAC PARA EL PERFIL ADMSAC*/
IF  EXISTS (SELECT * 
			   FROM   PERMISO 
			   WHERE DESCRIPCION =@PERMISO) 

BEGIN
--SELECT * FROM PERMISO WHERE DESCRIPCION =@PERMISO
DELETE FROM PERMISO WHERE DESCRIPCION =@PERMISO
SELECT 'EL REGISTRO FUE ELIMINADO'
END
ELSE
BEGIN
SELECT 'EL REGISTRO NO SE ELIMINÒ'
END
go

use [BelcorpEcuador]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

/*CREAMOS LA NUEVA OPCIÒN EN MENU SAC PARA EL PERFIL ADMSAC*/
IF  EXISTS (SELECT * 
			   FROM   PERMISO 
			   WHERE DESCRIPCION =@PERMISO) 

BEGIN
--SELECT * FROM PERMISO WHERE DESCRIPCION =@PERMISO
DELETE FROM PERMISO WHERE DESCRIPCION =@PERMISO
SELECT 'EL REGISTRO FUE ELIMINADO'
END
ELSE
BEGIN
SELECT 'EL REGISTRO NO SE ELIMINÒ'
END
go

use [BelcorpGuatemala]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

/*CREAMOS LA NUEVA OPCIÒN EN MENU SAC PARA EL PERFIL ADMSAC*/
IF  EXISTS (SELECT * 
			   FROM   PERMISO 
			   WHERE DESCRIPCION =@PERMISO) 

BEGIN
--SELECT * FROM PERMISO WHERE DESCRIPCION =@PERMISO
DELETE FROM PERMISO WHERE DESCRIPCION =@PERMISO
SELECT 'EL REGISTRO FUE ELIMINADO'
END
ELSE
BEGIN
SELECT 'EL REGISTRO NO SE ELIMINÒ'
END
go

use [BelcorpMexico]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

/*CREAMOS LA NUEVA OPCIÒN EN MENU SAC PARA EL PERFIL ADMSAC*/
IF  EXISTS (SELECT * 
			   FROM   PERMISO 
			   WHERE DESCRIPCION =@PERMISO) 

BEGIN
--SELECT * FROM PERMISO WHERE DESCRIPCION =@PERMISO
DELETE FROM PERMISO WHERE DESCRIPCION =@PERMISO
SELECT 'EL REGISTRO FUE ELIMINADO'
END
ELSE
BEGIN
SELECT 'EL REGISTRO NO SE ELIMINÒ'
END
go

use [BelcorpPanama]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

/*CREAMOS LA NUEVA OPCIÒN EN MENU SAC PARA EL PERFIL ADMSAC*/
IF  EXISTS (SELECT * 
			   FROM   PERMISO 
			   WHERE DESCRIPCION =@PERMISO) 

BEGIN
--SELECT * FROM PERMISO WHERE DESCRIPCION =@PERMISO
DELETE FROM PERMISO WHERE DESCRIPCION =@PERMISO
SELECT 'EL REGISTRO FUE ELIMINADO'
END
ELSE
BEGIN
SELECT 'EL REGISTRO NO SE ELIMINÒ'
END
go

use [BelcorpPeru]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

/*CREAMOS LA NUEVA OPCIÒN EN MENU SAC PARA EL PERFIL ADMSAC*/
IF  EXISTS (SELECT * 
			   FROM   PERMISO 
			   WHERE DESCRIPCION =@PERMISO) 

BEGIN
--SELECT * FROM PERMISO WHERE DESCRIPCION =@PERMISO
DELETE FROM PERMISO WHERE DESCRIPCION =@PERMISO
SELECT 'EL REGISTRO FUE ELIMINADO'
END
ELSE
BEGIN
SELECT 'EL REGISTRO NO SE ELIMINÒ'
END
go

use [BelcorpPuertoRico]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

/*CREAMOS LA NUEVA OPCIÒN EN MENU SAC PARA EL PERFIL ADMSAC*/
IF  EXISTS (SELECT * 
			   FROM   PERMISO 
			   WHERE DESCRIPCION =@PERMISO) 

BEGIN
--SELECT * FROM PERMISO WHERE DESCRIPCION =@PERMISO
DELETE FROM PERMISO WHERE DESCRIPCION =@PERMISO
SELECT 'EL REGISTRO FUE ELIMINADO'
END
ELSE
BEGIN
SELECT 'EL REGISTRO NO SE ELIMINÒ'
END
go

use [BelcorpSalvador]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

/*CREAMOS LA NUEVA OPCIÒN EN MENU SAC PARA EL PERFIL ADMSAC*/
IF  EXISTS (SELECT * 
			   FROM   PERMISO 
			   WHERE DESCRIPCION =@PERMISO) 

BEGIN
--SELECT * FROM PERMISO WHERE DESCRIPCION =@PERMISO
DELETE FROM PERMISO WHERE DESCRIPCION =@PERMISO
SELECT 'EL REGISTRO FUE ELIMINADO'
END
ELSE
BEGIN
SELECT 'EL REGISTRO NO SE ELIMINÒ'
END
go