use [BelcorpBolivia]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF  EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   DELETE
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			   SELECT 'EL REGISTRO FUE ELIMINADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE ELIMINÒ'
			   END

go

use [BelcorpChile]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF  EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   DELETE
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			   SELECT 'EL REGISTRO FUE ELIMINADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE ELIMINÒ'
			   END

go

use [BelcorpColombia]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF  EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   DELETE
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			   SELECT 'EL REGISTRO FUE ELIMINADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE ELIMINÒ'
			   END

go

use [BelcorpCostaRica]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF  EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   DELETE
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			   SELECT 'EL REGISTRO FUE ELIMINADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE ELIMINÒ'
			   END

go

use [BelcorpDominicana]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF  EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   DELETE
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			   SELECT 'EL REGISTRO FUE ELIMINADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE ELIMINÒ'
			   END

go

use [BelcorpEcuador]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF  EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   DELETE
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			   SELECT 'EL REGISTRO FUE ELIMINADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE ELIMINÒ'
			   END

go

use [BelcorpGuatemala]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF  EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   DELETE
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			   SELECT 'EL REGISTRO FUE ELIMINADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE ELIMINÒ'
			   END

go

use [BelcorpMexico]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF  EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   DELETE
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			   SELECT 'EL REGISTRO FUE ELIMINADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE ELIMINÒ'
			   END

go

use [BelcorpPanama]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF  EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   DELETE
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			   SELECT 'EL REGISTRO FUE ELIMINADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE ELIMINÒ'
			   END

go

use [BelcorpPeru]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF  EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   DELETE
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			   SELECT 'EL REGISTRO FUE ELIMINADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE ELIMINÒ'
			   END

go

use [BelcorpPuertoRico]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF  EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   DELETE
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			   SELECT 'EL REGISTRO FUE ELIMINADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE ELIMINÒ'
			   END

go

use [BelcorpSalvador]	
go

DECLARE @PERMISO AS VARCHAR(128)='Pedidos de campaña'
DECLARE @PERMISOID AS INT

IF  EXISTS (SELECT * 
			   FROM   rolpermiso
			   WHERE ROLID=3 AND PERMISOID IN(SELECT PERMISOID FROM PERMISO WHERE DESCRIPCION=@PERMISO)
			    ) 
			   begin
			   DELETE
			   FROM PERMISO WHERE DESCRIPCION=@PERMISO
			   SELECT 'EL REGISTRO FUE ELIMINADO'
			   end
			   ELSE
			   BEGIN
			   SELECT 'EL REGISTRO NO SE ELIMINÒ'
			   END

go