use [BelcorpBolivia]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[Updpedidowebindicadorenviadosinmarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[Updpedidowebindicadorenviadosinmarcar]
GO
/*         
CREADO POR  : PAQUIRRI SEPERAK         
FECHA : 24/06/2019         
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS  
*/ 
CREATE PROCEDURE [DBO].[Updpedidowebindicadorenviadosinmarcar] 
  -- EN ESTE SP SE COLOCA EL INDICADORGPR = 1 
  @NUEVONROLOTE          INT, 
  @FIRMARPEDIDO          BIT, 
  @ESTADO                TINYINT, 
  @MENSAJE               NVARCHAR(255), 
  @MENSAJEEXCEPCION      VARCHAR(2000), 
  @NOMBREARCHIVOCABECERA VARCHAR(100) = NULL, 
  @NOMBREARCHIVODETALLE  VARCHAR (100) = NULL, 
  @NOMBRESERVER          VARCHAR(100) = NULL 
AS 
  BEGIN 
      -- ACTUALIZA ESTADO DE PEDIDOS PARA DESCARGA 
      -- ACTUALIZA EL INDICADORGPR 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 
      DECLARE @INDICADORGPRPAIS BIT; 

      SELECT @INDICADORGPRPAIS = ISNULL(PEDIDORECHAZADO, 0) 
      FROM   PAIS 
      WHERE  ESTADOACTIVO = 1; 

      UPDATE DBO.PEDIDODESCARGASINMARCAR 
      SET    ESTADO = @ESTADO, 
             MENSAJE = @MENSAJE, 
             MENSAJEEXCEPCION = @MENSAJEEXCEPCION, 
             FECHAFIN = @FECHAGENERAL, 
             NOMBREARCHIVOCABECERA = @NOMBREARCHIVOCABECERA, 
             NOMBREARCHIVODETALLE = @NOMBREARCHIVODETALLE, 
             NOMBRESERVER = @NOMBRESERVER 
      WHERE  NROLOTE = @NUEVONROLOTE; 

	  UPDATE PedidoDescargaValidador SET ESTADO=0 
  END 
GO


use [BelcorpChile]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[Updpedidowebindicadorenviadosinmarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[Updpedidowebindicadorenviadosinmarcar]
GO
/*         
CREADO POR  : PAQUIRRI SEPERAK         
FECHA : 24/06/2019         
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS  
*/ 
CREATE PROCEDURE [DBO].[Updpedidowebindicadorenviadosinmarcar] 
  -- EN ESTE SP SE COLOCA EL INDICADORGPR = 1 
  @NUEVONROLOTE          INT, 
  @FIRMARPEDIDO          BIT, 
  @ESTADO                TINYINT, 
  @MENSAJE               NVARCHAR(255), 
  @MENSAJEEXCEPCION      VARCHAR(2000), 
  @NOMBREARCHIVOCABECERA VARCHAR(100) = NULL, 
  @NOMBREARCHIVODETALLE  VARCHAR (100) = NULL, 
  @NOMBRESERVER          VARCHAR(100) = NULL 
AS 
  BEGIN 
      -- ACTUALIZA ESTADO DE PEDIDOS PARA DESCARGA 
      -- ACTUALIZA EL INDICADORGPR 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 
      DECLARE @INDICADORGPRPAIS BIT; 

      SELECT @INDICADORGPRPAIS = ISNULL(PEDIDORECHAZADO, 0) 
      FROM   PAIS 
      WHERE  ESTADOACTIVO = 1; 

      UPDATE DBO.PEDIDODESCARGASINMARCAR 
      SET    ESTADO = @ESTADO, 
             MENSAJE = @MENSAJE, 
             MENSAJEEXCEPCION = @MENSAJEEXCEPCION, 
             FECHAFIN = @FECHAGENERAL, 
             NOMBREARCHIVOCABECERA = @NOMBREARCHIVOCABECERA, 
             NOMBREARCHIVODETALLE = @NOMBREARCHIVODETALLE, 
             NOMBRESERVER = @NOMBRESERVER 
      WHERE  NROLOTE = @NUEVONROLOTE; 
	  UPDATE PedidoDescargaValidador SET ESTADO=0 
  END 
GO


use [BelcorpColombia]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[Updpedidowebindicadorenviadosinmarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[Updpedidowebindicadorenviadosinmarcar]
GO
/*         
CREADO POR  : PAQUIRRI SEPERAK         
FECHA : 24/06/2019         
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS  
*/ 
CREATE PROCEDURE [DBO].[Updpedidowebindicadorenviadosinmarcar] 
  -- EN ESTE SP SE COLOCA EL INDICADORGPR = 1 
  @NUEVONROLOTE          INT, 
  @FIRMARPEDIDO          BIT, 
  @ESTADO                TINYINT, 
  @MENSAJE               NVARCHAR(255), 
  @MENSAJEEXCEPCION      VARCHAR(2000), 
  @NOMBREARCHIVOCABECERA VARCHAR(100) = NULL, 
  @NOMBREARCHIVODETALLE  VARCHAR (100) = NULL, 
  @NOMBRESERVER          VARCHAR(100) = NULL 
AS 
  BEGIN 
      -- ACTUALIZA ESTADO DE PEDIDOS PARA DESCARGA 
      -- ACTUALIZA EL INDICADORGPR 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 
      DECLARE @INDICADORGPRPAIS BIT; 

      SELECT @INDICADORGPRPAIS = ISNULL(PEDIDORECHAZADO, 0) 
      FROM   PAIS 
      WHERE  ESTADOACTIVO = 1; 

      UPDATE DBO.PEDIDODESCARGASINMARCAR 
      SET    ESTADO = @ESTADO, 
             MENSAJE = @MENSAJE, 
             MENSAJEEXCEPCION = @MENSAJEEXCEPCION, 
             FECHAFIN = @FECHAGENERAL, 
             NOMBREARCHIVOCABECERA = @NOMBREARCHIVOCABECERA, 
             NOMBREARCHIVODETALLE = @NOMBREARCHIVODETALLE, 
             NOMBRESERVER = @NOMBRESERVER 
      WHERE  NROLOTE = @NUEVONROLOTE; 
	  UPDATE PedidoDescargaValidador SET ESTADO=0 
  END 
GO


use [BelcorpCostaRica]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[Updpedidowebindicadorenviadosinmarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[Updpedidowebindicadorenviadosinmarcar]
GO
/*         
CREADO POR  : PAQUIRRI SEPERAK         
FECHA : 24/06/2019         
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS  
*/ 
CREATE PROCEDURE [DBO].[Updpedidowebindicadorenviadosinmarcar] 
  -- EN ESTE SP SE COLOCA EL INDICADORGPR = 1 
  @NUEVONROLOTE          INT, 
  @FIRMARPEDIDO          BIT, 
  @ESTADO                TINYINT, 
  @MENSAJE               NVARCHAR(255), 
  @MENSAJEEXCEPCION      VARCHAR(2000), 
  @NOMBREARCHIVOCABECERA VARCHAR(100) = NULL, 
  @NOMBREARCHIVODETALLE  VARCHAR (100) = NULL, 
  @NOMBRESERVER          VARCHAR(100) = NULL 
AS 
  BEGIN 
      -- ACTUALIZA ESTADO DE PEDIDOS PARA DESCARGA 
      -- ACTUALIZA EL INDICADORGPR 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 
      DECLARE @INDICADORGPRPAIS BIT; 

      SELECT @INDICADORGPRPAIS = ISNULL(PEDIDORECHAZADO, 0) 
      FROM   PAIS 
      WHERE  ESTADOACTIVO = 1; 

      UPDATE DBO.PEDIDODESCARGASINMARCAR 
      SET    ESTADO = @ESTADO, 
             MENSAJE = @MENSAJE, 
             MENSAJEEXCEPCION = @MENSAJEEXCEPCION, 
             FECHAFIN = @FECHAGENERAL, 
             NOMBREARCHIVOCABECERA = @NOMBREARCHIVOCABECERA, 
             NOMBREARCHIVODETALLE = @NOMBREARCHIVODETALLE, 
             NOMBRESERVER = @NOMBRESERVER 
      WHERE  NROLOTE = @NUEVONROLOTE; 
	  UPDATE PedidoDescargaValidador SET ESTADO=0 
  END 
GO


use [BelcorpDominicana]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[Updpedidowebindicadorenviadosinmarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[Updpedidowebindicadorenviadosinmarcar]
GO
/*         
CREADO POR  : PAQUIRRI SEPERAK         
FECHA : 24/06/2019         
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS  
*/ 
CREATE PROCEDURE [DBO].[Updpedidowebindicadorenviadosinmarcar] 
  -- EN ESTE SP SE COLOCA EL INDICADORGPR = 1 
  @NUEVONROLOTE          INT, 
  @FIRMARPEDIDO          BIT, 
  @ESTADO                TINYINT, 
  @MENSAJE               NVARCHAR(255), 
  @MENSAJEEXCEPCION      VARCHAR(2000), 
  @NOMBREARCHIVOCABECERA VARCHAR(100) = NULL, 
  @NOMBREARCHIVODETALLE  VARCHAR (100) = NULL, 
  @NOMBRESERVER          VARCHAR(100) = NULL 
AS 
  BEGIN 
      -- ACTUALIZA ESTADO DE PEDIDOS PARA DESCARGA 
      -- ACTUALIZA EL INDICADORGPR 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 
      DECLARE @INDICADORGPRPAIS BIT; 

      SELECT @INDICADORGPRPAIS = ISNULL(PEDIDORECHAZADO, 0) 
      FROM   PAIS 
      WHERE  ESTADOACTIVO = 1; 

      UPDATE DBO.PEDIDODESCARGASINMARCAR 
      SET    ESTADO = @ESTADO, 
             MENSAJE = @MENSAJE, 
             MENSAJEEXCEPCION = @MENSAJEEXCEPCION, 
             FECHAFIN = @FECHAGENERAL, 
             NOMBREARCHIVOCABECERA = @NOMBREARCHIVOCABECERA, 
             NOMBREARCHIVODETALLE = @NOMBREARCHIVODETALLE, 
             NOMBRESERVER = @NOMBRESERVER 
      WHERE  NROLOTE = @NUEVONROLOTE; 
	  UPDATE PedidoDescargaValidador SET ESTADO=0 
  END 
GO


use [BelcorpEcuador]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[Updpedidowebindicadorenviadosinmarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[Updpedidowebindicadorenviadosinmarcar]
GO
/*         
CREADO POR  : PAQUIRRI SEPERAK         
FECHA : 24/06/2019         
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS  
*/ 
CREATE PROCEDURE [DBO].[Updpedidowebindicadorenviadosinmarcar] 
  -- EN ESTE SP SE COLOCA EL INDICADORGPR = 1 
  @NUEVONROLOTE          INT, 
  @FIRMARPEDIDO          BIT, 
  @ESTADO                TINYINT, 
  @MENSAJE               NVARCHAR(255), 
  @MENSAJEEXCEPCION      VARCHAR(2000), 
  @NOMBREARCHIVOCABECERA VARCHAR(100) = NULL, 
  @NOMBREARCHIVODETALLE  VARCHAR (100) = NULL, 
  @NOMBRESERVER          VARCHAR(100) = NULL 
AS 
  BEGIN 
      -- ACTUALIZA ESTADO DE PEDIDOS PARA DESCARGA 
      -- ACTUALIZA EL INDICADORGPR 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 
      DECLARE @INDICADORGPRPAIS BIT; 

      SELECT @INDICADORGPRPAIS = ISNULL(PEDIDORECHAZADO, 0) 
      FROM   PAIS 
      WHERE  ESTADOACTIVO = 1; 

      UPDATE DBO.PEDIDODESCARGASINMARCAR 
      SET    ESTADO = @ESTADO, 
             MENSAJE = @MENSAJE, 
             MENSAJEEXCEPCION = @MENSAJEEXCEPCION, 
             FECHAFIN = @FECHAGENERAL, 
             NOMBREARCHIVOCABECERA = @NOMBREARCHIVOCABECERA, 
             NOMBREARCHIVODETALLE = @NOMBREARCHIVODETALLE, 
             NOMBRESERVER = @NOMBRESERVER 
      WHERE  NROLOTE = @NUEVONROLOTE; 
	  UPDATE PedidoDescargaValidador SET ESTADO=0 
  END 
GO


use [BelcorpGuatemala]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[Updpedidowebindicadorenviadosinmarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[Updpedidowebindicadorenviadosinmarcar]
GO
/*         
CREADO POR  : PAQUIRRI SEPERAK         
FECHA : 24/06/2019         
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS  
*/ 
CREATE PROCEDURE [DBO].[Updpedidowebindicadorenviadosinmarcar] 
  -- EN ESTE SP SE COLOCA EL INDICADORGPR = 1 
  @NUEVONROLOTE          INT, 
  @FIRMARPEDIDO          BIT, 
  @ESTADO                TINYINT, 
  @MENSAJE               NVARCHAR(255), 
  @MENSAJEEXCEPCION      VARCHAR(2000), 
  @NOMBREARCHIVOCABECERA VARCHAR(100) = NULL, 
  @NOMBREARCHIVODETALLE  VARCHAR (100) = NULL, 
  @NOMBRESERVER          VARCHAR(100) = NULL 
AS 
  BEGIN 
      -- ACTUALIZA ESTADO DE PEDIDOS PARA DESCARGA 
      -- ACTUALIZA EL INDICADORGPR 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 
      DECLARE @INDICADORGPRPAIS BIT; 

      SELECT @INDICADORGPRPAIS = ISNULL(PEDIDORECHAZADO, 0) 
      FROM   PAIS 
      WHERE  ESTADOACTIVO = 1; 

      UPDATE DBO.PEDIDODESCARGASINMARCAR 
      SET    ESTADO = @ESTADO, 
             MENSAJE = @MENSAJE, 
             MENSAJEEXCEPCION = @MENSAJEEXCEPCION, 
             FECHAFIN = @FECHAGENERAL, 
             NOMBREARCHIVOCABECERA = @NOMBREARCHIVOCABECERA, 
             NOMBREARCHIVODETALLE = @NOMBREARCHIVODETALLE, 
             NOMBRESERVER = @NOMBRESERVER 
      WHERE  NROLOTE = @NUEVONROLOTE; 
	  UPDATE PedidoDescargaValidador SET ESTADO=0 
  END 
GO


use [BelcorpMexico]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[Updpedidowebindicadorenviadosinmarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[Updpedidowebindicadorenviadosinmarcar]
GO
/*         
CREADO POR  : PAQUIRRI SEPERAK         
FECHA : 24/06/2019         
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS  
*/ 
CREATE PROCEDURE [DBO].[Updpedidowebindicadorenviadosinmarcar] 
  -- EN ESTE SP SE COLOCA EL INDICADORGPR = 1 
  @NUEVONROLOTE          INT, 
  @FIRMARPEDIDO          BIT, 
  @ESTADO                TINYINT, 
  @MENSAJE               NVARCHAR(255), 
  @MENSAJEEXCEPCION      VARCHAR(2000), 
  @NOMBREARCHIVOCABECERA VARCHAR(100) = NULL, 
  @NOMBREARCHIVODETALLE  VARCHAR (100) = NULL, 
  @NOMBRESERVER          VARCHAR(100) = NULL 
AS 
  BEGIN 
      -- ACTUALIZA ESTADO DE PEDIDOS PARA DESCARGA 
      -- ACTUALIZA EL INDICADORGPR 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 
      DECLARE @INDICADORGPRPAIS BIT; 

      SELECT @INDICADORGPRPAIS = ISNULL(PEDIDORECHAZADO, 0) 
      FROM   PAIS 
      WHERE  ESTADOACTIVO = 1; 

      UPDATE DBO.PEDIDODESCARGASINMARCAR 
      SET    ESTADO = @ESTADO, 
             MENSAJE = @MENSAJE, 
             MENSAJEEXCEPCION = @MENSAJEEXCEPCION, 
             FECHAFIN = @FECHAGENERAL, 
             NOMBREARCHIVOCABECERA = @NOMBREARCHIVOCABECERA, 
             NOMBREARCHIVODETALLE = @NOMBREARCHIVODETALLE, 
             NOMBRESERVER = @NOMBRESERVER 
      WHERE  NROLOTE = @NUEVONROLOTE; 
	  UPDATE PedidoDescargaValidador SET ESTADO=0 
  END 
GO


use [BelcorpPanama]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[Updpedidowebindicadorenviadosinmarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[Updpedidowebindicadorenviadosinmarcar]
GO
/*         
CREADO POR  : PAQUIRRI SEPERAK         
FECHA : 24/06/2019         
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS  
*/ 
CREATE PROCEDURE [DBO].[Updpedidowebindicadorenviadosinmarcar] 
  -- EN ESTE SP SE COLOCA EL INDICADORGPR = 1 
  @NUEVONROLOTE          INT, 
  @FIRMARPEDIDO          BIT, 
  @ESTADO                TINYINT, 
  @MENSAJE               NVARCHAR(255), 
  @MENSAJEEXCEPCION      VARCHAR(2000), 
  @NOMBREARCHIVOCABECERA VARCHAR(100) = NULL, 
  @NOMBREARCHIVODETALLE  VARCHAR (100) = NULL, 
  @NOMBRESERVER          VARCHAR(100) = NULL 
AS 
  BEGIN 
      -- ACTUALIZA ESTADO DE PEDIDOS PARA DESCARGA 
      -- ACTUALIZA EL INDICADORGPR 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 
      DECLARE @INDICADORGPRPAIS BIT; 

      SELECT @INDICADORGPRPAIS = ISNULL(PEDIDORECHAZADO, 0) 
      FROM   PAIS 
      WHERE  ESTADOACTIVO = 1; 

      UPDATE DBO.PEDIDODESCARGASINMARCAR 
      SET    ESTADO = @ESTADO, 
             MENSAJE = @MENSAJE, 
             MENSAJEEXCEPCION = @MENSAJEEXCEPCION, 
             FECHAFIN = @FECHAGENERAL, 
             NOMBREARCHIVOCABECERA = @NOMBREARCHIVOCABECERA, 
             NOMBREARCHIVODETALLE = @NOMBREARCHIVODETALLE, 
             NOMBRESERVER = @NOMBRESERVER 
      WHERE  NROLOTE = @NUEVONROLOTE; 
	  UPDATE PedidoDescargaValidador SET ESTADO=0 
  END 
GO


use [BelcorpPeru]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[Updpedidowebindicadorenviadosinmarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[Updpedidowebindicadorenviadosinmarcar]
GO
/*         
CREADO POR  : PAQUIRRI SEPERAK         
FECHA : 24/06/2019         
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS  
*/ 
CREATE PROCEDURE [DBO].[Updpedidowebindicadorenviadosinmarcar] 
  -- EN ESTE SP SE COLOCA EL INDICADORGPR = 1 
  @NUEVONROLOTE          INT, 
  @FIRMARPEDIDO          BIT, 
  @ESTADO                TINYINT, 
  @MENSAJE               NVARCHAR(255), 
  @MENSAJEEXCEPCION      VARCHAR(2000), 
  @NOMBREARCHIVOCABECERA VARCHAR(100) = NULL, 
  @NOMBREARCHIVODETALLE  VARCHAR (100) = NULL, 
  @NOMBRESERVER          VARCHAR(100) = NULL 
AS 
  BEGIN 
      -- ACTUALIZA ESTADO DE PEDIDOS PARA DESCARGA 
      -- ACTUALIZA EL INDICADORGPR 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 
      DECLARE @INDICADORGPRPAIS BIT; 

      SELECT @INDICADORGPRPAIS = ISNULL(PEDIDORECHAZADO, 0) 
      FROM   PAIS 
      WHERE  ESTADOACTIVO = 1; 

      UPDATE DBO.PEDIDODESCARGASINMARCAR 
      SET    ESTADO = @ESTADO, 
             MENSAJE = @MENSAJE, 
             MENSAJEEXCEPCION = @MENSAJEEXCEPCION, 
             FECHAFIN = @FECHAGENERAL, 
             NOMBREARCHIVOCABECERA = @NOMBREARCHIVOCABECERA, 
             NOMBREARCHIVODETALLE = @NOMBREARCHIVODETALLE, 
             NOMBRESERVER = @NOMBRESERVER 
      WHERE  NROLOTE = @NUEVONROLOTE; 
	  UPDATE PedidoDescargaValidador SET ESTADO=0 
  END 
GO


use [BelcorpPuertoRico]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[Updpedidowebindicadorenviadosinmarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[Updpedidowebindicadorenviadosinmarcar]
GO
/*         
CREADO POR  : PAQUIRRI SEPERAK         
FECHA : 24/06/2019         
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS  
*/ 
CREATE PROCEDURE [DBO].[Updpedidowebindicadorenviadosinmarcar] 
  -- EN ESTE SP SE COLOCA EL INDICADORGPR = 1 
  @NUEVONROLOTE          INT, 
  @FIRMARPEDIDO          BIT, 
  @ESTADO                TINYINT, 
  @MENSAJE               NVARCHAR(255), 
  @MENSAJEEXCEPCION      VARCHAR(2000), 
  @NOMBREARCHIVOCABECERA VARCHAR(100) = NULL, 
  @NOMBREARCHIVODETALLE  VARCHAR (100) = NULL, 
  @NOMBRESERVER          VARCHAR(100) = NULL 
AS 
  BEGIN 
      -- ACTUALIZA ESTADO DE PEDIDOS PARA DESCARGA 
      -- ACTUALIZA EL INDICADORGPR 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 
      DECLARE @INDICADORGPRPAIS BIT; 

      SELECT @INDICADORGPRPAIS = ISNULL(PEDIDORECHAZADO, 0) 
      FROM   PAIS 
      WHERE  ESTADOACTIVO = 1; 

      UPDATE DBO.PEDIDODESCARGASINMARCAR 
      SET    ESTADO = @ESTADO, 
             MENSAJE = @MENSAJE, 
             MENSAJEEXCEPCION = @MENSAJEEXCEPCION, 
             FECHAFIN = @FECHAGENERAL, 
             NOMBREARCHIVOCABECERA = @NOMBREARCHIVOCABECERA, 
             NOMBREARCHIVODETALLE = @NOMBREARCHIVODETALLE, 
             NOMBRESERVER = @NOMBRESERVER 
      WHERE  NROLOTE = @NUEVONROLOTE; 
	  UPDATE PedidoDescargaValidador SET ESTADO=0 
  END 
GO


use [BelcorpSalvador]	
go
IF EXISTS (
	SELECT * FROM sys.objects 
	WHERE object_id = 
	OBJECT_ID(N'[dbo].[Updpedidowebindicadorenviadosinmarcar]') 
	AND type in (N'P', N'PC')
) 
	DROP PROCEDURE [dbo].[Updpedidowebindicadorenviadosinmarcar]
GO
/*         
CREADO POR  : PAQUIRRI SEPERAK         
FECHA : 24/06/2019         
DESCRIPCIÓN : ACTUALIZA LA CANTIDAD DE PEDIDOS  
*/ 
CREATE PROCEDURE [DBO].[Updpedidowebindicadorenviadosinmarcar] 
  -- EN ESTE SP SE COLOCA EL INDICADORGPR = 1 
  @NUEVONROLOTE          INT, 
  @FIRMARPEDIDO          BIT, 
  @ESTADO                TINYINT, 
  @MENSAJE               NVARCHAR(255), 
  @MENSAJEEXCEPCION      VARCHAR(2000), 
  @NOMBREARCHIVOCABECERA VARCHAR(100) = NULL, 
  @NOMBREARCHIVODETALLE  VARCHAR (100) = NULL, 
  @NOMBRESERVER          VARCHAR(100) = NULL 
AS 
  BEGIN 
      -- ACTUALIZA ESTADO DE PEDIDOS PARA DESCARGA 
      -- ACTUALIZA EL INDICADORGPR 
      DECLARE @FECHAGENERAL DATETIME = DBO.FNOBTENERFECHAHORAPAIS(); 
      DECLARE @INDICADORGPRPAIS BIT; 

      SELECT @INDICADORGPRPAIS = ISNULL(PEDIDORECHAZADO, 0) 
      FROM   PAIS 
      WHERE  ESTADOACTIVO = 1; 

      UPDATE DBO.PEDIDODESCARGASINMARCAR 
      SET    ESTADO = @ESTADO, 
             MENSAJE = @MENSAJE, 
             MENSAJEEXCEPCION = @MENSAJEEXCEPCION, 
             FECHAFIN = @FECHAGENERAL, 
             NOMBREARCHIVOCABECERA = @NOMBREARCHIVOCABECERA, 
             NOMBREARCHIVODETALLE = @NOMBREARCHIVODETALLE, 
             NOMBRESERVER = @NOMBRESERVER 
      WHERE  NROLOTE = @NUEVONROLOTE; 
	  UPDATE PedidoDescargaValidador SET ESTADO=0 
  END 
GO

