//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Consultoras.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.catalogosbelcorp.com/Web/MulticatalogoWebService.asmx")]
        public string Portal_Consultoras_Web_ServiceCatalogosIssuu_MulticatalogoWebService {
            get {
                return ((string)(this["Portal_Consultoras_Web_ServiceCatalogosIssuu_MulticatalogoWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.229.102:8102/AppBelcorp-ProBelcorp-context-root/BusinessPort")]
        public string Portal_Consultoras_Web_ServiceOSBBelcorp_BusinessService {
            get {
                return ((string)(this["Portal_Consultoras_Web_ServiceOSBBelcorp_BusinessService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pelnx12.galileo.ebel:7777/ssiccpeesprd/services/ProcesoMAEPortalConsultora" +
            "WebService")]
        public string Portal_Consultoras_Web_ServiceActualizaDatosConsultoraPeru_ProcesoMAEPortalConsultoraWebServiceImplService {
            get {
                return ((string)(this["Portal_Consultoras_Web_ServiceActualizaDatosConsultoraPeru_ProcesoMAEPortalConsul" +
                    "toraWebServiceImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pelnx32.galileo.ebel:7777/ssiccclesprd/services/ProcesoMAEPortalConsultora" +
            "WebService")]
        public string Portal_Consultoras_Web_ServiceActualizaDatosConsultoraChile_ProcesoMAEPortalConsultoraWebServiceImplService {
            get {
                return ((string)(this["Portal_Consultoras_Web_ServiceActualizaDatosConsultoraChile_ProcesoMAEPortalConsu" +
                    "ltoraWebServiceImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pelnx47.galileo.ebel:7777/ssicceclbprd/services/ProcesoMAEPortalConsultora" +
            "WebService")]
        public string Portal_Consultoras_Web_ServiceActualizaDatosConsultoraEcuador_ProcesoMAEPortalConsultoraWebServiceImplService {
            get {
                return ((string)(this["Portal_Consultoras_Web_ServiceActualizaDatosConsultoraEcuador_ProcesoMAEPortalCon" +
                    "sultoraWebServiceImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.229.103:8102/belcorp/ffvv/ConsultoraPS")]
        public string Portal_Consultoras_Web_ServiceOSBBelcorpConsultora_ConsultoraBS {
            get {
                return ((string)(this["Portal_Consultoras_Web_ServiceOSBBelcorpConsultora_ConsultoraBS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.229.103:8102/belcorp/ffvv/PedidoPS")]
        public string Portal_Consultoras_Web_ServiceOSBBelcorpPedido_PedidoBS {
            get {
                return ((string)(this["Portal_Consultoras_Web_ServiceOSBBelcorpPedido_PedidoBS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://107.23.205.231/test_wsPROLSicc/ServiceStockSsic.asmx")]
        public string Portal_Consultoras_Web_ServicePROL_ServiceStockSsic {
            get {
                return ((string)(this["Portal_Consultoras_Web_ServicePROL_ServiceStockSsic"]));
            }
        }
    }
}
