
USE BelcorpPeru
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_NAME = N'UsuarioExterno')
BEGIN
  DROP TABLE dbo.UsuarioExterno
END
GO


CREATE TABLE UsuarioExterno
(
	CodigoUsuario VARCHAR(20) NOT NULL PRIMARY KEY,
	Proveedor VARCHAR(20) NOT NULL,
	IdAplicacion VARCHAR(50) NOT NULL,
	[Login] VARCHAR(50) NOT NULL,
	Nombres VARCHAR(50) NULL,
	Apellidos VARCHAR(50) NULL,
	FechaNacimiento VARCHAR(20) NULL,
	Correo VARCHAR(50) NULL,
	Genero VARCHAR(10) NULL,
	Ubicacion VARCHAR(30) NULL,
	LinkPerfil VARCHAR(150) NULL,
	FotoPerfil VARCHAR(255) NULL,
	FechaRegistro DATETIME NOT NULL,
	Estado TINYINT NOT NULL
)
GO

