GO
USE BelcorpPeru
GO

IF  EXISTS (SELECT 1
               FROM   TABLALOGICADATOS
               WHERE  TABLALOGICAID = 179)
BEGIN
DELETE FROM TABLALOGICADATOS WHERE TABLALOGICAID= 179
END


IF  EXISTS (SELECT 1
               FROM   TABLALOGICA
               WHERE  TABLALOGICAID = 179)
  BEGIN
  DELETE FROM TABLALOGICA WHERE TABLALOGICAID = 179
  END

GO

GO
USE BelcorpMexico
GO

IF  EXISTS (SELECT 1
               FROM   TABLALOGICADATOS
               WHERE  TABLALOGICAID = 179)
BEGIN
DELETE FROM TABLALOGICADATOS WHERE TABLALOGICAID= 179
END


IF  EXISTS (SELECT 1
               FROM   TABLALOGICA
               WHERE  TABLALOGICAID = 179)
  BEGIN
  DELETE FROM TABLALOGICA WHERE TABLALOGICAID = 179
  END

GO

GO
USE BelcorpColombia
GO

IF  EXISTS (SELECT 1
               FROM   TABLALOGICADATOS
               WHERE  TABLALOGICAID = 179)
BEGIN
DELETE FROM TABLALOGICADATOS WHERE TABLALOGICAID= 179
END


IF  EXISTS (SELECT 1
               FROM   TABLALOGICA
               WHERE  TABLALOGICAID = 179)
  BEGIN
  DELETE FROM TABLALOGICA WHERE TABLALOGICAID = 179
  END

GO

GO
USE BelcorpSalvador
GO

IF  EXISTS (SELECT 1
               FROM   TABLALOGICADATOS
               WHERE  TABLALOGICAID = 179)
BEGIN
DELETE FROM TABLALOGICADATOS WHERE TABLALOGICAID= 179
END


IF  EXISTS (SELECT 1
               FROM   TABLALOGICA
               WHERE  TABLALOGICAID = 179)
  BEGIN
  DELETE FROM TABLALOGICA WHERE TABLALOGICAID = 179
  END

GO

GO
USE BelcorpPuertoRico
GO

IF  EXISTS (SELECT 1
               FROM   TABLALOGICADATOS
               WHERE  TABLALOGICAID = 179)
BEGIN
DELETE FROM TABLALOGICADATOS WHERE TABLALOGICAID= 179
END


IF  EXISTS (SELECT 1
               FROM   TABLALOGICA
               WHERE  TABLALOGICAID = 179)
  BEGIN
  DELETE FROM TABLALOGICA WHERE TABLALOGICAID = 179
  END

GO

GO
USE BelcorpPanama
GO

IF  EXISTS (SELECT 1
               FROM   TABLALOGICADATOS
               WHERE  TABLALOGICAID = 179)
BEGIN
DELETE FROM TABLALOGICADATOS WHERE TABLALOGICAID= 179
END


IF  EXISTS (SELECT 1
               FROM   TABLALOGICA
               WHERE  TABLALOGICAID = 179)
  BEGIN
  DELETE FROM TABLALOGICA WHERE TABLALOGICAID = 179
  END

GO

GO
USE BelcorpGuatemala
GO

IF  EXISTS (SELECT 1
               FROM   TABLALOGICADATOS
               WHERE  TABLALOGICAID = 179)
BEGIN
DELETE FROM TABLALOGICADATOS WHERE TABLALOGICAID= 179
END


IF  EXISTS (SELECT 1
               FROM   TABLALOGICA
               WHERE  TABLALOGICAID = 179)
  BEGIN
  DELETE FROM TABLALOGICA WHERE TABLALOGICAID = 179
  END

GO

GO
USE BelcorpEcuador
GO

IF  EXISTS (SELECT 1
               FROM   TABLALOGICADATOS
               WHERE  TABLALOGICAID = 179)
BEGIN
DELETE FROM TABLALOGICADATOS WHERE TABLALOGICAID= 179
END


IF  EXISTS (SELECT 1
               FROM   TABLALOGICA
               WHERE  TABLALOGICAID = 179)
  BEGIN
  DELETE FROM TABLALOGICA WHERE TABLALOGICAID = 179
  END

GO

GO
USE BelcorpDominicana
GO

IF  EXISTS (SELECT 1
               FROM   TABLALOGICADATOS
               WHERE  TABLALOGICAID = 179)
BEGIN
DELETE FROM TABLALOGICADATOS WHERE TABLALOGICAID= 179
END


IF  EXISTS (SELECT 1
               FROM   TABLALOGICA
               WHERE  TABLALOGICAID = 179)
  BEGIN
  DELETE FROM TABLALOGICA WHERE TABLALOGICAID = 179
  END

GO

GO
USE BelcorpCostaRica
GO

IF  EXISTS (SELECT 1
               FROM   TABLALOGICADATOS
               WHERE  TABLALOGICAID = 179)
BEGIN
DELETE FROM TABLALOGICADATOS WHERE TABLALOGICAID= 179
END


IF  EXISTS (SELECT 1
               FROM   TABLALOGICA
               WHERE  TABLALOGICAID = 179)
  BEGIN
  DELETE FROM TABLALOGICA WHERE TABLALOGICAID = 179
  END

GO

GO
USE BelcorpChile
GO

IF  EXISTS (SELECT 1
               FROM   TABLALOGICADATOS
               WHERE  TABLALOGICAID = 179)
BEGIN
DELETE FROM TABLALOGICADATOS WHERE TABLALOGICAID= 179
END


IF  EXISTS (SELECT 1
               FROM   TABLALOGICA
               WHERE  TABLALOGICAID = 179)
  BEGIN
  DELETE FROM TABLALOGICA WHERE TABLALOGICAID = 179
  END

GO

GO
USE BelcorpBolivia
GO

IF  EXISTS (SELECT 1
               FROM   TABLALOGICADATOS
               WHERE  TABLALOGICAID = 179)
BEGIN
DELETE FROM TABLALOGICADATOS WHERE TABLALOGICAID= 179
END


IF  EXISTS (SELECT 1
               FROM   TABLALOGICA
               WHERE  TABLALOGICAID = 179)
  BEGIN
  DELETE FROM TABLALOGICA WHERE TABLALOGICAID = 179
  END

GO

GO
