USE BelcorpPeru
GO

DELETE ConfiguracionPaisDatos WHERE CODIGO='ENCUESTA' AND ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME')
DELETE CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME'

GO

USE BelcorpMexico
GO

DELETE ConfiguracionPaisDatos WHERE CODIGO='ENCUESTA' AND ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME')
DELETE CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME'

GO

USE BelcorpColombia
GO

DELETE ConfiguracionPaisDatos WHERE CODIGO='ENCUESTA' AND ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME')
DELETE CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME'

GO

USE BelcorpSalvador
GO

DELETE ConfiguracionPaisDatos WHERE CODIGO='ENCUESTA' AND ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME')
DELETE CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME'

GO

USE BelcorpPuertoRico
GO

DELETE ConfiguracionPaisDatos WHERE CODIGO='ENCUESTA' AND ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME')
DELETE CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME'

GO

USE BelcorpPanama
GO

DELETE ConfiguracionPaisDatos WHERE CODIGO='ENCUESTA' AND ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME')
DELETE CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME'

GO

USE BelcorpGuatemala
GO

DELETE ConfiguracionPaisDatos WHERE CODIGO='ENCUESTA' AND ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME')
DELETE CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME'

GO

USE BelcorpEcuador
GO

DELETE ConfiguracionPaisDatos WHERE CODIGO='ENCUESTA' AND ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME')
DELETE CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME'

GO

USE BelcorpDominicana
GO

DELETE ConfiguracionPaisDatos WHERE CODIGO='ENCUESTA' AND ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME')
DELETE CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME'

GO

USE BelcorpCostaRica
GO

DELETE ConfiguracionPaisDatos WHERE CODIGO='ENCUESTA' AND ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME')
DELETE CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME'

GO

USE BelcorpChile
GO

DELETE ConfiguracionPaisDatos WHERE CODIGO='ENCUESTA' AND ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME')
DELETE CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME'

GO

USE BelcorpBolivia
GO

DELETE ConfiguracionPaisDatos WHERE CODIGO='ENCUESTA' AND ConfiguracionPaisID IN (SELECT ConfiguracionPaisID FROM CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME')
DELETE CONFIGURACIONPAIS WHERE CODIGO='FUNCIONALIDAD_HOME'

GO

