USE BelcorpPeru
GO

DELETE MenuApp WHERE VERSIONMENU=9 AND Codigo='MEN_LAT_INFO_CAMP' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

UPDATE MenuApp 
SET ORDEN=9
WHERE CODIGO='MEN_LAT_TUVOZ' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

GO

USE BelcorpMexico
GO

DELETE MenuApp WHERE VERSIONMENU=9 AND Codigo='MEN_LAT_INFO_CAMP' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

UPDATE MenuApp 
SET ORDEN=9
WHERE CODIGO='MEN_LAT_TUVOZ' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

GO

USE BelcorpColombia
GO

DELETE MenuApp WHERE VERSIONMENU=9 AND Codigo='MEN_LAT_INFO_CAMP' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

UPDATE MenuApp 
SET ORDEN=9
WHERE CODIGO='MEN_LAT_TUVOZ' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

GO

USE BelcorpSalvador
GO

DELETE MenuApp WHERE VERSIONMENU=9 AND Codigo='MEN_LAT_INFO_CAMP' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

UPDATE MenuApp 
SET ORDEN=9
WHERE CODIGO='MEN_LAT_TUVOZ' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

GO

USE BelcorpPuertoRico
GO

DELETE MenuApp WHERE VERSIONMENU=9 AND Codigo='MEN_LAT_INFO_CAMP' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

UPDATE MenuApp 
SET ORDEN=9
WHERE CODIGO='MEN_LAT_TUVOZ' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

GO

USE BelcorpPanama
GO

DELETE MenuApp WHERE VERSIONMENU=9 AND Codigo='MEN_LAT_INFO_CAMP' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

UPDATE MenuApp 
SET ORDEN=9
WHERE CODIGO='MEN_LAT_TUVOZ' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

GO

USE BelcorpGuatemala
GO

DELETE MenuApp WHERE VERSIONMENU=9 AND Codigo='MEN_LAT_INFO_CAMP' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

UPDATE MenuApp 
SET ORDEN=9
WHERE CODIGO='MEN_LAT_TUVOZ' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

GO

USE BelcorpEcuador
GO

DELETE MenuApp WHERE VERSIONMENU=9 AND Codigo='MEN_LAT_INFO_CAMP' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

UPDATE MenuApp 
SET ORDEN=9
WHERE CODIGO='MEN_LAT_TUVOZ' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

GO

USE BelcorpDominicana
GO

DELETE MenuApp WHERE VERSIONMENU=9 AND Codigo='MEN_LAT_INFO_CAMP' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

UPDATE MenuApp 
SET ORDEN=9
WHERE CODIGO='MEN_LAT_TUVOZ' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

GO

USE BelcorpCostaRica
GO

DELETE MenuApp WHERE VERSIONMENU=9 AND Codigo='MEN_LAT_INFO_CAMP' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

UPDATE MenuApp 
SET ORDEN=9
WHERE CODIGO='MEN_LAT_TUVOZ' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

GO

USE BelcorpChile
GO

DELETE MenuApp WHERE VERSIONMENU=9 AND Codigo='MEN_LAT_INFO_CAMP' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

UPDATE MenuApp 
SET ORDEN=9
WHERE CODIGO='MEN_LAT_TUVOZ' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

GO

USE BelcorpBolivia
GO

DELETE MenuApp WHERE VERSIONMENU=9 AND Codigo='MEN_LAT_INFO_CAMP' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

UPDATE MenuApp 
SET ORDEN=9
WHERE CODIGO='MEN_LAT_TUVOZ' AND CodigoMenuPadre='MEN_LAT_GRUPO1'

GO

