USE BelcorpPeru
GO
	DECLARE @ID INT
	SET @ID=(SELECT PermisoID FROM Permiso P  WHERE P.Codigo='ReporteEncSatisfaccion')

	IF @ID IS NOT NULL AND EXISTS (SELECT 1 FROM ROLPERMISO WHERE PermisoID=@ID)
	BEGIN

		    DELETE FROM ROLPERMISO WHERE RolID=1 AND PermisoID=@ID

	END

GO
USE BelcorpMexico
GO
	DECLARE @ID INT
	SET @ID=(SELECT PermisoID FROM Permiso P  WHERE P.Codigo='ReporteEncSatisfaccion')

	IF @ID IS NOT NULL AND EXISTS (SELECT 1 FROM ROLPERMISO WHERE PermisoID=@ID)
	BEGIN

		    DELETE FROM ROLPERMISO WHERE RolID=1 AND PermisoID=@ID

	END

GO
USE BelcorpColombia
GO
	DECLARE @ID INT
	SET @ID=(SELECT PermisoID FROM Permiso P  WHERE P.Codigo='ReporteEncSatisfaccion')

	IF @ID IS NOT NULL AND EXISTS (SELECT 1 FROM ROLPERMISO WHERE PermisoID=@ID)
	BEGIN

		    DELETE FROM ROLPERMISO WHERE RolID=1 AND PermisoID=@ID

	END

GO
USE BelcorpSalvador
GO
	DECLARE @ID INT
	SET @ID=(SELECT PermisoID FROM Permiso P  WHERE P.Codigo='ReporteEncSatisfaccion')

	IF @ID IS NOT NULL AND EXISTS (SELECT 1 FROM ROLPERMISO WHERE PermisoID=@ID)
	BEGIN

		    DELETE FROM ROLPERMISO WHERE RolID=1 AND PermisoID=@ID

	END

GO
USE BelcorpPuertoRico
GO
	DECLARE @ID INT
	SET @ID=(SELECT PermisoID FROM Permiso P  WHERE P.Codigo='ReporteEncSatisfaccion')

	IF @ID IS NOT NULL AND EXISTS (SELECT 1 FROM ROLPERMISO WHERE PermisoID=@ID)
	BEGIN

		    DELETE FROM ROLPERMISO WHERE RolID=1 AND PermisoID=@ID

	END

GO
USE BelcorpPanama
GO
	DECLARE @ID INT
	SET @ID=(SELECT PermisoID FROM Permiso P  WHERE P.Codigo='ReporteEncSatisfaccion')

	IF @ID IS NOT NULL AND EXISTS (SELECT 1 FROM ROLPERMISO WHERE PermisoID=@ID)
	BEGIN

		    DELETE FROM ROLPERMISO WHERE RolID=1 AND PermisoID=@ID

	END

GO
USE BelcorpGuatemala
GO
	DECLARE @ID INT
	SET @ID=(SELECT PermisoID FROM Permiso P  WHERE P.Codigo='ReporteEncSatisfaccion')

	IF @ID IS NOT NULL AND EXISTS (SELECT 1 FROM ROLPERMISO WHERE PermisoID=@ID)
	BEGIN

		    DELETE FROM ROLPERMISO WHERE RolID=1 AND PermisoID=@ID

	END

GO
USE BelcorpEcuador
GO
	DECLARE @ID INT
	SET @ID=(SELECT PermisoID FROM Permiso P  WHERE P.Codigo='ReporteEncSatisfaccion')

	IF @ID IS NOT NULL AND EXISTS (SELECT 1 FROM ROLPERMISO WHERE PermisoID=@ID)
	BEGIN

		    DELETE FROM ROLPERMISO WHERE RolID=1 AND PermisoID=@ID

	END

GO
USE BelcorpDominicana
GO
	DECLARE @ID INT
	SET @ID=(SELECT PermisoID FROM Permiso P  WHERE P.Codigo='ReporteEncSatisfaccion')

	IF @ID IS NOT NULL AND EXISTS (SELECT 1 FROM ROLPERMISO WHERE PermisoID=@ID)
	BEGIN

		    DELETE FROM ROLPERMISO WHERE RolID=1 AND PermisoID=@ID

	END

GO
USE BelcorpCostaRica
GO
	DECLARE @ID INT
	SET @ID=(SELECT PermisoID FROM Permiso P  WHERE P.Codigo='ReporteEncSatisfaccion')

	IF @ID IS NOT NULL AND EXISTS (SELECT 1 FROM ROLPERMISO WHERE PermisoID=@ID)
	BEGIN

		    DELETE FROM ROLPERMISO WHERE RolID=1 AND PermisoID=@ID

	END

GO
USE BelcorpChile
GO
	DECLARE @ID INT
	SET @ID=(SELECT PermisoID FROM Permiso P  WHERE P.Codigo='ReporteEncSatisfaccion')

	IF @ID IS NOT NULL AND EXISTS (SELECT 1 FROM ROLPERMISO WHERE PermisoID=@ID)
	BEGIN

		    DELETE FROM ROLPERMISO WHERE RolID=1 AND PermisoID=@ID

	END

GO
USE BelcorpBolivia
GO
	DECLARE @ID INT
	SET @ID=(SELECT PermisoID FROM Permiso P  WHERE P.Codigo='ReporteEncSatisfaccion')

	IF @ID IS NOT NULL AND EXISTS (SELECT 1 FROM ROLPERMISO WHERE PermisoID=@ID)
	BEGIN

		    DELETE FROM ROLPERMISO WHERE RolID=1 AND PermisoID=@ID

	END

GO
