IF NOT EXISTS(SELECT * 
	FROM SYS.COLUMNS C
		JOIN SYS.OBJECTS  O
		ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'TipoEstrategia'
	AND C.NAME = 'NombreComercial')
BEGIN
	ALTER TABLE TipoEstrategia
	ADD NombreComercial VARCHAR(255)
	CONSTRAINT COST_TipoEstrategia_NombreComercial DEFAULT ''
END
GO