IF NOT EXISTS (
	SELECT * 
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'Comunicado'
	AND C.NAME = 'Comentario'
	)
BEGIN
	ALTER TABLE Comunicado
	DROP COLUMN Comentario 
END
GO