IF NOT EXISTS (
	SELECT * 
	FROM SYS.COLUMNS C
	JOIN SYS.OBJECTS  O
	ON C.[OBJECT_ID] = O.[OBJECT_ID]
	WHERE  O.TYPE = 'U'
	AND O.NAME = 'COMUNICADO'
	AND C.NAME = 'TipoComunicado'
	)
BEGIN
	ALTER TABLE COMUNICADO
	DROP COLUMN TipoComunicado
END